name: peridem
# create env using
# conda env create -f conda-peridem-env.yml
channels:
  - conda
  - conda-forge
dependencies:
  - pip
  - packaging
  - matplotlib
  - jupyter
  - numpy
  - scipy
  - pip:
    - pygmsh
    - meshio
    - pyvista
    - jupyterthemes
