PeriDEM: /home/user/project/apps/peridynamics/main.cpp File Reference
main.cpp File Reference
#include <PeriDEMConfig.h>
#include "model/dem/demModel.h"
#include "material/materialUtil.h"
#include "particle/baseParticle.h"
#include "util/function.h"
#include "util/geomObjects.h"
#include "util/matrix.h"
#include "util/methods.h"
#include "util/point.h"
#include "inp/pdecks/contactDeck.h"
#include "rw/reader.h"
#include "util/geom.h"
#include "util/randomDist.h"
#include "util/parallelUtil.h"
#include "inp/decks/materialDeck.h"
#include "inp/decks/modelDeck.h"
#include "inp/decks/outputDeck.h"
#include "inp/decks/restartDeck.h"
#include "rw/vtkParticleWriter.h"
#include "rw/vtkParticleReader.h"
#include "fe/elemIncludes.h"
#include "fe/meshUtil.h"
#include <fmt/format.h>
#include <fstream>
#include <iostream>
#include <random>
#include <taskflow/taskflow/taskflow.hpp>
#include <taskflow/taskflow/algorithm/for_each.hpp>
Data Structures
class peridynamics::Model
Main model class to simulate peridynamics deformation of single particle.
Namespaces
namespace peridynamics
Namespace to define peridynamics app for single particle deformation.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 137 of file main.cpp.
{
  // print program version
  std::cout << "Peridynamics (PeriDEM)"
            << " (Version " << MAJOR_VERSION << "." << MINOR_VERSION << "."
            << UPDATE_VERSION << ")" << std::endl << std::flush;
  util::io::InputParser input(argc, argv);
  if (input.cmdOptionExists("-h")) {
    // print help
    std::cout << "Syntax to run the app: ./Peridynamics -i <input file> -nThreads <number of threads>";
    std::cout << "Example: ./Peridynamics -i input.yaml -nThreads 2";
  }
  // read input arguments
  unsigned int nThreads;
  if (input.cmdOptionExists("-nThreads")) nThreads = std::stoi(input.getCmdOption("-nThreads"));
  else {
    nThreads = 2;
    util::io::print(fmt::format("Running Peridynamics with number of threads = {}\n", nThreads));
  }
  // set number of threads
  util::parallel::initNThreads(nThreads);
  util::io::print(fmt::format("Number of threads = {}\n", util::parallel::getNThreads()));
  std::string filename;
  if (input.cmdOptionExists("-i"))
    filename = input.getCmdOption("-i");
  else {
    filename = "./example/input_1.yaml";
    util::io::print(fmt::format("Running Peridynamics with example input file = {}\n", filename));
  }
  // current time
  auto begin = steady_clock::now();
  // create deck
  auto *deck = new inp::Input(filename);
  // check which model to run
  if (deck->isPeriDEM()) {
    // ensure two variables in the deck are set
    deck->getModelDeck()->d_populateElementNodeConnectivity = true;
    // simulate model
    peridynamics::Model dem(deck);
    dem.run(deck);
  }
  // get time elapsed
  auto end = steady_clock::now();
  std::cout << "Total simulation time (s) = "
            << util::methods::timeDiff(begin, end, "seconds")
            << std::endl;
}
References util::io::InputParser::cmdOptionExists(), util::io::InputParser::getCmdOption(), util::parallel::getNThreads(), util::parallel::initNThreads(), MAJOR_VERSION, MINOR_VERSION, util::io::print(), model::DEMModel::run(), util::methods::timeDiff(), and UPDATE_VERSION.