PeriDEM: util::geometry::Cuboid Class Reference
util::geometry::Cuboid Class Reference
Defines cuboid.
#include <geomObjects.h>
Public Member Functions
Cuboid ()
Constructor.
Cuboid (double Lx, double Ly, double Lz, util::Point x=util::Point(), std::string description="")
Constructor.
Cuboid (util::Point x1, util::Point x2, std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< util::Point > d_vertices
Vertices.
util::Point d_x
Center.
double d_Lx
Edge length of cuboid in x-direction.
double d_Ly
Edge length of cuboid in y-direction.
double d_Lz
Edge length of cuboid in z-direction.
double d_r
Radius of bounding circle.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines cuboid.
Definition at line 1662 of file geomObjects.h.
Constructor & Destructor Documentation
Cuboid() [1/3]
util::geometry::Cuboid::Cuboid () inline
Constructor.
Definition at line 1668 of file geomObjects.h.
                    : GeomObject("cuboid", ""),
                      d_Lx(0.),
                      d_Ly(0.),
                      d_Lz(0.),
                      d_r(0.),
                      d_x(util::Point()),
                      d_vertices(std::vector<util::Point>(8, util::Point())) {};
Cuboid() [2/3]
util::geometry::Cuboid::Cuboid (double Lx, double Ly, double Lz, util::Point x = util::Point(), std::string description = "") inline
Constructor.
Parameters
Lx Length along x-direction
Ly Length along y-direction
Lz Length along z-direction
x Center point
description Description of object (e.g., further classification or any tag)
Definition at line 1686 of file geomObjects.h.
                    : GeomObject("cuboid", description),
                      d_Lx(Lx),
                      d_Ly(Ly),
                      d_Lz(Lz),
                      d_r(std::sqrt(std::pow(Lx, 2) + std::pow(Ly, 2) +
                                    std::pow(Lz, 2))),
                      d_x(x),
                      d_vertices(std::vector<util::Point>(8, util::Point())) {
              // numbering assuming x - left-right, y - back-front, z - bottom-top
              // counterclockwise in bottom plane (i.e.,
              // 0 - left-back-bottom, 1 - right-back-bottom,
              // 2 - right-front-bottom, 3 - left-front-bottom
              // similarly, in top plane
              d_vertices[0] =
                      d_x + util::Point(-0.5 * d_Lx, -0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[1] =
                      d_x + util::Point(0.5 * d_Lx, -0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[2] =
                      d_x + util::Point(0.5 * d_Lx, 0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[3] =
                      d_x + util::Point(-0.5 * d_Lx, 0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[4] =
                      d_x + util::Point(-0.5 * d_Lx, -0.5 * d_Ly, 0.5 * d_Lz);
              d_vertices[5] =
                      d_x + util::Point(0.5 * d_Lx, -0.5 * d_Ly, 0.5 * d_Lz);
              d_vertices[6] =
                      d_x + util::Point(0.5 * d_Lx, 0.5 * d_Ly, 0.5 * d_Lz);
              d_vertices[7] =
                      d_x + util::Point(-0.5 * d_Lx, 0.5 * d_Ly, 0.5 * d_Lz);
            };
References d_Lx, d_Ly, d_Lz, d_vertices, and d_x.
Cuboid() [3/3]
util::geometry::Cuboid::Cuboid (util::Point x1, util::Point x2, std::string description = "") inline
Constructor.
Parameters
x1 Left-bottom-back corner point
x2 Right-top-front corner point
description Description of object (e.g., further classification or any tag)
Definition at line 1728 of file geomObjects.h.
                    : GeomObject("cuboid", description),
                      d_Lx(x2.d_x - x1.d_x),
                      d_Ly(x2.d_y - x1.d_y),
                      d_Lz(x2.d_z - x1.d_z),
                      d_r(std::sqrt(
                                  std::pow(x2.d_x - x1.d_x, 2)
                                  + std::pow(x2.d_y - x1.d_y, 2)
                                  + std::pow(x2.d_z - x1.d_z, 2)
                          )
                      ),
                      d_x(0.5 * (x1 + x2)),
                      d_vertices(std::vector<util::Point>(8, util::Point())) {
              // numbering assuming x - left-right, y - back-front, z - bottom-top
              // counterclockwise in bottom plane (i.e.,
              // 0 - left-back-bottom, 1 - right-back-bottom,
              // 2 - right-front-bottom, 3 - left-front-bottom
              // similarly, in top plane
              d_vertices[0] =
                      d_x + util::Point(-0.5 * d_Lx, -0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[1] =
                      d_x + util::Point(0.5 * d_Lx, -0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[2] =
                      d_x + util::Point(0.5 * d_Lx, 0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[3] =
                      d_x + util::Point(-0.5 * d_Lx, 0.5 * d_Ly, -0.5 * d_Lz);
              d_vertices[4] =
                      d_x + util::Point(-0.5 * d_Lx, -0.5 * d_Ly, 0.5 * d_Lz);
              d_vertices[5] =
                      d_x + util::Point(0.5 * d_Lx, -0.5 * d_Ly, 0.5 * d_Lz);
              d_vertices[6] =
                      d_x + util::Point(0.5 * d_Lx, 0.5 * d_Ly, 0.5 * d_Lz);
              d_vertices[7] =
                      d_x + util::Point(-0.5 * d_Lx, 0.5 * d_Ly, 0.5 * d_Lz);
            };
References d_Lx, d_Ly, d_Lz, d_vertices, and d_x.
Member Function Documentation
boundingRadius()
double util::geometry::Cuboid::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1082 of file geomObjects.cpp.
{
      return d_r;
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Cuboid::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1063 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Cuboid::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1068 of file geomObjects.cpp.
{
      return {util::Point(d_vertices[0].d_x - tol, d_vertices[0].d_y - tol,
                          d_vertices[0].d_z - tol),
              util::Point(d_vertices[6].d_x + tol, d_vertices[6].d_y + tol,
                          d_vertices[6].d_z + tol)};
    }
center()
util::Point util::geometry::Cuboid::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 1059 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Cuboid::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 1157 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(3, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Cuboid::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 1124 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Cuboid::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1076 of file geomObjects.cpp.
{
      auto l = util::isLess(d_Lx, d_Ly) ? d_Lx : d_Ly;
      return util::isLess(l, d_Lz) ? l : d_Lz;
    }
References util::isLess().
isInside() [1/2]
bool util::geometry::Cuboid::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1129 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(3, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Cuboid::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1087 of file geomObjects.cpp.
{
      return util::isPointInsideCuboid(x, d_vertices[0], d_vertices[6]);
    }
References util::isPointInsideCuboid().
isNear() [1/2]
bool util::geometry::Cuboid::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1150 of file geomObjects.cpp.
          {
      return util::areBoxesNear(box(), bbox, tol, 3);
    }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Cuboid::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1095 of file geomObjects.cpp.
{
      // get a bigger box containing this object
      auto bbox = box(tol);
      return util::isPointInsideBox(x, 3, bbox);
    }
References util::isPointInsideBox().
isNearBoundary()
bool util::geometry::Cuboid::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 1104 of file geomObjects.cpp.
{
      // check if particle is within the tolerance distance
      if (!isNear(x, within ? 0. : tol))
        return false;
      bool near_x_edge = util::isLess(std::abs(x.d_x - d_vertices[0].d_x), tol) or
                         util::isLess(std::abs(x.d_x - d_vertices[6].d_x), tol);
      bool near_y_edge = util::isLess(std::abs(x.d_y - d_vertices[0].d_y), tol) or
                         util::isLess(std::abs(x.d_y - d_vertices[6].d_y), tol);
      bool near_z_edge = util::isLess(std::abs(x.d_z - d_vertices[0].d_z), tol) or
                         util::isLess(std::abs(x.d_z - d_vertices[6].d_z), tol);
      return near_x_edge || near_y_edge || near_z_edge;
    }
References util::Point::d_x, util::Point::d_y, util::Point::d_z, and util::isLess().
isOutside() [1/2]
bool util::geometry::Cuboid::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1139 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(3, box))
        if (!intersect)
          intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Cuboid::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1091 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Cuboid::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 1882 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Cuboid::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 1875 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Cuboid::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 1168 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Cuboid --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Lengths (Lx, Ly, Lz) = "
                  << util::io::printStr(std::vector<double>{d_Lx, d_Ly, d_Lz}, 0)
                  << std::endl;
      oss << tabS << "Bounding sphere radius = " << d_r << std::endl;
      oss << tabS << "Center = " << d_x.printStr(0, 0) << std::endl;
      oss << tabS << "Vertices = " << util::io::printStr(d_vertices, 0) << std::endl;
      oss << std::endl;
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), util::io::printBoxStr(), and util::io::printStr().
Referenced by print().
volume()
double util::geometry::Cuboid::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 1055 of file geomObjects.cpp.
{
      return d_Lx * d_Ly * d_Lz;
    }
Field Documentation
d_Lx
double util::geometry::Cuboid::d_Lx
Edge length of cuboid in x-direction.
Definition at line 1891 of file geomObjects.h.
Referenced by Cuboid(), and Cuboid().
d_Ly
double util::geometry::Cuboid::d_Ly
Edge length of cuboid in y-direction.
Definition at line 1894 of file geomObjects.h.
Referenced by Cuboid(), and Cuboid().
d_Lz
double util::geometry::Cuboid::d_Lz
Edge length of cuboid in z-direction.
Definition at line 1897 of file geomObjects.h.
Referenced by Cuboid(), and Cuboid().
d_r
double util::geometry::Cuboid::d_r
Radius of bounding circle.
Definition at line 1900 of file geomObjects.h.
d_vertices
std::vector<util::Point> util::geometry::Cuboid::d_vertices
Vertices.
Definition at line 1885 of file geomObjects.h.
Referenced by Cuboid(), and Cuboid().
d_x
util::Point util::geometry::Cuboid::d_x
Center.
Definition at line 1888 of file geomObjects.h.
Referenced by Cuboid(), and Cuboid().
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp