PeriDEM: util::geometry::AnnulusGeomObject Class Reference
util::geometry::AnnulusGeomObject Class Reference
Defines annulus rectangle.
#include <geomObjects.h>
Public Member Functions
AnnulusGeomObject ()
Constructor.
AnnulusGeomObject (GeomObject *in, GeomObject *out, size_t dim, std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
util::geometry::GeomObject * d_outObj_p
Outer object.
util::geometry::GeomObject * d_inObj_p
Inner object.
size_t d_dim
Dimension objects live in.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines annulus rectangle.
Definition at line 2570 of file geomObjects.h.
Constructor & Destructor Documentation
AnnulusGeomObject() [1/2]
util::geometry::AnnulusGeomObject::AnnulusGeomObject () inline
Constructor.
Definition at line 2576 of file geomObjects.h.
                    : GeomObject("annulus_object", ""),
                      d_outObj_p(nullptr),
                      d_inObj_p(nullptr),
                      d_dim(0) {};
AnnulusGeomObject() [2/2]
util::geometry::AnnulusGeomObject::AnnulusGeomObject (GeomObject * in, GeomObject * out, size_t dim, std::string description = "") inline
Constructor.
Parameters
in Inner object
out Outer object
dim Dimension of the composite object
description Description of object (e.g., further classification or any tag)
Definition at line 2590 of file geomObjects.h.
                    : GeomObject("annulus_object", description),
                      d_outObj_p(out),
                      d_inObj_p(in),
                      d_dim(dim) {};
Member Function Documentation
boundingRadius()
double util::geometry::AnnulusGeomObject::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1735 of file geomObjects.cpp.
{
      return d_outObj_p->boundingRadius();
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::AnnulusGeomObject::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1720 of file geomObjects.cpp.
                     {
      return d_outObj_p->box();
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::AnnulusGeomObject::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1725 of file geomObjects.cpp.
{
      return d_outObj_p->box(tol);
    }
center()
util::Point util::geometry::AnnulusGeomObject::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 1706 of file geomObjects.cpp.
{
      // we use the formula for centroid of composite objects
      // x = sum_i sign(i) V_i x_i / sum_i sign(i) V_i
      // where sign(i) = +1 if object is filling
      // sign(i) = -1 if object is empty
      auto vol = volume();
      if (util::isGreater(vol, 0.))
        return (1./vol) * (d_outObj_p->volume() * d_outObj_p->center()
                - d_inObj_p->volume() * d_inObj_p->center());
      else
        return d_outObj_p->center();
    }
References util::isGreater().
doesIntersect() [1/2]
bool util::geometry::AnnulusGeomObject::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 1800 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(d_dim, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::AnnulusGeomObject::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 1767 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::AnnulusGeomObject::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1730 of file geomObjects.cpp.
{
      return d_outObj_p->inscribedRadius();
    }
isInside() [1/2]
bool util::geometry::AnnulusGeomObject::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1773 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(d_dim, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::AnnulusGeomObject::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1741 of file geomObjects.cpp.
{
      // should be outside inner object and inside outer object
      return !d_inObj_p->isInside(x) && d_outObj_p->isInside(x);
    }
isNear() [1/2]
bool util::geometry::AnnulusGeomObject::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1793 of file geomObjects.cpp.
{
      return d_outObj_p->isNear(box, tol) || d_inObj_p->isNear(box, tol);
    }
isNear() [2/2]
bool util::geometry::AnnulusGeomObject::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1752 of file geomObjects.cpp.
{
      return d_outObj_p->isNear(x, tol) || d_inObj_p->isNear(x, tol);
    }
isNearBoundary()
bool util::geometry::AnnulusGeomObject::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 1758 of file geomObjects.cpp.
{
      return d_outObj_p->isNearBoundary(x, tol, within) ||
             d_inObj_p->isNearBoundary(x, tol, within);
    }
isOutside() [1/2]
bool util::geometry::AnnulusGeomObject::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1783 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(d_dim, box))
        intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::AnnulusGeomObject::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1748 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::AnnulusGeomObject::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 2714 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::AnnulusGeomObject::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 2707 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References d_dim, and printStr().
printStr()
std::string util::geometry::AnnulusGeomObject::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 1812 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- AnnulusGeomObject --------" << std::endl
          << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Center = " << center().printStr() << std::endl;
      oss << tabS << "Inner object info:" << std::endl;
      oss << d_inObj_p->printStr(nt + 1, lvl);
      oss << tabS << "Outer object info:" << std::endl;
      oss << d_outObj_p->printStr(nt + 1, lvl);
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printBoxStr().
Referenced by print().
volume()
double util::geometry::AnnulusGeomObject::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 1702 of file geomObjects.cpp.
{
      return d_outObj_p->volume() - d_inObj_p->volume();
    }
Field Documentation
d_dim
size_t util::geometry::AnnulusGeomObject::d_dim
Dimension objects live in.
Definition at line 2723 of file geomObjects.h.
Referenced by print().
d_inObj_p
util::geometry::GeomObject* util::geometry::AnnulusGeomObject::d_inObj_p
Inner object.
Definition at line 2720 of file geomObjects.h.
d_outObj_p
util::geometry::GeomObject* util::geometry::AnnulusGeomObject::d_outObj_p
Outer object.
Definition at line 2717 of file geomObjects.h.
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp