PeriDEM: util::geometry::Cylinder Class Reference
util::geometry::Cylinder Class Reference
Defines cylinder.
#include <geomObjects.h>
Public Member Functions
Cylinder ()
Constructor.
Cylinder (double r, double l, util::Point x_begin, util::Point xa, std::string description="")
Constructor.
Cylinder (double r, util::Point x_begin, util::Point xa, std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
util::Point d_x
Center.
util::Point d_xBegin
Center point of cross-section at the beginning.
util::Point d_xa
Axis of cylinder (unit vector)
double d_r
Radius.
double d_l
Length.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines cylinder.
Definition at line 2382 of file geomObjects.h.
Constructor & Destructor Documentation
Cylinder() [1/3]
util::geometry::Cylinder::Cylinder () inline
Constructor.
Definition at line 2388 of file geomObjects.h.
                    : GeomObject("cylinder", ""),
                      d_xBegin(util::Point()),
                      d_xa(util::Point(1., 1., 1.)),
                      d_r(0.),
                      d_l(0.),
                      d_x(util::Point()) {};
Cylinder() [2/3]
util::geometry::Cylinder::Cylinder (double r, double l, util::Point x_begin, util::Point xa, std::string description = "") inline
Constructor.
Parameters
r Radius of cylinder
l Length of cylinder
x_begin Center of the bottom bottom cross-section
xa Axis of cylinder (if it is not a unit vector, we compute unit vector along xa)
description Description of object (e.g., further classification or any tag)
Definition at line 2405 of file geomObjects.h.
                    : GeomObject("cylinder", description),
                      d_xBegin(x_begin),
                      d_xa(xa / xa.length()),
                      d_r(r),
                      d_l(l),
                      d_x(x_begin + 0.5 * l * xa) {};
Cylinder() [3/3]
util::geometry::Cylinder::Cylinder (double r, util::Point x_begin, util::Point xa, std::string description = "") inline
Constructor.
Parameters
r Radius of cylinder
x_begin Center of the bottom bottom cross-section
xa Axis of cylinder (should be the actual vector from center of bottom section to top section so that the length of the vector is a length of cylinder)
description Description of object (e.g., further classification or any tag)
Definition at line 2423 of file geomObjects.h.
                    : GeomObject("cylinder", description),
                      d_xBegin(x_begin),
                      d_xa(xa / xa.length()),
                      d_r(r),
                      d_l(xa.length()),
                      d_x(x_begin + 0.5 * xa.length() * xa) {};
Member Function Documentation
boundingRadius()
double util::geometry::Cylinder::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1392 of file geomObjects.cpp.
{
      return 0.5 * std::sqrt(d_l * d_l + 4. * d_r * d_r);
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Cylinder::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1366 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Cylinder::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1372 of file geomObjects.cpp.
{
      if (d_xa.length() < 1.0E-10)
        return {util::Point(), util::Point()};
      auto xb = d_xBegin - tol * d_xa;
      auto xt = d_xBegin + (d_l + tol) * d_xa;
      double r = d_r + tol;
      return {xb - r, xt + r};
    }
center()
util::Point util::geometry::Cylinder::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 1362 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Cylinder::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 1500 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(3, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Cylinder::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 1467 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Cylinder::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1385 of file geomObjects.cpp.
{
      auto box = this->box();
      return 0.5 * (box.second - box.first).length();
    }
isInside() [1/2]
bool util::geometry::Cylinder::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1472 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(3, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Cylinder::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1397 of file geomObjects.cpp.
{
      auto dx = x - d_xBegin;
      if (dx.length() < 1.0E-10)
        return true;
      double dx_dot_xa = dx * d_xa;
      if (util::isLess(dx_dot_xa, 0.) or
          util::isGreater(dx_dot_xa, d_l))
        return false;
      else {
        // project dx onto cross-section plane of cylinder
        auto dx_project = dx - dx_dot_xa * d_xa;
        return !util::isGreater(dx_project.length(), d_r + 1.0E-12);
      }
    }
References util::isGreater(), and util::isLess().
isNear() [1/2]
bool util::geometry::Cylinder::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1493 of file geomObjects.cpp.
{
      return util::areBoxesNear(this->box(), box, tol, 3);
    }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Cylinder::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1421 of file geomObjects.cpp.
                {
      auto dx = x - d_xBegin;
      if (dx.length() < tol)
        return true;
      double dx_dot_xa = dx * d_xa;
      if (util::isLess(dx_dot_xa, -tol) or
          util::isGreater(dx_dot_xa, d_l + tol))
        return false;
      else {
        // project dx onto cross-section plane of cylinder
        auto dx_project = dx - dx_dot_xa * d_xa;
        return !util::isGreater(dx_project.length(), d_r + tol);
      }
    }
References util::isGreater(), and util::isLess().
isNearBoundary()
bool util::geometry::Cylinder::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 1442 of file geomObjects.cpp.
{
      auto dx = x - d_xBegin;
      if (dx.length() < tol)
        return true;
      double dx_dot_xa = dx * d_xa;
      if (util::isLess(dx_dot_xa, -tol) or
          util::isGreater(dx_dot_xa, tol) or
          util::isGreater(dx_dot_xa, d_l + tol) or
          util::isLess(dx_dot_xa, d_l - tol))
        return false;
      else {
        // project dx onto cross-section plane of cylinder
        auto dx_project = dx - dx_dot_xa * d_xa;
        return !(util::isLess(dx_project.length(), d_r - tol) or
                 util::isGreater(dx_project.length(), d_r + tol));
      }
    }
References util::isGreater(), and util::isLess().
isOutside() [1/2]
bool util::geometry::Cylinder::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1482 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(3, box))
        if (!intersect)
          intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Cylinder::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1417 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Cylinder::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 2549 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Cylinder::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 2542 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Cylinder::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 1512 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Cylinder --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Center = " << d_xBegin.printStr(0, lvl) << std::endl;
      oss << tabS << "Axis = " << d_xa.printStr(0, lvl) << std::endl;
      oss << tabS << "Radius = " << d_r << std::endl;
      oss << tabS << "Center = " << d_x.printStr(0, 0) << std::endl;
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printBoxStr().
Referenced by print().
volume()
double util::geometry::Cylinder::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 1358 of file geomObjects.cpp.
{
      return M_PI * d_r * d_r * d_l;
    }
Field Documentation
d_l
double util::geometry::Cylinder::d_l
Length.
Definition at line 2564 of file geomObjects.h.
d_r
double util::geometry::Cylinder::d_r
Radius.
Definition at line 2561 of file geomObjects.h.
d_x
util::Point util::geometry::Cylinder::d_x
Center.
Definition at line 2552 of file geomObjects.h.
d_xa
util::Point util::geometry::Cylinder::d_xa
Axis of cylinder (unit vector)
Definition at line 2558 of file geomObjects.h.
d_xBegin
util::Point util::geometry::Cylinder::d_xBegin
Center point of cross-section at the beginning.
Definition at line 2555 of file geomObjects.h.
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp