PeriDEM: util::io::Logger Class Reference
util::io::Logger Class Reference
Prints log to std::cout and also write to the file.
#include <io.h>
Public Member Functions
Logger (LoggerDeck *deck=nullptr)
Constructor.
~Logger ()
Destructor.
void log (std::ostringstream &oss, bool screen_out=false, int printMpiRank=print_default_mpi_rank)
Log the message.
void log (const std::string &str, bool screen_out=false, int printMpiRank=print_default_mpi_rank)
Log the message.
Data Fields
LoggerDeck * d_deck_p
Pointer to logger deck.
std::ofstream d_logFile
Filestream for logging.
Detailed Description
Prints log to std::cout and also write to the file.
Definition at line 251 of file io.h.
Constructor & Destructor Documentation
Logger()
util::io::Logger::Logger (LoggerDeck * deck = nullptr) inline
Constructor.
Parameters
deck Logger deck
Definition at line 260 of file io.h.
                                     : d_deck_p(deck) {
    if (d_deck_p == nullptr)
      d_deck_p = new LoggerDeck();
  }
References d_deck_p.
~Logger()
util::io::Logger::~Logger () inline
Destructor.
Definition at line 269 of file io.h.
            {
    if (d_deck_p->d_printFile)
      d_logFile.close();
  }
References d_deck_p, d_logFile, and util::io::LoggerDeck::d_printFile.
Member Function Documentation
log() [1/2]
void util::io::Logger::log (const std::string & str, bool screen_out = false, int printMpiRank = print_default_mpi_rank) inline
Log the message.
Parameters
str Message
screen_out Specify if it goes to std::cout as well
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 299 of file io.h.
{
    if (printMpiRank < 0 or util::parallel::mpiRank() == printMpiRank) {
      if (d_deck_p->d_printScreen || screen_out)
        std::cout << str << std::flush;
      // log
      if (d_deck_p->d_printFile) {
        d_logFile.open(d_deck_p->d_filename, std::ios_base::app);
        d_logFile << str;
        d_logFile.close();
      }
    }
  };
References d_deck_p, util::io::LoggerDeck::d_filename, d_logFile, util::io::LoggerDeck::d_printFile, util::io::LoggerDeck::d_printScreen, and util::parallel::mpiRank().
log() [2/2]
void util::io::Logger::log (std::ostringstream & oss, bool screen_out = false, int printMpiRank = print_default_mpi_rank) inline
Log the message.
Parameters
oss Message
screen_out Specify if it goes to std::cout as well
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 282 of file io.h.
{
    log(oss.str(), screen_out, printMpiRank);
    // reset oss
    oss.str("");
    oss.clear();
  };
References log().
Referenced by util::io::log(), util::io::log(), and log().
Field Documentation
d_deck_p
LoggerDeck* util::io::Logger::d_deck_p
Pointer to logger deck.
Definition at line 316 of file io.h.
Referenced by log(), Logger(), and ~Logger().
d_logFile
std::ofstream util::io::Logger::d_logFile
Filestream for logging.
Definition at line 319 of file io.h.
Referenced by log(), and ~Logger().
The documentation for this class was generated from the following file:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/util/io.h