PeriDEM: util::geometry::Square Class Reference
util::geometry::Square Class Reference
Defines Square.
#include <geomObjects.h>
Public Member Functions
Square ()
Constructor.
Square (double L, util::Point x=util::Point(), std::string description="")
Constructor.
Square (util::Point x1, util::Point x2, std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< util::Point > d_vertices
Vertices.
util::Point d_x
Center.
double d_L
Edge length of a square.
double d_r
Radius of bounding circle.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines Square.
Definition at line 641 of file geomObjects.h.
Constructor & Destructor Documentation
Square() [1/3]
util::geometry::Square::Square () inline
Constructor.
Definition at line 647 of file geomObjects.h.
                    : GeomObject("square", ""),
                      d_L(0.),
                      d_r(0.),
                      d_x(util::Point()),
                      d_vertices({util::Point(), util::Point(),
                                  util::Point(), util::Point()}) {};
Square() [2/3]
util::geometry::Square::Square (double L, util::Point x = util::Point(), std::string description = "") inline
Constructor.
Parameters
L Length along x and y-directions (Square)
x Center point
description Description of object (e.g., further classification or any tag)
Definition at line 662 of file geomObjects.h.
                    : GeomObject("square", description),
                      d_L(L),
                      d_r(L / std::sqrt(2)),
                      d_x(x),
                      d_vertices({x + util::Point(-0.5 * L, -0.5 * L, 0.),
                                  x + util::Point(0.5 * L, -0.5 * L, 0.),
                                  x + util::Point(0.5 * L, 0.5 * L, 0.),
                                  x + util::Point(-0.5 * L, 0.5 * L, 0.)}) {};
Square() [3/3]
util::geometry::Square::Square (util::Point x1, util::Point x2, std::string description = "") inline
Constructor.
Parameters
x1 Left-bottom corner point
x2 Right-top corner point
description Description of object (e.g., further classification or any tag)
Definition at line 680 of file geomObjects.h.
                    : GeomObject("square", description),
                      d_L((x1 - x2).length() * (1. / std::sqrt(2))),
                      d_r((x1 - x2).length() / 2.),
                      d_x(0.5 * (x1 + x2)) {
              d_vertices.push_back(x1);
              d_vertices.push_back(util::Point(x1.d_x + d_L, x1.d_y, x1.d_z));
              d_vertices.push_back(x2);
              d_vertices.push_back(util::Point(x2.d_x - d_L, x2.d_y, x2.d_z));
            };
References d_L, d_vertices, util::Point::d_x, util::Point::d_y, and util::Point::d_z.
Member Function Documentation
boundingRadius()
double util::geometry::Square::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 371 of file geomObjects.cpp.
{
    return d_r;
  }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Square::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 353 of file geomObjects.cpp.
{
    return box(0.);
  }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Square::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 357 of file geomObjects.cpp.
{
    return {util::Point(d_vertices[0].d_x - tol, d_vertices[0].d_y - tol,
                        0.),
            util::Point(d_vertices[2].d_x + tol, d_vertices[2].d_y + tol,
                        0.)};
  }
center()
util::Point util::geometry::Square::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 349 of file geomObjects.cpp.
{
    return d_x;
  }
doesIntersect() [1/2]
bool util::geometry::Square::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 442 of file geomObjects.cpp.
{
    // need to check all four corner points
    for (auto p : util::getCornerPoints(2, box))
      if (this->isInside(p))
        return true;
    return false;
  }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Square::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 410 of file geomObjects.cpp.
{
    return isNearBoundary(x, 1.0E-8, false);
  }
inscribedRadius()
double util::geometry::Square::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 366 of file geomObjects.cpp.
{
    return 0.5*d_L;
  }
isInside() [1/2]
bool util::geometry::Square::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 415 of file geomObjects.cpp.
{
    for (auto p : util::getCornerPoints(2, box))
      if(!this->isInside(p))
        return false;
    return true;
  }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Square::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 376 of file geomObjects.cpp.
{
    return util::isPointInsideRectangle(x, d_vertices[0], d_vertices[2]);
  }
References util::isPointInsideRectangle().
isNear() [1/2]
bool util::geometry::Square::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 436 of file geomObjects.cpp.
{
    return util::areBoxesNear(this->box(), box, tol, 2);
  }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Square::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 384 of file geomObjects.cpp.
{
    // get a bigger box containing this object
    auto bbox = box(tol);
    return util::isPointInsideBox(x, 2, bbox);
  }
References util::isPointInsideBox().
isNearBoundary()
bool util::geometry::Square::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 393 of file geomObjects.cpp.
{
    // check if particle is inside the object
    if (!isNear(x, within ? 0. : tol))
      return false;
    bool near_x_edge = util::isLess(std::abs(x.d_x - d_vertices[0].d_x), tol) or
                       util::isLess(std::abs(x.d_x - d_vertices[2].d_x), tol);
    bool near_y_edge = util::isLess(std::abs(x.d_y - d_vertices[0].d_y), tol) or
                       util::isLess(std::abs(x.d_y - d_vertices[2].d_y), tol);
    return near_x_edge || near_y_edge;
  }
References util::Point::d_x, util::Point::d_y, and util::isLess().
isOutside() [1/2]
bool util::geometry::Square::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 425 of file geomObjects.cpp.
{
    bool intersect = false;
    for (auto p : util::getCornerPoints(2, box))
      if (!intersect)
        intersect = this->isInside(p);
    return !intersect;
  }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Square::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 380 of file geomObjects.cpp.
{
    return !isInside(x);
  }
print() [1/2]
void util::geometry::Square::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 809 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Square::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 802 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Square::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 453 of file geomObjects.cpp.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- Rectangle --------" << std::endl << std::endl;
    oss << tabS << "Name = " << d_name << std::endl;
    oss << tabS << "Length = " << d_L << std::endl;
    oss << tabS << "Bounding radius = " << d_r << std::endl;
    oss << tabS << "Center = " << d_x.printStr(0, lvl) << std::endl;
    oss << tabS << "Vertices = " << util::io::printStr(d_vertices, 0) << std::endl;
    oss << std::endl;
    if (lvl > 0)
      oss << tabS << "Bounding box: " << util::io::printBoxStr(box(0.), nt + 1);
    if (lvl == 0)
      oss << std::endl;
    return oss.str();
  }
References util::io::getTabS(), util::io::printBoxStr(), and util::io::printStr().
Referenced by print().
volume()
double util::geometry::Square::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 345 of file geomObjects.cpp.
{
    return std::pow(d_L, 2);
  }
Field Documentation
d_L
double util::geometry::Square::d_L
Edge length of a square.
Definition at line 818 of file geomObjects.h.
Referenced by Square().
d_r
double util::geometry::Square::d_r
Radius of bounding circle.
Definition at line 821 of file geomObjects.h.
d_vertices
std::vector<util::Point> util::geometry::Square::d_vertices
Vertices.
Definition at line 812 of file geomObjects.h.
Referenced by Square().
d_x
util::Point util::geometry::Square::d_x
Center.
Definition at line 815 of file geomObjects.h.
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp