PeriDEM: util::geometry::Sphere Class Reference
util::geometry::Sphere Class Reference
Defines sphere.
#include <geomObjects.h>
Public Member Functions
Sphere ()
Constructor.
Sphere (double r, util::Point x=util::Point(), std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
util::Point d_x
Center.
double d_r
Radius.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines sphere.
Definition at line 2059 of file geomObjects.h.
Constructor & Destructor Documentation
Sphere() [1/2]
util::geometry::Sphere::Sphere () inline
Constructor.
Definition at line 2065 of file geomObjects.h.
                    : GeomObject("sphere", ""),
                      d_x(util::Point()),
                      d_r(0.) {};
Sphere() [2/2]
util::geometry::Sphere::Sphere (double r, util::Point x = util::Point(), std::string description = "") inline
Constructor.
Parameters
r Radius
x Center
description Description of object (e.g., further classification or any tag)
Definition at line 2077 of file geomObjects.h.
                    : GeomObject("sphere", description),
                      d_x(x),
                      d_r(r) {};
Member Function Documentation
boundingRadius()
double util::geometry::Sphere::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1569 of file geomObjects.cpp.
{
      return d_r;
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Sphere::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1549 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Sphere::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1554 of file geomObjects.cpp.
{
      double r = d_r + tol;
      return {
              util::Point(d_x.d_x - r, d_x.d_y - r, d_x.d_z - r),
              util::Point(d_x.d_x + r, d_x.d_y + r, d_x.d_z + r)
      };
    }
center()
util::Point util::geometry::Sphere::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 1545 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Sphere::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 1664 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(3, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Sphere::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 1607 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Sphere::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1564 of file geomObjects.cpp.
{
      return d_r;
    }
isInside() [1/2]
bool util::geometry::Sphere::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1612 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(3, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Sphere::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1574 of file geomObjects.cpp.
{
      return util::isLess(d_x.dist(x), d_r + 1.0E-12);
    }
References util::isLess().
isNear() [1/2]
bool util::geometry::Sphere::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1633 of file geomObjects.cpp.
{
      if (this->isInside(box))
        return true;
      // get corner points of box
      auto cp = getCornerPoints(3, box);
      for (auto p: cp) {
        // check the distance of corner point with the center
        auto dx = p - d_x;
        if (util::isLess(dx.length(), d_r + tol))
          return true;
      }
      // check center to center distance
      auto dxc = util::getCenter(3, box) - d_x;
      // check wrt inscribed circle
      auto r = util::inscribedRadiusInBox(3, box);
      if (util::isLess(dxc.length(), d_r + r + tol))
        return true;
      // check wrt circumscribed circle
      r = util::circumscribedRadiusInBox(3, box);
      return util::isLess(dxc.length(), d_r + r + tol);
    }
References util::circumscribedRadiusInBox(), util::getCenter(), util::getCornerPoints(), util::inscribedRadiusInBox(), and util::isLess().
isNear() [2/2]
bool util::geometry::Sphere::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1583 of file geomObjects.cpp.
{
      // translate to origin
      auto x0 = x - d_x;
      return util::isLess(x0.length(), d_r + tol);
    }
References util::isLess().
isNearBoundary()
bool util::geometry::Sphere::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 1592 of file geomObjects.cpp.
{
      // check if particle is within the tolerance distance
      if (!isNear(x, within ? 0. : tol))
        return false;
      // check if it is close enough to circumference
      auto x0 = x - d_x;
      return util::isLess(x0.length(), d_r + tol) ||
             util::isLess(x0.length(), d_r - tol);
    }
References util::isLess().
isOutside() [1/2]
bool util::geometry::Sphere::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1622 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(3, box))
        if (!intersect)
          intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Sphere::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1579 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Sphere::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 2200 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Sphere::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 2193 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Sphere::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 1675 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Sphere --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Center = " << d_x.printStr(0, lvl) << std::endl;
      oss << tabS << "Radius = " << d_r << std::endl;
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printBoxStr().
Referenced by print().
volume()
double util::geometry::Sphere::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 1541 of file geomObjects.cpp.
{
      return 4. * M_PI * d_r * d_r * d_r / 3.;
    }
Field Documentation
d_r
double util::geometry::Sphere::d_r
Radius.
Definition at line 2206 of file geomObjects.h.
d_x
util::Point util::geometry::Sphere::d_x
Center.
Definition at line 2203 of file geomObjects.h.
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp