PeriDEM: nsearch::NFlannSearchKd< dim > Class Template Reference
nsearch::NFlannSearchKd< dim > Class Template Reference
A class for nearest neighbor search using nanoflann library.
#include <nsearch.h>
Public Member Functions
NFlannSearchKd (const PointCloud &x, size_t debug=0, size_t max_leafs=10)
Constructor.
double setInputCloud () override
Set input cloud.
double updatePointCloud (const std::vector< util::Point > &x, bool parallel=true) override
Function to implement point cloud update.
size_t radiusSearch (const util::Point &searchPoint, const double &search_r, std::vector< size_t > &neighs, std::vector< double > &sqr_dist) override
Perform radius search to find points in a point cloud within specified distance from a given point. = 0 = 0 = 0
size_t radiusSearch (const util::Point &searchPoint, const double &search_r, std::vector< int > &neighs, std::vector< float > &sqr_dist) override
Perform radius search to find points in a point cloud within specified distance from a given point. = 0
size_t radiusSearchExcludeTag (const util::Point &searchPoint, const double &search_r, std::vector< size_t > &neighs, std::vector< double > &sqr_dist, const size_t &searchPointTag, const std::vector< size_t > &dataTags) override
= 0
size_t radiusSearchExcludeTag (const util::Point &searchPoint, const double &search_r, std::vector< int > &neighs, std::vector< float > &sqr_dist, const size_t &searchPointTag, const std::vector< size_t > &dataTags) override
= 0
size_t radiusSearchIncludeTag (const util::Point &searchPoint, const double &search_r, std::vector< size_t > &neighs, std::vector< double > &sqr_dist, const size_t &searchPointTag, const std::vector< size_t > &dataTags) override
= 0
size_t radiusSearchIncludeTag (const util::Point &searchPoint, const double &search_r, std::vector< int > &neighs, std::vector< float > &sqr_dist, const size_t &searchPointTag, const std::vector< size_t > &dataTags) override
= 0
void closestPoint (const util::Point &searchPoint, size_t &neigh, double &sqrDistNeigh) override
= 0
Public Member Functions inherited from nsearch::BaseNSearch
BaseNSearch (std::string name, size_t debug=0)
Constructor.
Data Fields
PointCloudAdaptor d_cloud
coordinates of the points
nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, PointCloudAdaptor >, PointCloudAdaptor, dim > d_tree
Tree.
nanoflann::SearchParameters d_params
Tree search parameters.
Data Fields inherited from nsearch::BaseNSearch
size_t d_debug
control the verbosity
std::string d_treeType
name of tree: nflann_kdtree
Detailed Description
template<int dim = 3>
class nsearch::NFlannSearchKd< dim >
A class for nearest neighbor search using nanoflann library.
Definition at line 178 of file nsearch.h.
Constructor & Destructor Documentation
NFlannSearchKd()
template<int dim = 3> nsearch::NFlannSearchKd< dim >::NFlannSearchKd (const PointCloud & x, size_t debug = 0, size_t max_leafs = 10) inline explicit
Constructor.
Parameters
x Point cloud
debug Debug level to print information
max_leaf Maximum number of leafs
Definition at line 188 of file nsearch.h.
          : BaseNSearch("nflann_kdtree", debug),
            d_cloud(x),
            d_tree(dim, d_cloud,
                   nanoflann::KDTreeSingleIndexAdaptorParams(max_leafs /* max leaf */)) {
    d_params.sorted = false;
  };
References nsearch::NFlannSearchKd< dim >::d_params.
Member Function Documentation
closestPoint()
template<int dim = 3> void nsearch::NFlannSearchKd< dim >::closestPoint (const util::Point & searchPoint, size_t & neigh, double & sqrDistNeigh) inline override virtual
= 0
= 0
Implements nsearch::BaseNSearch.
Definition at line 400 of file nsearch.h.
{
      double query_pt[3] = {searchPoint[0], searchPoint[1], searchPoint[2]};
      unsigned int neigh_temp = 0;
      d_tree.knnSearch(&query_pt[0], 1, &neigh_temp, &sqrDistNeigh);
      neigh = neigh_temp;
    };
References nsearch::NFlannSearchKd< dim >::d_tree.
radiusSearch() [1/2]
template<int dim = 3> size_t nsearch::NFlannSearchKd< dim >::radiusSearch (const util::Point & searchPoint, const double & search_r, std::vector< int > & neighs, std::vector< float > & sqr_dist) inline override virtual
Perform radius search to find points in a point cloud within specified distance from a given point. = 0
Parameters
searchPoint Point near which we want neighbors
search_r Search radius
neighs Indices of points in neighborhood
sqr_dist Squared distance of neighboring points from search point
Returns
number Number of points in neighborhood = 0
Implements nsearch::BaseNSearch.
Definition at line 244 of file nsearch.h.
{
    // ugly but quick fix
    // first, get results using int and float and then convert
    std::vector<size_t> neighs_temp;
    std::vector<double> sqr_dist_temp;
    auto N =
            this->radiusSearch(searchPoint, search_r, neighs_temp, sqr_dist_temp);
    if (N > 0) {
      neighs.resize(N);
      sqr_dist.resize(N);
      for (size_t i=0; i<N; i++) {
        neighs.push_back(int(neighs_temp[i]));
        sqr_dist.push_back(float(sqr_dist_temp[i]));
      }
    }
    return N;
  };
References nsearch::NFlannSearchKd< dim >::radiusSearch().
radiusSearch() [2/2]
template<int dim = 3> size_t nsearch::NFlannSearchKd< dim >::radiusSearch (const util::Point & searchPoint, const double & search_r, std::vector< size_t > & neighs, std::vector< double > & sqr_dist) inline override virtual
Perform radius search to find points in a point cloud within specified distance from a given point. = 0 = 0 = 0
Parameters
searchPoint Point near which we want neighbors
search_r Search radius
neighs Indices of points in neighborhood
sqr_dist Squared distance of neighboring points from search point
Returns
number Number of points in neighborhood = 0 = 0 = 0
Implements nsearch::BaseNSearch.
Definition at line 227 of file nsearch.h.
{
    double query_pt[3] = {searchPoint[0], searchPoint[1], searchPoint[2]};
    TreeSearchRes resultSet(search_r * search_r, neighs, sqr_dist);
    return d_tree.radiusSearchCustomCallback(&query_pt[0], resultSet, d_params);
  };
References nsearch::NFlannSearchKd< dim >::d_params, and nsearch::NFlannSearchKd< dim >::d_tree.
Referenced by nsearch::NFlannSearchKd< dim >::radiusSearch().
radiusSearchExcludeTag() [1/2]
template<int dim = 3> size_t nsearch::NFlannSearchKd< dim >::radiusSearchExcludeTag (const util::Point & searchPoint, const double & search_r, std::vector< int > & neighs, std::vector< float > & sqr_dist, const size_t & searchPointTag, const std::vector< size_t > & dataTags) inline override virtual
= 0
= 0
Implements nsearch::BaseNSearch.
Definition at line 303 of file nsearch.h.
{
      // first, get results using int and float and then convert
      std::vector<size_t> neighs_temp;
      std::vector<double> sqr_dist_temp;
      auto N =
              this->radiusSearchExcludeTag(searchPoint, search_r,
                                           neighs_temp, sqr_dist_temp,
                                           searchPointTag, dataTags);
      if (N > 0) {
        neighs.resize(N);
        sqr_dist.resize(N);
        for (size_t i=0; i<N; i++) {
          neighs.push_back(int(neighs_temp[i]));
          sqr_dist.push_back(float(sqr_dist_temp[i]));
        }
      }
      return N;
    };
References nsearch::NFlannSearchKd< dim >::radiusSearchExcludeTag().
radiusSearchExcludeTag() [2/2]
template<int dim = 3> size_t nsearch::NFlannSearchKd< dim >::radiusSearchExcludeTag (const util::Point & searchPoint, const double & search_r, std::vector< size_t > & neighs, std::vector< double > & sqr_dist, const size_t & searchPointTag, const std::vector< size_t > & dataTags) inline override virtual
= 0
= 0
Implements nsearch::BaseNSearch.
Definition at line 278 of file nsearch.h.
{
      double query_pt[3] = {searchPoint[0], searchPoint[1], searchPoint[2]};
      TreeSearchCheckIDExcludeRes resultSet(search_r * search_r,
                            neighs, sqr_dist, searchPointTag, dataTags);
      return d_tree.radiusSearchCustomCallback(&query_pt[0], resultSet, d_params);
    };
References nsearch::NFlannSearchKd< dim >::d_params, and nsearch::NFlannSearchKd< dim >::d_tree.
Referenced by nsearch::NFlannSearchKd< dim >::radiusSearchExcludeTag().
radiusSearchIncludeTag() [1/2]
template<int dim = 3> size_t nsearch::NFlannSearchKd< dim >::radiusSearchIncludeTag (const util::Point & searchPoint, const double & search_r, std::vector< int > & neighs, std::vector< float > & sqr_dist, const size_t & searchPointTag, const std::vector< size_t > & dataTags) inline override virtual
= 0
= 0
Implements nsearch::BaseNSearch.
Definition at line 366 of file nsearch.h.
{
      // first, get results using int and float and then convert
      std::vector<size_t> neighs_temp;
      std::vector<double> sqr_dist_temp;
      auto N =
              this->radiusSearchIncludeTag(searchPoint, search_r,
                                           neighs_temp, sqr_dist_temp,
                                           searchPointTag, dataTags);
      if (N > 0) {
        neighs.resize(N);
        sqr_dist.resize(N);
        for (size_t i=0; i<N; i++) {
          neighs.push_back(int(neighs_temp[i]));
          sqr_dist.push_back(float(sqr_dist_temp[i]));
        }
      }
      return N;
    };
References nsearch::NFlannSearchKd< dim >::radiusSearchIncludeTag().
radiusSearchIncludeTag() [2/2]
template<int dim = 3> size_t nsearch::NFlannSearchKd< dim >::radiusSearchIncludeTag (const util::Point & searchPoint, const double & search_r, std::vector< size_t > & neighs, std::vector< double > & sqr_dist, const size_t & searchPointTag, const std::vector< size_t > & dataTags) inline override virtual
= 0
= 0
Implements nsearch::BaseNSearch.
Definition at line 340 of file nsearch.h.
{
      double query_pt[3] = {searchPoint[0], searchPoint[1], searchPoint[2]};
      TreeSearchCheckIDIncludeRes resultSet(search_r * search_r,
                                            neighs, sqr_dist,
                                            searchPointTag, dataTags);
      return d_tree.radiusSearchCustomCallback(&query_pt[0], resultSet, d_params);
    };
References nsearch::NFlannSearchKd< dim >::d_params, and nsearch::NFlannSearchKd< dim >::d_tree.
Referenced by nsearch::NFlannSearchKd< dim >::radiusSearchIncludeTag().
setInputCloud()
template<int dim = 3> double nsearch::NFlannSearchKd< dim >::setInputCloud () inline override virtual
Set input cloud.
Returns
double Time taken to update the point cloud
Implements nsearch::BaseNSearch.
Definition at line 200 of file nsearch.h.
{
    auto t1 = steady_clock::now();
    d_tree.buildIndex();
    auto t2 = steady_clock::now();
    return util::methods::timeDiff(t1, t2);
  };
References nsearch::NFlannSearchKd< dim >::d_tree, and util::methods::timeDiff().
updatePointCloud()
template<int dim = 3> double nsearch::NFlannSearchKd< dim >::updatePointCloud (const std::vector< util::Point > & x, bool parallel = true) inline override virtual
Function to implement point cloud update.
TODO Implement this function
Parameters
x Vector of positions of points
parallel Specify if this is done in parallel
Returns
double Time taken to update the point cloud
Implements nsearch::BaseNSearch.
Definition at line 216 of file nsearch.h.
{
    return 0;
  };
Field Documentation
d_cloud
template<int dim = 3> PointCloudAdaptor nsearch::NFlannSearchKd< dim >::d_cloud
coordinates of the points
Definition at line 413 of file nsearch.h.
d_params
template<int dim = 3> nanoflann::SearchParameters nsearch::NFlannSearchKd< dim >::d_params
Tree search parameters.
Definition at line 422 of file nsearch.h.
Referenced by nsearch::NFlannSearchKd< dim >::NFlannSearchKd(), nsearch::NFlannSearchKd< dim >::radiusSearch(), nsearch::NFlannSearchKd< dim >::radiusSearchExcludeTag(), and nsearch::NFlannSearchKd< dim >::radiusSearchIncludeTag().
d_tree
template<int dim = 3> nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor<double, PointCloudAdaptor>, PointCloudAdaptor, dim > nsearch::NFlannSearchKd< dim >::d_tree
Tree.
Definition at line 419 of file nsearch.h.
Referenced by nsearch::NFlannSearchKd< dim >::closestPoint(), nsearch::NFlannSearchKd< dim >::radiusSearch(), nsearch::NFlannSearchKd< dim >::radiusSearchExcludeTag(), nsearch::NFlannSearchKd< dim >::radiusSearchIncludeTag(), and nsearch::NFlannSearchKd< dim >::setInputCloud().
The documentation for this class was generated from the following file:
/home/user/project/src/nsearch/nsearch.h