PeriDEM: util::geometry::Drum2D Class Reference
util::geometry::Drum2D Class Reference
Defines Drum2D.
#include <geomObjects.h>
Public Member Functions
Drum2D ()
Constructor.
Drum2D (double r, double w, util::Point x=util::Point(0., 0., 0.), util::Point a=util::Point(1., 0., 0.), std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< util::Point > d_vertices
Vertices.
util::Point d_x
Center.
double d_w
Half width of neck.
double d_r
Distance between center and the farthest vertex.
util::Point d_a
Axis: defined as the vector pointing from center to the first vertex v3 v2.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines Drum2D.
        v3   o-------------------o   v2
             \                   /
              \                 /
               \               /
          v4    o      +      o v1
               /       c       \
              /                 \
             /                   \
       v5   o---------------------o  v6
w = distance between c and v1 = half-width of neck r = distance between c and v2 theta = pi/3 = angle between c-v2 and c-v1 a = axis = unit vector from c to v1
Definition at line 1230 of file geomObjects.h.
Constructor & Destructor Documentation
Drum2D() [1/2]
util::geometry::Drum2D::Drum2D () inline
Constructor.
Definition at line 1236 of file geomObjects.h.
                    : GeomObject("drum2d", ""),
                      d_r(0.),
                      d_w(0.),
                      d_a(util::Point(1., 0., 0.)),
                      d_x(util::Point()),
                      d_vertices(std::vector<util::Point>(6, util::Point())) {};
Drum2D() [2/2]
util::geometry::Drum2D::Drum2D (double r, double w, util::Point x = util::Point(0., 0., 0.), util::Point a = util::Point(1., 0., 0.), std::string description = "") inline
Constructor.
Parameters
r Distance between center and farthest vertex of drum2d structure
w Half of the distance between two vertices in the neck (half width of neck)
x Center point
a Axis vector that will be rotated and scaled by r to get the farthest four vertices of structure
description Description of object (e.g., further classification or any tag)
Definition at line 1254 of file geomObjects.h.
                    : GeomObject("drum2d", description),
                      d_r(r),
                      d_w(w),
                      d_a(a),
                      d_x(x),
                      d_vertices(std::vector<util::Point>(6, util::Point())) {
              // generate vertices
              auto rotate_axis = util::Point(0., 0., 1.); // z-axis
              // half-width of big (top and bottom) edge
              double w_big_edge = d_r * std::cos(M_PI / 3.);
              d_vertices[0] = d_x + d_w * d_a;
              d_vertices[3] = d_x - d_w * d_a;
              d_vertices[1] =
                      d_x + d_r * util::rotate(d_a, M_PI / 3., rotate_axis);
              // to get third vertex, we could either rotate axis further or use second vertex to get
              // to the third vertex
              // Option 1
              // d_vertices[2] = d_x + d_r * util::rotate(d_a, 2.*M_PI/3., rotate_axis);
              // Option 2
              d_vertices[2] = d_vertices[1] - 2 * w_big_edge * rotate_axis;
              d_vertices[4] = d_x + d_r * util::rotate(-1. * d_a, M_PI / 3.,
                                                       rotate_axis);
              // Option 2
              d_vertices[5] = d_vertices[4] + 2. * w_big_edge * d_a;
            };
References d_a, d_r, d_vertices, d_w, d_x, and util::rotate().
Member Function Documentation
boundingRadius()
double util::geometry::Drum2D::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 786 of file geomObjects.cpp.
{
      return d_r;
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Drum2D::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 768 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Drum2D::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 773 of file geomObjects.cpp.
{
      auto p1 = d_x - util::Point(d_r + tol, d_r + tol, d_x[2] + tol);
      auto p2 = d_x + util::Point(d_r + tol, d_r + tol, d_x[2] + tol);
      return {p1, p2};
    }
center()
util::Point util::geometry::Drum2D::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 764 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Drum2D::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 876 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(2, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Drum2D::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 843 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Drum2D::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 781 of file geomObjects.cpp.
{
      return d_w;
    }
isInside() [1/2]
bool util::geometry::Drum2D::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 848 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(2, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Drum2D::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 791 of file geomObjects.cpp.
{
      if ((x - d_x).length() > d_r)
        return false;
      if ((x - d_x).length() < inscribedRadius())
        return true;
      // rotate axis to get orthogonal axis
      auto ortho_axis = util::rotate(d_a, M_PI * 0.5, util::Point(0., 0., 1.));
      //
      //                                   + v2
      //                                  /
      //                                /    x
      //                              /
      //                            /
      //                     o----+v1
      //
      auto ox = x - d_x;
      double angle_ox_ov1 = std::acos(std::abs(d_a.dot(ox)) / ox.length());
      double max_length = d_w + angle_ox_ov1 * (d_r - d_w) / (M_PI / 3.);
      return ox.length() <= max_length;
    }
References util::rotate().
isNear() [1/2]
bool util::geometry::Drum2D::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 869 of file geomObjects.cpp.
{
      return util::areBoxesNear(this->box(), box, tol, 2);
    }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Drum2D::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 821 of file geomObjects.cpp.
{
      // get a bigger box containing this object
      auto bbox = box(tol);
      return util::isPointInsideBox(x, 2, bbox);
    }
References util::isPointInsideBox().
isNearBoundary()
bool util::geometry::Drum2D::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 830 of file geomObjects.cpp.
{
      if ((x - d_x).length() > d_r + tol)
        return false;
      if ((x - d_x).length() < this->inscribedRadius() - tol)
        return false;
      return true;
    }
isOutside() [1/2]
bool util::geometry::Drum2D::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 858 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(2, box))
        if (!intersect)
          intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Drum2D::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 817 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Drum2D::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 1405 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Drum2D::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 1398 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Drum2D::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 887 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Drum2D --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Radius = " << d_r << std::endl;
      oss << tabS << "Neck half-width = " << d_w << std::endl;
      oss << tabS << "Center = " << d_x.printStr(0, lvl) << std::endl;
      oss << tabS << "Axis = " << d_a.printStr(0, lvl) << std::endl;
      oss << tabS << "Vertices = " << util::io::printStr(d_vertices, lvl) <<
          std::endl;
      oss << std::endl;
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printStr().
Referenced by print().
volume()
double util::geometry::Drum2D::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 759 of file geomObjects.cpp.
{
      return (2. * d_r * d_r - d_r * (d_r - 2. * d_w)) * std::sin(M_PI / 3.);
    }
Field Documentation
d_a
util::Point util::geometry::Drum2D::d_a
Axis: defined as the vector pointing from center to the first vertex v3 v2.
+
                 +         o           +
                v4         x            v1
          +                                +
          v5                               v6
Axis is a unit vector from x to v1
Definition at line 1433 of file geomObjects.h.
Referenced by Drum2D().
d_r
double util::geometry::Drum2D::d_r
Distance between center and the farthest vertex.
Definition at line 1417 of file geomObjects.h.
Referenced by Drum2D().
d_vertices
std::vector<util::Point> util::geometry::Drum2D::d_vertices
Vertices.
Definition at line 1408 of file geomObjects.h.
Referenced by Drum2D().
d_w
double util::geometry::Drum2D::d_w
Half width of neck.
Definition at line 1414 of file geomObjects.h.
Referenced by Drum2D().
d_x
util::Point util::geometry::Drum2D::d_x
Center.
Definition at line 1411 of file geomObjects.h.
Referenced by Drum2D().
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp