PeriDEM: nsearch::TreeSearchResult< _DistanceType, _IndexType > Class Template Reference
nsearch::TreeSearchResult< _DistanceType, _IndexType > Class Template Reference
To collect results of nanoflann tree search. Default result output of nanoflann search uses std::vector<std::pair<size_t, double>>. We prefer to get the index and distance in a separate list.
#include <nflannSetup.h>
Public Types
typedef _DistanceType DistanceType
Distance type (double, float, etc)
typedef _IndexType IndexType
Index type (int, size_t, etc)
Public Member Functions
TreeSearchResult (DistanceType radius_, std::vector< IndexType > &indices, std::vector< DistanceType > &dists)
Constructor.
void init ()
Initialize the data (clear)
void clear ()
Clear the data.
size_t size () const
Get the size of currently stored (found so far) indices.
bool full () const
Check (not implemented)
bool addPoint (DistanceType dist, IndexType index)
Called during search to add an element matching the criteria.
DistanceType worstDist () const
Return maximum distance for search.
std::pair< IndexType, DistanceType > worst_item () const
Find the worst result (furtherest neighbor) without copying or sorting Pre-conditions: size() > 0.
Data Fields
const DistanceType d_r
Define search radius. Note this should be square of radius, where radius is a distance within which we are searching for points.
std::vector< IndexType > & d_indices
Indices within the search radius.
std::vector< DistanceType > & d_dists
Distance of points found within the search radius.
Detailed Description
template<typename _DistanceType, typename _IndexType = size_t>
class nsearch::TreeSearchResult< _DistanceType, _IndexType >
To collect results of nanoflann tree search. Default result output of nanoflann search uses std::vector<std::pair<size_t, double>>. We prefer to get the index and distance in a separate list.
Definition at line 86 of file nflannSetup.h.
Member Typedef Documentation
DistanceType
template<typename _DistanceType , typename _IndexType = size_t> typedef _DistanceType nsearch::TreeSearchResult< _DistanceType, _IndexType >::DistanceType
Distance type (double, float, etc)
Definition at line 89 of file nflannSetup.h.
IndexType
template<typename _DistanceType , typename _IndexType = size_t> typedef _IndexType nsearch::TreeSearchResult< _DistanceType, _IndexType >::IndexType
Index type (int, size_t, etc)
Definition at line 92 of file nflannSetup.h.
Constructor & Destructor Documentation
TreeSearchResult()
template<typename _DistanceType , typename _IndexType = size_t> nsearch::TreeSearchResult< _DistanceType, _IndexType >::TreeSearchResult (DistanceType radius_, std::vector< IndexType > & indices, std::vector< DistanceType > & dists) inline
Constructor.
Parameters
radius_ Search radius (square of radius)
indices Reference to index vector
dists Reference to distance vector
Definition at line 112 of file nflannSetup.h.
       : d_r(radius_), d_indices(indices), d_dists(dists) {
     init();
   }
References nsearch::TreeSearchResult< _DistanceType, _IndexType >::init().
Member Function Documentation
addPoint()
template<typename _DistanceType , typename _IndexType = size_t> bool nsearch::TreeSearchResult< _DistanceType, _IndexType >::addPoint (DistanceType dist, IndexType index) inline
Called during search to add an element matching the criteria.
Parameters
dist Distance of point from the search point
index Id of point
Returns
True True if continue the search further
Definition at line 152 of file nflannSetup.h.
{
     if (dist < d_r) {
       d_indices.push_back(index);
       d_dists.push_back(dist);
     }
     return true;
   }
References nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_dists, nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_indices, and nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_r.
clear()
template<typename _DistanceType , typename _IndexType = size_t> void nsearch::TreeSearchResult< _DistanceType, _IndexType >::clear () inline
Clear the data.
Definition at line 127 of file nflannSetup.h.
                       {
     d_indices.clear();
     d_dists.clear();
   }
References nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_dists, and nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_indices.
Referenced by nsearch::TreeSearchResult< _DistanceType, _IndexType >::init().
full()
template<typename _DistanceType , typename _IndexType = size_t> bool nsearch::TreeSearchResult< _DistanceType, _IndexType >::full () const inline
Check (not implemented)
Returns
bool Status
Definition at line 143 of file nflannSetup.h.
 { return true; }
init()
template<typename _DistanceType , typename _IndexType = size_t> void nsearch::TreeSearchResult< _DistanceType, _IndexType >::init () inline
Initialize the data (clear)
Definition at line 122 of file nflannSetup.h.
 { clear(); }
References nsearch::TreeSearchResult< _DistanceType, _IndexType >::clear().
Referenced by nsearch::TreeSearchResult< _DistanceType, _IndexType >::TreeSearchResult().
size()
template<typename _DistanceType , typename _IndexType = size_t> size_t nsearch::TreeSearchResult< _DistanceType, _IndexType >::size () const inline
Get the size of currently stored (found so far) indices.
Returns
size Size of indices data
Definition at line 137 of file nflannSetup.h.
 { return d_indices.size(); }
References nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_indices.
worst_item()
template<typename _DistanceType , typename _IndexType = size_t> std::pair<IndexType, DistanceType> nsearch::TreeSearchResult< _DistanceType, _IndexType >::worst_item () const inline
Find the worst result (furtherest neighbor) without copying or sorting Pre-conditions: size() > 0.
Currently, we return pair(0, 0.)
Returns
Pair Pair of id and max distanced point
Definition at line 174 of file nflannSetup.h.
{
     if (d_indices.empty())
       throw std::runtime_error("Cannot invoke RadiusResultSet::worst_item() on "
                                "an empty list of results.");
     return std::make_pair(0, 0.);
   }
References nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_indices.
worstDist()
template<typename _DistanceType , typename _IndexType = size_t> DistanceType nsearch::TreeSearchResult< _DistanceType, _IndexType >::worstDist () const inline
Return maximum distance for search.
Returns
Radius Maximum distance for search
Definition at line 164 of file nflannSetup.h.
 { return d_r; }
References nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_r.
Field Documentation
d_dists
template<typename _DistanceType , typename _IndexType = size_t> std::vector<DistanceType>& nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_dists
Distance of points found within the search radius.
Definition at line 103 of file nflannSetup.h.
Referenced by nsearch::TreeSearchResult< _DistanceType, _IndexType >::addPoint(), and nsearch::TreeSearchResult< _DistanceType, _IndexType >::clear().
d_indices
template<typename _DistanceType , typename _IndexType = size_t> std::vector<IndexType>& nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_indices
Indices within the search radius.
Definition at line 100 of file nflannSetup.h.
Referenced by nsearch::TreeSearchResult< _DistanceType, _IndexType >::addPoint(), nsearch::TreeSearchResult< _DistanceType, _IndexType >::clear(), nsearch::TreeSearchResult< _DistanceType, _IndexType >::size(), and nsearch::TreeSearchResult< _DistanceType, _IndexType >::worst_item().
d_r
template<typename _DistanceType , typename _IndexType = size_t> const DistanceType nsearch::TreeSearchResult< _DistanceType, _IndexType >::d_r
Define search radius. Note this should be square of radius, where radius is a distance within which we are searching for points.
Definition at line 97 of file nflannSetup.h.
Referenced by nsearch::TreeSearchResult< _DistanceType, _IndexType >::addPoint(), and nsearch::TreeSearchResult< _DistanceType, _IndexType >::worstDist().
The documentation for this class was generated from the following file:
/home/user/project/src/nsearch/nflannSetup.h