PeriDEM: particle::RefParticle Class Reference
particle::RefParticle Class Reference
A class to store reference particle related data. Consider a case of multiple hexagon-shaped particle related to each other by affine transformation. In such a case, it is possible to consider a reference hexagon particle and store the mesh and other details of only the reference particle. To get the data relevant to specific hexagon particle, one can apply the appropriate transformation on data for the reference hexagon particle.
#include <refParticle.h>
Public Member Functions
RefParticle (inp::ParticleZone *z_deck, fe::Mesh *mesh)
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Accessors
fe::Mesh * getMeshP ()
Get pointer to mesh object.
const fe::Mesh * getMeshP () const
Get pointer to mesh object.
fe::Mesh & getMesh ()
Get reference to mesh object.
const fe::Mesh & getMesh () const
Get reference to mesh object.
size_t getDimension () const
Get the dimension of the domain.
size_t getNumNodes () const
Get the number of nodes.
util::Point getNode (const size_t &i) const
Get reference coordinate of a node.
double getNodalVolume (const size_t &i) const
Get nodal volume.
size_t getCenterNodeId () const
Get id of center node of particle.
double getParticleRadius () const
Get radius of reference particle.
Private Attributes
std::unique_ptr< fe::Mesh > d_mesh_p
Pointer to mesh on reference particle.
size_t d_centerNode
Id of mesh node closest to the particle center.
std::shared_ptr< util::geometry::GeomObject > d_geom_p
Geometrical object defining this particle.
double d_pRadius
Particle radius.
std::vector< size_t > d_bNodes
List of nodes near boundary.
std::vector< uint8_t > d_intFlags
Interior flags. For given node i the flag is d_intFlags[i%8]. We use 1 bit per node.
Detailed Description
A class to store reference particle related data. Consider a case of multiple hexagon-shaped particle related to each other by affine transformation. In such a case, it is possible to consider a reference hexagon particle and store the mesh and other details of only the reference particle. To get the data relevant to specific hexagon particle, one can apply the appropriate transformation on data for the reference hexagon particle.
Definition at line 149 of file refParticle.h.
Constructor & Destructor Documentation
RefParticle()
particle::RefParticle::RefParticle (inp::ParticleZone * z_deck, fe::Mesh * mesh)
Constructor.
Parameters
z_deck Particle zone deck
mesh Pointer to mesh
Definition at line 18 of file refParticle.cpp.
    : d_mesh_p(mesh), d_centerNode(0), d_geom_p(z_deck->d_rParticle_p),
      d_pRadius(z_deck->d_rParticle_p->boundingRadius()) {
  if (d_pRadius < 1.0E-10) {
    std::cerr << "Error: Reference particle radius is too small.\n";
    exit(1);
  }
  // find the node which is closest to the particle center
  // also add node near boundary to list
  auto center = d_geom_p->center();
  auto dx = util::Point();
  double dist = d_geom_p->boundingRadius();
  for (size_t i = 0; i < mesh->getNumNodes(); i++) {
    dx = center - mesh->getNode(i);
    if (util::isLess(dx.length(), dist)) {
      dist = dx.length();
      d_centerNode = i;
    }
  }
}
References d_centerNode, d_geom_p, d_pRadius, fe::Mesh::getNode(), fe::Mesh::getNumNodes(), util::isLess(), and util::Point::length().
Member Function Documentation
getCenterNodeId()
size_t particle::RefParticle::getCenterNodeId () const inline
Get id of center node of particle.
Returns
Id Id of center node
Definition at line 219 of file refParticle.h.
{ return d_centerNode; };
References d_centerNode.
getDimension()
size_t particle::RefParticle::getDimension () const inline
Get the dimension of the domain.
Returns
N Dimension
Definition at line 185 of file refParticle.h.
{
    return d_mesh_p->getDimension();
  };
References d_mesh_p.
getMesh() [1/2]
fe::Mesh & particle::RefParticle::getMesh () inline
Get reference to mesh object.
Returns
mesh Reference to mesh
Definition at line 176 of file refParticle.h.
{ return *d_mesh_p; };
References d_mesh_p.
getMesh() [2/2]
const fe::Mesh & particle::RefParticle::getMesh () const inline
Get reference to mesh object.
Returns
mesh Reference to mesh
Definition at line 179 of file refParticle.h.
{ return *d_mesh_p; };
References d_mesh_p.
getMeshP() [1/2]
fe::Mesh * particle::RefParticle::getMeshP () inline
Get pointer to mesh object.
Returns
mesh Pointer to mesh
Definition at line 167 of file refParticle.h.
{ return d_mesh_p.get(); };
References d_mesh_p.
getMeshP() [2/2]
const fe::Mesh * particle::RefParticle::getMeshP () const inline
Get pointer to mesh object.
Returns
mesh Pointer to mesh
Definition at line 170 of file refParticle.h.
{ return d_mesh_p.get(); };
References d_mesh_p.
getNodalVolume()
double particle::RefParticle::getNodalVolume (const size_t & i) const inline
Get nodal volume.
Parameters
i Index of node
Returns
volume Nodal volume
Definition at line 211 of file refParticle.h.
{
    return d_mesh_p->getNodalVolume(i);
  };
References d_mesh_p.
getNode()
util::Point particle::RefParticle::getNode (const size_t & i) const inline
Get reference coordinate of a node.
Parameters
i Index of node
Returns
x Reference coordinate
Definition at line 202 of file refParticle.h.
{
    return d_mesh_p->getNode(i);
  };
References d_mesh_p.
getNumNodes()
size_t particle::RefParticle::getNumNodes () const inline
Get the number of nodes.
Returns
N number of nodes
Definition at line 193 of file refParticle.h.
{
    return d_mesh_p->getNumNodes();
  };
References d_mesh_p.
getParticleRadius()
double particle::RefParticle::getParticleRadius () const inline
Get radius of reference particle.
Returns
Radius Radius of reference particle
Definition at line 225 of file refParticle.h.
{ return d_pRadius; };
References d_pRadius.
print()
void particle::RefParticle::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 244 of file refParticle.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string particle::RefParticle::printStr (int nt = 0, int lvl = 0) const
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 41 of file refParticle.cpp.
{
  auto tabS = util::io::getTabS(nt);
  std::ostringstream oss;
  oss << tabS << "------- Reference particle --------" << std::endl
      << std::endl;
  oss << tabS << "Mesh pointer = " << d_mesh_p.get() << std::endl;
  oss << tabS << "Mesh info: " << std::endl;
  oss << d_mesh_p->printStr(nt + 1, lvl);
  oss << tabS << "Center node = " << d_centerNode << std::endl;
  oss << tabS << "Center node location = " << getNode(d_centerNode).printStr()
      << std::endl;
  oss << tabS << "Geometry info: " << std::endl;
  oss << d_geom_p->printStr(nt + 1, lvl);
  oss << tabS << "Radius = " << d_pRadius << std::endl;
  oss << tabS << "Num interior flag data = " << d_intFlags.size() << std::endl;
  oss << tabS << std::endl;
  return oss.str();
}
References util::io::getTabS().
Referenced by print().
Field Documentation
d_bNodes
std::vector<size_t> particle::RefParticle::d_bNodes private
List of nodes near boundary.
Definition at line 260 of file refParticle.h.
d_centerNode
size_t particle::RefParticle::d_centerNode private
Id of mesh node closest to the particle center.
Definition at line 251 of file refParticle.h.
Referenced by getCenterNodeId(), and RefParticle().
d_geom_p
std::shared_ptr<util::geometry::GeomObject> particle::RefParticle::d_geom_p private
Geometrical object defining this particle.
Definition at line 254 of file refParticle.h.
Referenced by RefParticle().
d_intFlags
std::vector<uint8_t> particle::RefParticle::d_intFlags private
Interior flags. For given node i the flag is d_intFlags[i%8]. We use 1 bit per node.
Definition at line 266 of file refParticle.h.
d_mesh_p
std::unique_ptr<fe::Mesh> particle::RefParticle::d_mesh_p private
Pointer to mesh on reference particle.
Definition at line 248 of file refParticle.h.
Referenced by getDimension(), getMesh(), getMesh(), getMeshP(), getMeshP(), getNodalVolume(), getNode(), and getNumNodes().
d_pRadius
double particle::RefParticle::d_pRadius private
Particle radius.
Definition at line 257 of file refParticle.h.
Referenced by getParticleRadius(), and RefParticle().
The documentation for this class was generated from the following files:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/particle/refParticle.h
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/particle/refParticle.cpp