PeriDEM: loading::ParticleULoading Class Reference
loading::ParticleULoading Class Reference
A class to apply displacement boundary condition.
#include <particleULoading.h>
Public Member Functions
ParticleULoading (std::vector< inp::PBCData > &bc_data)
Constructor.
void setFixityParticle (particle::BaseParticle *particle)
Sets fixity mask.
void setFixityWall (particle::BaseParticle *wall)
Sets fixity mask.
void setFixity (particle::BaseParticle *wall)
Sets fixity mask.
void applyParticle (const double &time, particle::BaseParticle *particle)
Applies displacement boundary condition.
void applyWall (const double &time, particle::BaseParticle *wall)
Applies displacement boundary condition.
void apply (const double &time, particle::BaseParticle *wall)
Applies displacement boundary condition.
Public Member Functions inherited from loading::ParticleLoading
ParticleLoading ()=default
Constructor.
Data Fields
std::vector< bool > d_pZeroDisplacementApplied
Flag to indicate whether particles are fixed.
std::vector< bool > d_wZeroDisplacementApplied
Flag to indicate whether particles are fixed.
Additional Inherited Members
Protected Attributes inherited from loading::ParticleLoading
std::vector< inp::PBCData > d_bcData
List of displacement bcs.
Detailed Description
A class to apply displacement boundary condition.
Definition at line 35 of file particleULoading.h.
Constructor & Destructor Documentation
ParticleULoading()
loading::ParticleULoading::ParticleULoading (std::vector< inp::PBCData > & bc_data)
Constructor.
Parameters
bc_data Boundary condition data
Definition at line 33 of file particleULoading.cpp.
{
   d_bcData = bc_data;
   d_pZeroDisplacementApplied = std::vector<bool>(d_bcData.size(), false);
   d_wZeroDisplacementApplied = std::vector<bool>(d_bcData.size(), false);
 }
References loading::ParticleLoading::d_bcData, d_pZeroDisplacementApplied, and d_wZeroDisplacementApplied.
Member Function Documentation
apply()
void loading::ParticleULoading::apply (const double & time, particle::BaseParticle * wall)
Applies displacement boundary condition.
Parameters
time Current time
wall Wall object pointer
Definition at line 141 of file particleULoading.cpp.
{
   if (particle->getType() == "particle")
     this->applyParticle(time, particle);
   else if (particle->getType() == "wall")
     this->applyWall(time, particle);
 }
applyParticle()
void loading::ParticleULoading::applyParticle (const double & time, particle::BaseParticle * particle)
Applies displacement boundary condition.
Parameters
time Current time
particle Particle object pointer
Definition at line 149 of file particleULoading.cpp.
{
   for (size_t s = 0; s < d_bcData.size(); s++) {
     // get alias for bc data
     const auto &bc = d_bcData[s];
     // if this is zero displacement condition, and if we have already applied
     // displacement then do not need to reapply this
     if (bc.d_isDisplacementZero && d_pZeroDisplacementApplied[s])
       continue;
     // set to true so that next time this is not called
     if (bc.d_isDisplacementZero)
       d_pZeroDisplacementApplied[s] = true;
     // check if we need to process this particle
     if ((bc.d_selectionType == "particle" ||
          bc.d_selectionType == "region_particle") &&
         !isInList(particle->getTypeId(), bc.d_pList))
       continue;
     if (bc.d_selectionType == "wall" || bc.d_selectionType == "region_wall")
       continue;
     // get bounding box
     auto box = bc.d_region_p->box();
     // for (size_t i = 0; i < particle->getNumNodes(); i++) {
     tf::Executor executor(util::parallel::getNThreads());
     tf::Taskflow taskflow;
     taskflow.for_each_index(
       (std::size_t) 0, particle->getNumNodes(), (std::size_t) 1,  [time, &particle, bc, box, this] (std::size_t i) {
         const auto x = particle->getXRefLocal(i);
         double umax = bc.d_timeFnParams[0];
         double du = 0.;
         double dv = 0.;
         bool compute_u_i = false;
         if (bc.d_selectionType == "region" && bc.d_region_p->isInside(x))
           compute_u_i = true;
         else if (bc.d_selectionType == "region_particle" &&
                   bc.d_region_p->isInside(x) &&
                   isInList(particle->getTypeId(), bc.d_pList))
           compute_u_i = true;
         else if (bc.d_selectionType == "particle" &&
                   isInList(particle->getTypeId(), bc.d_pList))
           compute_u_i = true;
         if (compute_u_i) {
           // apply spatial function
           if (bc.d_spatialFnType == "sin_x") {
             double a = M_PI * bc.d_spatialFnParams[0];
             umax = umax * std::sin(a * x.d_x);
           } else if (bc.d_spatialFnType == "sin_y") {
             double a = M_PI * bc.d_spatialFnParams[0];
             umax = umax * std::sin(a * x.d_y);
           } else if (bc.d_spatialFnType == "linear_x") {
             double a = bc.d_spatialFnParams[0];
             umax = umax * a * x.d_x;
           } else if (bc.d_spatialFnType == "linear_y") {
             double a = bc.d_spatialFnParams[0];
             umax = umax * a * x.d_y;
           }
           // apply time function
           if (bc.d_timeFnType == "constant")
             du = umax;
           else if (bc.d_timeFnType == "linear") {
             du = umax * time;
             dv = umax;
           } else if (bc.d_timeFnType == "quadratic") {
             du = umax * time + bc.d_timeFnParams[1] * time * time;
             dv = umax + bc.d_timeFnParams[1] * time;
           } else if (bc.d_timeFnType == "sin") {
             double a = M_PI * bc.d_timeFnParams[1];
             du = umax * std::sin(a * time);
             dv = umax * a * std::cos(a * time);
           }
           for (auto d : bc.d_direction) {
             particle->setULocal(i, d-1, du);
             particle->setVLocal(i, d-1, dv);
             auto xref = particle->getXRefLocal(i)[d-1];
             particle->setXLocal(i, d-1, du + xref);
           }
         } // if compute displacement
       }
     ); // for_each
     executor.run(taskflow).get();
   } // loop over bc sets
 }
References util::parallel::getNThreads(), and anonymous_namespace{particleULoading.cpp}::isInList().
applyWall()
void loading::ParticleULoading::applyWall (const double & time, particle::BaseParticle * wall)
Applies displacement boundary condition.
Parameters
time Current time
wall Wall object pointer
Definition at line 247 of file particleULoading.cpp.
{
   for (size_t s = 0; s < d_bcData.size(); s++) {
     // get alias for bc data
     const auto &bc = d_bcData[s];
     // if this is zero displacement condition, and if we have already applied
     // displacement then do not need to reapply this
     if (bc.d_isDisplacementZero && d_wZeroDisplacementApplied[s])
       continue;
     // set to true so that next time this is not called
     if (bc.d_isDisplacementZero)
       d_wZeroDisplacementApplied[s] = true;
     // check if we need to process this particle
     if ((bc.d_selectionType == "wall" || bc.d_selectionType == "region_wall") &&
         !isInList(wall->getTypeId(), bc.d_wList))
       continue;
     if (bc.d_selectionType == "particle" ||
         bc.d_selectionType == "region_particle")
       continue;
     // get bounding box
     auto box = bc.d_region_p->box();
     // for (size_t i = 0; i < wall->getNumNodes(); i++) {
     tf::Executor executor(util::parallel::getNThreads());
     tf::Taskflow taskflow;
     taskflow.for_each_index(
       (std::size_t) 0, wall->getNumNodes(), (std::size_t) 1, [time, &wall, bc, box, this] (std::size_t i) {
         const auto x = wall->getXRefLocal(i);
         double umax = bc.d_timeFnParams[0];
         double du = 0.;
         double dv = 0.;
         bool compute_u_i = false;
         if (bc.d_selectionType == "region" && bc.d_region_p->isInside(x))
           compute_u_i = true;
         else if (bc.d_selectionType == "region_wall" &&
                   bc.d_region_p->isInside(x) &&
                   isInList(wall->getTypeId(), bc.d_wList))
           compute_u_i = true;
         else if (bc.d_selectionType == "wall" &&
                   isInList(wall->getTypeId(), bc.d_wList))
           compute_u_i = true;
         if (compute_u_i) {
           // apply spatial function
           if (bc.d_spatialFnType == "sin_x") {
             double a = M_PI * bc.d_spatialFnParams[0];
             umax = umax * std::sin(a * x.d_x);
           } else if (bc.d_spatialFnType == "sin_y") {
             double a = M_PI * bc.d_spatialFnParams[0];
             umax = umax * std::sin(a * x.d_y);
           } else if (bc.d_spatialFnType == "linear_x") {
             double a = bc.d_spatialFnParams[0];
             umax = umax * a * x.d_x;
           } else if (bc.d_spatialFnType == "linear_y") {
             double a = bc.d_spatialFnParams[0];
             umax = umax * a * x.d_y;
           }
           // apply time function
           if (bc.d_timeFnType == "constant")
             du = umax;
           else if (bc.d_timeFnType == "linear") {
             du = umax * time;
             dv = umax;
           } else if (bc.d_timeFnType == "quadratic") {
             du = umax * time + bc.d_timeFnParams[1] * time * time;
             dv = umax + bc.d_timeFnParams[1] * time;
           } else if (bc.d_timeFnType == "sin") {
             double a = M_PI * bc.d_timeFnParams[1];
             du = umax * std::sin(a * time);
             dv = umax * a * std::cos(a * time);
           }
           auto u_i = util::Point();
           auto v_i = util::Point();
           for (auto d : bc.d_direction) {
             if (d == 1) {
               u_i.d_x = du;
               v_i.d_x = dv;
             } else if (d == 2) {
               u_i.d_y = du;
               v_i.d_y = dv;
             } else if (d == 3) {
               u_i.d_z = du;
               v_i.d_z = dv;
             }
           }
           if (bc.d_timeFnType == "rotation") {
             auto x0 = util::Point(bc.d_timeFnParams[1], bc.d_timeFnParams[2],
                                     bc.d_timeFnParams[3]);
             auto dx = x - x0;
             auto r_x = util::rotate2D(
                 dx, bc.d_timeFnParams[0] * time);
             auto dr_x = util::derRotate2D(
                 dx, bc.d_timeFnParams[0] * time);
             u_i += r_x - dx;
             v_i += bc.d_timeFnParams[0] * dr_x;
           }
           for (auto d : bc.d_direction) {
             wall->setULocal(i, d-1, u_i[d-1]);
             wall->setVLocal(i, d-1, v_i[d-1]);
             auto xref = wall->getXRefLocal(i)[d-1];
             wall->setXLocal(i, d-1, u_i[d-1] + xref);
           }
         } // if compute displacement
       }
     ); // for_each
     executor.run(taskflow).get();
   } // loop over bc sets
 }
References util::parallel::getNThreads(), particle::BaseParticle::getNumNodes(), particle::BaseParticle::getTypeId(), and anonymous_namespace{particleULoading.cpp}::isInList().
setFixity()
void loading::ParticleULoading::setFixity (particle::BaseParticle * wall)
Sets fixity mask.
Parameters
wall Wall object pointer
Definition at line 42 of file particleULoading.cpp.
{
   if (particle->getType() == "particle")
     this->setFixityParticle(particle);
   else if (particle->getType() == "wall")
     this->setFixityWall(particle);
 }
setFixityParticle()
void loading::ParticleULoading::setFixityParticle (particle::BaseParticle * particle)
Sets fixity mask.
Parameters
particle Particle object pointer
Definition at line 49 of file particleULoading.cpp.
{
   for (size_t s = 0; s < d_bcData.size(); s++) {
     // get alias for bc data
     const auto &bc = d_bcData[s];
     // check if we need to process this particle
     if ((bc.d_selectionType == "particle" ||
          bc.d_selectionType == "region_particle") &&
         !isInList(particle->getTypeId(), bc.d_pList))
       continue;
     if (bc.d_selectionType == "wall" || bc.d_selectionType == "region_wall")
       continue;
     // get bounding box
     auto box = bc.d_region_p->box();
     for (size_t i = 0; i < particle->getNumNodes(); i++) {
       const auto x = particle->getXRefLocal(i);
       bool compute_u_i = false;
       if (bc.d_selectionType == "region" && bc.d_region_p->isInside(x))
         compute_u_i = true;
       else if (bc.d_selectionType == "region_particle" &&
                bc.d_region_p->isInside(x) &&
                isInList(particle->getTypeId(), bc.d_pList))
         compute_u_i = true;
       else if (bc.d_selectionType == "particle" &&
                isInList(particle->getTypeId(), bc.d_pList))
         compute_u_i = true;
       if (!compute_u_i)
         continue;
       // set fixity to true
       for (auto d : bc.d_direction)
         particle->setFixLocal(i, d - 1, true);
     } // loop over nodes
   }   // loop over bc sets
 }
References particle_wall::d, and anonymous_namespace{particleULoading.cpp}::isInList().
setFixityWall()
void loading::ParticleULoading::setFixityWall (particle::BaseParticle * wall)
Sets fixity mask.
Parameters
wall Wall object pointer
Definition at line 93 of file particleULoading.cpp.
{
   for (size_t s = 0; s < d_bcData.size(); s++) {
     // get alias for bc data
     const auto &bc = d_bcData[s];
     // check if we need to process this particle
     if ((bc.d_selectionType == "wall" || bc.d_selectionType == "region_wall") &&
         !isInList(wall->getTypeId(), bc.d_wList))
       continue;
     if (bc.d_selectionType == "particle" ||
         bc.d_selectionType == "region_particle")
       continue;
     // get bounding box
     auto box = bc.d_region_p->box();
     for (size_t i = 0; i < wall->getNumNodes(); i++) {
       const auto x = wall->getXRefLocal(i);
       double umax = bc.d_timeFnParams[0];
       double du = 0.;
       double dv = 0.;
       bool compute_u_i = false;
       if (bc.d_selectionType == "region" && bc.d_region_p->isInside(x))
         compute_u_i = true;
       else if (bc.d_selectionType == "region_wall" &&
                bc.d_region_p->isInside(x) &&
                isInList(wall->getTypeId(), bc.d_wList))
         compute_u_i = true;
       else if (bc.d_selectionType == "wall" &&
                isInList(wall->getTypeId(), bc.d_wList))
         compute_u_i = true;
       if (!compute_u_i)
         continue;
       // set fixity to true
       for (auto d : bc.d_direction)
         wall->setFixLocal(i, d - 1, true);
     } // loop over nodes
   }   // loop over bc sets
 }
References particle_wall::d, particle::BaseParticle::getNumNodes(), particle::BaseParticle::getTypeId(), particle::BaseParticle::getXRefLocal(), anonymous_namespace{particleULoading.cpp}::isInList(), and particle::BaseParticle::setFixLocal().
Field Documentation
d_pZeroDisplacementApplied
std::vector<bool> loading::ParticleULoading::d_pZeroDisplacementApplied
Flag to indicate whether particles are fixed.
Definition at line 85 of file particleULoading.h.
Referenced by ParticleULoading().
d_wZeroDisplacementApplied
std::vector<bool> loading::ParticleULoading::d_wZeroDisplacementApplied
Flag to indicate whether particles are fixed.
Definition at line 88 of file particleULoading.h.
Referenced by ParticleULoading().
The documentation for this class was generated from the following files:
/home/user/project/src/loading/particleULoading.h
/home/user/project/src/loading/particleULoading.cpp