PeriDEM: material::Material Class Reference
material::Material Class Reference abstract
Collection of methods and database related to peridynamic material.
#include <material.h>
Public Member Functions
Material (std::string name="")
Constructor.
virtual ~Material ()
Destructor.
std::string name ()
Returns name of the material.
size_t getDimension ()
Returns dimension of the problem.
bool isPlaneStrain ()
Returns plane-strain condition.
virtual bool isStateActive () const =0
Returns true if state-based potential is active.
virtual std::pair< double, double > getBondEF (const double &r, const double &s, bool &fs, const bool &break_bonds) const =0
Returns energy and force between bond due to pairwise interaction.
virtual std::pair< double, double > getBondEF (const double &r, const double &s, bool &fs, const double &mx, const double &thetax) const =0
Returns energy and force between bond due to state-based model.
virtual util::Point getBondForceDirection (const util::Point &dx, const util::Point &du) const =0
Returns the unit vector along which bond-force acts.
virtual double getS (const util::Point &dx, const util::Point &du) const =0
Returns the bond strain.
virtual double getSc (const double &r) const =0
Returns critical bond strain.
virtual double getDensity () const =0
Returns the density of the material.
virtual double getInfFn (const double &r) const =0
Returns the value of influence function.
virtual double getMoment (const size_t &i) const =0
Returns the moment of influence function.
virtual double getHorizon () const =0
Returns horizon.
virtual inp::MatData computeMaterialProperties (const size_t &dim) const =0
Computes elastic and fracture material properties and returns the data.
virtual std::string printStr (int nt, int lvl) const
Returns the string containing printable information about the object.
virtual void print (int nt, int lvl) const
Prints the information about the object.
virtual void print () const
Prints the information about the object.
Private Attributes
std::string d_name
Name of the material.
Detailed Description
Collection of methods and database related to peridynamic material.
At present we have implemented both bond-based and state-based model. We consider RNP regularized potential proposed and studied in Lipton 2016, Jha and Lipton 2018, Diehl et al 2018, Jha and Lipton 2019. We have also implemented PMB material model (Prototypical micro-elastic brittle material), see Silling 2000.
A class providing methods to compute energy density and force of peridynamic material
Definition at line 76 of file material.h.
Constructor & Destructor Documentation
Material()
material::Material::Material (std::string name = "") inline explicit
Constructor.
Parameters
name Name of material model
Definition at line 83 of file material.h.
 : d_name(name) {}
~Material()
virtual material::Material::~Material () inline virtual
Destructor.
Make it virtual so that class inheriting from it are destroyed properly.
Definition at line 90 of file material.h.
 {}
Member Function Documentation
computeMaterialProperties()
virtual inp::MatData material::Material::computeMaterialProperties (const size_t & dim) const pure virtual
Computes elastic and fracture material properties and returns the data.
Parameters
dim Dimension of the problem
Returns
Data Material data
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getBondEF() [1/2]
virtual std::pair<double, double> material::Material::getBondEF (const double & r, const double & s, bool & fs, const bool & break_bonds) const pure virtual
Returns energy and force between bond due to pairwise interaction.
Parameters
r Reference (initial) bond length
s Bond strain
fs Bond fracture state
break_bonds Flag to specify whether bonds are allowed to break or not
Returns
value Pair of energy and force
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getBondEF() [2/2]
virtual std::pair<double, double> material::Material::getBondEF (const double & r, const double & s, bool & fs, const double & mx, const double & thetax) const pure virtual
Returns energy and force between bond due to state-based model.
Parameters
r Reference (initial) bond length
s Bond strain
fs Bond fracture state
mx Weighted volume at node
thetax Dilation
Returns
value Pair of energy and force
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getBondForceDirection()
virtual util::Point material::Material::getBondForceDirection (const util::Point & dx, const util::Point & du) const pure virtual
Returns the unit vector along which bond-force acts.
Parameters
dx Reference bond vector
du Difference of displacement
Returns
vector Unit vector
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getDensity()
virtual double material::Material::getDensity () const pure virtual
Returns the density of the material.
Returns
density Density of the material
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getDimension()
size_t material::Material::getDimension () inline
Returns dimension of the problem.
Returns
dim Dimension
Definition at line 102 of file material.h.
 { return dimension; }
References anonymous_namespace{material.h}::dimension.
getHorizon()
virtual double material::Material::getHorizon () const pure virtual
Returns horizon.
Returns
horizon Horizon
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getInfFn()
virtual double material::Material::getInfFn (const double & r) const pure virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getMoment()
virtual double material::Material::getMoment (const size_t & i) const pure virtual
Returns the moment of influence function.
If \(J(r) \) is the influence function for \(r\in [0,1)\) then \(i^{th}\) moment is given by
\[ M_i = \int_0^1 J(r) r^i dr. \]
Parameters
i ith moment
Returns
value Moment
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getS()
virtual double material::Material::getS (const util::Point & dx, const util::Point & du) const pure virtual
Returns the bond strain.
Parameters
dx Reference bond vector
du Difference of displacement
Returns
strain Bond strain \(S = \frac{du \cdot dx}{|dx|^2} \)
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
getSc()
virtual double material::Material::getSc (const double & r) const pure virtual
Returns critical bond strain.
Parameters
r Reference length of bond
Returns
strain Critical strain
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
isPlaneStrain()
bool material::Material::isPlaneStrain () inline
Returns plane-strain condition.
Returns
bool True if plane-strain active
Definition at line 108 of file material.h.
 { return is_plane_strain; }
References anonymous_namespace{material.h}::is_plane_strain.
isStateActive()
virtual bool material::Material::isStateActive () const pure virtual
Returns true if state-based potential is active.
Returns
bool True/false
Implemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
name()
std::string material::Material::name () inline
Returns name of the material.
Returns
string Name
Definition at line 96 of file material.h.
 { return d_name; }
References d_name.
print() [1/2]
virtual void material::Material::print () const inline virtual
Prints the information about the object.
Reimplemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
Definition at line 240 of file material.h.
 { print(0, 0); }
References print().
Referenced by print().
print() [2/2]
virtual void material::Material::print (int nt, int lvl) const inline virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
Definition at line 237 of file material.h.
 { std::cout << printStr(nt, lvl); }
References printStr().
printStr()
virtual std::string material::Material::printStr (int nt, int lvl) const inline virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented in material::PdState, material::PdElastic, material::PmbMaterial, and material::RnpMaterial.
Definition at line 217 of file material.h.
{
     auto tabS = util::io::getTabS(nt);
     std::ostringstream oss;
     oss << tabS << "------- particle::Material --------" << std::endl
         << std::endl;
     oss << tabS << "Abstract class of peridynamic materials" << std::endl;
     oss << tabS << "See RnpMaterial and PmbMaterial for implementation"
         << std::endl;
     oss << tabS << std::endl;
     return oss.str();
   }
References util::io::getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by print().
Field Documentation
d_name
std::string material::Material::d_name private
Name of the material.
Definition at line 244 of file material.h.
Referenced by name().
The documentation for this class was generated from the following file:
/home/user/project/src/material/mparticle/material.h