PeriDEM: util::geometry::Rectangle Class Reference
util::geometry::Rectangle Class Reference
Defines Rectangle.
#include <geomObjects.h>
Public Member Functions
Rectangle ()
Constructor.
Rectangle (double Lx, double Ly, util::Point x=util::Point(), std::string description="")
Constructor.
Rectangle (util::Point x1, util::Point x2, std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< util::Point > d_vertices
Vertices.
util::Point d_x
Center.
double d_Lx
Edge length of a rectangle in x-direction.
double d_Ly
Edge length of a rectangle in y-direction.
double d_r
Radius of bounding circle.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines Rectangle.
Definition at line 827 of file geomObjects.h.
Constructor & Destructor Documentation
Rectangle() [1/3]
util::geometry::Rectangle::Rectangle () inline
Constructor.
Definition at line 833 of file geomObjects.h.
                    : GeomObject("rectangle", ""),
                      d_Lx(0.),
                      d_Ly(0.),
                      d_r(0.),
                      d_x(util::Point()),
                      d_vertices({util::Point(), util::Point(),
                                  util::Point(), util::Point()}) {};
Rectangle() [2/3]
util::geometry::Rectangle::Rectangle (double Lx, double Ly, util::Point x = util::Point(), std::string description = "") inline
Constructor.
Parameters
Lx Length along x-direction
Ly Length along y-direction
x Center point
description Description of object (e.g., further classification or any tag)
Definition at line 850 of file geomObjects.h.
                    : GeomObject("rectangle", description),
                      d_Lx(Lx),
                      d_Ly(Ly),
                      d_r(0.5 * std::sqrt(std::pow(Lx, 2) + std::pow(Ly, 2))),
                      d_x(x) {
              d_vertices.push_back(
                      x + util::Point(-0.5 * d_Lx, -0.5 * d_Ly, 0.));
              d_vertices.push_back(
                      x + util::Point(0.5 * d_Lx, -0.5 * d_Ly, 0.));
              d_vertices.push_back(x + util::Point(0.5 * d_Lx, 0.5 * d_Ly, 0.));
              d_vertices.push_back(
                      x + util::Point(-0.5 * d_Lx, 0.5 * d_Ly, 0.));
            };
References d_Lx, d_Ly, and d_vertices.
Rectangle() [3/3]
util::geometry::Rectangle::Rectangle (util::Point x1, util::Point x2, std::string description = "") inline
Constructor.
Parameters
x1 Left-bottom corner point
x2 Right-top corner point
description Description of object (e.g., further classification or any tag)
Definition at line 874 of file geomObjects.h.
                    : GeomObject("rectangle", description),
                      d_Lx(x2.d_x - x1.d_x),
                      d_Ly(x2.d_y - x1.d_y),
                      d_r(0.5 *
                          std::sqrt(std::pow(d_Lx, 2) + std::pow(d_Ly, 2))),
                      d_x(0.5 * (x1 + x2)) {
              d_vertices.push_back(x1);
              d_vertices.push_back(util::Point(x1.d_x + d_Lx, x1.d_y, x1.d_z));
              d_vertices.push_back(x2);
              d_vertices.push_back(util::Point(x2.d_x - d_Lx, x2.d_y, x2.d_z));
            };
References d_Lx, d_vertices, util::Point::d_x, util::Point::d_y, and util::Point::d_z.
Member Function Documentation
boundingRadius()
double util::geometry::Rectangle::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 508 of file geomObjects.cpp.
{
      return d_r;
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Rectangle::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 489 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Rectangle::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 494 of file geomObjects.cpp.
{
      return {util::Point(d_vertices[0].d_x - tol, d_vertices[0].d_y - tol,
                          0.),
              util::Point(d_vertices[2].d_x + tol, d_vertices[2].d_y + tol,
                          0.)};
    }
center()
util::Point util::geometry::Rectangle::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 485 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Rectangle::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 580 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(2, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Rectangle::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 547 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Rectangle::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 503 of file geomObjects.cpp.
{
      return util::isLess(d_Lx, d_Ly) ? d_Lx : d_Ly;
    }
References util::isLess().
isInside() [1/2]
bool util::geometry::Rectangle::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 552 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(2, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Rectangle::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 513 of file geomObjects.cpp.
{
      return util::isPointInsideRectangle(x, d_vertices[0], d_vertices[2]);
    }
References util::isPointInsideRectangle().
isNear() [1/2]
bool util::geometry::Rectangle::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 573 of file geomObjects.cpp.
{
      return util::areBoxesNear(this->box(), box, tol, 2);
    }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Rectangle::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 521 of file geomObjects.cpp.
{
      // get a bigger box containing this object
      auto bbox = box(tol);
      return util::isPointInsideBox(x, 2, bbox);
    }
References util::isPointInsideBox().
isNearBoundary()
bool util::geometry::Rectangle::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 530 of file geomObjects.cpp.
{
      // check if particle is inside the object
      if (!isNear(x, within ? 0. : tol))
        return false;
      bool near_x_edge = util::isLess(std::abs(x.d_x - d_vertices[0].d_x), tol) or
                         util::isLess(std::abs(x.d_x - d_vertices[2].d_x), tol);
      bool near_y_edge = util::isLess(std::abs(x.d_y - d_vertices[0].d_y), tol) or
                         util::isLess(std::abs(x.d_y - d_vertices[2].d_y), tol);
      return near_x_edge || near_y_edge;
    }
References util::Point::d_x, util::Point::d_y, and util::isLess().
isOutside() [1/2]
bool util::geometry::Rectangle::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 562 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(2, box))
        if (!intersect)
          intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Rectangle::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 517 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Rectangle::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 1006 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Rectangle::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 999 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Rectangle::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 591 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Rectangle --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Lengths (Lx, Ly) = (" << d_Lx << ", " << d_Ly << ")" << std::endl;
      oss << tabS << "Bounding circle radius = " << d_r << std::endl;
      oss << tabS << "Vertices = " << util::io::printStr(d_vertices, 0) << std::endl;
      oss << std::endl;
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), util::io::printBoxStr(), and util::io::printStr().
Referenced by print().
volume()
double util::geometry::Rectangle::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 481 of file geomObjects.cpp.
{
      return d_Lx * d_Ly;
    }
Field Documentation
d_Lx
double util::geometry::Rectangle::d_Lx
Edge length of a rectangle in x-direction.
Definition at line 1015 of file geomObjects.h.
Referenced by Rectangle(), and Rectangle().
d_Ly
double util::geometry::Rectangle::d_Ly
Edge length of a rectangle in y-direction.
Definition at line 1018 of file geomObjects.h.
Referenced by Rectangle().
d_r
double util::geometry::Rectangle::d_r
Radius of bounding circle.
Definition at line 1021 of file geomObjects.h.
d_vertices
std::vector<util::Point> util::geometry::Rectangle::d_vertices
Vertices.
Definition at line 1009 of file geomObjects.h.
Referenced by Rectangle(), and Rectangle().
d_x
util::Point util::geometry::Rectangle::d_x
Center.
Definition at line 1012 of file geomObjects.h.
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp