PeriDEM: material::LinearInfluenceFn Class Reference
material::LinearInfluenceFn Class Reference
A class to implement linear influence function.
#include <influenceFn.h>
Public Member Functions
LinearInfluenceFn (const std::vector< double > &params, const size_t &dim)
Constructor.
double getInfFn (const double &r) const override
Returns the value of influence function.
double getMoment (const size_t &i) const override
Returns the moment of influence function.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Public Member Functions inherited from material::BaseInfluenceFn
BaseInfluenceFn ()=default
Constructor.
Private Attributes
double d_a0
Constants such that J(r) = d_a0 + d_a1 * r.
double d_a1
Constants such that J(r) = d_a0 + d_a1 * r.
Detailed Description
A class to implement linear influence function.
\(J(r) = a0 + a1 r \)
Definition at line 151 of file influenceFn.h.
Constructor & Destructor Documentation
LinearInfluenceFn()
material::LinearInfluenceFn::LinearInfluenceFn (const std::vector< double > & params, const size_t & dim)
Constructor.
Parameters
params List of parameters
dim Dimension
Definition at line 29 of file influenceFn.cpp.
     : BaseInfluenceFn(), d_a0(0.), d_a1(0.) {
   if (params.empty()) {
     // choose a0, a1 = -a0 such that \int_0^1 J(r) r^d dr = 1
     // and J(r) = a0 (1 - r)
     if (dim == 1) {
       d_a0 = 6.;
       d_a1 = -d_a0;
     } else if (dim == 2) {
       d_a0 = 12.;
       d_a1 = -d_a0;
     } else if (dim == 3) {
       d_a0 = 20.;
       d_a1 = -d_a0;
     }
   } else {
     d_a0 = params[0];
     if (params.size() < 2)
       d_a1 = -d_a0;
     else
       d_a1 = params[1];
   }
 }
References d_a0, and d_a1.
Member Function Documentation
getInfFn()
double material::LinearInfluenceFn::getInfFn (const double & r) const override virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implements material::BaseInfluenceFn.
Definition at line 55 of file influenceFn.cpp.
{
   return d_a0 + d_a1 * r;
 }
getMoment()
double material::LinearInfluenceFn::getMoment (const size_t & i) const override virtual
Returns the moment of influence function.
If \(J(r) \) is the influence function for \(r\in [0,1)\) then \(i^{th}\) moment is given by
\[ M_i = \int_0^1 J(r) r^i dr. \]
Parameters
i ith moment
Returns
moment Moment
Implements material::BaseInfluenceFn.
Definition at line 59 of file influenceFn.cpp.
{
   return (d_a0 / double(i + 1)) + (d_a1 / double(i + 2));
 }
Referenced by printStr().
print() [1/2]
void material::LinearInfluenceFn::print () const inline override virtual
Prints the information about the object.
Reimplemented from material::BaseInfluenceFn.
Definition at line 213 of file influenceFn.h.
 { print(0, 0); }
References print().
Referenced by print().
print() [2/2]
void material::LinearInfluenceFn::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from material::BaseInfluenceFn.
Definition at line 208 of file influenceFn.h.
{
     std::cout << printStr(nt, lvl);
   }
References printStr().
printStr()
std::string material::LinearInfluenceFn::printStr (int nt, int lvl) const inline override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from material::BaseInfluenceFn.
Definition at line 187 of file influenceFn.h.
{
     auto tabS = util::io::getTabS(nt);
     std::ostringstream oss;
     oss << tabS << "------- LinearInfluenceFn --------" << std::endl << std::endl;
     oss << tabS << "Linear function a0 + a1*r with constants: a0 = "
                 << d_a0 << ", a1 = " << d_a1 << std::endl;
     oss << tabS << "First moment = " << getMoment(1)
         << ", second moment = " << getMoment(2)
         << ", third moment = " << getMoment(3) << std::endl;
     oss << tabS << std::endl;
     return oss.str();
   }
References d_a0, d_a1, getMoment(), util::io::getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by print().
Field Documentation
d_a0
double material::LinearInfluenceFn::d_a0 private
Constants such that J(r) = d_a0 + d_a1 * r.
Definition at line 217 of file influenceFn.h.
Referenced by LinearInfluenceFn(), and printStr().
d_a1
double material::LinearInfluenceFn::d_a1 private
Constants such that J(r) = d_a0 + d_a1 * r.
Definition at line 220 of file influenceFn.h.
Referenced by LinearInfluenceFn(), and printStr().
The documentation for this class was generated from the following files:
/home/user/project/src/material/mparticle/influenceFn.h
/home/user/project/src/material/mparticle/influenceFn.cpp