PeriDEM: material::ConstInfluenceFn Class Reference
material::ConstInfluenceFn Class Reference
A class to implement constant influence function.
#include <influenceFn.h>
Public Member Functions
ConstInfluenceFn (const std::vector< double > &params, const size_t &dim)
Constructor.
double getInfFn (const double &r) const override
Returns the value of influence function.
double getMoment (const size_t &i) const override
Returns the moment of influence function.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Public Member Functions inherited from material::BaseInfluenceFn
BaseInfluenceFn ()=default
Constructor.
Private Attributes
double d_a0
Constant such that J(r) = Constant.
Detailed Description
A class to implement constant influence function.
Definition at line 79 of file influenceFn.h.
Constructor & Destructor Documentation
ConstInfluenceFn()
material::ConstInfluenceFn::ConstInfluenceFn (const std::vector< double > & params, const size_t & dim)
Constructor.
Parameters
params List of parameters
dim Dimension
Definition at line 14 of file influenceFn.cpp.
     : BaseInfluenceFn(), d_a0(0.) {
   d_a0 = params.empty() ? double(dim + 1) : params[0];
 }
References d_a0.
Member Function Documentation
getInfFn()
double material::ConstInfluenceFn::getInfFn (const double & r) const override virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implements material::BaseInfluenceFn.
Definition at line 21 of file influenceFn.cpp.
{
   return d_a0;
 }
getMoment()
double material::ConstInfluenceFn::getMoment (const size_t & i) const override virtual
Returns the moment of influence function.
If \(J(r) \) is the influence function for \(r\in [0,1)\) then \(i^{th}\) moment is given by
\[ M_i = \int_0^1 J(r) r^i dr. \]
Parameters
i ith moment
Returns
moment Moment
Implements material::BaseInfluenceFn.
Definition at line 25 of file influenceFn.cpp.
{
   return d_a0 / double(i + 1);
 }
Referenced by printStr().
print() [1/2]
void material::ConstInfluenceFn::print () const inline override virtual
Prints the information about the object.
Reimplemented from material::BaseInfluenceFn.
Definition at line 140 of file influenceFn.h.
 { print(0, 0); }
References print().
Referenced by print().
print() [2/2]
void material::ConstInfluenceFn::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from material::BaseInfluenceFn.
Definition at line 135 of file influenceFn.h.
{
     std::cout << printStr(nt, lvl);
   }
References printStr().
printStr()
std::string material::ConstInfluenceFn::printStr (int nt, int lvl) const inline override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from material::BaseInfluenceFn.
Definition at line 115 of file influenceFn.h.
{
     auto tabS = util::io::getTabS(nt);
     std::ostringstream oss;
     oss << tabS << "------- ConstInfluenceFn --------" << std::endl << std::endl;
     oss << tabS << "Constant function with constant = " << d_a0 << std::endl;
     oss << tabS << "First moment = " << getMoment(1)
               << ", second moment = " << getMoment(2)
               << ", third moment = " << getMoment(3) << std::endl;
     oss << tabS << std::endl;
     return oss.str();
   }
References d_a0, getMoment(), util::io::getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by print().
Field Documentation
d_a0
double material::ConstInfluenceFn::d_a0 private
Constant such that J(r) = Constant.
Definition at line 144 of file influenceFn.h.
Referenced by ConstInfluenceFn(), and printStr().
The documentation for this class was generated from the following files:
/home/user/project/src/material/mparticle/influenceFn.h
/home/user/project/src/material/mparticle/influenceFn.cpp