PeriDEM: material::PmbMaterial Class Reference
material::PmbMaterial Class Reference
A class providing methods to compute energy density and force of peridynamic material.
#include <material.h>
Public Member Functions
PmbMaterial (inp::MaterialDeck &deck, const size_t &dim, const double &horizon)
Constructor.
bool isStateActive () const override
Returns true if state-based potential is active.
std::pair< double, double > getBondEF (const double &r, const double &s, bool &fs, const bool &break_bonds) const override
Returns energy and force between bond due to pairwise interaction.
std::pair< double, double > getBondEF (const double &r, const double &s, bool &fs, const double &mx, const double &thetax) const override
Returns energy and force between bond due to state-based model.
util::Point getBondForceDirection (const util::Point &dx, const util::Point &du) const override
Returns the unit vector along which bond-force acts.
double getS (const util::Point &dx, const util::Point &du) const override
Returns the bond strain.
double getSc (const double &r) const override
Returns critical bond strain.
double getDensity () const override
Returns the density of the material.
double getInfFn (const double &r) const override
Returns the value of influence function.
double getMoment (const size_t &i) const override
Returns the moment of influence function.
double getHorizon () const override
Returns horizon.
inp::MatData computeMaterialProperties (const size_t &dim) const override
Computes elastic and fracture material properties and returns the data.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Public Member Functions inherited from material::Material
Material (std::string name="")
Constructor.
virtual ~Material ()
Destructor.
std::string name ()
Returns name of the material.
size_t getDimension ()
Returns dimension of the problem.
bool isPlaneStrain ()
Returns plane-strain condition.
Private Member Functions
void computeParameters (inp::MaterialDeck &deck, const size_t &dim)
Compute material model parameters.
Private Attributes
double d_horizon
Horizon.
double d_density
Density.
Material parameters
double d_c
Parameter C.
double d_s0
Parameter \(\beta \).
Detailed Description
A class providing methods to compute energy density and force of peridynamic material.
Definition at line 665 of file material.h.
Constructor & Destructor Documentation
PmbMaterial()
material::PmbMaterial::PmbMaterial (inp::MaterialDeck & deck, const size_t & dim, const double & horizon) inline
Constructor.
Parameters
deck Input deck which contains user-specified information
dim Dimension
horizon Horizon
Definition at line 674 of file material.h.
       : Material("PMBBond"), d_horizon(horizon), d_density(deck.d_density),
         d_c(0.), d_s0(0.) {
     // set global fields
     if (dimension != dim)
       dimension = dim;
     if (is_plane_strain != deck.d_isPlaneStrain)
       is_plane_strain = deck.d_isPlaneStrain;
     // create influence function
     if (deck.d_influenceFnType == 0) {
       if (influence_fn == nullptr)
         influence_fn = std::make_shared<material::ConstInfluenceFn>(
             deck.d_influenceFnParams, dim);
     }
     else if (deck.d_influenceFnType == 1) {
       if (influence_fn == nullptr)
         influence_fn = std::make_shared<material::LinearInfluenceFn>(
             deck.d_influenceFnParams, dim);
     }
     else if (deck.d_influenceFnType == 2) {
       if (influence_fn == nullptr)
         influence_fn = std::make_shared<material::GaussianInfluenceFn>(
             deck.d_influenceFnParams, dim);
     }
     else {
       std::cerr << "Error: Influence function type = "
                 << deck.d_influenceFnType
                 << " is invalid.\n";
       exit(1);
     }
     // check if we need to compute the material parameters
     if (deck.d_computeParamsFromElastic)
       computeParameters(deck, dim);
     else {
       d_c = deck.d_bondPotentialParams[0];
       d_s0 = deck.d_bondPotentialParams[1];
     }
   };
References computeParameters(), inp::MaterialDeck::d_bondPotentialParams, d_c, inp::MaterialDeck::d_computeParamsFromElastic, inp::MaterialDeck::d_influenceFnParams, inp::MaterialDeck::d_influenceFnType, inp::MaterialDeck::d_isPlaneStrain, d_s0, anonymous_namespace{material.h}::dimension, anonymous_namespace{material.h}::influence_fn, and anonymous_namespace{material.h}::is_plane_strain.
Member Function Documentation
computeMaterialProperties()
inp::MatData material::PmbMaterial::computeMaterialProperties (const size_t & dim) const inline override virtual
Computes elastic and fracture material properties and returns the data.
Parameters
dim Dimension of the problem
Returns
inp::MatData Material data
Implements material::Material.
Definition at line 846 of file material.h.
{
     auto data = inp::MatData();
     // set Poisson's ratio to 1/4
     data.d_nu = 0.25;
     // compute peridynamic parameters
     if (dim == 2) {
       data.d_lambda = d_c * (M_PI * std::pow(d_horizon, 3.0)) / 24.0;
       data.d_E = data.toELambda(data.d_lambda, data.d_nu);
       data.d_Gc = d_s0 * d_s0 * (9.0 * data.d_E * d_horizon) / (5.0 * M_PI);
     } else if (dim == 3) {
       data.d_lambda = d_c * (M_PI * std::pow(d_horizon, 3.0)) / 24.0;
       data.d_E = data.toELambda(data.d_lambda, data.d_nu);
       data.d_Gc = d_s0 * d_s0 * (9.0 * data.d_E * d_horizon) / (5.0 * M_PI);
     }
     data.d_mu = data.d_lambda;
     data.d_G = data.d_lambda;
     data.d_K =
         data.toK(data.d_E, data.d_nu);
     data.d_KIc = data.toKIc(
         data.d_Gc, data.d_nu, data.d_E);
     return data;
   };
References d_c, d_horizon, and d_s0.
computeParameters()
void material::PmbMaterial::computeParameters (inp::MaterialDeck & deck, const size_t & dim) inline private
Compute material model parameters.
Parameters
deck MaterialDeck
dim Dimension of the domain
Definition at line 919 of file material.h.
{
     //
     // Need following elastic and fracture properties
     // 1. E or K
     // 2. Gc or KIc
     // For bond-based, Poisson's ratio is fixed to 1/4
     //
     if (util::isLess(deck.d_matData.d_E, 0.) &&
         util::isLess(deck.d_matData.d_K, 0.)) {
       std::cerr << "Error: Require either Young's modulus E or Bulk modulus K"
                    " to compute the RNP bond-based peridynamic parameters.\n";
       exit(1);
     }
     if (util::isGreater(deck.d_matData.d_E, 0.) &&
         util::isGreater(deck.d_matData.d_K, 0.)) {
       std::cout << "Warning: Both Young's modulus E and Bulk modulus K are "
                    "provided.\n";
       std::cout << "Warning: To compute the RNP bond-based peridynamic "
                    "parameters, we only require one of those.\n";
       std::cout
           << "Warning: Selecting Young's modulus to compute parameters.\n";
     }
     if (util::isLess(deck.d_matData.d_Gc, 0.) &&
         util::isLess(deck.d_matData.d_KIc, 0.)) {
       std::cerr << "Error: Require either critical energy release rate Gc or "
                    "critical stress intensity factor KIc to compute the RNP "
                    "bond-based peridynamic parameters.\n";
       exit(1);
     } else if (util::isGreater(deck.d_matData.d_Gc, 0.) &&
                util::isGreater(deck.d_matData.d_KIc, 0.)) {
       std::cout << "Warning: Both critical energy release rate Gc and critical "
                    "stress intensity factor KIc are provided.\n";
       std::cout << "Warning: To compute the RNP bond-based peridynamic "
                    "parameters, we only require one of those.\n";
       std::cout << "Warning: Selecting critical energy release rate Gc to "
                    "compute parameters.\n";
     }
     // set Poisson's ratio to 1/4
     deck.d_matData.d_nu = 0.25;
     // compute E if not provided or K if not provided
     if (deck.d_matData.d_E > 0.)
       deck.d_matData.d_K =
           deck.d_matData.toK(deck.d_matData.d_E, deck.d_matData.d_nu);
     if (deck.d_matData.d_K > 0. && deck.d_matData.d_E < 0.)
       deck.d_matData.d_E =
           deck.d_matData.toE(deck.d_matData.d_K, deck.d_matData.d_nu);
     if (deck.d_matData.d_Gc > 0.)
       deck.d_matData.d_KIc = deck.d_matData.toKIc(
           deck.d_matData.d_Gc, deck.d_matData.d_nu, deck.d_matData.d_E);
     if (deck.d_matData.d_KIc > 0. && deck.d_matData.d_Gc < 0.)
       deck.d_matData.d_Gc = deck.d_matData.toGc(
           deck.d_matData.d_KIc, deck.d_matData.d_nu, deck.d_matData.d_E);
     // compute lame parameter
     deck.d_matData.d_lambda =
         deck.d_matData.toLambdaE(deck.d_matData.d_E, deck.d_matData.d_nu);
     deck.d_matData.d_G =
         deck.d_matData.toGE(deck.d_matData.d_E, deck.d_matData.d_nu);
     deck.d_matData.d_mu = deck.d_matData.d_G;
     // compute peridynamic parameters
     if (dim == 2) {
       // Ha, Bobaru 2010 "Studies of dynamic crack propagation and crack branching
       // with peridynamics"
       d_c = 24.0 * deck.d_matData.d_E / (M_PI * std::pow(d_horizon, 3.0) *
                       (1. - deck.d_matData.d_nu));
       d_s0 = std::sqrt(5.0 * M_PI * deck.d_matData.d_Gc /
                        (9.0 * deck.d_matData.d_E * d_horizon));
     } else if (dim == 3) {
       d_c = 24.0 * deck.d_matData.d_lambda / (M_PI * std::pow(d_horizon, 3.0));
       d_s0 = std::sqrt(5.0 * M_PI * deck.d_matData.d_Gc /
                        (9.0 * deck.d_matData.d_E * d_horizon));
     }
   };
References d_c, inp::MatData::d_E, inp::MatData::d_G, inp::MatData::d_Gc, d_horizon, inp::MatData::d_K, inp::MatData::d_KIc, inp::MatData::d_lambda, inp::MaterialDeck::d_matData, inp::MatData::d_mu, inp::MatData::d_nu, d_s0, util::isGreater(), util::isLess(), inp::MatData::toE(), inp::MatData::toGc(), inp::MatData::toGE(), inp::MatData::toK(), inp::MatData::toKIc(), and inp::MatData::toLambdaE().
Referenced by PmbMaterial().
getBondEF() [1/2]
std::pair<double, double> material::PmbMaterial::getBondEF (const double & r, const double & s, bool & fs, const bool & break_bonds) const inline override virtual
Returns energy and force between bond due to pairwise interaction.
Parameters
r Reference (initial) bond length
s Bond strain
fs Bond fracture state
break_bonds Flag to specify whether bonds are allowed to break or not
Returns
value Pair of energy and force
Implements material::Material.
Definition at line 732 of file material.h.
{
     if (!break_bonds)
       return std::make_pair(getInfFn(r) * 0.5 * d_c * s *
                                 s * r,
                             getInfFn(r) * d_c * s);
     // check if fracture state of the bond need to be updated
     if (!fs && util::isGreater(std::abs(s), d_s0 + 1.0e-10))
       fs = true;
     // if bond is not fractured, return energy and force from nonlinear
     // potential otherwise return energy of fractured bond, and zero force
     if (!fs)
       return std::make_pair(getInfFn(r) * 0.5 * d_c * s *
                                 s * r,
                             getInfFn(r) * d_c * s);
     else
       return std::make_pair(
           getInfFn(r) * 0.5 * d_c * d_s0 * d_s0 * r, 0.);
   };
References d_c, d_s0, getInfFn(), and util::isGreater().
Referenced by getBondEF().
getBondEF() [2/2]
std::pair<double, double> material::PmbMaterial::getBondEF (const double & r, const double & s, bool & fs, const double & mx, const double & thetax) const inline override virtual
Returns energy and force between bond due to state-based model.
Parameters
r Reference (initial) bond length
s Bond strain
fs Bond fracture state
mx Weighted volume at node
thetax Dilation
Returns
value Pair of energy and force
Implements material::Material.
Definition at line 767 of file material.h.
{
     return this->getBondEF(r, s, fs, true);
   };
References getBondEF().
getBondForceDirection()
util::Point material::PmbMaterial::getBondForceDirection (const util::Point & dx, const util::Point & du) const inline override virtual
Returns the unit vector along which bond-force acts.
Parameters
dx Reference bond vector
du Difference of displacement
Returns
vector Unit vector
Implements material::Material.
Definition at line 780 of file material.h.
{
     return (dx + du) / (dx + du).length();
   };
getDensity()
double material::PmbMaterial::getDensity () const inline override virtual
Returns the density of the material.
Returns
density Density of the material
Implements material::Material.
Definition at line 807 of file material.h.
 { return d_density; };
References d_density.
getHorizon()
double material::PmbMaterial::getHorizon () const inline override virtual
Returns horizon.
Returns
horizon Horizon
Implements material::Material.
Definition at line 837 of file material.h.
 { return d_horizon; };
References d_horizon.
getInfFn()
double material::PmbMaterial::getInfFn (const double & r) const inline override virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implements material::Material.
Definition at line 815 of file material.h.
{
     return getGlobalInfFn(r / d_horizon);
   };
References d_horizon, and anonymous_namespace{material.h}::getGlobalInfFn().
Referenced by getBondEF().
getMoment()
double material::PmbMaterial::getMoment (const size_t & i) const inline override virtual
Returns the moment of influence function.
If \(J(r) \) is the influence function for \(r\in [0,1)\) then \(i^{th}\) moment is given by
\[ M_i = \int_0^1 J(r) r^i dr. \]
Parameters
i ith moment
Returns
value Moment
Implements material::Material.
Definition at line 828 of file material.h.
{
     return getGlobalMoment(i);
   };
References anonymous_namespace{material.h}::getGlobalMoment().
getS()
double material::PmbMaterial::getS (const util::Point & dx, const util::Point & du) const inline override virtual
Returns the bond strain.
Parameters
dx Reference bond vector
du Difference of displacement
Returns
strain Bond strain \(S = \frac{du \cdot dx}{|dx|^2} \)
Implements material::Material.
Definition at line 791 of file material.h.
{
     return ((dx + du).length() - dx.length()) / dx.length();
   };
References util::Point::length().
getSc()
double material::PmbMaterial::getSc (const double & r) const inline override virtual
Returns critical bond strain.
Parameters
r Reference length of bond
Returns
strain Critical strain
Implements material::Material.
Definition at line 801 of file material.h.
 { return d_s0; };
References d_s0.
isStateActive()
bool material::PmbMaterial::isStateActive () const inline override virtual
Returns true if state-based potential is active.
Returns
bool True/false
Implements material::Material.
Definition at line 721 of file material.h.
 { return false; };
print() [1/2]
void material::PmbMaterial::print () const inline override virtual
Prints the information about the object.
Reimplemented from material::Material.
Definition at line 910 of file material.h.
 { print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void material::PmbMaterial::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from material::Material.
Definition at line 905 of file material.h.
{
     std::cout << printStr(nt, lvl);
   };
References printStr().
printStr()
std::string material::PmbMaterial::printStr (int nt, int lvl) const inline override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from material::Material.
Definition at line 880 of file material.h.
{
     auto tabS = util::io::getTabS(nt);
     std::ostringstream oss;
     oss << tabS << "------- particle::PmbMaterial --------" << std::endl
         << std::endl;
     oss << tabS << "State active = " << 0 << std::endl;
     oss << tabS << "Horizon = " << d_horizon << std::endl;
     oss << tabS << "Influence fn address = " << influence_fn.get() << std::endl;
     oss << tabS << "Influence fn info: " << std::endl;
     oss << influence_fn->printStr(nt + 1, lvl);
     oss << tabS << "Peridynamic parameters: " << std::endl;
     oss << tabS << "  c = " << d_c << std::endl;
     oss << tabS << "  s0 = " << d_s0 << std::endl;
     oss << tabS << std::endl;
     return oss.str();
   };
References d_c, d_horizon, d_s0, util::io::getTabS(), anonymous_namespace{material.h}::influence_fn, and anonymous_namespace{main.cpp}::oss.
Referenced by print().
Field Documentation
d_c
double material::PmbMaterial::d_c private
Parameter C.
Definition at line 1013 of file material.h.
Referenced by computeMaterialProperties(), computeParameters(), getBondEF(), PmbMaterial(), and printStr().
d_density
double material::PmbMaterial::d_density private
Density.
Definition at line 1005 of file material.h.
Referenced by getDensity().
d_horizon
double material::PmbMaterial::d_horizon private
Horizon.
Definition at line 998 of file material.h.
Referenced by computeMaterialProperties(), computeParameters(), getHorizon(), getInfFn(), and printStr().
d_s0
double material::PmbMaterial::d_s0 private
Parameter \(\beta \).
Definition at line 1016 of file material.h.
Referenced by computeMaterialProperties(), computeParameters(), getBondEF(), getSc(), PmbMaterial(), and printStr().
The documentation for this class was generated from the following file:
/home/user/project/src/material/mparticle/material.h