PeriDEM: util::geometry::Hexagon Class Reference
util::geometry::Hexagon Class Reference
Defines Hexagon.
#include <geomObjects.h>
Public Member Functions
Hexagon ()
Constructor.
Hexagon (double r, util::Point x=util::Point(0., 0., 0.), util::Point a=util::Point(1., 0., 0.), std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
TODO implement methods robustly
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< util::Point > d_vertices
Vertices.
util::Point d_x
Center.
double d_r
Distance between center and the farthest vertex of hexagon.
util::Point d_a
Axis: defined as the vector pointing from center to the first vertex.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines Hexagon.
Definition at line 1027 of file geomObjects.h.
Constructor & Destructor Documentation
Hexagon() [1/2]
util::geometry::Hexagon::Hexagon () inline
Constructor.
Definition at line 1033 of file geomObjects.h.
                    : GeomObject("hexagon", ""),
                      d_r(0.),
                      d_a(util::Point(1., 0., 0.)),
                      d_x(util::Point()),
                      d_vertices(std::vector<util::Point>(6, util::Point())) {};
Hexagon() [2/2]
util::geometry::Hexagon::Hexagon (double r, util::Point x = util::Point(0., 0., 0.), util::Point a = util::Point(1., 0., 0.), std::string description = "") inline
Constructor.
Parameters
r Radius (distance between center and one of the vertices)
x Center point
a Axis vector that will be rotated and scaled by r to obtain coordinates of vertices of hexagon
description Description of object (e.g., further classification or any tag)
Definition at line 1048 of file geomObjects.h.
                    : GeomObject("hexagon", ""),
                      d_r(r),
                      d_a(a),
                      d_x(x),
                      d_vertices(std::vector<util::Point>(6, util::Point())) {
              // generate vertices
              auto rotate_axis = util::Point(0., 0., 1.); // z-axis
              for (int i = 0; i < 6; i++) {
                d_vertices[i] = d_x + d_r * util::rotate(
                        d_a, i * M_PI / 3., rotate_axis);
              }
            };
References d_a, d_r, d_vertices, d_x, and util::rotate().
Member Function Documentation
boundingRadius()
double util::geometry::Hexagon::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 647 of file geomObjects.cpp.
{
      return d_r;
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Hexagon::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 629 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Hexagon::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 634 of file geomObjects.cpp.
{
      auto p1 = d_x - util::Point(d_r + tol, d_r + tol, d_x[2] + tol);
      auto p2 = d_x + util::Point(d_r + tol, d_r + tol, d_x[2] + tol);
      return {p1, p2};
    }
center()
util::Point util::geometry::Hexagon::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 625 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Hexagon::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 722 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(2, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Hexagon::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 689 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Hexagon::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 642 of file geomObjects.cpp.
{
      return d_r * 0.5 * std::sqrt(3.);
    }
isInside() [1/2]
bool util::geometry::Hexagon::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 694 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(2, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Hexagon::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 652 of file geomObjects.cpp.
{
      if ((x - d_x).length() > d_r)
        return false;
      if ((x - d_x).length() < inscribedRadius())
        return true;
      return false;
    }
isNear() [1/2]
bool util::geometry::Hexagon::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 715 of file geomObjects.cpp.
{
      return util::areBoxesNear(this->box(), box, tol, 2);
    }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Hexagon::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 667 of file geomObjects.cpp.
{
      // get a bigger box containing this object
      auto bbox = box(tol);
      return util::isPointInsideBox(x, 2, bbox);
    }
References util::isPointInsideBox().
isNearBoundary()
bool util::geometry::Hexagon::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 676 of file geomObjects.cpp.
{
      if ((x - d_x).length() > d_r + tol)
        return false;
      if ((x - d_x).length() < inscribedRadius() - tol)
        return false;
      return true;
    }
isOutside() [1/2]
bool util::geometry::Hexagon::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 704 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(2, box))
        if (!intersect)
          intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Hexagon::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 663 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Hexagon::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 1184 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Hexagon::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 1177 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Hexagon::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 733 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Hexagon --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Radius = " << d_r << std::endl;
      oss << tabS << "Center = " << d_x.printStr(0, lvl) << std::endl;
      oss << tabS << "Axis = " << d_a.printStr(0, lvl) << std::endl;
      oss << tabS << "Vertices = " << util::io::printStr(d_vertices, lvl) <<
          std::endl;
      oss << std::endl;
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printStr().
Referenced by print().
volume()
double util::geometry::Hexagon::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 619 of file geomObjects.cpp.
{
      // https://en.wikipedia.org/wiki/Hexagon
      double r_small = this->inscribedRadius();
      return 2. * std::sqrt(3.) * r_small * r_small;
    }
Field Documentation
d_a
util::Point util::geometry::Hexagon::d_a
Axis: defined as the vector pointing from center to the first vertex.
                   +              +
               +           o           +
                           x            v1
                   +              +
Axis is a vector from x to v1
Definition at line 1208 of file geomObjects.h.
Referenced by Hexagon().
d_r
double util::geometry::Hexagon::d_r
Distance between center and the farthest vertex of hexagon.
Definition at line 1193 of file geomObjects.h.
Referenced by Hexagon().
d_vertices
std::vector<util::Point> util::geometry::Hexagon::d_vertices
Vertices.
Definition at line 1187 of file geomObjects.h.
Referenced by Hexagon().
d_x
util::Point util::geometry::Hexagon::d_x
Center.
Definition at line 1190 of file geomObjects.h.
Referenced by Hexagon().
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp