PeriDEM: util::geometry::Triangle Class Reference
util::geometry::Triangle Class Reference
Defines Triangle.
#include <geomObjects.h>
Public Member Functions
Triangle ()
Constructor.
Triangle (double r, util::Point x=util::Point(0., 0., 0.), util::Point a=util::Point(1., 0., 0.), std::string description="uniform")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
TODO Implement methods
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< util::Point > d_vertices
Vertices.
util::Point d_x
Center.
double d_r
Distance between center and the farthest vertex of triangle.
util::Point d_a
Axis: defined as the vector pointing from center to the first vertex v2 +.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines Triangle.
Definition at line 454 of file geomObjects.h.
Constructor & Destructor Documentation
Triangle() [1/2]
util::geometry::Triangle::Triangle () inline
Constructor.
Definition at line 460 of file geomObjects.h.
                    : GeomObject("triangle", ""),
                      d_r(0.),
                      d_a(util::Point(1., 0., 0.)),
                      d_x(util::Point()),
                      d_vertices(std::vector<util::Point>(3, util::Point())) {};
Triangle() [2/2]
util::geometry::Triangle::Triangle (double r, util::Point x = util::Point(0., 0., 0.), util::Point a = util::Point(1., 0., 0.), std::string description = "uniform") inline
Constructor.
Parameters
r Radius (distance of vertex from center)
x Center point
a Axis vector that will be rotated and scaled by r to find coordiantes of triangle vertices
description Description of object (e.g., further classification or any tag)
Definition at line 475 of file geomObjects.h.
                    : GeomObject("triangle", description),
                      d_r(r),
                      d_a(a),
                      d_x(x),
                      d_vertices(std::vector<util::Point>(3, util::Point())) {
              // generate vertices
              auto rotate_axis = util::Point(0., 0., 1.); // z-axis
              for (int i = 0; i < 3; i++) {
                d_vertices[i] = d_x + d_r * util::rotate(
                        d_a, i * 2. * M_PI / 3., rotate_axis);
              }
            };
References d_a, d_r, d_vertices, d_x, and util::rotate().
Member Function Documentation
boundingRadius()
double util::geometry::Triangle::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 210 of file geomObjects.cpp.
{
      return d_r;
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Triangle::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 190 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Triangle::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 195 of file geomObjects.cpp.
{
      // find lower and upper coordinates
      auto p1 = util::Point(d_x.d_x - d_r, d_x.d_y - d_r, d_x.d_z);
      auto p2 = util::Point(d_x.d_x + d_r, d_x.d_y + d_r, d_x.d_z);
      return {p1 - tol, p2 + tol};
    }
center()
util::Point util::geometry::Triangle::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 186 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Triangle::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 309 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(2, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Triangle::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 276 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Triangle::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 205 of file geomObjects.cpp.
{
      return d_r * std::sin(M_PI / 3);
    }
isInside() [1/2]
bool util::geometry::Triangle::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 281 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(2, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Triangle::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 215 of file geomObjects.cpp.
{
      if ((x - d_x).length() > d_r)
        return false;
      if ((x - d_x).length() < this->inscribedRadius())
        return true;
      double a = this->volume();
      double a1 =
              std::abs(util::triangleArea(x, d_vertices[1], d_vertices[2]));
      double a2 =
              std::abs(util::triangleArea(d_vertices[0], x, d_vertices[2]));
      double a3 =
              std::abs(util::triangleArea(d_vertices[0], d_vertices[1], x));
      return (a1 + a2 + a3 < a);
    }
References util::triangleArea().
isNear() [1/2]
bool util::geometry::Triangle::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 302 of file geomObjects.cpp.
{
      return util::areBoxesNear(this->box(), box, tol, 2);
    }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Triangle::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 238 of file geomObjects.cpp.
{
      // get a bigger box containing this object
      auto bbox = box(tol);
      return util::isPointInsideBox(x, 2, bbox);
    }
References util::isPointInsideBox().
isNearBoundary()
bool util::geometry::Triangle::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 247 of file geomObjects.cpp.
{
      // check if particle is inside the object
      if (!isNear(x, within ? 0. : tol))
        return false;
      double a = this->volume();
      double l = 0.5 * std::sqrt(a);
      double a1 =
              std::abs(util::triangleArea(x, d_vertices[1], d_vertices[2]));
      if (a1 < tol * l)
        return true;
      double a2 =
              std::abs(util::triangleArea(d_vertices[0], x, d_vertices[2]));
      if (a2 < tol * l)
        return true;
      double a3 =
              std::abs(util::triangleArea(d_vertices[0], d_vertices[1], x));
      if (a3 < tol * l)
        return true;
      return false;
    }
References util::triangleArea().
isOutside() [1/2]
bool util::geometry::Triangle::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 291 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(2, box))
        if (!intersect)
          intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Triangle::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 234 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Triangle::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 610 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Triangle::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 603 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Triangle::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 320 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Triangle --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Center = " << d_x.printStr(0, lvl) << std::endl;
      oss << tabS << "Radius = " << d_r << std::endl;
      oss << tabS << "Vertices = " << util::io::printStr(d_vertices)
          << std::endl;
      oss << std::endl;
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printStr().
Referenced by print().
volume()
double util::geometry::Triangle::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 182 of file geomObjects.cpp.
{
      return d_r * d_r * (1. + std::sin(M_PI / 3));
    }
Field Documentation
d_a
util::Point util::geometry::Triangle::d_a
Axis: defined as the vector pointing from center to the first vertex v2 +.
                           o           +
                           x            v1
                   +
                   v3
Axis is a vector from x to v1
Definition at line 635 of file geomObjects.h.
Referenced by Triangle().
d_r
double util::geometry::Triangle::d_r
Distance between center and the farthest vertex of triangle.
Definition at line 619 of file geomObjects.h.
Referenced by Triangle().
d_vertices
std::vector<util::Point> util::geometry::Triangle::d_vertices
Vertices.
Definition at line 613 of file geomObjects.h.
Referenced by Triangle().
d_x
util::Point util::geometry::Triangle::d_x
Center.
Definition at line 616 of file geomObjects.h.
Referenced by Triangle().
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp