PeriDEM: util::geometry::Ellipse Class Reference
util::geometry::Ellipse Class Reference
Defines ellipse.
#include <geomObjects.h>
Public Member Functions
Ellipse ()
Constructor.
Ellipse (double a, double b, util::Point x=util::Point(), double theta=0., std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
util::Point d_x
Center.
double d_a
Semi-major axis length.
double d_b
Semi-minor axis length.
double d_theta
Rotation angle in radians (counterclockwise from x-axis)
double d_r
Bounding radius (max of semi-major and semi-minor axis)
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines ellipse.
Definition at line 2059 of file geomObjects.h.
Constructor & Destructor Documentation
Ellipse() [1/2]
util::geometry::Ellipse::Ellipse () inline
Constructor.
Definition at line 2065 of file geomObjects.h.
                    : GeomObject("ellipse", ""),
                      d_x(util::Point()),
                      d_a(0.),
                      d_b(0.),
                      d_theta(0.),
                      d_r(0.) {};
Ellipse() [2/2]
util::geometry::Ellipse::Ellipse (double a, double b, util::Point x = util::Point(), double theta = 0., std::string description = "") inline
Constructor.
Parameters
a Semi-major axis length
b Semi-minor axis length
x Center point
theta Rotation angle in radians (counterclockwise from x-axis)
description Description of object (e.g., further classification or any tag)
Definition at line 2082 of file geomObjects.h.
                    : GeomObject("ellipse", description),
                      d_x(x),
                      d_a(a),
                      d_b(b),
                      d_theta(theta),
                      d_r(std::max(a, b)) {};
Member Function Documentation
boundingRadius()
double util::geometry::Ellipse::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 2083 of file geomObjects.cpp.
{
      return d_r;  // Maximum of semi-major and semi-minor axes (set in constructor)
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Ellipse::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 2062 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Ellipse::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 2066 of file geomObjects.cpp.
{
      // For a rotated ellipse, we need to find the extreme points
      double cos_t = std::cos(d_theta);
      double sin_t = std::sin(d_theta);
      // Maximum extents in x and y directions
      double xmax = std::sqrt(std::pow(d_a * cos_t, 2) + std::pow(d_b * sin_t, 2));
      double ymax = std::sqrt(std::pow(d_a * sin_t, 2) + std::pow(d_b * cos_t, 2));
      return {d_x - util::Point(xmax + tol, ymax + tol, 0.),
              d_x + util::Point(xmax + tol, ymax + tol, 0.)};
    }
center()
util::Point util::geometry::Ellipse::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 2058 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Ellipse::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 2154 of file geomObjects.cpp.
{
      // Check if any corner point is inside
      for (auto p: util::getCornerPoints(2, box))
        if (isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::Ellipse::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 2126 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Ellipse::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 2079 of file geomObjects.cpp.
{
      return std::min(d_a, d_b);  // Minimum of semi-major and semi-minor axes
    }
isInside() [1/2]
bool util::geometry::Ellipse::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 2130 of file geomObjects.cpp.
{
      // Check if all corners of the box are inside the ellipse
      for (auto p: util::getCornerPoints(2, box))
        if (!isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::Ellipse::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 2087 of file geomObjects.cpp.
{
      // Transform point to ellipse coordinate system
      util::Point dx = x - d_x;
      double cos_t = std::cos(d_theta);
      double sin_t = std::sin(d_theta);
      // Rotate point to align with ellipse axes
      double x_rot = dx.d_x * cos_t + dx.d_y * sin_t;
      double y_rot = -dx.d_x * sin_t + dx.d_y * cos_t;
      // Check standard ellipse equation (x/a + y/b  1)
      return util::isLess(std::pow(x_rot/d_a, 2) + std::pow(y_rot/d_b, 2), 1.0);
    }
References util::Point::d_x, util::Point::d_y, and util::isLess().
isNear() [1/2]
bool util::geometry::Ellipse::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 2148 of file geomObjects.cpp.
{
      return util::areBoxesNear(this->box(), box, tol, 2);
    }
References util::areBoxesNear().
isNear() [2/2]
bool util::geometry::Ellipse::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 2105 of file geomObjects.cpp.
{
      // Transform point to ellipse coordinate system
      util::Point dx = x - d_x;
      double cos_t = std::cos(d_theta);
      double sin_t = std::sin(d_theta);
      // Rotate point to align with ellipse axes
      double x_rot = dx.d_x * cos_t + dx.d_y * sin_t;
      double y_rot = -dx.d_x * sin_t + dx.d_y * cos_t;
      // Calculate normalized distance from ellipse boundary
      double dist = std::pow(x_rot/d_a, 2) + std::pow(y_rot/d_b, 2);
      return util::isLess(std::abs(dist - 1.0), tol/std::min(d_a, d_b));
    }
References util::Point::d_x, util::Point::d_y, and util::isLess().
isNearBoundary()
bool util::geometry::Ellipse::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 2120 of file geomObjects.cpp.
{
      return isNear(x, tol) && (within ? isInside(x) : isOutside(x));
    }
isOutside() [1/2]
bool util::geometry::Ellipse::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 2139 of file geomObjects.cpp.
{
      // Check if all corners of the box are outside the ellipse
      for (auto p: util::getCornerPoints(2, box))
        if (!isOutside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::Ellipse::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 2101 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Ellipse::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 2208 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Ellipse::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 2201 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Ellipse::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 2163 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Ellipse --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Center = " << d_x.printStr(0, lvl) << std::endl;
      oss << tabS << "Semi-major axis = " << d_a << std::endl;
      oss << tabS << "Semi-minor axis = " << d_b << std::endl;
      oss << tabS << "Rotation angle = " << d_theta << " radians" << std::endl;
      oss << std::endl;
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printBoxStr().
Referenced by print().
volume()
double util::geometry::Ellipse::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 2054 of file geomObjects.cpp.
{
      return M_PI * d_a * d_b;  // Area of ellipse =  * a * b
    }
Field Documentation
d_a
double util::geometry::Ellipse::d_a
Semi-major axis length.
Definition at line 2214 of file geomObjects.h.
d_b
double util::geometry::Ellipse::d_b
Semi-minor axis length.
Definition at line 2217 of file geomObjects.h.
d_r
double util::geometry::Ellipse::d_r
Bounding radius (max of semi-major and semi-minor axis)
Definition at line 2223 of file geomObjects.h.
d_theta
double util::geometry::Ellipse::d_theta
Rotation angle in radians (counterclockwise from x-axis)
Definition at line 2220 of file geomObjects.h.
d_x
util::Point util::geometry::Ellipse::d_x
Center.
Definition at line 2211 of file geomObjects.h.
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp