PeriDEM: geometry::Fracture Class Reference
geometry::Fracture Class Reference
A class for fracture state of bonds.
#include <fracture.h>
Public Member Functions
Fracture (const std::vector< util::Point > *nodes, const std::vector< std::vector< std::size_t > > *neighbor_list=nullptr)
Constructor.
Fracture ()
Constructor.
void setBondState (const std::size_t &i, const std::size_t &j, const bool &state)
Sets the bond state.
bool getBondState (const std::size_t &i, const std::size_t &j) const
Read bond state.
const std::vector< uint8_t > & getBonds (const std::size_t &i) const
Returns the list of bonds of node i.
std::vector< uint8_t > & getBonds (const std::size_t &i)
Returns the list of bonds of node i.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Private Attributes
std::vector< std::vector< uint8_t > > d_fracture
Vector which stores the state of bonds.
Detailed Description
A class for fracture state of bonds.
This class provides method to read and modify fracture state of bonds
Definition at line 26 of file fracture.h.
Constructor & Destructor Documentation
Fracture() [1/2]
geometry::Fracture::Fracture (const std::vector< util::Point > * nodes, const std::vector< std::vector< std::size_t > > * neighbor_list = nullptr)
Constructor.
If neighbor list is null, then it assumes all nodes interact with all other nodes (PeriDEM implementation).
Parameters
nodes Pointer to nodal coordinates
neighbor_list Pointer to neighbor list
Definition at line 20 of file fracture.cpp.
{
  std::size_t n = nodes->size();
  d_fracture.resize(n);
  tf::Executor executor(util::parallel::getNThreads());
  tf::Taskflow taskflow;
  taskflow.for_each_index(
    (std::size_t) 0, n, (std::size_t) 1, [this, &nodes, &neighbor_list, n](std::size_t i) {
      // get neighborlist of node i if neighborlist is provided
      std::vector<size_t> neighs;
      if (neighbor_list != nullptr)
        neighs = (*neighbor_list)[i];
      // compute number of neighbors
      size_t ns = n;
      if (!neighs.empty())
        ns = neighs.size();
      size_t s = ns / 8;
      if (s * 8 < ns)
        s++;
      d_fracture[i] = std::vector<uint8_t>(s, uint8_t(0));
    }
  ); // for_each
  executor.run(taskflow).get();
}
References util::parallel::getNThreads().
Fracture() [2/2]
geometry::Fracture::Fracture ()
Constructor.
Definition at line 18 of file fracture.cpp.
{}
Member Function Documentation
getBonds() [1/2]
std::vector< uint8_t > & geometry::Fracture::getBonds (const std::size_t & i)
Returns the list of bonds of node i.
Parameters
i Nodal id
Returns
list Bonds of node i
Definition at line 74 of file fracture.cpp.
{
  return d_fracture[i];
}
getBonds() [2/2]
const std::vector< uint8_t > & geometry::Fracture::getBonds (const std::size_t & i) const
Returns the list of bonds of node i.
Parameters
i Nodal id
Returns
list Bonds of node i
Definition at line 70 of file fracture.cpp.
      {
  return d_fracture[i];
}
getBondState()
bool geometry::Fracture::getBondState (const std::size_t & i, const std::size_t & j) const
Read bond state.
Parameters
i Nodal id
j Local id of bond in neighbor list of i
Returns
bool True if bond is fractured otherwise false
Definition at line 64 of file fracture.cpp.
{
  auto bond = d_fracture[i][j / 8];
  return bond >> (j % 8) & 1UL;
}
Referenced by anonymous_namespace{materialUtil.cpp}::computeHydrostaticStrainI(), anonymous_namespace{materialUtil.cpp}::computeStateThetaxI(), and anonymous_namespace{materialUtil.cpp}::updateBondFractureDataI().
print()
void geometry::Fracture::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 90 of file fracture.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string geometry::Fracture::printStr (int nt = 0, int lvl = 0) const
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 78 of file fracture.cpp.
{
  auto tabS = util::io::getTabS(nt);
  std::ostringstream oss;
  oss << tabS << "------- Fracture --------" << std::endl << std::endl;
  oss << tabS << "Num of outer fracture data = " << d_fracture.size() <<
  std::endl;
  oss << tabS << std::endl;
  return oss.str();
}
References util::io::getTabS().
Referenced by print().
setBondState()
void geometry::Fracture::setBondState (const std::size_t & i, const std::size_t & j, const bool & state)
Sets the bond state.
Parameters
i Nodal id
j Local id of bond in neighbor list of i
state State which is applied to the bond
Definition at line 51 of file fracture.cpp.
{
  // to set i^th bit as true of integer a,
  // a |= 1UL << (i % 8)
  // to set i^th bit as false of integer a,
  // a &= ~(1UL << (i % 8))
  state ? (d_fracture[i][j / 8] |= 1UL << (j % 8))
        : (d_fracture[i][j / 8] &= ~(1UL << (j % 8)));
}
Referenced by anonymous_namespace{materialUtil.cpp}::updateBondFractureDataI().
Field Documentation
d_fracture
std::vector<std::vector<uint8_t> > geometry::Fracture::d_fracture private
Vector which stores the state of bonds.
Given node i, vector d_fracture[i] is the list of state of bonds of node i.
We only use 1 bit per bond of node to store the state.
Definition at line 101 of file fracture.h.
The documentation for this class was generated from the following files:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/geometry/fracture.h
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/geometry/fracture.cpp