PeriDEM: util::geometry::ComplexGeomObject Class Reference
util::geometry::ComplexGeomObject Class Reference
Defines complex geometrical object.
#include <geomObjects.h>
Public Member Functions
ComplexGeomObject ()
Constructor.
ComplexGeomObject (std::vector< std::shared_ptr< util::geometry::GeomObject > > &obj, std::vector< std::string > obj_flag, size_t dim, std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< std::shared_ptr< util::geometry::GeomObject > > d_obj
Object.
std::vector< std::string > d_objFlag
Object flag.
std::vector< int > d_objFlagInt
Object integer flags. Here, +1 means object is filling and -1 means object is void.
size_t d_dim
Dimension objects live in.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines complex geometrical object.
Definition at line 2729 of file geomObjects.h.
Constructor & Destructor Documentation
ComplexGeomObject() [1/2]
util::geometry::ComplexGeomObject::ComplexGeomObject () inline
Constructor.
Definition at line 2735 of file geomObjects.h.
: GeomObject("complex", ""), d_dim(0) {};
ComplexGeomObject() [2/2]
util::geometry::ComplexGeomObject::ComplexGeomObject (std::vector< std::shared_ptr< util::geometry::GeomObject > > & obj, std::vector< std::string > obj_flag, size_t dim, std::string description = "") inline
Constructor.
Parameters
obj Vector of geometrical objects
obj_flag Specifies which objects are filling and which are void
dim Dimension of the composite object
description Description of object (e.g., further classification or any tag)
Definition at line 2745 of file geomObjects.h.
                    : GeomObject("complex", description),
                      d_obj(obj),
                      d_objFlag(obj_flag),
                      d_dim(dim) {
              for (const auto &s: d_objFlag)
                if (s == "plus")
                  d_objFlagInt.push_back(1);
                else if (s == "minus")
                  d_objFlagInt.push_back(-1);
                else {
                  std::cerr
                          << "Error: Check object flag " + s +
                             " passed to create ComplexGeomObject\n";
                  exit(1);
                }
            };
References d_dim, d_objFlag, and d_objFlagInt.
Member Function Documentation
boundingRadius()
double util::geometry::ComplexGeomObject::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1909 of file geomObjects.cpp.
{
      auto box = this->box();
      return 0.5 * (box.first - box.second).length();
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::ComplexGeomObject::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1875 of file geomObjects.cpp.
                     {
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::ComplexGeomObject::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 1881 of file geomObjects.cpp.
{
      auto p1 = d_obj[0]->box(tol).first;
      auto p2 = d_obj[0]->box(tol).second;
      for (size_t i = 1; i < d_objFlag.size(); i++) {
        auto q1 = d_obj[i]->box(tol).first;
        auto q2 = d_obj[i]->box(tol).second;
        for (size_t i = 0; i < 3; i++) {
          if (q1[i] < p1[i])
            p1[i] = q1[i];
          if (q2[i] > p2[i])
            p2[i] = q2[i];
        }
      }
      return std::make_pair(p1, p2);
    }
center()
util::Point util::geometry::ComplexGeomObject::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 1852 of file geomObjects.cpp.
{
      // use formula for centroid of composite objects
      auto vol = volume();
      if (util::isGreater(vol, 0.)) {
        auto center = util::Point();
        for (size_t i = 0; i < d_objFlag.size(); i++)
          center += d_obj[i]->volume() * d_objFlagInt[i] * d_obj[i]->center();
        return (1./vol) * center;
      }
      else {
        // find biggest object that has positive d_objFlagInt
        // (that is it is a filling and not void object)
        std::vector<double> vol_vec(d_obj.size());
        for (size_t i = 0; i < d_obj.size(); i++)
          vol_vec[i] = d_obj[i]->volume() * d_objFlagInt[i];
        auto max_vol_obj = util::methods::maxIndex(vol_vec);
        return d_obj[max_vol_obj]->center();
      }
    }
References util::isGreater(), and util::methods::maxIndex().
doesIntersect() [1/2]
bool util::geometry::ComplexGeomObject::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 2006 of file geomObjects.cpp.
{
      // need to check all four corner points
      for (auto p: util::getCornerPoints(d_dim, box))
        if (this->isInside(p))
          return true;
      return false;
    }
References util::getCornerPoints().
doesIntersect() [2/2]
bool util::geometry::ComplexGeomObject::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 1966 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::ComplexGeomObject::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 1903 of file geomObjects.cpp.
{
      auto box = this->box();
      return 0.5 * (box.first - box.second).length();
    }
isInside() [1/2]
bool util::geometry::ComplexGeomObject::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1972 of file geomObjects.cpp.
{
      for (auto p: util::getCornerPoints(d_dim, box))
        if (!this->isInside(p))
          return false;
      return true;
    }
References util::getCornerPoints().
isInside() [2/2]
bool util::geometry::ComplexGeomObject::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 1916 of file geomObjects.cpp.
{
      // point inside means x should be inside in the object with plus flag and
      // outside in the object with minus flag
      bool point_inside = d_obj[0]->isInside(x);
      for (size_t i = 1; i < d_objFlag.size(); i++) {
        const auto &obj_i = d_obj[i];
        if (d_objFlagInt[i] < 0)
          point_inside = point_inside and !obj_i->isInside(x);
        else
          point_inside = point_inside or obj_i->isInside(x);
      }
      return point_inside;
    }
isNear() [1/2]
bool util::geometry::ComplexGeomObject::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1992 of file geomObjects.cpp.
{
      bool is_near = d_obj[0]->isNear(box, tol);
      for (size_t i = 1; i < d_objFlag.size(); i++) {
        const auto &obj_i = d_obj[i];
        is_near = is_near or obj_i->isNear(box, tol);
      }
      return is_near;
    }
isNear() [2/2]
bool util::geometry::ComplexGeomObject::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 1938 of file geomObjects.cpp.
{
      bool is_near = d_obj[0]->isNear(x, tol);
      for (size_t i = 1; i < d_objFlag.size(); i++) {
        const auto &obj_i = d_obj[i];
        is_near = is_near or obj_i->isNear(x, tol);
      }
      return is_near;
    }
isNearBoundary()
bool util::geometry::ComplexGeomObject::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 1951 of file geomObjects.cpp.
{
      bool is_near = d_obj[0]->isNearBoundary(x, tol, within);
      for (size_t i = 1; i < d_objFlag.size(); i++) {
        const auto &obj_i = d_obj[i];
        is_near = is_near or obj_i->isNearBoundary(x, tol, within);
      }
      return is_near;
    }
isOutside() [1/2]
bool util::geometry::ComplexGeomObject::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1982 of file geomObjects.cpp.
{
      bool intersect = false;
      for (auto p: util::getCornerPoints(d_dim, box))
        intersect = this->isInside(p);
      return !intersect;
    }
References util::getCornerPoints().
isOutside() [2/2]
bool util::geometry::ComplexGeomObject::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 1934 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::ComplexGeomObject::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 2884 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::ComplexGeomObject::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 2877 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References d_dim, and printStr().
printStr()
std::string util::geometry::ComplexGeomObject::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 2018 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- ComplexGeomObject --------" << std::endl
          << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Center = " << center().printStr() << std::endl;
      oss << tabS << "Object info:" << std::endl;
      auto ocount = 0;
      for (const auto &p: d_obj) {
        oss << tabS << "Object id: " << ocount << std::endl;
        oss << tabS << "Object flag: " << d_objFlag[ocount] << std::endl;
        oss << tabS << "Object int flag: " << d_objFlagInt[ocount] << std::endl;
        oss << p->printStr(nt + 1, lvl);
        ocount++;
      }
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printBoxStr().
Referenced by print().
volume()
double util::geometry::ComplexGeomObject::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 1843 of file geomObjects.cpp.
{
      double volume = 0.;
      for (size_t i = 0; i < d_objFlag.size(); i++)
        volume += d_obj[i]->volume() * d_objFlagInt[i];
      return volume;
    }
Field Documentation
d_dim
size_t util::geometry::ComplexGeomObject::d_dim
Dimension objects live in.
Definition at line 2905 of file geomObjects.h.
Referenced by ComplexGeomObject(), and print().
d_obj
std::vector<std::shared_ptr<util::geometry::GeomObject> > util::geometry::ComplexGeomObject::d_obj
Object.
Definition at line 2887 of file geomObjects.h.
d_objFlag
std::vector<std::string> util::geometry::ComplexGeomObject::d_objFlag
Object flag.
Ordering of objects is important. To describe a rectangle with circular hole, we will have d_obj = {rectangle, circle} and have flag = {plus, minus}. This means final object is rectangle - circle
Definition at line 2897 of file geomObjects.h.
Referenced by ComplexGeomObject().
d_objFlagInt
std::vector<int> util::geometry::ComplexGeomObject::d_objFlagInt
Object integer flags. Here, +1 means object is filling and -1 means object is void.
Definition at line 2902 of file geomObjects.h.
Referenced by ComplexGeomObject().
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp