PeriDEM: particle::Wall Class Reference
particle::Wall Class Reference
Specialization of BaseParticle for modeling of walls. Wall differ from the particles in the sense that they do not have any reference particle and they have their own mesh object.
#include <wall.h>
Public Member Functions
Wall (size_t id, size_t wall_id, inp::WallZone &z_deck, size_t z_id, fe::Mesh *mesh, std::shared_ptr< model::ModelData > model_data, bool populate_data=true)
Constructor.
fe::Mesh * getMeshP ()
Get pointer to mesh object.
const fe::Mesh * getMeshP () const
Get pointer to mesh object.
fe::Mesh & getMesh ()
Get reference to mesh object.
const fe::Mesh & getMesh () const
Get reference to mesh object.
size_t getWallId () const
Get id of this wall.
Public Member Functions inherited from particle::BaseParticle
BaseParticle (std::string type="none")
Constructor.
BaseParticle (std::string type, size_t id, size_t type_id, size_t zone_id, size_t dim, size_t num_nodes, double h, std::shared_ptr< model::ModelData > model_data)
Constructor.
std::string getType () const
Get type of this object.
int getTypeIndex () const
Get type (in integer format) of this object.
size_t getId () const
Get id.
size_t getTypeId () const
Get id among the group of object in the same type as this.
size_t getDimension () const
Get the dimension of the domain.
double getMeshSize () const
Get mesh size.
double getDensity () const
Get density.
double getHorizon () const
Get horizon.
material::Material * getMaterial ()
Get pointer to material object.
const material::Material * getMaterial () const
Get type of this object.
size_t getNumNodes () const
Get the number of nodes.
size_t getNodeId (size_t i_loc) const
Get global id of node given the local id of node in this object.
util::Point & getXRef (size_t i)
Get reference coordinate of the node.
const util::Point & getXRef (size_t i) const
Get reference coordinate of the node.
void setXRef (size_t i, const util::Point &x)
Set reference coordinate of the node.
void addXRef (size_t i, const util::Point &x)
Add reference coordinate of the node.
void setXRef (size_t i, int dof, double x)
Set specific reference coordinate of the node.
void addXRef (size_t i, int dof, double x)
Add specific reference coordinate of the node.
util::Point & getXRefLocal (size_t i)
Get reference coordinate of the node given node's local id.
const util::Point & getXRefLocal (size_t i) const
Get reference coordinate of the node.
void setXRefLocal (size_t i, const util::Point &x)
Set reference coordinate of the node given node's local id.
void addXRefLocal (size_t i, const util::Point &x)
Add to reference coordinate of the node given node's local id.
void setXRefLocal (size_t i, int dof, double x)
Set specific reference coordinate of the node given node's local id.
void addXRefLocal (size_t i, int dof, double x)
Add to specific reference coordinate of the node given node's local id.
util::Point & getX (size_t i)
Get current coordinate of the node.
const util::Point & getX (size_t i) const
Get current coordinate of the node.
void setX (size_t i, const util::Point &x)
Set current coordinate of the node.
void addX (size_t i, const util::Point &x)
Add current coordinate of the node.
void setX (size_t i, int dof, double x)
Set specific current coordinate of the node.
void addX (size_t i, int dof, double x)
Add to specific current coordinate of the node.
util::Point & getXLocal (size_t i)
Get current coordinate of the node given node's local id.
const util::Point & getXLocal (size_t i) const
Get current coordinate of the node.
void setXLocal (size_t i, const util::Point &x)
Set current coordinate of the node given node's local id.
void addXLocal (size_t i, const util::Point &x)
Add to current coordinate of the node given node's local id.
void setXLocal (size_t i, int dof, double x)
Set specific current coordinate of the node given node's local id.
void addXLocal (size_t i, int dof, double x)
Add to specific current coordinate of the node given node's local id.
util::Point & getU (size_t i)
Get displacement of the node.
const util::Point & getU (size_t i) const
Get displacement of the node.
void setU (size_t i, const util::Point &u)
Set displacement of the node.
void addU (size_t i, const util::Point &u)
Add to displacement of the node.
void setU (size_t i, int dof, double u)
Set displacement of the node.
void addU (size_t i, int dof, double u)
Add to displacement of the node.
util::Point & getULocal (size_t i)
Get displacement of the node given node's local id.
const util::Point & getULocal (size_t i) const
Get displacement of the node given node's local id.
void setULocal (size_t i, const util::Point &u)
Set displacement of the node given node's local id.
void addULocal (size_t i, const util::Point &u)
Add to displacement of the node given node's local id.
void setULocal (size_t i, int dof, double u)
Set displacement of the node given node's local id.
void addULocal (size_t i, int dof, double u)
Add to displacement of the node given node's local id.
util::Point & getV (size_t i)
Get velocity of the node.
const util::Point & getV (size_t i) const
Get velocity of the node.
void setV (size_t i, const util::Point &v)
Set velocity of the node.
void addV (size_t i, const util::Point &v)
Add to velocity of the node.
void setV (size_t i, int dof, double v)
Set velocity of the node.
void addV (size_t i, int dof, double v)
Add to velocity of the node.
util::Point & getVLocal (size_t i)
Get velocity of the node given node's local id.
const util::Point & getVLocal (size_t i) const
Get velocity of the node.
void setVLocal (size_t i, const util::Point &v)
Set velocity of the node given node's local id.
void addVLocal (size_t i, const util::Point &v)
Add to velocity of the node given node's local id.
void setVLocal (size_t i, int dof, double v)
Set velocity of the node given node's local id.
void addVLocal (size_t i, int dof, double v)
Add to velocity of the node given node's local id.
util::Point & getF (size_t i)
Get force of the node.
const util::Point & getF (size_t i) const
Get force of the node.
void setF (size_t i, const util::Point &f)
Set force of the node.
void addF (size_t i, const util::Point &f)
Add to force of the node.
void setF (size_t i, int dof, double f)
Set force of the node.
void addF (size_t i, int dof, double f)
Add to force of the node.
util::Point & getFLocal (size_t i)
Get force of the node given node's local id.
const util::Point & getFLocal (size_t i) const
Get force of the node.
void setFLocal (size_t i, const util::Point &f)
Set force of the node given node's local id.
void addFLocal (size_t i, const util::Point &f)
Add to force of the node given node's local id.
void setFLocal (size_t i, int dof, double f)
Set force of the node given node's local id.
void addFLocal (size_t i, int dof, double f)
Add to force of the node given node's local id.
double & getVol (size_t i)
Get volume of the node.
const double & getVol (size_t i) const
Get volume of the node.
void setVol (size_t i, const double &vol)
Set volume of the node.
void addVol (size_t i, const double &vol)
Add to volume of the node.
double & getVolLocal (size_t i)
Get volume of the node given node's local id.
const double & getVolLocal (size_t i) const
Get volume of the node.
void setVolLocal (size_t i, const double &vol)
Set volume of the node given node's local id.
void addVolLocal (size_t i, const double &vol)
Add to volume of the node given node's local id.
uint8_t & getFix (size_t i)
Get fixity of the node.
const uint8_t & getFix (size_t i) const
Get fixity of the node.
void setFix (size_t i, const unsigned int &dof, const bool &flag)
Set fixity of the node.
uint8_t & getFixLocal (size_t i)
Get fixity of the node given node's local id.
const uint8_t & getFixLocal (size_t i) const
Get fixity of the node.
void setFixLocal (size_t i, const unsigned int &dof, const bool &flag)
Set fixity of the node given node's local id.
double & getMx (size_t i)
Get weighted-volume (mx) of the node.
const double & getMx (size_t i) const
Get weighted-volume (mx) of the node.
void setMx (size_t i, const double &mx)
Set weighted-volume (mx) of the node.
void addMx (size_t i, const double &mx)
Add to weighted-volume (mx) of the node.
double & getMxLocal (size_t i)
Get weighted-volume (mx) of the node given node's local id.
const double & getMxLocal (size_t i) const
Get weighted-volume (mx) of the node.
void setMxLocal (size_t i, const double &mx)
Set weighted-volume (mx) of the node given node's local id.
void addMxLocal (size_t i, const double &mx)
Add to weighted-volume (mx) of the node given node's local id.
double & getThetax (size_t i)
Get volumetric deformation (thetax) of the node.
const double & getThetax (size_t i) const
Get volumetric deformation (thetax) of the node.
void setThetax (size_t i, const double &thetax)
Set volumetric deformation (thetax) of the node.
void addThetax (size_t i, const double &thetax)
Add to volumetric deformation (thetax) of the node.
double & getThetaxLocal (size_t i)
Get volumetric deformation (thetax) of the node given node's local id.
const double & getThetaxLocal (size_t i) const
Get volumetric deformation (thetax) of the node.
void setThetaxLocal (size_t i, const double &thetax)
Set volumetric deformation (thetax) of the node given node's local id.
void addThetaxLocal (size_t i, const double &thetax)
Add to volumetric deformation (thetax) of the node given node's local id.
Data Fields
std::string d_wallType
Wall type.
std::unique_ptr< fe::Mesh > d_mesh_p
Pointer to mesh on reference particle.
Data Fields inherited from particle::BaseParticle
std::string d_type
particle type
int d_typeIndex
size_t d_id
Id of this particle.
size_t d_typeId
Id of this particle in the category (for example if this is a wall, what is its id in vector of walls)
size_t d_zoneId
Specify zone to which this particle belongs to.
size_t d_dim
Dimension of this particle.
size_t d_numNodes
Number of nodes in this particle.
double d_h
mesh size
bool d_computeForce
Specify if we compute force.
double d_horizon
horizon
double d_density
density
std::unique_ptr< material::Material > d_material_p
Pointer to peridynamic material object.
double d_Rc
Contact radius for contact between internal nodes of particle.
double d_Kn
Normal contact coefficient for internal contact.
size_t d_globStart
Id of first node of this object in global node list.
size_t d_globEnd
Id of last node of this object in global node list.
std::shared_ptr< model::ModelData > d_modelData_p
Reference to model class.
Detailed Description
Specialization of BaseParticle for modeling of walls. Wall differ from the particles in the sense that they do not have any reference particle and they have their own mesh object.
Definition at line 27 of file wall.h.
Constructor & Destructor Documentation
Wall()
particle::Wall::Wall (size_t id, size_t wall_id, inp::WallZone & z_deck, size_t z_id, fe::Mesh * mesh, std::shared_ptr< model::ModelData > model_data, bool populate_data = true)
Constructor.
Parameters
id Id of this object in group of all base particles
wall_id Wall id of this object in group of walls
z_deck Wall zone input deck
z_id Zone id this object belongs to
mesh Mesh of this object
model_data Global model data
populate_data Modify global model data to add the properties of this object
Definition at line 21 of file wall.cpp.
    : BaseParticle("wall", id, wall_id, z_id, mesh->getDimension(),
                   mesh->getNumNodes(),
                   0.,
                   model_data),
      d_wallType(z_deck.d_type), d_mesh_p(mesh) {
  if (populate_data) {
    d_globStart = d_modelData_p->d_x.size();
    d_globEnd = d_modelData_p->d_x.size() + d_mesh_p->getNumNodes();
    for (size_t i = 0; i < d_mesh_p->getNumNodes(); i++) {
      d_modelData_p->d_xRef.push_back(d_mesh_p->getNode(i));
      d_modelData_p->d_x.push_back(d_mesh_p->getNode(i));
      d_modelData_p->d_u.push_back(util::Point());
      d_modelData_p->d_v.push_back(util::Point());
      d_modelData_p->d_f.push_back(util::Point());
      d_modelData_p->d_vol.push_back(d_mesh_p->getNodalVolume(i));
      d_modelData_p->d_fix.push_back(uint8_t(0));
      d_modelData_p->d_forceFixity.push_back(uint8_t(0));
      d_modelData_p->d_thetaX.push_back(0.);
      d_modelData_p->d_mX.push_back(0.);
      d_modelData_p->d_ptId.push_back(id); // id of this wall
    }
  }
  d_h = d_mesh_p->getMeshSize();
  // material class
  // initialize material class
  auto &material_deck = z_deck.d_matDeck;
  double horizon = material_deck.d_horizon;
  if (material_deck.d_materialType == "RNPBond")
    d_material_p = std::make_unique<material::RnpMaterial>(
        material_deck, d_mesh_p->getDimension(), horizon);
  else if (material_deck.d_materialType == "PMBBond")
    d_material_p = std::make_unique<material::PmbMaterial>(
        material_deck, d_mesh_p->getDimension(), horizon);
  else if (material_deck.d_materialType == "PDElasticBond")
    d_material_p = std::make_unique<material::PdElastic>(
        material_deck, d_mesh_p->getDimension(), horizon);
  else if (material_deck.d_materialType == "PDState")
    d_material_p = std::make_unique<material::PdState>(
        material_deck, d_mesh_p->getDimension(), horizon);
  d_horizon = horizon;
  d_density = d_material_p->getDensity();
  if (z_deck.d_allDofsConstrained)
    d_computeForce = false;
  // set contact radius for internal contact
  d_Rc = 0.9 * d_h;
  // set contact coefficient for internal contact
  d_Kn = (18. / (M_PI * std::pow(horizon, 5))) *
         d_material_p->computeMaterialProperties(getDimension()).d_K;
}
References inp::WallZone::d_allDofsConstrained, particle::BaseParticle::d_computeForce, particle::BaseParticle::d_density, particle::BaseParticle::d_globEnd, particle::BaseParticle::d_globStart, particle::BaseParticle::d_h, inp::MaterialDeck::d_horizon, particle::BaseParticle::d_horizon, particle::BaseParticle::d_Kn, inp::WallZone::d_matDeck, particle::BaseParticle::d_material_p, d_mesh_p, particle::BaseParticle::d_modelData_p, particle::BaseParticle::d_Rc, particle::BaseParticle::getDimension(), and particle::BaseParticle::getNumNodes().
Member Function Documentation
getMesh() [1/2]
fe::Mesh & particle::Wall::getMesh () inline
Get reference to mesh object.
Returns
mesh Reference to mesh
Definition at line 59 of file wall.h.
{ return *d_mesh_p; };
References d_mesh_p.
getMesh() [2/2]
const fe::Mesh & particle::Wall::getMesh () const inline
Get reference to mesh object.
Returns
mesh Reference to mesh
Definition at line 62 of file wall.h.
{ return *d_mesh_p; };
References d_mesh_p.
getMeshP() [1/2]
fe::Mesh * particle::Wall::getMeshP () inline
Get pointer to mesh object.
Returns
mesh Pointer to mesh
Definition at line 50 of file wall.h.
{ return d_mesh_p.get(); };
References d_mesh_p.
getMeshP() [2/2]
const fe::Mesh * particle::Wall::getMeshP () const inline
Get pointer to mesh object.
Returns
mesh Pointer to mesh
Definition at line 53 of file wall.h.
{ return d_mesh_p.get(); };
References d_mesh_p.
getWallId()
size_t particle::Wall::getWallId () const inline
Get id of this wall.
Returns
id Wall id
Definition at line 68 of file wall.h.
{return getTypeId(); }
References particle::BaseParticle::getTypeId().
Field Documentation
d_mesh_p
std::unique_ptr<fe::Mesh> particle::Wall::d_mesh_p
Pointer to mesh on reference particle.
Definition at line 75 of file wall.h.
Referenced by getMesh(), getMesh(), getMeshP(), getMeshP(), and Wall().
d_wallType
std::string particle::Wall::d_wallType
Wall type.
Definition at line 72 of file wall.h.
The documentation for this class was generated from the following files:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/particle/wall.h
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/particle/wall.cpp