PeriDEM: material::BaseInfluenceFn Class Reference
material::BaseInfluenceFn Class Reference abstract
A base class for computing influence function.
#include <influenceFn.h>
Public Member Functions
BaseInfluenceFn ()=default
Constructor.
virtual double getInfFn (const double &r) const =0
Returns the value of influence function.
virtual double getMoment (const size_t &i) const =0
Returns the moment of influence function.
virtual std::string printStr (int nt, int lvl) const
Returns the string containing printable information about the object.
virtual void print (int nt, int lvl) const
Prints the information about the object.
virtual void print () const
Prints the information about the object.
Detailed Description
A base class for computing influence function.
Definition at line 22 of file influenceFn.h.
Constructor & Destructor Documentation
BaseInfluenceFn()
material::BaseInfluenceFn::BaseInfluenceFn () default
Constructor.
Member Function Documentation
getInfFn()
virtual double material::BaseInfluenceFn::getInfFn (const double & r) const pure virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implemented in material::ConstInfluenceFn, material::GaussianInfluenceFn, and material::LinearInfluenceFn.
getMoment()
virtual double material::BaseInfluenceFn::getMoment (const size_t & i) const pure virtual
Returns the moment of influence function.
If \(J(r) \) is the influence function for \(r\in [0,1)\) then \(i^{th} \) moment is given by
\[ M_i = \int_0^1 J(r) r^i dr. \]
Parameters
i ith moment
Returns
moment Moment
Implemented in material::ConstInfluenceFn, material::GaussianInfluenceFn, and material::LinearInfluenceFn.
print() [1/2]
virtual void material::BaseInfluenceFn::print () const inline virtual
Prints the information about the object.
Reimplemented in material::ConstInfluenceFn, material::GaussianInfluenceFn, and material::LinearInfluenceFn.
Definition at line 75 of file influenceFn.h.
{ print(0, 0); }
References print().
Referenced by print().
print() [2/2]
virtual void material::BaseInfluenceFn::print (int nt, int lvl) const inline virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented in material::ConstInfluenceFn, material::GaussianInfluenceFn, and material::LinearInfluenceFn.
Definition at line 72 of file influenceFn.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
virtual std::string material::BaseInfluenceFn::printStr (int nt, int lvl) const inline virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented in material::ConstInfluenceFn, material::GaussianInfluenceFn, and material::LinearInfluenceFn.
Definition at line 54 of file influenceFn.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- BaseInfluenceFn --------" << std::endl << std::endl;
    oss << tabS << "Provides abstraction for different influence function "
                   "types" << std::endl;
    oss << tabS << std::endl;
    return oss.str();
  }
References util::io::getTabS().
Referenced by print().
The documentation for this class was generated from the following file:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/material/mparticle/influenceFn.h