PeriDEM: util::geometry::Line Class Reference
util::geometry::Line Class Reference
Defines Line.
#include <geomObjects.h>
Public Member Functions
Line ()
Constructor.
Line (util::Point x1, util::Point x2, std::string description="")
Constructor.
Line (double L, util::Point x=util::Point(), std::string description="")
Constructor.
double volume () const override
Computes the volume (area in 2d, length in 1d) of object.
util::Point center () const override
Computes the center of object.
std::pair< util::Point, util::Point > box () const override
Computes the bounding box of object.
std::pair< util::Point, util::Point > box (const double &tol) const override
Computes the bounding box of object.
double inscribedRadius () const override
Computes the radius of biggest circle/sphere completely within the object.
double boundingRadius () const override
Computes the radius of smallest circle/sphere such that object can be fit into it.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Interaction with point
bool isInside (const util::Point &x) const override
Checks if point is inside this object.
bool isOutside (const util::Point &x) const override
Checks if point is outside of this object.
bool isNear (const util::Point &x, const double &tol) const override
Checks if point is within given distance of this object.
bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const override
cons
bool doesIntersect (const util::Point &x) const override
Checks if point lies exactly on the boundary.
Interaction with box
TODO Implement methods
bool isInside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is completely inside.
bool isOutside (const std::pair< util::Point, util::Point > &box) const override
Checks if box is outside of the object.
bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const override
Checks if box is within given distance of this object.
bool doesIntersect (const std::pair< util::Point, util::Point > &box) const override
Checks if box intersects this object.
Public Member Functions inherited from util::geometry::GeomObject
GeomObject (std::string name="", std::string description="")
Constructor.
Data Fields
std::vector< util::Point > d_vertices
Vertices.
util::Point d_x
Center.
double d_L
Length of line.
double d_r
Radius of bounding circle.
Data Fields inherited from util::geometry::GeomObject
const std::string d_name
name of object
const std::string d_description
Further description of object.
std::vector< std::string > d_tags
Tags/attributes about the object.
Detailed Description
Defines Line.
Definition at line 275 of file geomObjects.h.
Constructor & Destructor Documentation
Line() [1/3]
util::geometry::Line::Line () inline
Constructor.
Definition at line 281 of file geomObjects.h.
                    : GeomObject("line", ""),
                      d_r(0.),
                      d_L(0.),
                      d_x(util::Point()),
                      d_vertices({util::Point(), util::Point()}) {};
Line() [2/3]
util::geometry::Line::Line (util::Point x1, util::Point x2, std::string description = "") inline
Constructor.
Parameters
x1 Left-bottom corner point
x2 Right-top corner point
description Description of object (e.g., further classification or any tag)
Definition at line 295 of file geomObjects.h.
                    : GeomObject("line", description),
                      d_L((x1 - x2).length()),
                      d_r(0.5 * (x1 - x2).length()),
                      d_x(0.5 * (x1 + x2)),
                      d_vertices({x1, x2}) {};
Line() [3/3]
util::geometry::Line::Line (double L, util::Point x = util::Point(), std::string description = "") inline
Constructor.
Parameters
L Length of a line
x Center point
description Description of object (e.g., further classification or any tag)
Definition at line 309 of file geomObjects.h.
                    : GeomObject("line", description),
                      d_L(L),
                      d_r(0.5 * L),
                      d_x(x),
                      d_vertices({x + util::Point(-0.5 * L, 0., 0.),
                                  x + util::Point(0.5 * L, 0., 0.)}) {};
Member Function Documentation
boundingRadius()
double util::geometry::Line::boundingRadius () const override virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 63 of file geomObjects.cpp.
{
      return d_r;
    }
box() [1/2]
std::pair< util::Point, util::Point > util::geometry::Line::box () const override virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 47 of file geomObjects.cpp.
{
      return box(0.);
    }
box() [2/2]
std::pair< util::Point, util::Point > util::geometry::Line::box (const double & tol) const override virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented from util::geometry::GeomObject.
Definition at line 52 of file geomObjects.cpp.
{
      return {d_vertices[0] - tol, d_vertices[1] + tol};
    }
center()
util::Point util::geometry::Line::center () const override virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented from util::geometry::GeomObject.
Definition at line 43 of file geomObjects.cpp.
{
      return d_x;
    }
doesIntersect() [1/2]
bool util::geometry::Line::doesIntersect (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented from util::geometry::GeomObject.
Definition at line 148 of file geomObjects.cpp.
{
      return false;
    }
doesIntersect() [2/2]
bool util::geometry::Line::doesIntersect (const util::Point & x) const override virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented from util::geometry::GeomObject.
Definition at line 124 of file geomObjects.cpp.
{
      return isNearBoundary(x, 1.0E-8, false);
    }
inscribedRadius()
double util::geometry::Line::inscribedRadius () const override virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented from util::geometry::GeomObject.
Definition at line 58 of file geomObjects.cpp.
{
      return d_r;
    }
isInside() [1/2]
bool util::geometry::Line::isInside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 129 of file geomObjects.cpp.
{
      return false;
    }
isInside() [2/2]
bool util::geometry::Line::isInside (const util::Point & x) const override virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented from util::geometry::GeomObject.
Definition at line 68 of file geomObjects.cpp.
{
      auto da = (d_vertices[1] - d_vertices[0]) / d_L;
      auto db = x - d_vertices[0];
      double dot = db * da;
      if (util::isLess(dot, 0.) or util::isGreater(dot, d_L))
        return false;
      auto dx = db - dot * da;
      return util::isLess(dx.length(), 1.0E-10);
    }
References util::dot(), util::isGreater(), and util::isLess().
isNear() [1/2]
bool util::geometry::Line::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const override virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 141 of file geomObjects.cpp.
{
      return true;
    }
isNear() [2/2]
bool util::geometry::Line::isNear (const util::Point & x, const double & tol) const override virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented from util::geometry::GeomObject.
Definition at line 88 of file geomObjects.cpp.
{
      auto da = (d_vertices[1] - d_vertices[0]) / d_L;
      auto db = x - d_vertices[0];
      double dot = db * da;
      if (util::isLess(dot, 0.) or util::isGreater(dot, d_L))
        return false;
      auto dx = db - dot * da;
      return util::isLess(dx.length(), tol);
    }
References util::dot(), util::isGreater(), and util::isLess().
isNearBoundary()
bool util::geometry::Line::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const override virtual
cons
cons
Reimplemented from util::geometry::GeomObject.
Definition at line 103 of file geomObjects.cpp.
{
      // check if particle is inside the object
      if (!isNear(x, within ? 0. : tol))
        return false;
      auto da = (d_vertices[1] - d_vertices[0]) / d_L;
      auto db = x - d_vertices[0];
      double dot = db * da;
      if (util::isLess(dot, 0.) or util::isGreater(dot, tol)
          or util::isGreater(dot, d_L) or util::isLess(dot, d_L - tol))
        return false;
      auto dx = db - dot * da;
      return util::isLess(dx.length(), tol);
    }
References util::dot(), util::isGreater(), and util::isLess().
isOutside() [1/2]
bool util::geometry::Line::isOutside (const std::pair< util::Point, util::Point > & box) const override virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 135 of file geomObjects.cpp.
{
      return true;
    }
isOutside() [2/2]
bool util::geometry::Line::isOutside (const util::Point & x) const override virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented from util::geometry::GeomObject.
Definition at line 83 of file geomObjects.cpp.
{
      return !isInside(x);
    }
print() [1/2]
void util::geometry::Line::print () const inline override virtual
Prints the information about the object.
Reimplemented from util::geometry::GeomObject.
Definition at line 436 of file geomObjects.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void util::geometry::Line::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from util::geometry::GeomObject.
Definition at line 429 of file geomObjects.h.
{
              std::cout << printStr(nt, lvl);
            };
References printStr().
printStr()
std::string util::geometry::Line::printStr (int nt, int lvl) const override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from util::geometry::GeomObject.
Definition at line 154 of file geomObjects.cpp.
{
      auto tabS = util::io::getTabS(nt);
      std::ostringstream oss;
      oss << tabS << "------- Line --------" << std::endl << std::endl;
      oss << tabS << "Name = " << d_name << std::endl;
      oss << tabS << "Length = " << d_L << std::endl;
      oss << tabS << "Point 1 = " << d_vertices[0].printStr(0, lvl) << std::endl;
      oss << tabS << "Point 2 = " << d_vertices[1].printStr(0, lvl) << std::endl;
      oss << std::endl;
      if (lvl > 0)
        oss << tabS << "Bounding box: "
            << util::io::printBoxStr(box(0.), nt + 1);
      if (lvl == 0)
        oss << std::endl;
      return oss.str();
    }
References util::io::getTabS(), and util::io::printBoxStr().
Referenced by print().
volume()
double util::geometry::Line::volume () const override virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented from util::geometry::GeomObject.
Definition at line 39 of file geomObjects.cpp.
{
      return d_L;
    }
Field Documentation
d_L
double util::geometry::Line::d_L
Length of line.
Definition at line 445 of file geomObjects.h.
d_r
double util::geometry::Line::d_r
Radius of bounding circle.
Definition at line 448 of file geomObjects.h.
d_vertices
std::vector<util::Point> util::geometry::Line::d_vertices
Vertices.
Definition at line 439 of file geomObjects.h.
d_x
util::Point util::geometry::Line::d_x
Center.
Definition at line 442 of file geomObjects.h.
The documentation for this class was generated from the following files:
/home/user/project/src/util/geomObjects.h
/home/user/project/src/util/geomObjects.cpp