PeriDEM: util::geometry::GeomObject Class Reference
util::geometry::GeomObject Class Reference
Defines abstract geometrical domain.
#include <geomObjects.h>
Public Member Functions
GeomObject (std::string name="", std::string description="")
Constructor.
virtual double volume () const
Computes the volume (area in 2d, length in 1d) of object.
virtual util::Point center () const
Computes the center of object.
virtual std::pair< util::Point, util::Point > box () const
Computes the bounding box of object.
virtual std::pair< util::Point, util::Point > box (const double &tol) const
Computes the bounding box of object.
virtual double inscribedRadius () const
Computes the radius of biggest circle/sphere completely within the object.
virtual double boundingRadius () const
Computes the radius of smallest circle/sphere such that object can be fit into it.
virtual std::string printStr (int nt, int lvl) const
Returns the string containing printable information about the object.
virtual void print (int nt, int lvl) const
Prints the information about the object.
virtual void print () const
Prints the information about the object.
Interaction with point
virtual bool isInside (const util::Point &x) const
Checks if point is inside this object.
virtual bool isOutside (const util::Point &x) const
Checks if point is outside of this object.
virtual bool isNear (const util::Point &x, const double &tol) const
Checks if point is within given distance of this object.
virtual bool isNearBoundary (const util::Point &x, const double &tol, const bool &within) const
Checks if point is within given distance of this object.
virtual bool doesIntersect (const util::Point &x) const
Checks if point lies exactly on the boundary.
Interaction with box
virtual bool isInside (const std::pair< util::Point, util::Point > &box) const
Checks if box is completely inside.
virtual bool isOutside (const std::pair< util::Point, util::Point > &box) const
Checks if box is outside of the object.
virtual bool isNear (const std::pair< util::Point, util::Point > &box, const double &tol) const
Checks if box is within given distance of this object.
virtual bool doesIntersect (const std::pair< util::Point, util::Point > &box) const
Checks if box intersects this object.
Data Fields
const std::string d_name
name of object
const std::string d_description
Further description of object.
Detailed Description
Defines abstract geometrical domain.
Definition at line 88 of file geomObjects.h.
Constructor & Destructor Documentation
GeomObject()
util::geometry::GeomObject::GeomObject (std::string name = "", std::string description = "") inline explicit
Constructor.
Parameters
name Name of the geometric object
description Description of object (e.g., further classification or any tag)
Definition at line 96 of file geomObjects.h.
                     : d_name(name), d_description(description) {};
Member Function Documentation
boundingRadius()
virtual double util::geometry::GeomObject::boundingRadius () const inline virtual
Computes the radius of smallest circle/sphere such that object can be fit into it.
Returns
Radius Radius of bounding circle/sphere
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 142 of file geomObjects.h.
 { return 0.; };
box() [1/2]
virtual std::pair<util::Point, util::Point> util::geometry::GeomObject::box () const inline virtual
Computes the bounding box of object.
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 116 of file geomObjects.h.
{
               return {util::Point(), util::Point()};
             };
box() [2/2]
virtual std::pair<util::Point, util::Point> util::geometry::GeomObject::box (const double & tol) const inline virtual
Computes the bounding box of object.
Parameters
tol Tolerance/padding used in creating bounding box
Returns
Pair Left-bottom-back and right-top-front corner points of box
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 126 of file geomObjects.h.
{
               return {util::Point(), util::Point()};
             };
center()
virtual util::Point util::geometry::GeomObject::center () const inline virtual
Computes the center of object.
Returns
Point Coordinates of center
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 110 of file geomObjects.h.
 { return {}; };
doesIntersect() [1/2]
virtual bool util::geometry::GeomObject::doesIntersect (const std::pair< util::Point, util::Point > & box) const inline virtual
Checks if box intersects this object.
Parameters
box Box
Returns
True True if intersects
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 236 of file geomObjects.h.
{
               return false;
             };
doesIntersect() [2/2]
virtual bool util::geometry::GeomObject::doesIntersect (const util::Point & x) const inline virtual
Checks if point lies exactly on the boundary.
Parameters
x Point
Returns
True True if it lies on the boundary
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 191 of file geomObjects.h.
 { return false; };
inscribedRadius()
virtual double util::geometry::GeomObject::inscribedRadius () const inline virtual
Computes the radius of biggest circle/sphere completely within the object.
Returns
Radius Radius of inscribed circle/sphere
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 135 of file geomObjects.h.
 { return 0.; };
isInside() [1/2]
virtual bool util::geometry::GeomObject::isInside (const std::pair< util::Point, util::Point > & box) const inline virtual
Checks if box is completely inside.
Parameters
box Box
Returns
True True if box lies inside
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 205 of file geomObjects.h.
{
               return false;
             };
isInside() [2/2]
virtual bool util::geometry::GeomObject::isInside (const util::Point & x) const inline virtual
Checks if point is inside this object.
Parameters
x Point
Returns
True If point lies inside
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 153 of file geomObjects.h.
 { return false; };
isNear() [1/2]
virtual bool util::geometry::GeomObject::isNear (const std::pair< util::Point, util::Point > & box, const double & tol) const inline virtual
Checks if box is within given distance of this object.
Parameters
box Box
tol Tolerance used in checking the nearness
Returns
True True if box is inside within the tol distance
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 225 of file geomObjects.h.
{
               return false;
             };
isNear() [2/2]
virtual bool util::geometry::GeomObject::isNear (const util::Point & x, const double & tol) const inline virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
Returns
True True if within the tol distance
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 169 of file geomObjects.h.
{
               return false;
             };
isNearBoundary()
virtual bool util::geometry::GeomObject::isNearBoundary (const util::Point & x, const double & tol, const bool & within) const inline virtual
Checks if point is within given distance of this object.
Parameters
x Point
tol Tolerance used in checking the nearness
within Check if the point is within (inside) the object
Returns
True True if it is near within tol distance
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 180 of file geomObjects.h.
{
               return false;
             };
isOutside() [1/2]
virtual bool util::geometry::GeomObject::isOutside (const std::pair< util::Point, util::Point > & box) const inline virtual
Checks if box is outside of the object.
Parameters
box Box
Returns
True True if box lies outside
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 215 of file geomObjects.h.
{
               return false;
             };
isOutside() [2/2]
virtual bool util::geometry::GeomObject::isOutside (const util::Point & x) const inline virtual
Checks if point is outside of this object.
Parameters
x Point
Returns
True If point lies outside
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 161 of file geomObjects.h.
 { return false; };
print() [1/2]
virtual void util::geometry::GeomObject::print () const inline virtual
Prints the information about the object.
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, util::geometry::Line, and util::geometry::NullGeomObject.
Definition at line 277 of file geomObjects.h.
 { print(0, 0); };
References print().
Referenced by print().
print() [2/2]
virtual void util::geometry::GeomObject::print (int nt, int lvl) const inline virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, util::geometry::Line, and util::geometry::NullGeomObject.
Definition at line 272 of file geomObjects.h.
{
               std::cout << printStr(nt, lvl);
             };
References printStr().
printStr()
virtual std::string util::geometry::GeomObject::printStr (int nt, int lvl) const inline virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, util::geometry::Line, and util::geometry::NullGeomObject.
Definition at line 250 of file geomObjects.h.
{
               auto tabS = util::io::getTabS(nt);
               std::ostringstream oss;
               oss << tabS << "------- GeomObject --------" << std::endl
                   << std::endl;
               oss << tabS << "Base geometrical object" << std::endl;
               oss << tabS << "Base implementation of GeomObject." << std::endl;
               oss << tabS << "Name of GeomObject = " << d_name << std::endl;
               oss << tabS << "Description of GeomObject = " << d_description
                   << std::endl;
               return oss.str();
             };
References d_description, d_name, util::io::getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by print().
volume()
virtual double util::geometry::GeomObject::volume () const inline virtual
Computes the volume (area in 2d, length in 1d) of object.
Returns
Volume Volume of object
Reimplemented in util::geometry::ComplexGeomObject, util::geometry::AnnulusGeomObject, util::geometry::Cylinder, util::geometry::Sphere, util::geometry::Circle, util::geometry::Cuboid, util::geometry::Cube, util::geometry::Drum2D, util::geometry::Hexagon, util::geometry::Rectangle, util::geometry::Square, util::geometry::Triangle, and util::geometry::Line.
Definition at line 104 of file geomObjects.h.
 { return 0.; };
Field Documentation
d_description
const std::string util::geometry::GeomObject::d_description
Further description of object.
Definition at line 284 of file geomObjects.h.
Referenced by printStr().
d_name
const std::string util::geometry::GeomObject::d_name
name of object
Definition at line 277 of file geomObjects.h.
Referenced by printStr(), and util::geometry::NullGeomObject::printStr().
The documentation for this class was generated from the following file:
/home/user/project/src/util/geomObjects.h