PeriDEM: particle::Particle Class Reference
particle::Particle Class Reference
A class to store particle geometry, nodal discretization, and methods.
#include <particle.h>
Public Member Functions
Particle (size_t id, inp::ParticleZone &z_deck, size_t particle_zone, std::shared_ptr< particle::RefParticle > ref_particle, std::shared_ptr< util::geometry::GeomObject > geom, const particle::ParticleTransform &transform, std::shared_ptr< model::ModelData > model_data, bool populate_data=true)
Constructor.
util::Point & getXCenter ()
Get current coordinate of center node.
const util::Point & getXCenter () const
Get current coordinate of center node.
util::Point & getUCenter ()
Get displacement of center node.
const util::Point & getUCenter () const
Get displacement of center node.
util::Point & getVCenter ()
Get velocity of center node.
const util::Point & getVCenter () const
Get velocity of center node.
Public Member Functions inherited from particle::BaseParticle
BaseParticle (std::string type="none")
Constructor.
BaseParticle (std::string type, size_t id, size_t type_id, size_t zone_id, size_t dim, size_t num_nodes, double h, std::shared_ptr< model::ModelData > model_data)
Constructor.
std::string getType () const
Get type of this object.
int getTypeIndex () const
Get type (in integer format) of this object.
size_t getId () const
Get id.
size_t getTypeId () const
Get id among the group of object in the same type as this.
size_t getDimension () const
Get the dimension of the domain.
double getMeshSize () const
Get mesh size.
double getDensity () const
Get density.
double getHorizon () const
Get horizon.
material::Material * getMaterial ()
Get pointer to material object.
const material::Material * getMaterial () const
Get type of this object.
size_t getNumNodes () const
Get the number of nodes.
size_t getNodeId (size_t i_loc) const
Get global id of node given the local id of node in this object.
util::Point & getXRef (size_t i)
Get reference coordinate of the node.
const util::Point & getXRef (size_t i) const
Get reference coordinate of the node.
void setXRef (size_t i, const util::Point &x)
Set reference coordinate of the node.
void addXRef (size_t i, const util::Point &x)
Add reference coordinate of the node.
void setXRef (size_t i, int dof, double x)
Set specific reference coordinate of the node.
void addXRef (size_t i, int dof, double x)
Add specific reference coordinate of the node.
util::Point & getXRefLocal (size_t i)
Get reference coordinate of the node given node's local id.
const util::Point & getXRefLocal (size_t i) const
Get reference coordinate of the node.
void setXRefLocal (size_t i, const util::Point &x)
Set reference coordinate of the node given node's local id.
void addXRefLocal (size_t i, const util::Point &x)
Add to reference coordinate of the node given node's local id.
void setXRefLocal (size_t i, int dof, double x)
Set specific reference coordinate of the node given node's local id.
void addXRefLocal (size_t i, int dof, double x)
Add to specific reference coordinate of the node given node's local id.
util::Point & getX (size_t i)
Get current coordinate of the node.
const util::Point & getX (size_t i) const
Get current coordinate of the node.
void setX (size_t i, const util::Point &x)
Set current coordinate of the node.
void addX (size_t i, const util::Point &x)
Add current coordinate of the node.
void setX (size_t i, int dof, double x)
Set specific current coordinate of the node.
void addX (size_t i, int dof, double x)
Add to specific current coordinate of the node.
util::Point & getXLocal (size_t i)
Get current coordinate of the node given node's local id.
const util::Point & getXLocal (size_t i) const
Get current coordinate of the node.
void setXLocal (size_t i, const util::Point &x)
Set current coordinate of the node given node's local id.
void addXLocal (size_t i, const util::Point &x)
Add to current coordinate of the node given node's local id.
void setXLocal (size_t i, int dof, double x)
Set specific current coordinate of the node given node's local id.
void addXLocal (size_t i, int dof, double x)
Add to specific current coordinate of the node given node's local id.
util::Point & getU (size_t i)
Get displacement of the node.
const util::Point & getU (size_t i) const
Get displacement of the node.
void setU (size_t i, const util::Point &u)
Set displacement of the node.
void addU (size_t i, const util::Point &u)
Add to displacement of the node.
void setU (size_t i, int dof, double u)
Set displacement of the node.
void addU (size_t i, int dof, double u)
Add to displacement of the node.
util::Point & getULocal (size_t i)
Get displacement of the node given node's local id.
const util::Point & getULocal (size_t i) const
Get displacement of the node given node's local id.
void setULocal (size_t i, const util::Point &u)
Set displacement of the node given node's local id.
void addULocal (size_t i, const util::Point &u)
Add to displacement of the node given node's local id.
void setULocal (size_t i, int dof, double u)
Set displacement of the node given node's local id.
void addULocal (size_t i, int dof, double u)
Add to displacement of the node given node's local id.
util::Point & getV (size_t i)
Get velocity of the node.
const util::Point & getV (size_t i) const
Get velocity of the node.
void setV (size_t i, const util::Point &v)
Set velocity of the node.
void addV (size_t i, const util::Point &v)
Add to velocity of the node.
void setV (size_t i, int dof, double v)
Set velocity of the node.
void addV (size_t i, int dof, double v)
Add to velocity of the node.
util::Point & getVLocal (size_t i)
Get velocity of the node given node's local id.
const util::Point & getVLocal (size_t i) const
Get velocity of the node.
void setVLocal (size_t i, const util::Point &v)
Set velocity of the node given node's local id.
void addVLocal (size_t i, const util::Point &v)
Add to velocity of the node given node's local id.
void setVLocal (size_t i, int dof, double v)
Set velocity of the node given node's local id.
void addVLocal (size_t i, int dof, double v)
Add to velocity of the node given node's local id.
util::Point & getF (size_t i)
Get force of the node.
const util::Point & getF (size_t i) const
Get force of the node.
void setF (size_t i, const util::Point &f)
Set force of the node.
void addF (size_t i, const util::Point &f)
Add to force of the node.
void setF (size_t i, int dof, double f)
Set force of the node.
void addF (size_t i, int dof, double f)
Add to force of the node.
util::Point & getFLocal (size_t i)
Get force of the node given node's local id.
const util::Point & getFLocal (size_t i) const
Get force of the node.
void setFLocal (size_t i, const util::Point &f)
Set force of the node given node's local id.
void addFLocal (size_t i, const util::Point &f)
Add to force of the node given node's local id.
void setFLocal (size_t i, int dof, double f)
Set force of the node given node's local id.
void addFLocal (size_t i, int dof, double f)
Add to force of the node given node's local id.
double & getVol (size_t i)
Get volume of the node.
const double & getVol (size_t i) const
Get volume of the node.
void setVol (size_t i, const double &vol)
Set volume of the node.
void addVol (size_t i, const double &vol)
Add to volume of the node.
double & getVolLocal (size_t i)
Get volume of the node given node's local id.
const double & getVolLocal (size_t i) const
Get volume of the node.
void setVolLocal (size_t i, const double &vol)
Set volume of the node given node's local id.
void addVolLocal (size_t i, const double &vol)
Add to volume of the node given node's local id.
uint8_t & getFix (size_t i)
Get fixity of the node.
const uint8_t & getFix (size_t i) const
Get fixity of the node.
void setFix (size_t i, const unsigned int &dof, const bool &flag)
Set fixity of the node.
uint8_t & getFixLocal (size_t i)
Get fixity of the node given node's local id.
const uint8_t & getFixLocal (size_t i) const
Get fixity of the node.
void setFixLocal (size_t i, const unsigned int &dof, const bool &flag)
Set fixity of the node given node's local id.
double & getMx (size_t i)
Get weighted-volume (mx) of the node.
const double & getMx (size_t i) const
Get weighted-volume (mx) of the node.
void setMx (size_t i, const double &mx)
Set weighted-volume (mx) of the node.
void addMx (size_t i, const double &mx)
Add to weighted-volume (mx) of the node.
double & getMxLocal (size_t i)
Get weighted-volume (mx) of the node given node's local id.
const double & getMxLocal (size_t i) const
Get weighted-volume (mx) of the node.
void setMxLocal (size_t i, const double &mx)
Set weighted-volume (mx) of the node given node's local id.
void addMxLocal (size_t i, const double &mx)
Add to weighted-volume (mx) of the node given node's local id.
double & getThetax (size_t i)
Get volumetric deformation (thetax) of the node.
const double & getThetax (size_t i) const
Get volumetric deformation (thetax) of the node.
void setThetax (size_t i, const double &thetax)
Set volumetric deformation (thetax) of the node.
void addThetax (size_t i, const double &thetax)
Add to volumetric deformation (thetax) of the node.
double & getThetaxLocal (size_t i)
Get volumetric deformation (thetax) of the node given node's local id.
const double & getThetaxLocal (size_t i) const
Get volumetric deformation (thetax) of the node.
void setThetaxLocal (size_t i, const double &thetax)
Set volumetric deformation (thetax) of the node given node's local id.
void addThetaxLocal (size_t i, const double &thetax)
Add to volumetric deformation (thetax) of the node given node's local id.
Data Fields
std::shared_ptr< particle::RefParticle > d_rp_p
Pointer to reference particle.
std::shared_ptr< util::geometry::GeomObject > d_geom_p
Geometrical object defining this particle.
particle::ParticleTransform d_tform
Transformation related data.
Data Fields inherited from particle::BaseParticle
std::string d_type
particle type
int d_typeIndex
size_t d_id
Id of this particle.
size_t d_typeId
Id of this particle in the category (for example if this is a wall, what is its id in vector of walls)
size_t d_zoneId
Specify zone to which this particle belongs to.
size_t d_dim
Dimension of this particle.
size_t d_numNodes
Number of nodes in this particle.
double d_h
mesh size
bool d_computeForce
Specify if we compute force.
double d_horizon
horizon
double d_density
density
std::unique_ptr< material::Material > d_material_p
Pointer to peridynamic material object.
double d_Rc
Contact radius for contact between internal nodes of particle.
double d_Kn
Normal contact coefficient for internal contact.
size_t d_globStart
Id of first node of this object in global node list.
size_t d_globEnd
Id of last node of this object in global node list.
std::shared_ptr< model::ModelData > d_modelData_p
Reference to model class.
Detailed Description
A class to store particle geometry, nodal discretization, and methods.
On top of this class, specialized class representing particle and wall are built.
Definition at line 35 of file particle.h.
Constructor & Destructor Documentation
Particle()
particle::Particle::Particle (size_t id, inp::ParticleZone & z_deck, size_t particle_zone, std::shared_ptr< particle::RefParticle > ref_particle, std::shared_ptr< util::geometry::GeomObject > geom, const particle::ParticleTransform & transform, std::shared_ptr< model::ModelData > model_data, bool populate_data = true)
Constructor.
Parameters
id Id of this object in group of all base particles
z_deck Zone input deck
particle_zone Id of zone this particle belongs to
ref_particle Pointer to reference particle
geom Geometrical object representing this object
transform Transform object to be applied to reference particle to get this particle
model_data Global model data
populate_data Modify global model data to add the properties of this object
Definition at line 23 of file particle.cpp.
    : BaseParticle("particle", id, id, particle_zone,
                   ref_particle->getDimension(),
                   ref_particle->getNumNodes(), 0., model_data),
      d_rp_p(ref_particle), d_geom_p(geom), d_tform(transform) {
  if (populate_data) {
    d_globStart = d_modelData_p->d_x.size();
    d_globEnd = d_modelData_p->d_x.size() + d_rp_p->getNumNodes();
    for (size_t i = 0; i < d_rp_p->getNumNodes(); i++) {
      d_modelData_p->d_xRef.push_back(d_tform.apply(d_rp_p->getNode(i)));
      d_modelData_p->d_x.push_back(d_tform.apply(d_rp_p->getNode(i)));
      d_modelData_p->d_u.push_back(util::Point());
      d_modelData_p->d_v.push_back(util::Point());
      d_modelData_p->d_f.push_back(util::Point());
      d_modelData_p->d_vol.push_back(
          d_rp_p->getNodalVolume(i) *
          std::pow(d_tform.d_scale, d_rp_p->getDimension()));
      d_modelData_p->d_fix.push_back(uint8_t(0));
      d_modelData_p->d_forceFixity.push_back(uint8_t(0));
      d_modelData_p->d_thetaX.push_back(0.);
      d_modelData_p->d_mX.push_back(0.);
      d_modelData_p->d_ptId.push_back(id); // id of this particle
    }
  }
  d_h = util::computeMeshSize(d_modelData_p->d_x, d_globStart,
                                        d_globEnd);
  // initialize material class
  inp::MaterialDeck material_deck = z_deck.d_matDeck;
  // double horizon = d_geom_p->inscribedRadius();
  double horizon = material_deck.d_horizon;
  if (material_deck.d_horizonMeshRatio > 0.)
    horizon = material_deck.d_horizonMeshRatio * d_h;
  if (material_deck.d_materialType == "RNPBond")
    d_material_p = std::make_unique<material::RnpMaterial>(
        material_deck, d_rp_p->getDimension(), horizon);
  else if (material_deck.d_materialType == "PMBBond")
    d_material_p = std::make_unique<material::PmbMaterial>(
        material_deck, d_rp_p->getDimension(), horizon);
  else if (material_deck.d_materialType == "PDElasticBond")
    d_material_p = std::make_unique<material::PdElastic>(
        material_deck, d_rp_p->getDimension(), horizon);
  else if (material_deck.d_materialType == "PDState")
    d_material_p = std::make_unique<material::PdState>(
        material_deck, d_rp_p->getDimension(), horizon);
  d_horizon = horizon;
  d_density = d_material_p->getDensity();
  // d_material_p->print();
  // set contact radius for internal contact
  d_Rc = 0.95 * d_h;
  // set contact coefficient for internal contact
  d_Kn = (18. / (M_PI * std::pow(horizon, 5))) *
         d_material_p->computeMaterialProperties(getDimension()).d_K;
}
References particle::ParticleTransform::apply(), util::computeMeshSize(), particle::BaseParticle::d_density, particle::BaseParticle::d_globEnd, particle::BaseParticle::d_globStart, particle::BaseParticle::d_h, inp::MaterialDeck::d_horizon, particle::BaseParticle::d_horizon, inp::MaterialDeck::d_horizonMeshRatio, particle::BaseParticle::d_Kn, inp::ParticleZone::d_matDeck, particle::BaseParticle::d_material_p, inp::MaterialDeck::d_materialType, particle::BaseParticle::d_modelData_p, particle::BaseParticle::d_Rc, d_rp_p, particle::ParticleTransform::d_scale, d_tform, particle::BaseParticle::getDimension(), and particle::BaseParticle::getNumNodes().
Member Function Documentation
getUCenter() [1/2]
util::Point & particle::Particle::getUCenter () inline
Get displacement of center node.
Returns
u Displacement
Definition at line 77 of file particle.h.
{
    return d_modelData_p->getU(d_globStart + d_rp_p->getCenterNodeId());
  };
References particle::BaseParticle::d_globStart, particle::BaseParticle::d_modelData_p, and d_rp_p.
getUCenter() [2/2]
const util::Point & particle::Particle::getUCenter () const inline
Get displacement of center node.
Returns
u Displacement
Definition at line 82 of file particle.h.
{
    return d_modelData_p->getU(d_globStart + d_rp_p->getCenterNodeId());
  };
References particle::BaseParticle::d_globStart, particle::BaseParticle::d_modelData_p, and d_rp_p.
getVCenter() [1/2]
util::Point & particle::Particle::getVCenter () inline
Get velocity of center node.
Returns
v Velocity
Definition at line 90 of file particle.h.
{
    return d_modelData_p->getV(d_globStart + d_rp_p->getCenterNodeId());
  };
References particle::BaseParticle::d_globStart, particle::BaseParticle::d_modelData_p, and d_rp_p.
getVCenter() [2/2]
const util::Point & particle::Particle::getVCenter () const inline
Get velocity of center node.
Returns
v Velocity
Definition at line 95 of file particle.h.
{
    return d_modelData_p->getV(d_globStart + d_rp_p->getCenterNodeId());
  };
References particle::BaseParticle::d_globStart, particle::BaseParticle::d_modelData_p, and d_rp_p.
getXCenter() [1/2]
util::Point & particle::Particle::getXCenter () inline
Get current coordinate of center node.
Returns
x Current coordinate
Definition at line 64 of file particle.h.
{
    return d_modelData_p->getX(d_globStart + d_rp_p->getCenterNodeId());
  };
References particle::BaseParticle::d_globStart, particle::BaseParticle::d_modelData_p, and d_rp_p.
getXCenter() [2/2]
const util::Point & particle::Particle::getXCenter () const inline
Get current coordinate of center node.
Returns
x Current coordinate
Definition at line 69 of file particle.h.
{
    return d_modelData_p->getX(d_globStart + d_rp_p->getCenterNodeId());
  };
References particle::BaseParticle::d_globStart, particle::BaseParticle::d_modelData_p, and d_rp_p.
Field Documentation
d_geom_p
std::shared_ptr<util::geometry::GeomObject> particle::Particle::d_geom_p
Geometrical object defining this particle.
Definition at line 104 of file particle.h.
d_rp_p
std::shared_ptr<particle::RefParticle> particle::Particle::d_rp_p
Pointer to reference particle.
Definition at line 101 of file particle.h.
Referenced by getUCenter(), getUCenter(), getVCenter(), getVCenter(), getXCenter(), getXCenter(), and Particle().
d_tform
particle::ParticleTransform particle::Particle::d_tform
Transformation related data.
Definition at line 107 of file particle.h.
Referenced by Particle().
The documentation for this class was generated from the following files:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/particle/particle.h
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/particle/particle.cpp