PeriDEM: material::PdState Class Reference
material::PdState Class Reference
A class providing methods to compute energy density and force of peridynamic material.
#include <material.h>
Public Member Functions
PdState (inp::MaterialDeck &deck, const size_t &dim, const double &horizon)
Constructor.
bool isStateActive () const override
Returns true if state-based potential is active.
std::pair< double, double > getBondEF (const double &r, const double &s, bool &fs, const bool &break_bonds) const override
Returns energy and force between bond due to pairwise interaction.
std::pair< double, double > getBondEF (const double &r, const double &s, bool &fs, const double &mx, const double &thetax) const override
Returns energy and force between bond due to state-based model.
util::Point getBondForceDirection (const util::Point &dx, const util::Point &du) const override
Returns the unit vector along which bond-force acts.
double getS (const util::Point &dx, const util::Point &du) const override
Returns the bond strain.
double getSc (const double &r) const override
Returns critical bond strain.
double getDensity () const override
Returns the density of the material.
double getInfFn (const double &r) const override
Returns the value of influence function.
double getMoment (const size_t &i) const override
Returns the moment of influence function.
double getHorizon () const override
Returns horizon.
inp::MatData computeMaterialProperties (const size_t &dim) const override
Computes elastic and fracture material properties and returns the data.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Public Member Functions inherited from material::Material
Material (std::string name="")
Constructor.
virtual ~Material ()
Destructor.
std::string name ()
Returns name of the material.
size_t getDimension ()
Returns dimension of the problem.
bool isPlaneStrain ()
Returns plane-strain condition.
Private Member Functions
void computeParameters (inp::MaterialDeck &deck, const size_t &dim)
Compute material model parameters.
Private Attributes
double d_horizon
Horizon.
double d_density
Density.
Material parameters
double d_K
Bulk modulus.
double d_G
Shear modulus.
double d_s0
Critical stretch.
Detailed Description
A class providing methods to compute energy density and force of peridynamic material.
Definition at line 1330 of file material.h.
Constructor & Destructor Documentation
PdState()
material::PdState::PdState (inp::MaterialDeck & deck, const size_t & dim, const double & horizon) inline
Constructor.
Parameters
deck Input deck which contains user-specified information
dim Dimension
horizon Horizon
Definition at line 1339 of file material.h.
      : Material("PDState"), d_horizon(horizon), d_density(deck.d_density),
        d_K(0.), d_G(0.), d_s0(0.) {
    // set global fields
    if (dimension != dim)
      dimension = dim;
    if (is_plane_strain != deck.d_isPlaneStrain)
      is_plane_strain = deck.d_isPlaneStrain;
    // create influence function
    if (deck.d_influenceFnType == 0) {
      if (influence_fn == nullptr)
        influence_fn = std::make_shared<material::ConstInfluenceFn>(
            deck.d_influenceFnParams, dim);
    }
    else if (deck.d_influenceFnType == 1) {
      if (influence_fn == nullptr)
        influence_fn = std::make_shared<material::LinearInfluenceFn>(
            deck.d_influenceFnParams, dim);
    }
    else if (deck.d_influenceFnType == 2) {
      if (influence_fn == nullptr)
        influence_fn = std::make_shared<material::GaussianInfluenceFn>(
            deck.d_influenceFnParams, dim);
    }
    else {
      std::cerr << "Error: Influence function type = "
                << deck.d_influenceFnType
                << " is invalid.\n";
      exit(1);
    }
    // check if we need to compute the material parameters
    if (deck.d_computeParamsFromElastic)
      computeParameters(deck, dim);
    else {
      d_K = deck.d_bondPotentialParams[0];
      d_G = deck.d_bondPotentialParams[1];
      d_s0 = deck.d_bondPotentialParams[2];
    }
  };
References computeParameters(), inp::MaterialDeck::d_bondPotentialParams, inp::MaterialDeck::d_computeParamsFromElastic, d_G, inp::MaterialDeck::d_influenceFnParams, inp::MaterialDeck::d_influenceFnType, inp::MaterialDeck::d_isPlaneStrain, d_K, and d_s0.
Member Function Documentation
computeMaterialProperties()
inp::MatData material::PdState::computeMaterialProperties (const size_t & dim) const inline override virtual
Computes elastic and fracture material properties and returns the data.
Parameters
dim Dimension of the problem
Returns
Data Material data
Implements material::Material.
Definition at line 1504 of file material.h.
{
    auto data = inp::MatData();
    // we already have G and K
    data.d_G = d_G;
    data.d_K = d_K;
    // get Poisson ratio and Young's modulus
    data.d_nu = (3. * d_K - 2. * d_G) / (2. * (3. * d_K + d_G));
    data.d_E = data.toE(d_K, data.d_nu);
    // get lame parameters
    data.d_lambda = data.toLambdaE(data.d_E, data.d_nu);
    data.d_mu = d_G;
    // get Gc
    double d =
        (3. * d_G + std::pow(3. / 4., 4) * (d_K - 5. * d_G / 3.)) * d_horizon;
    data.d_Gc = d_s0 * d_s0 * d;
    // KIc
    data.d_KIc = data.toKIc(
        data.d_Gc, data.d_nu, data.d_E);
    return data;
  };
References d_G, d_horizon, d_K, and d_s0.
computeParameters()
void material::PdState::computeParameters (inp::MaterialDeck & deck, const size_t & dim) inline private
Compute material model parameters.
Parameters
deck MaterialDeck
dim Dimension of the domain
Definition at line 1579 of file material.h.
{
    //
    // Need following elastic and fracture properties
    // 1. E or K
    // 2. Poisson ratio or shear modulus
    // 3. Gc or KIc
    //
    bool found_E = false;
    bool found_K = false;
    bool found_G = false;
    bool found_nu = false;
    size_t num_props = 0;
    found_E = util::isGreater(deck.d_matData.d_E, 0.);
    if (found_E)
      num_props++;
    found_K = util::isGreater(deck.d_matData.d_K, 0.);
    if (found_K)
      num_props++;
    found_G = util::isGreater(deck.d_matData.d_G, 0.);
    if (found_G)
      num_props++;
    found_nu = util::isGreater(deck.d_matData.d_nu, 0.);
    if (found_nu)
      num_props++;
    if (num_props != 2) {
      std::ostringstream oss;
      oss << "Error: Require two different elastic properties for the "
                   "PdState material. Pairs supported are (E, K), (E, G), "
                   "(E, nu), (K, G).\n";
      oss << deck.printStr(0, 0) << "\n";
      std::cout << oss.str();
      exit(1);
    }
    if (util::isLess(deck.d_matData.d_Gc, 0.) &&
        util::isLess(deck.d_matData.d_KIc, 0.)) {
      std::cerr << "Error: Require either critical energy release rate Gc or "
                   "critical stress intensity factor KIc to compute the RNP "
                   "bond-based peridynamic parameters.\n";
      exit(1);
    } else if (util::isGreater(deck.d_matData.d_Gc, 0.) &&
               util::isGreater(deck.d_matData.d_KIc, 0.)) {
      std::cout << "Warning: Both critical energy release rate Gc and critical "
                   "stress intensity factor KIc are provided.\n";
      std::cout << "Warning: To compute the RNP bond-based peridynamic "
                   "parameters, we only require one of those.\n";
      std::cout << "Warning: Selecting critical energy release rate Gc to "
                   "compute parameters.\n";
    }
    // compute nu if not provided
    if (!found_nu) {
      if (found_E and found_G)
        deck.d_matData.d_nu =
            (0.5 * deck.d_matData.d_E / deck.d_matData.d_G) - 1.;
      if (found_E and found_K)
        deck.d_matData.d_nu =
            (3. * deck.d_matData.d_K - deck.d_matData.d_E) /
            (6. * deck.d_matData.d_K);
      if (found_G and found_K)
        deck.d_matData.d_nu =
            (3. * deck.d_matData.d_K - 2. * deck.d_matData.d_G) /
            (2. * (3. * deck.d_matData.d_K + deck.d_matData.d_G));
    }
    found_nu = true;
    // compute E if not provided
    if (!found_E) {
      if (found_K)
        deck.d_matData.d_E =
            deck.d_matData.toE(deck.d_matData.d_K, deck.d_matData.d_nu);
      if (found_G)
        deck.d_matData.d_E =
            2. * deck.d_matData.d_G * (1. + deck.d_matData.d_nu);
    }
    found_E = true;
    // compute K if not provided
    if (!found_K)
      deck.d_matData.d_K =
          deck.d_matData.toK(deck.d_matData.d_E, deck.d_matData.d_nu);
    found_K = true;
    // compute G if not provided
    if (!found_G)
      deck.d_matData.d_G =
          deck.d_matData.toGE(deck.d_matData.d_E, deck.d_matData.d_nu);
    found_G = true;
    // compute Gc (if not provided) and KIc (if not provided)
    if (deck.d_matData.d_Gc > 0.)
      deck.d_matData.d_KIc = deck.d_matData.toKIc(
          deck.d_matData.d_Gc, deck.d_matData.d_nu, deck.d_matData.d_E);
    if (deck.d_matData.d_KIc > 0. && deck.d_matData.d_Gc < 0.)
      deck.d_matData.d_Gc = deck.d_matData.toGc(
          deck.d_matData.d_KIc, deck.d_matData.d_nu, deck.d_matData.d_E);
    // compute lame parameter
    deck.d_matData.d_lambda =
        deck.d_matData.toLambdaE(deck.d_matData.d_E, deck.d_matData.d_nu);
    deck.d_matData.d_mu = deck.d_matData.d_G;
    // compute peridynamic parameters
    d_K = deck.d_matData.d_K;
    d_G = deck.d_matData.d_G;
    double d =
        (3. * d_G + std::pow(3. / 4., 4) * (d_K - 5. * d_G / 3.)) * d_horizon;
    d_s0 = std::sqrt(deck.d_matData.d_Gc / d);
  };
References inp::MatData::d_E, inp::MatData::d_G, d_G, inp::MatData::d_Gc, d_horizon, inp::MatData::d_K, d_K, inp::MatData::d_KIc, inp::MatData::d_lambda, inp::MaterialDeck::d_matData, inp::MatData::d_mu, inp::MatData::d_nu, d_s0, util::isGreater(), util::isLess(), inp::MaterialDeck::printStr(), inp::MatData::toE(), inp::MatData::toGc(), inp::MatData::toGE(), inp::MatData::toK(), inp::MatData::toKIc(), and inp::MatData::toLambdaE().
Referenced by PdState().
getBondEF() [1/2]
std::pair< double, double > material::PdState::getBondEF (const double & r, const double & s, bool & fs, const bool & break_bonds) const inline override virtual
Returns energy and force between bond due to pairwise interaction.
Parameters
r Reference (initial) bond length
s Bond strain
fs Bond fracture state
break_bonds Flag to specify whether bonds are allowed to break or not
Returns
value Pair of energy and force
Implements material::Material.
Definition at line 1398 of file material.h.
{
    return {0., 0.};
  };
getBondEF() [2/2]
std::pair< double, double > material::PdState::getBondEF (const double & r, const double & s, bool & fs, const double & mx, const double & thetax) const inline override virtual
Returns energy and force between bond due to state-based model.
Parameters
r Reference (initial) bond length
s Bond strain
fs Bond fracture state
mx Weighted volume at node
thetax Dilation
Returns
value Pair of energy and force
Implements material::Material.
Definition at line 1416 of file material.h.
{
    if (fs)
      return {0., 0.};
    double J = getInfFn(r);
    double change_length = s * r;
    double alpha = 15. * d_G / mx;
    double factor = (3. * d_K / mx) - alpha / 3.;
    return {0., J * (r * thetax * factor + change_length * alpha)};
  };
References d_G, d_K, and getInfFn().
getBondForceDirection()
util::Point material::PdState::getBondForceDirection (const util::Point & dx, const util::Point & du) const inline override virtual
Returns the unit vector along which bond-force acts.
Parameters
dx Reference bond vector
du Difference of displacement
Returns
vector Unit vector
Implements material::Material.
Definition at line 1438 of file material.h.
{
    return (dx + du) / (dx + du).length();
  };
getDensity()
double material::PdState::getDensity () const inline override virtual
Returns the density of the material.
Returns
density Density of the material
Implements material::Material.
Definition at line 1465 of file material.h.
{ return d_density; };
References d_density.
getHorizon()
double material::PdState::getHorizon () const inline override virtual
Returns horizon.
Returns
horizon Horizon
Implements material::Material.
Definition at line 1495 of file material.h.
{ return d_horizon; };
References d_horizon.
getInfFn()
double material::PdState::getInfFn (const double & r) const inline override virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implements material::Material.
Definition at line 1473 of file material.h.
{
    return getGlobalInfFn(r / d_horizon);
  };
References d_horizon.
Referenced by getBondEF().
getMoment()
double material::PdState::getMoment (const size_t & i) const inline override virtual
Returns the moment of influence function.
If \(J(r) \) is the influence function for \(r\in [0,1)\) then \(i^{th}\) moment is given by
\[ M_i = \int_0^1 J(r) r^i dr. \]
Parameters
i ith moment
Returns
value Moment
Implements material::Material.
Definition at line 1486 of file material.h.
{
    return getGlobalMoment(i);
  };
getS()
double material::PdState::getS (const util::Point & dx, const util::Point & du) const inline override virtual
Returns the bond strain.
Parameters
dx Reference bond vector
du Difference of displacement
Returns
strain Bond strain \(S = \frac{du \cdot dx}{|dx|^2} \)
Implements material::Material.
Definition at line 1449 of file material.h.
{
    return ((dx + du).length() - dx.length()) / dx.length();
  };
References util::Point::length().
getSc()
double material::PdState::getSc (const double & r) const inline override virtual
Returns critical bond strain.
Parameters
r Reference length of bond
Returns
strain Critical strain
Implements material::Material.
Definition at line 1459 of file material.h.
{ return d_s0; };
References d_s0.
isStateActive()
bool material::PdState::isStateActive () const inline override virtual
Returns true if state-based potential is active.
Returns
bool True/false
Implements material::Material.
Definition at line 1387 of file material.h.
{ return true; };
print() [1/2]
void material::PdState::print () const inline override virtual
Prints the information about the object.
Reimplemented from material::Material.
Definition at line 1570 of file material.h.
{ print(0, 0); };
References print().
Referenced by print().
print() [2/2]
void material::PdState::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from material::Material.
Definition at line 1565 of file material.h.
{
    std::cout << printStr(nt, lvl);
  };
References printStr().
printStr()
std::string material::PdState::printStr (int nt, int lvl) const inline override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from material::Material.
Definition at line 1539 of file material.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- particle::PdState --------" << std::endl
        << std::endl;
    oss << tabS << "State active = " << 1 << std::endl;
    oss << tabS << "Horizon = " << d_horizon << std::endl;
    oss << tabS << "Influence fn address = " << influence_fn.get() << std::endl;
    oss << tabS << "Influence fn info: " << std::endl;
    oss << influence_fn->printStr(nt + 1, lvl);
    oss << tabS << "Peridynamic parameters: " << std::endl;
    oss << tabS << "  K = " << d_K << std::endl;
    oss << tabS << "  G = " << d_G << std::endl;
    oss << tabS << "  s0 = " << d_s0 << std::endl;
    oss << tabS << std::endl;
    return oss.str();
  };
References d_G, d_horizon, d_K, d_s0, and util::io::getTabS().
Referenced by print().
Field Documentation
d_density
double material::PdState::d_density private
Density.
Definition at line 1707 of file material.h.
Referenced by getDensity().
d_G
double material::PdState::d_G private
Shear modulus.
Definition at line 1718 of file material.h.
Referenced by computeMaterialProperties(), computeParameters(), getBondEF(), PdState(), and printStr().
d_horizon
double material::PdState::d_horizon private
Horizon.
Definition at line 1704 of file material.h.
Referenced by computeMaterialProperties(), computeParameters(), getHorizon(), getInfFn(), and printStr().
d_K
double material::PdState::d_K private
Bulk modulus.
Definition at line 1715 of file material.h.
Referenced by computeMaterialProperties(), computeParameters(), getBondEF(), PdState(), and printStr().
d_s0
double material::PdState::d_s0 private
Critical stretch.
Definition at line 1721 of file material.h.
Referenced by computeMaterialProperties(), computeParameters(), getSc(), PdState(), and printStr().
The documentation for this class was generated from the following file:
/home/user/project/src/material/mparticle/material.h