PeriDEM: material::GaussianInfluenceFn Class Reference
material::GaussianInfluenceFn Class Reference
A class to implement Gaussian influence function.
#include <influenceFn.h>
Public Member Functions
GaussianInfluenceFn (const std::vector< double > &params, const size_t &dim)
Constructor.
double getInfFn (const double &r) const override
Returns the value of influence function.
double getMoment (const size_t &i) const override
Returns the moment of influence function.
std::string printStr (int nt, int lvl) const override
Returns the string containing printable information about the object.
void print (int nt, int lvl) const override
Prints the information about the object.
void print () const override
Prints the information about the object.
Public Member Functions inherited from material::BaseInfluenceFn
BaseInfluenceFn ()=default
Constructor.
Private Attributes
double d_alpha
Constants.
double d_beta
Constants.
Detailed Description
A class to implement Gaussian influence function.
\(J(r) = \alpha \exp(-r^2/\beta) \)
Definition at line 227 of file influenceFn.h.
Constructor & Destructor Documentation
GaussianInfluenceFn()
material::GaussianInfluenceFn::GaussianInfluenceFn (const std::vector< double > & params, const size_t & dim)
Constructor.
Parameters
params List of parameters
dim Dimension
Definition at line 63 of file influenceFn.cpp.
     : BaseInfluenceFn(), d_alpha(0.), d_beta(0.) {
   if (params.empty()) {
     // beta = 0.2 (default value)
     // choose alpha such that \int_0^1 J(r) r^d dr = 1
     d_beta = 0.2;
     if (dim == 1)
       d_alpha = 2. / (d_beta * (1. - std::exp(-1. / d_beta)));
     else if (dim == 2)
       d_alpha = (4.0 / d_beta) * 1.0 /
                 (std::sqrt(M_PI * d_beta) * std::erf(1.0 / std::sqrt(d_beta)) -
                  2.0 * std::exp(-1.0 / d_beta));
     else if (dim == 3)
       d_alpha = (2.0 / d_beta) * 1.0 /
                 (d_beta - (d_beta + 1.) * std::exp(-1.0 / d_beta));
   } else {
     d_alpha = params[0];
     d_beta = params[1];
   }
 }
References d_alpha, and d_beta.
Member Function Documentation
getInfFn()
double material::GaussianInfluenceFn::getInfFn (const double & r) const override virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implements material::BaseInfluenceFn.
Definition at line 86 of file influenceFn.cpp.
{
   return d_alpha * std::exp(-r * r / d_beta);
 }
getMoment()
double material::GaussianInfluenceFn::getMoment (const size_t & i) const override virtual
Returns the moment of influence function.
If \(J(r) \) is the influence function for \(r\in [0,1)\) then \(i^{th}\) moment is given by
\[ M_i = \int_0^1 J(r) r^i dr. \]
Parameters
i ith moment
Returns
moment Moment
Implements material::BaseInfluenceFn.
Definition at line 90 of file influenceFn.cpp.
{
   double sq1 = std::sqrt(d_beta);
   double sq2 = std::sqrt(M_PI);
   // M_i = \int_0^1 alpha exp(-r^2/beta) r^i dr
   if (i == 0) {
     // M0 = 0.5 * \alpha (\beta)^(1/2) * (pi)^(1/2) * erf((1/beta)^(1/2))
     return 0.5 * d_alpha * sq1 * sq2 * std::erf(1. / sq1);
   } else if (i == 1) {
     // M1 = 0.5 * \alpha \beta (1 - exp(-1/beta))
     return 0.5 * d_alpha * d_beta * (1. - std::exp(-1. / d_beta));
   } else if (i == 2) {
     // M2 = 0.5 * \alpha (\beta)^(3/2) * [0.5 * (pi)^(1/2) erf((1/beta)^(1/2)
     // ) - (1/beta)^(1/2) * exp(-1/beta) ]
     return 0.5 * d_alpha * d_beta * sq1 *
            (0.5 * sq2 * std::erf(1. / sq1) -
             (1. / sq1) * std::exp(-1. / d_beta));
   } else if (i == 3) {
     // M3 = 0.5 * \alpha (\beta)^(2) * [1 - ((1/beta) + 1) * exp(-1/beta)]
     return 0.5 * d_alpha * d_beta * d_beta *
            (1. - (1. + 1. / d_beta) * std::exp(-1. / d_beta));
   } else {
     std::cerr << "Error: getMoment() accepts argument i from 0 to 3.\n";
     exit(1);
   }
 }
Referenced by printStr().
print() [1/2]
void material::GaussianInfluenceFn::print () const inline override virtual
Prints the information about the object.
Reimplemented from material::BaseInfluenceFn.
Definition at line 289 of file influenceFn.h.
 { print(0, 0); }
References print().
Referenced by print().
print() [2/2]
void material::GaussianInfluenceFn::print (int nt, int lvl) const inline override virtual
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Reimplemented from material::BaseInfluenceFn.
Definition at line 284 of file influenceFn.h.
{
     std::cout << printStr(nt, lvl);
   }
References printStr().
printStr()
std::string material::GaussianInfluenceFn::printStr (int nt, int lvl) const inline override virtual
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Reimplemented from material::BaseInfluenceFn.
Definition at line 263 of file influenceFn.h.
{
     auto tabS = util::io::getTabS(nt);
     std::ostringstream oss;
     oss << tabS << "------- GaussianInfluenceFn --------" << std::endl << std::endl;
     oss << tabS << "Gaussian function a0 * exp(-r*r / a1) with constants: a0 = "
                 << d_alpha << ", a1 = " << d_beta << std::endl;
     oss << tabS << "First moment = " << getMoment(1)
         << ", second moment = " << getMoment(2)
         << ", third moment = " << getMoment(3) << std::endl;
     oss << tabS << std::endl;
     return oss.str();
   }
References d_alpha, d_beta, getMoment(), util::io::getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by print().
Field Documentation
d_alpha
double material::GaussianInfluenceFn::d_alpha private
Constants.
Definition at line 293 of file influenceFn.h.
Referenced by GaussianInfluenceFn(), and printStr().
d_beta
double material::GaussianInfluenceFn::d_beta private
Constants.
Definition at line 296 of file influenceFn.h.
Referenced by GaussianInfluenceFn(), and printStr().
The documentation for this class was generated from the following files:
/home/user/project/src/material/mparticle/influenceFn.h
/home/user/project/src/material/mparticle/influenceFn.cpp