PeriDEM: anonymous_namespace{tetElem.cpp} Namespace Reference
anonymous_namespace{tetElem.cpp} Namespace Reference
Functions
void checkPoint (const std::vector< double > &p, const std::vector< util::Point > &nodes)
Function Documentation
checkPoint()
void anonymous_namespace{tetElem.cpp}::checkPoint (const std::vector< double > & p, const std::vector< util::Point > & nodes)
Definition at line 21 of file tetElem.cpp.
{
   // check to see if p is in reference tet element
   bool check = false;
   if (util::isLess(p[0], -1.0E-5) || util::isLess(p[1], -1.0E-5) || util::isLess(p[2], -1.0E-5) ||
       util::isGreater(p[0], 1. + 1.0E-5) ||
       util::isGreater(p[1], 1. + 1.0E-5) ||
       util::isGreater(p[2], 1. + 1.0E-5)) {
     check = true;
   }
   if (!check) {
     // check if projection of point in x, y, z plane is within the limit
     if (util::isGreater(p[0], 1. + 1.0E-5 - p[1]))
       check = true;
     if (util::isGreater(p[1], 1. + 1.0E-5 - p[2]))
       check = true;
     if (util::isGreater(p[2], 1. + 1.0E-5 - p[0]))
       check = true;
   }
   if (check) {
     std::cerr << "Error: Point p = ("
               << p[0] << ", " << p[1] << ", " << p[2]
               << ") does not belong to reference tet element = {("
               << nodes[0].d_x << ", " << nodes[0].d_y << ", " << nodes[0].d_z
               << "), ("
               << nodes[1].d_x << "," << nodes[1].d_y << ", " << nodes[1].d_z
               << "), ("
               << nodes[2].d_x << "," << nodes[2].d_y << ", " << nodes[2].d_z
               << "), ("
               << nodes[3].d_x << "," << nodes[3].d_y << ", " << nodes[3].d_z
               << ")}.\n"
               << "Coordinates in reference element are: "
               << "xi = " << p[0]
               << ", eta = " << p[1]
               << ", zeta = " << p[2] << "\n";
     exit(1);
   }
 }
References util::isGreater(), and util::isLess().
Referenced by fe::TetElem::mapPointToRefElem().