PeriDEM: anonymous_namespace{input.cpp} Namespace Reference
anonymous_namespace{input.cpp} Namespace Reference
Functions
bool definitelyGreaterThan (const double &a, const double &b)
void rectDataSizeWarning ()
std::string stringVecSerial (const std::vector< std::string > &svec)
void readGeometry (YAML::Node data, std::string data_block_name, std::string &name, std::vector< double > &params, std::pair< std::vector< std::string >, std::vector< std::string >> &complexInfo)
Function Documentation
definitelyGreaterThan()
bool anonymous_namespace{input.cpp}::definitelyGreaterThan (const double & a, const double & b) inline
Definition at line 27 of file input.cpp.
{
   return (a - b) >
          ((std::abs(a) < std::abs(b) ? std::abs(b) : std::abs(a)) * 1.0E-5);
 }
readGeometry()
void anonymous_namespace{input.cpp}::readGeometry (YAML::Node data, std::string data_block_name, std::string & name, std::vector< double > & params, std::pair< std::vector< std::string >, std::vector< std::string >> & complexInfo)
Definition at line 52 of file input.cpp.
{
   if (!data["Type"]) {
     std::cerr << "Error; Can not read geometry type in yaml data in block = "
               << data_block_name << ".\n";
     exit(EXIT_FAILURE);
   }
   name = data["Type"].as<std::string>();
   if (name == "complex") {
     // read vector of types and flags
     if (data["Vec_Type"]) {
       for (auto f: data["Vec_Type"])
         complexInfo.first.push_back(f.as<std::string>());
     } else {
       std::cerr << "Error: To define complex geometry, we require vector of "
                    "types in yaml data block = "
                 << data_block_name << "\n";
       exit(EXIT_FAILURE);
     }
     if (data["Vec_Flag"]) {
       for (auto f: data["Vec_Flag"])
         complexInfo.second.push_back(f.as<std::string>());
     } else {
       std::cerr << "Error: To define complex geometry, we require vector of "
                    "flags in yaml data block = "
                 << data_block_name << "\n";
       exit(EXIT_FAILURE);
     }
   }
   params.clear();
   if (data["Parameters"]) {
     for (auto f : data["Parameters"])
       params.push_back(f.as<double>());
   } else {
     std::cerr << "Error: Parameters defining geometry is not present in data block = "
               << data_block_name << ".\n";
     exit(EXIT_FAILURE);
   }
 }
Referenced by inp::Input::setParticleData(), inp::Input::setParticleDeck(), and inp::Input::setZoneData().
rectDataSizeWarning()
void anonymous_namespace{input.cpp}::rectDataSizeWarning ()
Definition at line 32 of file input.cpp.
{
   std::cout << "Warning: We now require rectangle to be specified "
                "by 3 dimensional coordinates of corner points. In "
                "future, this will be strongly preferred.\n";
 }
stringVecSerial()
std::string anonymous_namespace{input.cpp}::stringVecSerial (const std::vector< std::string > & svec)
Definition at line 38 of file input.cpp.
{
   if (svec.empty())
     return "";
   std::string s = "";
   for (size_t i=0; i<svec.size(); i++) {
     s = s + svec[i];
     if (i < svec.size() - 1)
       s = s + "; ";
   }
   return s;
 }
Referenced by inp::Input::setZoneData().