PeriDEM: anonymous_namespace{materialUtil.cpp} Namespace Reference
anonymous_namespace{materialUtil.cpp} Namespace Reference
Functions
double computeStateMxI (size_t i, const std::vector< util::Point > &nodes, const std::vector< double > &nodal_vol, const std::vector< std::vector< size_t >> &neighbors, const std::vector< std::vector< float >> &neighbors_sq_dist, const double &mesh_size, const material::Material *material)
double computeStateThetaxI (size_t i, const std::vector< util::Point > &nodes, const std::vector< util::Point > &nodes_disp, const std::vector< double > &nodal_vol, const std::vector< std::vector< size_t >> &neighbors, const std::vector< std::vector< float >> &neighbors_sq_dist, const double &mesh_size, const material::Material *material, const geometry::Fracture *fracture, const std::vector< double > &mx)
double computeHydrostaticStrainI (size_t i, const std::vector< util::Point > &nodes, const std::vector< util::Point > &nodes_disp, const std::vector< double > &nodal_vol, const std::vector< std::vector< size_t >> &neighbors, const std::vector< std::vector< float >> &neighbors_sq_dist, const double &mesh_size, const material::Material *material, const geometry::Fracture *fracture, size_t dim)
void updateBondFractureDataI (size_t i, const std::vector< util::Point > &nodes, const std::vector< std::vector< size_t >> &neighbors, const std::vector< util::Point > &nodes_disp, const material::Material *material, geometry::Fracture *fracture)
Function Documentation
computeHydrostaticStrainI()
double anonymous_namespace{materialUtil.cpp}::computeHydrostaticStrainI (size_t i, const std::vector< util::Point > & nodes, const std::vector< util::Point > & nodes_disp, const std::vector< double > & nodal_vol, const std::vector< std::vector< size_t >> & neighbors, const std::vector< std::vector< float >> & neighbors_sq_dist, const double & mesh_size, const material::Material * material, const geometry::Fracture * fracture, size_t dim)
Definition at line 128 of file materialUtil.cpp.
{
   double horizon = material->getHorizon();
   const auto &xi = nodes[i];
   const auto &ui = nodes_disp[i];
   double theta = 0.;
   // upper and lower bound for volume correction
   auto check_up = horizon + 0.5 * mesh_size;
   auto check_low = horizon - 0.5 * mesh_size;
   // get volume of ball
   double vol_ball = std::pow(horizon, 2) * M_PI;
   if (dim == 3)
     vol_ball *= horizon * 4. / 3.;
   size_t k = 0;
   for (size_t j : neighbors[i]) {
     const auto &xj = nodes[j];
     const auto &uj = nodes_disp[j];
     double rji = (xj - xi).length();
     //double rji = std::sqrt(neighbors_sq_dist[i][k]);
     if (util::isGreater(rji, horizon) or j == i)
       continue;
     // get corrected volume of node j
     auto volj = nodal_vol[j];
     if (util::isGreater(rji, check_low))
       volj *= (check_up - rji) / mesh_size;
     // get bond state
     double bond_state = fracture->getBondState(i, k) ? 0. : 1.;
     // get bond strain
     double Sji = material->getS(xj - xi, uj - ui);
     theta += bond_state * rji * Sji *
              material->getInfFn(rji) * volj / vol_ball;
     k += 1;
   }
   return theta;
 }
References geometry::Fracture::getBondState(), particle_wall::horizon, and util::isGreater().
Referenced by material::computeHydrostaticStrain().
computeStateMxI()
double anonymous_namespace{materialUtil.cpp}::computeStateMxI (size_t i, const std::vector< util::Point > & nodes, const std::vector< double > & nodal_vol, const std::vector< std::vector< size_t >> & neighbors, const std::vector< std::vector< float >> & neighbors_sq_dist, const double & mesh_size, const material::Material * material)
Definition at line 21 of file materialUtil.cpp.
{
   double horizon = material->getHorizon();
   const auto &xi = nodes[i];
   double m = 0.;
   // upper and lower bound for volume correction
   auto check_up = horizon + 0.5 * mesh_size;
   auto check_low = horizon - 0.5 * mesh_size;
   size_t k = 0;
   for (size_t j : neighbors[i]) {
     const auto &xj = nodes[j];
     double rji = (xj - xi).length();
     //double rji = std::sqrt(neighbors_sq_dist[i][k]);
     if (util::isGreater(rji, horizon) or j == i)
       continue;
     // get corrected volume of node j
     auto volj = nodal_vol[j];
     if (util::isGreater(rji, check_low))
       volj *= (check_up - rji) / mesh_size;
     m += std::pow(rji, 2) * material->getInfFn(rji) * volj;
     k++;
   }
   if (util::isLess(m, 1.0E-18)) {
     std::ostringstream oss;
     oss << "Error: Weighted nodal volume = " << m
               << " should not be too close to zero.\n";
     oss << "Mesh size = " << mesh_size << "\n";
     oss << "J = " << material->getInfFn(0.5 * horizon) << "\n";
     oss << material->printStr(0, 0);
     std::cout << oss.str();
     exit(1);
   }
   return m;
 }
References particle_wall::horizon, util::isGreater(), util::isLess(), and anonymous_namespace{main.cpp}::oss.
Referenced by material::computeStateMx().
computeStateThetaxI()
double anonymous_namespace{materialUtil.cpp}::computeStateThetaxI (size_t i, const std::vector< util::Point > & nodes, const std::vector< util::Point > & nodes_disp, const std::vector< double > & nodal_vol, const std::vector< std::vector< size_t >> & neighbors, const std::vector< std::vector< float >> & neighbors_sq_dist, const double & mesh_size, const material::Material * material, const geometry::Fracture * fracture, const std::vector< double > & mx)
Definition at line 73 of file materialUtil.cpp.
{
   double horizon = material->getHorizon();
   const auto &xi = nodes[i];
   const auto &ui = nodes_disp[i];
   double m = mx[i];
   double theta = 0.;
   // upper and lower bound for volume correction
   auto check_up = horizon + 0.5 * mesh_size;
   auto check_low = horizon - 0.5 * mesh_size;
   size_t k = 0;
   for (size_t j : neighbors[i]) {
     const auto &xj = nodes[j];
     const auto &uj = nodes_disp[j];
     double rji = (xj - xi).length();
     //double rji = std::sqrt(neighbors_sq_dist[i][k]); // distance in
                                                       // reference configuration
     if (util::isGreater(rji, horizon) or j == i)
       continue;
     // get corrected volume of node j
     auto volj = nodal_vol[j];
     if (util::isGreater(rji, check_low))
       volj *= (check_up - rji) / mesh_size;
     // get bond state
     double bond_state = fracture->getBondState(i, k) ? 0. : 1.;
     // get change in bond length
     auto yi = xi + ui;
     auto yj = xj + uj;
     double change_length = (yj - yi).length() - rji;
     theta += bond_state * rji * change_length *
              material->getInfFn(rji) * volj;
     k += 1;
   }
   return 3. * theta / m;
 }
References geometry::Fracture::getBondState(), particle_wall::horizon, and util::isGreater().
Referenced by material::computeStateThetax().
updateBondFractureDataI()
void anonymous_namespace{materialUtil.cpp}::updateBondFractureDataI (size_t i, const std::vector< util::Point > & nodes, const std::vector< std::vector< size_t >> & neighbors, const std::vector< util::Point > & nodes_disp, const material::Material * material, geometry::Fracture * fracture)
Definition at line 184 of file materialUtil.cpp.
{
   size_t k = 0;
   for (size_t j : neighbors[i]) {
     double s = material->getS(nodes[j] - nodes[i], nodes_disp[j] -
     nodes_disp[i]);
     double sc = material->getSc((nodes[j] - nodes[i]).length());
     // get fracture state, modify, and set
     auto fs = fracture->getBondState(i, k);
     if (!fs && util::isGreater(std::abs(s), sc + 1.0e-10))
       fs = true;
     fracture->setBondState(i, k, fs);
     k += 1;
   }
 }
References geometry::Fracture::getBondState(), util::isGreater(), and geometry::Fracture::setBondState().
Referenced by material::updateBondFractureData().