PeriDEM: anonymous_namespace{particleULoading.cpp} Namespace Reference
anonymous_namespace{particleULoading.cpp} Namespace Reference
Functions
bool isInList (const size_t &i, const std::vector< size_t > &list)
Function Documentation
isInList()
bool anonymous_namespace{particleULoading.cpp}::isInList (const size_t & i, const std::vector< size_t > & list)
Definition at line 23 of file particleULoading.cpp.
{
   for (const auto &l : list)
     if (l == i)
       return true;
   return false;
 }
Referenced by loading::ParticleULoading::applyParticle(), loading::ParticleULoading::applyWall(), loading::ParticleULoading::setFixityParticle(), and loading::ParticleULoading::setFixityWall().