PeriDEM: rw::reader Namespace Reference
rw::reader Namespace Reference
Collection of methods and database related to reading.
Data Structures
class MshReader
A class to read Gmsh (msh) mesh files.
class VtkParticleReader
A vtk writer for simple point data and complex fem mesh data.
class VtkReader
A class to read VTK (.vtu) mesh files.
Functions
CSV specific functions
void readCsvFile (const std::string &filename, size_t dim, std::vector< util::Point > *nodes, std::vector< double > *volumes)
Reads mesh data into node file and element file.
void readParticleCsvFile (const std::string &filename, size_t dim, std::vector< util::Point > *nodes, std::vector< double > *rads, std::vector< size_t > *zones)
Reads particles center location, radius, and zone id.
void readParticleCsvFile (const std::string &filename, size_t dim, std::vector< util::Point > *nodes, std::vector< double > *rads, const size_t &zone)
Reads particles center location, radius, and zone id.
void readParticleWithOrientCsvFile (const std::string &filename, size_t dim, std::vector< util::Point > *nodes, std::vector< double > *rads, std::vector< double > *orients, const size_t &zone)
Reads particles center location, radius, and zone id. In this case, file also provides initial orientation of particles.
VTU specific functions
void readVtuFile (const std::string &filename, size_t dim, std::vector< util::Point > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t > > *nec, std::vector< double > *volumes, bool is_fd=false)
Reads mesh data into node file and element file.
void readVtuFileNodes (const std::string &filename, size_t dim, std::vector< util::Point > *nodes, bool ref_config=false)
Reads nodal coordinates.
void readVtuFileCells (const std::string &filename, size_t dim, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t > > *nec)
Reads cell data, i.e. element-node connectivity and node-element connectivity.
void readVtuFileRestart (const std::string &filename, std::vector< util::Point > *u, std::vector< util::Point > *v, const std::vector< util::Point > *X=nullptr)
Reads mesh data into node file and element file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< uint8_t > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< size_t > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< int > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< float > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< double > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< util::Point > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< util::SymMatrix3 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< util::Matrix3 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< float > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< double > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< util::Point > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< util::SymMatrix3 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< util::Matrix3 > *data)
Reads data of specified tag from the vtu file.
MSH specific functions
void readMshFile (const std::string &filename, size_t dim, std::vector< util::Point > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t > > *nec, std::vector< double > *volumes, bool is_fd=false)
Reads mesh data into node file and element file.
void readMshFileRestart (const std::string &filename, std::vector< util::Point > *u, std::vector< util::Point > *v, const std::vector< util::Point > *X=nullptr)
Reads mesh data into node file and element file.
bool readMshFilePointData (const std::string &filename, const std::string &tag, std::vector< double > *data)
Reads data of specified tag from the vtu file.
void readMshFileCells (const std::string &filename, size_t dim, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t > > *nec)
Reads cell data, i.e. element-node connectivity and node-element connectivity.
Detailed Description
Collection of methods and database related to reading.
This namespace provides methods and data members specific to reading of the mesh data. Currently, .csv, .vtu and .msh files are supported.
Function Documentation
readCsvFile()
void rw::reader::readCsvFile (const std::string & filename, size_t dim, std::vector< util::Point > * nodes, std::vector< double > * volumes)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
volumes Vector holding volume of the nodes
Definition at line 16 of file reader.cpp.
{
  nodes->clear();
  volumes->clear();
  if (dim == 1) {
    io::CSVReader<3> in(filename);
    in.read_header(io::ignore_extra_column, "id", "x", "volume");
    double x;
    double volume;
    int id;
    while (in.read_row(id, x, volume)) {
      volumes->emplace_back(volume);
      nodes->emplace_back(util::Point(x, 0., 0.));
    }
  }
  if (dim == 2) {
    io::CSVReader<4> in(filename);
    in.read_header(io::ignore_extra_column, "id", "x", "y", "volume");
    double x, y, volume;
    int id;
    while (in.read_row(id, x, y, volume)) {
      volumes->emplace_back(volume);
      nodes->emplace_back(util::Point(x, y, 0.));
    }
  }
  if (dim == 3) {
    io::CSVReader<5> in(filename);
    in.read_header(io::ignore_extra_column, "id", "x", "y", "z", "volume");
    double x, y, z, volume;
    int id;
    while (in.read_row(id, x, y, z, volume)) {
      volumes->emplace_back(volume);
      nodes->emplace_back(util::Point(x, y, z));
    }
  }
}
Referenced by fe::Mesh::createData().
readMshFile()
void rw::reader::readMshFile (const std::string & filename, size_t dim, std::vector< util::Point > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t > > * nec, std::vector< double > * volumes, bool is_fd = false)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
element_type Type of element
num_elem Number of elements
enc Vector holding element-node connectivity
nec Vector holding node-element connectivity
volumes Vector holding volume of the nodes
is_fd Flag indicating if this mesh is for finite_difference simulation
Definition at line 351 of file reader.cpp.
{
  // call msh reader
  auto rdr = rw::reader::MshReader(filename);
  rdr.readMesh(dim, nodes, element_type, num_elem, enc, nec, volumes, is_fd);
  rdr.close();
}
Referenced by fe::Mesh::createData().
readMshFileCells()
void rw::reader::readMshFileCells (const std::string & filename, size_t dim, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t > > * nec)
Reads cell data, i.e. element-node connectivity and node-element connectivity.
Parameters
filename Name of mesh file
dim Dimension
element_type Type of element
num_elem Number of elements
enc Element-node connectivity
nec Node-element connectivity
Definition at line 401 of file reader.cpp.
{
  // call msh reader
  auto rdr = rw::reader::MshReader(filename);
  rdr.readCells(dim, element_type, num_elem, enc, nec);
  rdr.close();
}
Referenced by fe::Mesh::readElementData().
readMshFilePointData()
bool rw::reader::readMshFilePointData (const std::string & filename, const std::string & tag, std::vector< double > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 390 of file reader.cpp.
{
  // call msh reader
  auto rdr = rw::reader::MshReader(filename);
  // get velocity
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readMshFileRestart()
void rw::reader::readMshFileRestart (const std::string & filename, std::vector< util::Point > * u, std::vector< util::Point > * v, const std::vector< util::Point > * X = nullptr)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
u Pointer to vector of nodal displacement
v Pointer to vector of nodal velocity
X Pointer to vector of nodal reference position (Optional)
Definition at line 363 of file reader.cpp.
{
  // call msh reader
  auto rdr = rw::reader::MshReader(filename);
  // if displacement is not in input file, use reference coordinate to get
  // displacement
  if (!rdr.readPointData("Displacement", u)) {
    std::vector<util::Point> y;
    rdr.readNodes(&y);
    if (y.size() != X->size()) {
      std::cerr << "Error: Number of nodes in input file = " << filename
                << " and number nodes in data X are not same.\n";
      exit(1);
    }
    u->resize(y.size());
    for (size_t i = 0; i < y.size(); i++)
      (*u)[i] = y[i] - (*X)[i];
  }
  // get velocity
  rdr.readPointData("Velocity", v);
  rdr.close();
}
readParticleCsvFile() [1/2]
void rw::reader::readParticleCsvFile (const std::string & filename, size_t dim, std::vector< util::Point > * nodes, std::vector< double > * rads, const size_t & zone)
Reads particles center location, radius, and zone id.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of center locations
rads Vector of radius
zone Only reads particle with this zone
Definition at line 80 of file reader.cpp.
{
  nodes->clear();
  rads->clear();
  io::CSVReader<5> in(filename);
  in.read_header(io::ignore_extra_column, "i", "x", "y", "z", "r");
  double x, y, z, r;
  int id;
  while (in.read_row(id, x, y, z, r)) {
    if (id == zone) {
      rads->emplace_back(r);
      nodes->emplace_back(util::Point(x, y, z));
    }
  }
}
readParticleCsvFile() [2/2]
void rw::reader::readParticleCsvFile (const std::string & filename, size_t dim, std::vector< util::Point > * nodes, std::vector< double > * rads, std::vector< size_t > * zones)
Reads particles center location, radius, and zone id.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of center locations
rads Vector of radius
zones Vector zone ids
Definition at line 59 of file reader.cpp.
{
  nodes->clear();
  zones->clear();
  rads->clear();
  io::CSVReader<5> in(filename);
  in.read_header(io::ignore_extra_column, "i", "x", "y", "z", "r");
  double x, y, z, r;
  int id;
  while (in.read_row(id, x, y, z, r)) {
    rads->emplace_back(r);
    nodes->emplace_back(util::Point(x, y, z));
    zones->emplace_back(id);
  }
}
Referenced by model::DEMModel::createParticlesFromFile().
readParticleWithOrientCsvFile()
void rw::reader::readParticleWithOrientCsvFile (const std::string & filename, size_t dim, std::vector< util::Point > * nodes, std::vector< double > * rads, std::vector< double > * orients, const size_t & zone)
Reads particles center location, radius, and zone id. In this case, file also provides initial orientation of particles.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of center locations
rads Vector of radius
orients Vector of orientation of particles
zone Only reads particle with this zone
Definition at line 101 of file reader.cpp.
{
  nodes->clear();
  rads->clear();
  orients->clear();
  io::CSVReader<6> in(filename);
  in.read_header(io::ignore_extra_column, "i", "x", "y", "z", "r", "o");
  double x, y, z, r, o;
  int id;
  while (in.read_row(id, x, y, z, r, o)) {
    if (id == zone) {
      rads->emplace_back(r);
      nodes->emplace_back(util::Point(x, y, z));
      orients->emplace_back(o);
    }
  }
}
Referenced by model::DEMModel::createParticlesFromFile().
readVtuFile()
void rw::reader::readVtuFile (const std::string & filename, size_t dim, std::vector< util::Point > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t > > * nec, std::vector< double > * volumes, bool is_fd = false)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
element_type Type of element
num_elem Number of elements
enc Vector holding element-node connectivity
nec Vector holding node-element connectivity
volumes Vector holding volume of the nodes
is_fd Flag indicating if this mesh is for finite_difference simulation
Definition at line 125 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  rdr.readMesh(dim, nodes, element_type, num_elem, enc, nec, volumes, is_fd);
  rdr.close();
}
readVtuFileCellData() [1/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< double > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 307 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readCellData(tag, data);
  rdr.close();
  return st;
}
readVtuFileCellData() [2/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< float > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 296 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readCellData(tag, data);
  rdr.close();
  return st;
}
readVtuFileCellData() [3/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< util::Matrix3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 340 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readCellData(tag, data);
  rdr.close();
  return st;
}
readVtuFileCellData() [4/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< util::Point > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 318 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readCellData(tag, data);
  rdr.close();
  return st;
}
readVtuFileCellData() [5/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< util::SymMatrix3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 329 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readCellData(tag, data);
  rdr.close();
  return st;
}
readVtuFileCells()
void rw::reader::readVtuFileCells (const std::string & filename, size_t dim, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t > > * nec)
Reads cell data, i.e. element-node connectivity and node-element connectivity.
Parameters
filename Name of mesh file
dim Dimension
element_type Type of element
num_elem Number of elements
enc Element-node connectivity
nec Node-element connectivity
Definition at line 168 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // below will read the current position of nodes
  rdr.readCells(dim, element_type, num_elem, enc, nec);
  rdr.close();
}
Referenced by fe::Mesh::createData(), and fe::Mesh::readElementData().
readVtuFileNodes()
void rw::reader::readVtuFileNodes (const std::string & filename, size_t dim, std::vector< util::Point > * nodes, bool ref_config = false)
Reads nodal coordinates.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
ref_config Flag which specifies if we need to subtract the displacement from nodes obtained from vtu file to get reference position of nodes
Definition at line 137 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // below will read the current position of nodes
  rdr.readNodes(nodes);
  // need to subtract the displacement to get reference configuration of nodes
  if (ref_config) {
    std::vector<util::Point> u;
    if (rdr.readPointData("Displacement", &u)) {
      std::cerr << "Error: Did not find displacement in the vtu file."
                << std::endl;
      exit(1);
    }
    if (u.size() != nodes->size()) {
      std::cerr << "Error: Displacement data and node data size do not match."
                << std::endl;
      exit(1);
    }
    for (size_t i = 0; i < u.size(); i++)
      (*nodes)[i] -= u[i];
  }
  rdr.close();
}
Referenced by fe::Mesh::createData().
readVtuFilePointData() [1/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< double > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 252 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readVtuFilePointData() [2/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< float > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 241 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readVtuFilePointData() [3/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< int > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 230 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readVtuFilePointData() [4/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< size_t > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 219 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readVtuFilePointData() [5/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< uint8_t > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 208 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
Referenced by fe::Mesh::createData().
readVtuFilePointData() [6/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< util::Matrix3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 285 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readVtuFilePointData() [7/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< util::Point > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 263 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readVtuFilePointData() [8/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< util::SymMatrix3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Definition at line 274 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // read data
  auto st = rdr.readPointData(tag, data);
  rdr.close();
  return st;
}
readVtuFileRestart()
void rw::reader::readVtuFileRestart (const std::string & filename, std::vector< util::Point > * u, std::vector< util::Point > * v, const std::vector< util::Point > * X = nullptr)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
u Pointer to vector of nodal displacement
v Pointer to vector of nodal velocity
X Pointer to vector of nodal reference position (Optional)
Definition at line 181 of file reader.cpp.
{
  // call vtk reader
  auto rdr = rw::reader::VtkReader(filename);
  // if displacement is not in input file, use reference coordinate to get
  // displacement
  if (!rdr.readPointData("Displacement", u)) {
    std::vector<util::Point> y;
    rdr.readNodes(&y);
    if (y.size() != X->size()) {
      std::cerr << "Error: Number of nodes in input file = " << filename
                << " and number nodes in data X are not same.\n";
      exit(1);
    }
    u->resize(y.size());
    for (size_t i = 0; i < y.size(); i++)
      (*u)[i] = y[i] - (*X)[i];
  }
  // get velocity
  rdr.readPointData("Velocity", v);
  rdr.close();
}