PeriDEM: util::parallel Namespace Reference
util::parallel Namespace Reference
Implements some key functions and classes regularly used in the code when running with MPI.
Data Structures
struct MpiStatus
Struct that stores MPI-related information.
Functions
void initMpi (int argc=0, char *argv[]=nullptr)
Initializes MPI and also creates MpiStatus struct.
void initMpiStatus ()
Initializes MpiStatus struct.
bool isMpiEnabled ()
Function to check if MPI is enabled.
int mpiSize ()
Get size (number) of processors.
int mpiRank ()
get rank (id) of this processor
MPI_Comm mpiComm ()
Get MPI comm.
const MpiStatus * getMpiStatus ()
Returns pointer to MpiStatus struct.
void initNThreads (unsigned int nThreads=std::thread::hardware_concurrency())
Initializes MpiStatus struct.
unsigned int getNThreads ()
Get number of threads to be used by taskflow.
Detailed Description
Implements some key functions and classes regularly used in the code when running with MPI.
Function Documentation
getMpiStatus()
const util::parallel::MpiStatus * util::parallel::getMpiStatus ()
Returns pointer to MpiStatus struct.
Returns
pointer Pointer to MpiStatus object
Definition at line 101 of file parallelUtil.cpp.
{
   //assert(mpiInitialized && "mpiInitialized is false indicating MPI_Init() or util::parallel::initMpi() has not been called.\n");
   if (mpistatus_p == nullptr)
     util::parallel::initMpi();
   return mpistatus_p;
 }
References initMpi(), and anonymous_namespace{parallelUtil.cpp}::mpistatus_p.
Referenced by main().
getNThreads()
unsigned int util::parallel::getNThreads ()
Get number of threads to be used by taskflow.
Returns
nThreads Number of threads
Definition at line 116 of file parallelUtil.cpp.
{
   if (numThreads == 0)
     numThreads = std::thread::hardware_concurrency();
   return numThreads;
 }
References anonymous_namespace{parallelUtil.cpp}::numThreads.
Referenced by loading::ParticleFLoading::apply(), loading::ParticleULoading::apply(), model::DEMModel::applyInitialCondition(), model::DEMModel::computeContactForces(), model::DEMModel::computeExternalForces(), model::DEMModel::computeForces(), material::computeHydrostaticStrain(), model::DEMModel::computePeridynamicForces(), material::computeStateMx(), material::computeStateThetax(), fe::Mesh::computeVol(), geometry::Fracture::Fracture(), fe::getCurrentQuadPoints(), fe::getStrainStress(), model::DEMModel::integrateCD(), model::DEMModel::integrateVerlet(), main(), anonymous_namespace{testNSearchLib.cpp}::neighSearchBrute(), anonymous_namespace{testNSearchLib.cpp}::neighSearchBruteExcludeInclude(), anonymous_namespace{testNSearchLib.cpp}::neighSearchTree(), anonymous_namespace{testNSearchLib.cpp}::neighSearchTreeSizet(), anonymous_namespace{testNSearchLib.cpp}::neighSearchTreeSizetExcludeInclude(), test::testTaskflow(), material::updateBondFractureData(), model::DEMModel::updateContactNeighborlist(), and model::DEMModel::updatePeridynamicNeighborlist().
initMpi()
void util::parallel::initMpi (int argc = 0, char * argv[] = nullptr)
Initializes MPI and also creates MpiStatus struct.
Parameters
argc Command line argument number
argv Command line argument values
Definition at line 25 of file parallelUtil.cpp.
{
   MPI_Initialized(&mpiInitialized);
   if (!mpiInitialized)
     MPI_Init(&argc, &argv);
   initMpiStatus();
 }
References initMpiStatus(), and anonymous_namespace{parallelUtil.cpp}::mpiInitialized.
Referenced by getMpiStatus(), isMpiEnabled(), main(), mpiComm(), mpiRank(), and mpiSize().
initMpiStatus()
void util::parallel::initMpiStatus ()
Initializes MpiStatus struct.
Definition at line 55 of file parallelUtil.cpp.
{
   if (mpistatus_p != nullptr)
     return;
   mpistatus_p = new util::parallel::MpiStatus();
 }
References anonymous_namespace{parallelUtil.cpp}::mpistatus_p.
Referenced by initMpi().
initNThreads()
void util::parallel::initNThreads (unsigned int nThreads = std::thread::hardware_concurrency())
Initializes MpiStatus struct.
Parameters
nThreads Number of threads to be used by Taskflow in asynchronous parallelism
Definition at line 109 of file parallelUtil.cpp.
{
   if (numThreads > 0) {
     std::cout << "Number of threads numThreads is already initialized.\n";
   } else
     numThreads = nThreads;
 }
References anonymous_namespace{parallelUtil.cpp}::numThreads.
Referenced by main().
isMpiEnabled()
bool util::parallel::isMpiEnabled ()
Function to check if MPI is enabled.
Returns
bool Bool
Definition at line 62 of file parallelUtil.cpp.
{
   // for now, we do not call assert and rather create MpiStatus if it is not instantiated
   /*
   //assert((mpistatus_p != nullptr) && "mpistatus_p "
   //                                   "(pointer of struct type util::parallel::MpiStatus) is not initialized. "
   //                                   "Call util::parallel::initMpiStatus() possibly right after MPI_Init().");
   */
   //assert(mpiInitialized && "mpiInitialized is false indicating MPI_Init() or util::parallel::initMpi() has not been called.\n");
   if (mpistatus_p == nullptr)
     util::parallel::initMpi();
   return mpistatus_p->d_mpiEnabled;
 }
References util::parallel::MpiStatus::d_mpiEnabled, initMpi(), and anonymous_namespace{parallelUtil.cpp}::mpistatus_p.
mpiComm()
MPI_Comm util::parallel::mpiComm ()
Get MPI comm.
Returns
comm MPI comm
Definition at line 93 of file parallelUtil.cpp.
{
   //assert(mpiInitialized && "mpiInitialized is false indicating MPI_Init() or util::parallel::initMpi() has not been called.\n");
   if (mpistatus_p == nullptr)
     util::parallel::initMpi();
   return mpistatus_p->d_comm;
 }
References util::parallel::MpiStatus::d_comm, initMpi(), and anonymous_namespace{parallelUtil.cpp}::mpistatus_p.
mpiRank()
int util::parallel::mpiRank ()
get rank (id) of this processor
Returns
int Rank of MPI process
Definition at line 85 of file parallelUtil.cpp.
{
   //assert(mpiInitialized && "mpiInitialized is false indicating MPI_Init() or util::parallel::initMpi() has not been called.\n");
   if (mpistatus_p == nullptr)
     util::parallel::initMpi();
   return mpistatus_p->d_mpiRank;
 }
References util::parallel::MpiStatus::d_mpiRank, initMpi(), and anonymous_namespace{parallelUtil.cpp}::mpistatus_p.
Referenced by anonymous_namespace{testParallelCompLib.cpp}::exchangeDispData(), util::io::Logger::log(), main(), util::io::print(), util::io::printBox(), anonymous_namespace{testParallelCompLib.cpp}::printMsg(), anonymous_namespace{testParallelCompLib.cpp}::setupOwnerAndGhost(), and test::testMPI().
mpiSize()
int util::parallel::mpiSize ()
Get size (number) of processors.
Returns
int Size of MPI processes
Definition at line 77 of file parallelUtil.cpp.
{
   //assert(mpiInitialized && "mpiInitialized is false indicating MPI_Init() or util::parallel::initMpi() has not been called.\n");
   if (mpistatus_p == nullptr)
     util::parallel::initMpi();
   return mpistatus_p->d_mpiSize;
 }
References util::parallel::MpiStatus::d_mpiSize, initMpi(), and anonymous_namespace{parallelUtil.cpp}::mpistatus_p.
Referenced by anonymous_namespace{testParallelCompLib.cpp}::exchangeDispData(), main(), anonymous_namespace{testParallelCompLib.cpp}::setupOwnerAndGhost(), and test::testMPI().