PeriDEM: problem_setup Namespace Reference
problem_setup Namespace Reference
Functions
def print_bool (arg, prefix="")
def print_dbl (arg, prefix="")
def print_int (arg, prefix="")
def print_dbl_list (arg, prefix="")
def print_int_list (arg, prefix="")
def does_intersect_rect (p, r, particles, padding, rect)
def does_intersect_with_cylindrical_wall (p, particles, R_in, center, bar_rect, padding)
def write_contact_zone_part (inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, zone_string, Kn)
def write_material_zone_part (inpf, zone_string, horizon, rho, K, G, Gc)
def get_E (K, nu)
def get_G (E, nu)
def get_eff_k (k1, k2)
def get_max (l)
def rotate (p, theta, axis)
def get_ref_triangle_points (center, radius, add_center=False)
def get_ref_hex_points (center, radius, add_center=False)
def get_ref_drum_points (center, radius, width, add_center=False)
def particle_locations (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, Nmax, R_in, bar_rect, z_coord, add_orient=True)
def generate_cir_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
def generate_hex_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
def generate_tri_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
def generate_drum2d_particle_gmsh_input (inp_dir, filename, center, radius, width, mesh_size, pp_tag)
def generate_wall_gmsh_input (inp_dir, filename, center, outer_radius, inner_radius, bar_width, bar_length, mesh_size, pp_tag)
def create_input_file (inp_dir, pp_tag)
def copy_contact_zone (inpf, zone_numbers, zone_copy_from)
def get_ref_rect_points (center, radius, add_center=False)
def does_rect_intersect_rect (r1, r2, padding)
def particle_locations (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, R_in, bar_rect, z_coord, add_orient=True)
def particle_locations (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, N1, N2, R_in, bar_rect, z_coord, add_orient=True)
def generate_cylindrical_wall_gmsh_input (inp_dir, filename, center, outer_radius, inner_radius, bar_width, bar_length, mesh_size, pp_tag)
def get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening (center, Lin, Win)
def get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening (center, Lin, Win)
def write_point_geo (geof, p_id, x, h)
def write_line_geo (geof, l_id, p1_id, p2_id)
def write_cir_line_geo (geof, l_id, p1_id, p2_id, p3_id)
def get_ref_rect_points (center, L, W, add_center=False)
def does_rect_intersect_rect_use_pair_coord (r1, r2, padding)
def does_intersect_with_rectangle_wall_with_protrusion_and_opening (p, particles, Lin, Win, center, padding)
def generate_rect_floor_gmsh_input (inp_dir, filename, center, L, W, mesh_size, pp_tag)
def generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2 (inp_dir, filename, center, Lin, Win, L, W, mesh_size, pp_tag)
def generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3 (inp_dir, filename, center, Lin, Win, L, W, mesh_size, pp_tag)
def serialize_matrix_list (p)
def get_center (p1, p2)
def generate_rect_container_gmsh_input (inp_dir, filename, pi1, pi2, dx, dy, mesh_size, pp_tag)
def does_intersect (p, r, R, particles, padding)
def particle_locations (inp_dir, pp_tag, R1, R2, rect, mesh_size, padding, add_orient=True)
def generate_rigid_wall_gmsh_input (inp_dir, filename, outer_rect, inner_rect, mesh_size, pp_tag)
def generate_moving_wall_gmsh_input (inp_dir, filename, rectangle, mesh_size, pp_tag)
def particle_locations (inp_dir, pp_tag, R1, R2, offset)
def generate_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
def particle_locations_orient (inp_dir, pp_tag, R1, R2, offset)
def generate_particle_gmsh_input (inp_dir, filename, center, radius, width, mesh_size, pp_tag)
def generate_wall_gmsh_input (inp_dir, filename, rectangle, mesh_size, pp_tag)
def does_particle_intersect_rect (p, r2, padding)
def does_particle_intersect (p, particles, rect, padding)
def particle_locations_old (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, N1, N2, rect, z_coord, add_orient=True)
def generate_rigid_rect_container_moving_wall_setup_gmsh_input (inp_dir, filename, outer_rect, inner_rect, mesh_size, pp_tag)
def generate_moving_rect_wall_gmsh_input (inp_dir, filename, rectangle, mesh_size, pp_tag)
def generate_drum_particle_gmsh_input (inp_dir, filename, center, radius, width, mesh_size, pp_tag)
def rect_to_five_param (r)
def particle_locations (inp_dir, pp_tag, R1, R2, offset, w1_rect_five_format, w2_rect_five_format)
def particle_locations_orient (inp_dir, pp_tag, R1, R2, offset, w1_rect_five_format, w2_rect_five_format)
Variables
string inp_dir = './'
----------------------------------------------------—## ----------------------------------------------------—##
int pp_tag = 0
Function Documentation
copy_contact_zone()
def problem_setup.copy_contact_zone (inpf, zone_numbers, zone_copy_from)
Definition at line 77 of file problem_setup.py.
 def copy_contact_zone(inpf, zone_numbers, zone_copy_from):
   for s in zone_numbers:
     inpf.write("  Zone_%d:\n" % (s))
     inpf.write("    Copy_Contact_Data: " + print_int_list(zone_copy_from))
References get_E(), get_eff_k(), get_G(), get_max(), print_int_list(), and rotate().
Referenced by generate_cylindrical_wall_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), particle_locations(), serialize_matrix_list(), and write_cir_line_geo().
create_input_file()
def problem_setup.create_input_file (inp_dir, pp_tag)
Generates input file for two-particle test
Definition at line 793 of file problem_setup.py.
 def create_input_file(inp_dir, pp_tag):
   """Generates input file for two-particle test"""
   sim_inp_dir = str(inp_dir)
   # 1 - small particle circle
   # 2 - small particle triangle
   # 3 - small particle drum2d
   # 4 - large particle circle
   # 5 - large particle triangle
   # 6 - large particle drum2d
   # 7 - cylindrical wall
   center = [0., 0., 0.]
   R_small = 0.001
   R_large = 0.003
   R_in = 0.02
   R_out = 0.021
   L_bar = 0.006
   W_bar = 0.003
   bar_rectangle_attached_to_cylinder = [R_in - L_bar, -0.5 * W_bar, 0., R_in, 0.5 * W_bar, 0.]
   mesh_size = R_small / 5.
   horizon = 3. * mesh_size
   # define geometric parameters
   # wall
   wall_circle_plus = [R_out, center[0], center[1], center[2]]
   wall_circle_minus = [R_in, center[0], center[1], center[2]]
   wall_rectangle_plus = bar_rectangle_attached_to_cylinder
   wall_params = wall_circle_plus + wall_circle_minus + wall_rectangle_plus
   # small circle
   small_circle = [R_small, center[0], center[1], center[2]]
   # small triangle
   small_triangle = small_circle
   # small drum2d
   w_small_drum2d = R_small * 0.4
   small_drum2d = [R_small, w_small_drum2d, center[0], center[1], center[2]]
   # large circle
   large_circle = [R_large, center[0], center[1], center[2]]
   # large triangle
   large_triangle = large_circle
   # large drum2d
   w_large_drum2d = R_large* 0.4
   large_drum2d = [R_large, w_large_drum2d, center[0], center[1], center[2]]
   final_time = 0.1
   num_steps = 1000000
   # final_time = 0.00002
   # num_steps = 2
   num_outputs = 400
   dt_out_n = num_steps / num_outputs
   test_dt_out_n = dt_out_n / 100
   perform_out = True
   poisson = 0.25
   rho_wall = 1200.
   K_wall = 1.e+5
   E_wall = get_E(K_wall, poisson)
   G_wall = get_G(E_wall, poisson)
   Gc_wall = 100.
   rho_large = rho_wall
   K_large = K_wall
   E_large = E_wall
   G_large = G_wall
   Gc_large = Gc_wall
   rho_small = 1200.
   K_small = 1.e+4
   E_small = get_E(K_small, poisson)
   G_small = get_G(E_small, poisson)
   Gc_small = 50.
   R_contact_factor = 0.95
   # Kn_V_max = 7.385158e+05
   # Kn = np.power(Kn_V_max, 2)
   # compute from bulk modulus
   # from bulk modulus
   Kn_small_small = 18. * get_eff_k(K_small, K_small) / (np.pi * np.power(horizon, 5))
   Kn_large_large = 18. * get_eff_k(K_large, K_large) / (np.pi * np.power(horizon, 5))
   Kn_wall_wall = 18. * get_eff_k(K_wall, K_wall) / (np.pi * np.power(horizon, 5))
   Kn_small_large = 18. * get_eff_k(K_small, K_large) / (np.pi * np.power(horizon, 5))
   Kn_small_wall = 18. * get_eff_k(K_small, K_wall) / (np.pi * np.power(horizon, 5))
   Kn_large_wall = 18. * get_eff_k(K_large, K_wall) / (np.pi * np.power(horizon, 5))
   beta_n_eps = 0.95
   friction_coeff = 0.5
   damping_active = False
   friction_active = False
   beta_n_factor = 100.
   Kn_factor = 1.
   gravity_active = True
   gravity = [0., -10., 0.]
   rotation_rate = -20. * np.pi
   neigh_search_factor = 10.
   neigh_search_interval = 40
   neigh_search_criteria = "simple_all"
   # generate particle locations
   padding = 1.1 * R_contact_factor * mesh_size
   Nmax = 5000
   max_y = 0.2*R_in
   num_particles_zones_1_to_6, particles_zones_1_to_6 = particle_locations(inp_dir, pp_tag, center, padding, max_y, mesh_size, R_small, R_large, [0, 1, 2], [3, 4, 5], Nmax, R_in, bar_rectangle_attached_to_cylinder, z_coord = 0., add_orient = True)
   # generate particle .geo file (large)
   zones_mesh_fnames = ["mesh_cir_small", "mesh_tri_small", "mesh_drum2d_small", "mesh_cir_large", "mesh_tri_large", "mesh_drum2d_large", "mesh_wall"]
   generate_cir_particle_gmsh_input(inp_dir, zones_mesh_fnames[0], center, R_small, mesh_size, pp_tag)
   generate_cir_particle_gmsh_input(inp_dir, zones_mesh_fnames[3], center, R_large, mesh_size, pp_tag)
   generate_tri_particle_gmsh_input(inp_dir, zones_mesh_fnames[1], center, R_small, mesh_size, pp_tag)
   generate_tri_particle_gmsh_input(inp_dir, zones_mesh_fnames[4], center, R_large, mesh_size, pp_tag)
   generate_drum2d_particle_gmsh_input(inp_dir, zones_mesh_fnames[2], center, R_small, 2.*w_small_drum2d, mesh_size, pp_tag)
   generate_drum2d_particle_gmsh_input(inp_dir, zones_mesh_fnames[5], center, R_large, 2.*w_large_drum2d, mesh_size, pp_tag)
   generate_wall_gmsh_input(inp_dir, zones_mesh_fnames[6], center, R_out, R_in, W_bar, L_bar, mesh_size, pp_tag)
   os.system("mkdir -p out")
   for s in zones_mesh_fnames:
     print('\n')
     print(s)
     print("gmsh {}_{}.geo -2 &> /dev/null".format(s, pp_tag))
     print('\n')
     os.system("gmsh {}_{}.geo -2".format(s, pp_tag))
     os.system("gmsh {}_{}.geo -2 &> /dev/null".format(s, pp_tag))
     os.system("gmsh {}_{}.geo -2 -o {}_{}.vtk &> /dev/null".format(s, pp_tag, s, pp_tag))
   inpf = open(sim_inp_dir + 'input_' + str(pp_tag) + '.yaml','w')
   inpf.write("Model:\n")
   inpf.write("  Dimension: 2\n")
   inpf.write("  Discretization_Type:\n")
   inpf.write("    Spatial: finite_difference\n")
   inpf.write("    Time: central_difference\n")
   inpf.write("  Final_Time: %4.6e\n" % (final_time))
   inpf.write("  Time_Steps: %d\n" % (num_steps))
   # container info
   inpf.write("Container:\n")
   inpf.write("  Geometry:\n")
   inpf.write("    Type: complex\n")
   inpf.write("    Vec_Type: [circle, circle, rectangle]\n")
   inpf.write("    Vec_Flag: [plus, minus, plus]\n")
   inpf.write("    Parameters: " + print_dbl_list(wall_params))
   # zone info
   inpf.write("Zone:\n")
   inpf.write("  Zones: 7\n")
   for i in range(7):
     inpf.write("  Zone_%d:\n" % (i+1))
     if i == 6:
       inpf.write("    Is_Wall: true\n")
     else:
       inpf.write("    Is_Wall: false\n")
   # particle info
   inpf.write("Particle:\n")
   inpf.write("  Test_Name: multi_particle_attrition\n")
   particle_data = [['circle', small_circle], ['triangle', small_triangle], ['drum2d', small_drum2d], ['circle', large_circle], ['triangle', large_triangle], ['drum2d', large_drum2d]]
   for i in range(6):
     inpf.write("  Zone_%d:\n" % (i+1))
     inpf.write("    Type: %s\n" % (particle_data[i][0]))
     inpf.write("    Parameters: " + print_dbl_list((particle_data[i][1])))
   inpf.write("  Zone_7:\n")
   inpf.write("    Is_Wall: true\n")
   inpf.write("    Type: complex\n")
   inpf.write("    Vec_Type: [circle, circle, rectangle]\n")
   inpf.write("    Vec_Flag: [plus, minus, plus]\n")
   inpf.write("    Parameters: " + print_dbl_list(wall_params))
   inpf.write("    All_Dofs_Constrained: true\n")
   inpf.write("    Create_Particle_Using_ParticleZone_GeomObject: true\n")
   # particle generation
   inpf.write("Particle_Generation:\n")
   inpf.write("  From_File: particle_locations_" + str(pp_tag) + ".csv\n")
   inpf.write("  File_Data_Type: loc_rad_orient\n")
   # Mesh info
   inpf.write("Mesh:\n")
   for i in range(7):
     inpf.write("  Zone_%d:\n" % (i+1))
     inpf.write("    File: %s\n" % (zones_mesh_fnames[i] + "_" + str(pp_tag) + ".msh"))
   # Contact info
   inpf.write("Contact:\n")
   write_contact_zone_part(inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, "11", Kn_small_small)
   inpf.write("  Zone_12:\n")
   inpf.write("    Copy_Contact_Data: [1, 1]\n")
   inpf.write("  Zone_13:\n")
   inpf.write("    Copy_Contact_Data: [1, 1]\n")
   write_contact_zone_part(inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, "14", Kn_small_large)
   inpf.write("  Zone_15:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   inpf.write("  Zone_16:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   write_contact_zone_part(inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, "17", Kn_small_wall)
   inpf.write("  Zone_22:\n")
   inpf.write("    Copy_Contact_Data: [1, 1]\n")
   inpf.write("  Zone_23:\n")
   inpf.write("    Copy_Contact_Data: [1, 1]\n")
   inpf.write("  Zone_24:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   inpf.write("  Zone_25:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   inpf.write("  Zone_26:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   inpf.write("  Zone_27:\n")
   inpf.write("    Copy_Contact_Data: [1, 7]\n")
   inpf.write("  Zone_33:\n")
   inpf.write("    Copy_Contact_Data: [1, 1]\n")
   inpf.write("  Zone_34:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   inpf.write("  Zone_35:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   inpf.write("  Zone_36:\n")
   inpf.write("    Copy_Contact_Data: [1, 4]\n")
   inpf.write("  Zone_37:\n")
   inpf.write("    Copy_Contact_Data: [1, 7]\n")
   write_contact_zone_part(inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, "44", Kn_large_large)
   inpf.write("  Zone_45:\n")
   inpf.write("    Copy_Contact_Data: [4, 4]\n")
   inpf.write("  Zone_46:\n")
   inpf.write("    Copy_Contact_Data: [4, 4]\n")
   write_contact_zone_part(inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, "47", Kn_large_wall)
   inpf.write("  Zone_55:\n")
   inpf.write("    Copy_Contact_Data: [4, 4]\n")
   inpf.write("  Zone_56:\n")
   inpf.write("    Copy_Contact_Data: [4, 4]\n")
   inpf.write("  Zone_57:\n")
   inpf.write("    Copy_Contact_Data: [4, 7]\n")
   inpf.write("  Zone_66:\n")
   inpf.write("    Copy_Contact_Data: [4, 4]\n")
   inpf.write("  Zone_67:\n")
   inpf.write("    Copy_Contact_Data: [4, 7]\n")
   write_contact_zone_part(inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, "77", Kn_wall_wall)
   # Neighbor info
   inpf.write("Neighbor:\n")
   inpf.write("  Update_Criteria: %s\n" % (neigh_search_criteria))
   inpf.write("  Search_Factor: %4.e\n" % (neigh_search_factor))
   inpf.write("  Search_Interval: %d\n" % (neigh_search_interval))
   # Material info
   inpf.write("Material:\n")
   write_material_zone_part(inpf, "1", horizon, rho_small, K_small, G_small, Gc_small)
   inpf.write("  Zone_2:\n")
   inpf.write("    Copy_Material_Data: 1\n")
   inpf.write("  Zone_3:\n")
   inpf.write("    Copy_Material_Data: 1\n")
   write_material_zone_part(inpf, "4", horizon, rho_large, K_large, G_large, Gc_large)
   inpf.write("  Zone_5:\n")
   inpf.write("    Copy_Material_Data: 4\n")
   inpf.write("  Zone_6:\n")
   inpf.write("    Copy_Material_Data: 4\n")
   write_material_zone_part(inpf, "7", horizon, rho_wall, K_wall, G_wall, Gc_wall)
   # Force
   if gravity_active == True:
     inpf.write("Force_BC:\n")
     inpf.write("  Gravity: " + print_dbl_list(gravity))
   # Displacement
   inpf.write("Displacement_BC:\n")
   inpf.write("  Sets: 1\n")
   inpf.write("  Set_1:\n")
   # wall particle id will be num_particles_zones_1_to_6
   inpf.write("    Particle_List: [%d]\n" % (num_particles_zones_1_to_6))
   inpf.write("    Direction: [1,2]\n")
   inpf.write("    Time_Function:\n")
   inpf.write("      Type: rotation\n")
   inpf.write("      Parameters: "+print_dbl_list([rotation_rate, center[0], center[1], center[2]]))
   inpf.write("    Spatial_Function:\n")
   inpf.write("      Type: rotation\n")
   inpf.write("    Zero_Displacement: false\n")
   #
   # Output info
   #
   inpf.write("Output:\n")
   inpf.write("  Path: ./out/\n")
   inpf.write("  Tags:\n")
   inpf.write("    - Displacement\n")
   inpf.write("    - Velocity\n")
   inpf.write("    - Force\n")
   inpf.write("    - Force_Density\n")
   inpf.write("    - Damage_Z\n")
   inpf.write("    - Damage\n")
   inpf.write("    - Nodal_Volume\n")
   inpf.write("    - Zone_ID\n")
   inpf.write("    - Particle_ID\n")
   inpf.write("    - Fixity\n")
   inpf.write("    - Force_Fixity\n")
   inpf.write("    - Contact_Nodes\n")
   inpf.write("    - No_Fail_Node\n")
   inpf.write("    - Boundary_Node_Flag\n")
   # inpf.write("    - Contact_Data\n")
   # inpf.write("    - Strain_Stress\n")
   inpf.write("  Output_Interval: %d\n" % (dt_out_n))
   inpf.write("  Compress_Type: zlib\n")
   inpf.write("  Perform_FE_Out: false\n")
   if perform_out:
     inpf.write("  Perform_Out: true\n")
   else:
     inpf.write("  Perform_Out: false\n")
   inpf.write("  Test_Output_Interval: %d\n" % (test_dt_out_n))
   inpf.write("  Debug: 3\n")
   inpf.write("  Tag_PP: %d\n" %(int(pp_tag)))
   # close file
   inpf.close()
References generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_tri_particle_gmsh_input(), generate_wall_gmsh_input(), get_E(), get_eff_k(), get_G(), particle_locations(), util::io.print(), print_dbl_list(), write_contact_zone_part(), and write_material_zone_part().
Referenced by generate_cylindrical_wall_gmsh_input(), generate_drum_particle_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_particle_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), generate_wall_gmsh_input(), particle_locations(), and particle_locations_orient().
does_intersect()
def problem_setup.does_intersect (p, r, R, particles, padding)
Definition at line 47 of file problem_setup.py.
 def does_intersect(p, r, R, particles, padding):
   for q in particles:
     pq = np.array([p[i] - q[i] for i in range(3)])
     if np.linalg.norm(pq) <= r + R + padding:
       return True
   return False
References does_intersect_rect(), get_E(), get_eff_k(), get_G(), get_max(), get_ref_hex_points(), and rotate().
does_intersect_rect()
def problem_setup.does_intersect_rect (p, r, particles, padding, rect)
Definition at line 49 of file problem_setup.py.
 def does_intersect_rect(p, r, particles, padding, rect):
   # check intersection with rectangle
   pr = [p[0] - r, p[1] - r, p[2], p[0] + r, p[1] + r, p[2]]
   if pr[0] < rect[0] + padding or pr[1] < rect[1] + padding or pr[3] > rect[3] - padding or pr[4] > rect[4] - padding:
     # print('circle (xc = {}, r = {:5.3e}) intersects rect = {} with pad = {:5.3e}'.format(p, r, rect, padding))
     return True
   # loop over particles
   # for pi in particles:
   #   dx = [p[0] - pi[1], p[1] - pi[2], p[2] - pi[3]]
   #   rR = r + pi[4] + padding
   #   if np.linalg.norm(dx) < rR:
   #     return True
   # print('circle (xc = {}, r = {:5.3e}) does not intersects rect = {} with pad = {:5.3e}'.format(p, r, rect, padding))
   return False
Referenced by does_intersect(), and particle_locations().
does_intersect_with_cylindrical_wall()
def problem_setup.does_intersect_with_cylindrical_wall (p, particles, R_in, center, bar_rect, padding)
Definition at line 70 of file problem_setup.py.
 def does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding):
   # p -> [id, x, y, z, r]
   for q in particles:
     pq = np.array([p[i+1] - q[i+1] for i in range(3)])
     if np.linalg.norm(pq) <= p[-1] + q[-1] + padding:
       return True
   dx = np.array([p[i+1] - center[i] for i in range(3)])
   if np.linalg.norm(dx) > R_in - p[-1] - padding:
     return True
   r = p[-1]
   for i in range(4):
     pr = [p[i+1] for i in range(3)]
     if i == 0:
       pr[0] = pr[0] - r
       pr[1] = pr[1] - r
     elif i == 1:
       pr[0] = pr[0] - r
       pr[1] = pr[1] + r
     elif i == 2:
       pr[0] = pr[0] + r
       pr[1] = pr[1] - r
     elif i == 3:
       pr[0] = pr[0] + r
       pr[1] = pr[1] + r
     if pr[0] > bar_rect[0] - padding and pr[1] > bar_rect[1] - padding and pr[0] < bar_rect[3] + padding and pr[1] < bar_rect[4] + padding:
       return True
   return False
Referenced by does_rect_intersect_rect(), and particle_locations().
does_intersect_with_rectangle_wall_with_protrusion_and_opening()
def problem_setup.does_intersect_with_rectangle_wall_with_protrusion_and_opening (p, particles, Lin, Win, center, padding)
Definition at line 304 of file problem_setup.py.
 def does_intersect_with_rectangle_wall_with_protrusion_and_opening(p, particles, Lin, Win, center, padding):
   # p -> [id, x, y, z, r]
   p_center = [p[i+1] for i in range(3)]
   p_r = p[4]
   p_rect = [[p_center[0] - p_r, p_center[1] - p_r, p_center[2]], [p_center[0] + p_r, p_center[1] + p_r, p_center[2]]]
   for q in particles:
     pq = np.array([p[i+1] - q[i+1] for i in range(3)])
     if np.linalg.norm(pq) <= p[-1] + q[-1] + padding:
       return True
   dx = np.array([p[i+1] - center[i] for i in range(3)])
   if np.abs(dx[0]) > 0.5*Lin - p[-1] - padding:
     return True
   if np.abs(dx[1]) > 0.5*Win - p[-1] - padding:
     return True
   # get protrusion points and approximate the protruding region using rectangle and check for intersection
   # process triangle protrusion
   p2, p1, p3 = get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win)
   tri_protrsn_rect_left_bottom = p2
   tri_protrsn_rect_right_top = [p2[0] + (p1[0] - p2[0]), p2[1] + (p3[1] - p2[1]), p2[2]]
   if does_rect_intersect_rect_use_pair_coord(p_rect, [tri_protrsn_rect_left_bottom, tri_protrsn_rect_right_top], padding):
     return True
   # process circular protrusion
   circ_protrsn_r, p1, p4, p2, p3 = get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win)
   circ_protrsn_rect_left_bottom = p1
   circ_protrsn_rect_right_top = [p1[0] + 2 * circ_protrsn_r, p1[1] + circ_protrsn_r, p1[2]]
   return does_rect_intersect_rect_use_pair_coord(p_rect, [circ_protrsn_rect_left_bottom, circ_protrsn_rect_right_top], padding)
References does_rect_intersect_rect_use_pair_coord(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_tri_particle_gmsh_input(), get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), get_ref_drum_points(), get_ref_hex_points(), get_ref_triangle_points(), get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), particle_locations(), and util::io.print().
Referenced by get_center().
does_particle_intersect()
def problem_setup.does_particle_intersect (p, particles, rect, padding)
Definition at line 294 of file problem_setup.py.
 def does_particle_intersect(p, particles, rect, padding):
   # p -> [id, x, y, z, r]
   p_center = [p[i+1] for i in range(3)]
   p_r = p[4]
   p_rect = [p_center[0] - p_r, p_center[1] - p_r, p_center[2], p_center[0] + p_r, p_center[1] + p_r, p_center[2]]
   if p_rect[0] < rect[0] + padding or p_rect[1] < rect[1] + padding or p_rect[3] > rect[3] - padding or p_rect[4] > rect[4] - padding:
     return True
   for q in particles:
     pq = np.array([p[i+1] - q[i+1] for i in range(3)])
     if np.linalg.norm(pq) <= p[-1] + q[-1] + padding:
       return True
   return False
References get_max(), particle_locations(), and util::io.print().
does_particle_intersect_rect()
def problem_setup.does_particle_intersect_rect (p, r2, padding)
Definition at line 286 of file problem_setup.py.
 def does_particle_intersect_rect(p, r2, padding):
   pr = p[4]
   pc = [p[1], p[2], p[3]]
   p_rect = [pc[0] - pr, pc[1] - pr, pc[2], pc[1] + pr, pc[2] + pr, pc[2]]
   return does_rect_intersect_rect(p_rect, r2, padding)
References does_rect_intersect_rect().
does_rect_intersect_rect()
def problem_setup.does_rect_intersect_rect (r1, r2, padding)
Definition at line 241 of file problem_setup.py.
 def does_rect_intersect_rect(r1, r2, padding):
   # enlarge rectangle by adding padding
   r1_padding = [r1[0] - padding, r1[1] - padding, r1[2], r1[3] + padding, r1[4] + padding, r1[5]]
   return r1_padding[0] < r2[3] and r1_padding[3] > r2[0] and r1_padding[1] < r2[4] and r1_padding[4] > r2[1]
References does_intersect_with_cylindrical_wall().
Referenced by does_particle_intersect_rect(), get_center(), and get_ref_rect_points().
does_rect_intersect_rect_use_pair_coord()
def problem_setup.does_rect_intersect_rect_use_pair_coord (r1, r2, padding)
Definition at line 293 of file problem_setup.py.
 def does_rect_intersect_rect_use_pair_coord(r1, r2, padding):
   # enlarge rectangle by adding padding
   p1_r1_padding = [r1[0][0] - padding, r1[0][1] - padding, r1[0][2]]
   p2_r1_padding = [r1[1][0] + padding, r1[1][1] + padding, r1[0][2]]
   p1_r2 = r2[0]
   p2_r2 = r2[1]
   return p1_r1_padding[0] < p2_r2[0] and p2_r1_padding[0] > p1_r2[0] and p1_r1_padding[1] < p2_r2[1] and p2_r1_padding[1] > p1_r2[1]
Referenced by does_intersect_with_rectangle_wall_with_protrusion_and_opening(), and get_center().
generate_cir_particle_gmsh_input()
def problem_setup.generate_cir_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
Definition at line 475 of file problem_setup.py.
 def generate_cir_particle_gmsh_input(inp_dir, filename, center, radius, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # center and radius
   sim_Cx = center[0]
   sim_Cy = center[1]
   sim_Cz = center[2]
   sim_radius = radius
   # mesh size
   sim_h = mesh_size
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   geof.write("Point(1) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx, sim_Cy, sim_Cz, sim_h));
   geof.write("Point(2) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx + sim_radius, sim_Cy, sim_Cz, sim_h))
   geof.write("Point(3) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx - sim_radius, sim_Cy, sim_Cz, sim_h))
   geof.write("Point(4) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx, sim_Cy + sim_radius, sim_Cz, sim_h))
   geof.write("Point(5) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx, sim_Cy - sim_radius, sim_Cz, sim_h))
   #
   # circlular arc
   #
   geof.write("Circle(1) = {2, 1, 4};\n")
   geof.write("Circle(2) = {4, 1, 3};\n")
   geof.write("Circle(3) = {3, 1, 5};\n")
   geof.write("Circle(4) = {5, 1, 2};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {2, 3, 4, 1};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{1} In Surface {1};")
   # close file
   geof.close()
Referenced by create_input_file(), does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_cylindrical_wall_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), get_center(), particle_locations(), and particle_locations_old().
generate_cylindrical_wall_gmsh_input()
def problem_setup.generate_cylindrical_wall_gmsh_input (inp_dir, filename, center, outer_radius, inner_radius, bar_width, bar_length, mesh_size, pp_tag)
Definition at line 689 of file problem_setup.py.
 def generate_cylindrical_wall_gmsh_input(inp_dir, filename, center, outer_radius, inner_radius, bar_width, bar_length, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # center and radius
   Cx = center[0]
   Cy = center[1]
   Cz = center[2]
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   points = []
   points.append([Cx, Cy, Cz])
   points.append([outer_radius, 0., 0.])
   points.append([0., outer_radius, 0.])
   points.append([-outer_radius, 0., 0.])
   points.append([0., -outer_radius, 0.])
   points.append([inner_radius, 0.5*bar_width, 0.])
   points.append([inner_radius, -0.5*bar_width, 0.])
   points.append([0., inner_radius, 0.])
   points.append([-inner_radius, 0., 0.])
   points.append([0., -inner_radius, 0.])
   points.append([inner_radius - bar_length, 0.5*bar_width, 0.])
   points.append([inner_radius - bar_length, -0.5*bar_width, 0.])
   count = 0
   for p in points:
     count += 1
     geof.write("Point(%d) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (count, p[0], p[1], p[2], mesh_size))
   #
   # circular arc
   #
   circles = []
   circles.append([2, 1, 3])
   circles.append([3, 1, 4])
   circles.append([4, 1, 5])
   circles.append([5, 1, 2])
   circles.append([6, 1, 8])
   circles.append([8, 1, 9])
   circles.append([9, 1, 10])
   circles.append([10, 1, 7])
   count = 0
   for c in circles:
     count += 1
     geof.write("Circle(%d) = {%d, %d, %d};\n" % (count, c[0], c[1], c[2]))
   #
   # line
   #
   lines = []
   lines.append([6, 11])
   lines.append([11, 12])
   lines.append([12, 7])
   #count = 0
   for l in lines:
     count += 1
     geof.write("Line(%d) = {%d, %d};\n" % (count, l[0], l[1]))
   #
   # curve loop
   #
   geof.write("Line Loop(1) = {2, 3, 4, 1};\n")
   geof.write("Line Loop(2) = {6, 7, 8, -11, -10, -9, 5};\n")
   #
   # plane surface and physical tag
   #
   geof.write("Plane Surface(1) = {1, 2};\n")
   #geof.write("Physical Surface(1) = {1};\n")
   #geof.write("Physical Point(2) = {9, 4, 10, 5, 2, 7, 6, 11, 12, 3, 8};\n")
   tag = '"' + "a" + '"'
   geof.write("Physical Surface(%s) = {1};\n" % (tag))
   geof.close()
References copy_contact_zone(), create_input_file(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_tri_particle_gmsh_input(), get_E(), get_eff_k(), get_G(), particle_locations(), util::io.print(), print_dbl_list(), write_contact_zone_part(), and write_material_zone_part().
generate_drum2d_particle_gmsh_input()
def problem_setup.generate_drum2d_particle_gmsh_input (inp_dir, filename, center, radius, width, mesh_size, pp_tag)
Definition at line 647 of file problem_setup.py.
 def generate_drum2d_particle_gmsh_input(inp_dir, filename, center, radius, width, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # points
   points = get_ref_drum_points(center, radius, width, True)
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   for i in range(7):
     p = points[i]
     sts = "Point({}) = ".format(i+1)
     sts += "{"
     sts += "{}, {}, {}, {}".format(p[0], p[1], p[2], mesh_size)
     sts += "};\n"
     geof.write(sts);
   #
   # circlular arc
   #
   geof.write("Line(1) = {2, 3};\n")
   geof.write("Line(2) = {3, 4};\n")
   geof.write("Line(3) = {4, 5};\n")
   geof.write("Line(4) = {5, 6};\n")
   geof.write("Line(5) = {6, 7};\n")
   geof.write("Line(6) = {7, 2};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4, 5, 6};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{1} In Surface {1};")
   # close file
   geof.close()
References get_ref_drum_points().
Referenced by create_input_file(), does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_cylindrical_wall_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), get_center(), particle_locations(), and particle_locations_old().
generate_drum_particle_gmsh_input()
def problem_setup.generate_drum_particle_gmsh_input (inp_dir, filename, center, radius, width, mesh_size, pp_tag)
Definition at line 260 of file problem_setup.py.
 def generate_drum_particle_gmsh_input(inp_dir, filename, center, radius, width, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # points
   points = get_ref_drum_points(center, radius, width, True)
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   for i in range(7):
     p = points[i]
     sts = "Point({}) = ".format(i+1)
     sts += "{"
     sts += "{}, {}, {}, {}".format(p[0], p[1], p[2], mesh_size)
     sts += "};\n"
     geof.write(sts);
   #
   # circlular arc
   #
   geof.write("Line(1) = {2, 3};\n")
   geof.write("Line(2) = {3, 4};\n")
   geof.write("Line(3) = {4, 5};\n")
   geof.write("Line(4) = {5, 6};\n")
   geof.write("Line(5) = {6, 7};\n")
   geof.write("Line(6) = {7, 2};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4, 5, 6};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{1} In Surface {1};")
   # close file
   geof.close()
References create_input_file(), generate_hex_particle_gmsh_input(), get_E(), get_eff_k(), get_G(), get_ref_drum_points(), particle_locations_orient(), util::io.print(), and print_dbl_list().
generate_hex_particle_gmsh_input()
def problem_setup.generate_hex_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
Definition at line 535 of file problem_setup.py.
 def generate_hex_particle_gmsh_input(inp_dir, filename, center, radius, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   points = get_ref_hex_points(center, radius, True)
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   for i in range(7):
     p = points[i]
     sts = "Point({}) = ".format(i+1)
     sts += "{"
     sts += "{}, {}, {}, {}".format(p[0], p[1], p[2], mesh_size)
     sts += "};\n"
     geof.write(sts);
   #
   # circlular arc
   #
   geof.write("Line(1) = {2, 3};\n")
   geof.write("Line(2) = {3, 4};\n")
   geof.write("Line(3) = {4, 5};\n")
   geof.write("Line(4) = {5, 6};\n")
   geof.write("Line(5) = {6, 7};\n")
   geof.write("Line(6) = {7, 2};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4, 5, 6};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{1} In Surface {1};")
   # close file
   geof.close()
References get_ref_hex_points().
Referenced by does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_cylindrical_wall_gmsh_input(), generate_drum_particle_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), get_center(), particle_locations(), and particle_locations_old().
generate_moving_rect_wall_gmsh_input()
def problem_setup.generate_moving_rect_wall_gmsh_input (inp_dir, filename, rectangle, mesh_size, pp_tag)
Definition at line 1096 of file problem_setup.py.
 def generate_moving_rect_wall_gmsh_input(inp_dir, filename, rectangle, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # outer rectangle
   sim_Lx_out1 = rectangle[0]
   sim_Ly_out1 = rectangle[1]
   sim_Lz_out1 = rectangle[2]
   sim_Lx_out2 = rectangle[3]
   sim_Ly_out2 = rectangle[4]
   sim_Lz_out2 = rectangle[5]
   # mesh size
   sim_h = mesh_size
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   geof.write("Point(1) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out1, sim_Lz_out1, sim_h));
   geof.write("Point(2) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out1, sim_Lz_out1, sim_h))
   geof.write("Point(3) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out2, sim_Lz_out1, sim_h))
   geof.write("Point(4) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out2, sim_Lz_out1, sim_h))
   #
   # lines
   #
   geof.write("Line(1) = {1, 2};\n")
   geof.write("Line(2) = {2, 3};\n")
   geof.write("Line(3) = {3, 4};\n")
   geof.write("Line(4) = {4, 1};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   tag = '"' + "a" + '"'
   geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # close file
   geof.close()
References copy_contact_zone(), create_input_file(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_rigid_rect_container_moving_wall_setup_gmsh_input(), generate_tri_particle_gmsh_input(), get_E(), get_eff_k(), get_G(), particle_locations(), util::io.print(), print_dbl_list(), write_contact_zone_part(), and write_material_zone_part().
generate_moving_wall_gmsh_input()
def problem_setup.generate_moving_wall_gmsh_input (inp_dir, filename, rectangle, mesh_size, pp_tag)
Definition at line 486 of file problem_setup.py.
 def generate_moving_wall_gmsh_input(inp_dir, filename, rectangle, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # outer rectangle
   sim_Lx_out1 = rectangle[0]
   sim_Ly_out1 = rectangle[1]
   sim_Lz_out1 = rectangle[2]
   sim_Lx_out2 = rectangle[3]
   sim_Ly_out2 = rectangle[4]
   sim_Lz_out2 = rectangle[5]
   # mesh size
   sim_h = mesh_size
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   geof.write("Point(1) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out1, sim_Lz_out1, sim_h));
   geof.write("Point(2) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out1, sim_Lz_out1, sim_h))
   geof.write("Point(3) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out2, sim_Lz_out1, sim_h))
   geof.write("Point(4) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out2, sim_Lz_out1, sim_h))
   #
   # lines
   #
   geof.write("Line(1) = {1, 2};\n")
   geof.write("Line(2) = {2, 3};\n")
   geof.write("Line(3) = {3, 4};\n")
   geof.write("Line(4) = {4, 1};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   tag = '"' + "a" + '"'
   geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # close file
   geof.close()
References create_input_file(), generate_cir_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_rigid_wall_gmsh_input(), get_E(), get_eff_k(), get_G(), particle_locations(), and print_dbl_list().
generate_particle_gmsh_input() [1/2]
def problem_setup.generate_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
Definition at line 84 of file problem_setup.py.
 def generate_particle_gmsh_input(inp_dir, filename, center, radius, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # center and radius
   sim_Cx = center[0]
   sim_Cy = center[1]
   sim_Cz = center[2]
   sim_radius = radius
   # mesh size
   sim_h = mesh_size
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   geof.write("Point(1) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx, sim_Cy, sim_Cz, sim_h));
   geof.write("Point(2) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx + sim_radius, sim_Cy, sim_Cz, sim_h))
   geof.write("Point(3) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx - sim_radius, sim_Cy, sim_Cz, sim_h))
   geof.write("Point(4) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx, sim_Cy + sim_radius, sim_Cz, sim_h))
   geof.write("Point(5) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Cx, sim_Cy - sim_radius, sim_Cz, sim_h))
   #
   # circlular arc
   #
   geof.write("Circle(1) = {2, 1, 4};\n")
   geof.write("Circle(2) = {4, 1, 3};\n")
   geof.write("Circle(3) = {3, 1, 5};\n")
   geof.write("Circle(4) = {5, 1, 2};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {2, 3, 4, 1};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{1} In Surface {1};")
   # close file
   geof.close()
References create_input_file(), get_E(), get_eff_k(), get_G(), particle_locations(), and print_dbl_list().
Referenced by generate_particle_gmsh_input(), generate_wall_gmsh_input(), and particle_locations_orient().
generate_particle_gmsh_input() [2/2]
def problem_setup.generate_particle_gmsh_input (inp_dir, filename, center, radius, width, mesh_size, pp_tag)
Definition at line 165 of file problem_setup.py.
 def generate_particle_gmsh_input(inp_dir, filename, center, radius, width, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # points
   points = get_ref_drum_points(center, radius, width, True)
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   for i in range(7):
     p = points[i]
     sts = "Point({}) = ".format(i+1)
     sts += "{"
     sts += "{}, {}, {}, {}".format(p[0], p[1], p[2], mesh_size)
     sts += "};\n"
     geof.write(sts);
   #
   # circlular arc
   #
   geof.write("Line(1) = {2, 3};\n")
   geof.write("Line(2) = {3, 4};\n")
   geof.write("Line(3) = {4, 5};\n")
   geof.write("Line(4) = {5, 6};\n")
   geof.write("Line(5) = {6, 7};\n")
   geof.write("Line(6) = {7, 2};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4, 5, 6};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{1} In Surface {1};")
   # close file
   geof.close()
References generate_particle_gmsh_input(), and get_ref_drum_points().
generate_rect_container_gmsh_input()
def problem_setup.generate_rect_container_gmsh_input (inp_dir, filename, pi1, pi2, dx, dy, mesh_size, pp_tag)
Definition at line 688 of file problem_setup.py.
 def generate_rect_container_gmsh_input(inp_dir, filename, pi1, pi2, dx, dy, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   innr_pts = get_ref_rect_points(get_center(pi1, pi2), pi2[0] - pi1[0], pi2[1] - pi1[1])
   outr_pts = get_ref_rect_points(get_center(pi1, pi2), pi2[0] - pi1[0] + 2*dx, pi2[1] - pi1[1] + 2*dy)
   h = mesh_size
   hout = h # 5*h
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   # points
   p_id = 1
   for i in range(4):
     p_id = write_point_geo(geof, p_id, outr_pts[i], h)
   for i in range(4):
     p_id = write_point_geo(geof, p_id, innr_pts[i], h)
   # line
   l_id = 1
   l_id = write_line_geo(geof, l_id, 1, 2)
   l_id = write_line_geo(geof, l_id, 2, 3)
   l_id = write_line_geo(geof, l_id, 3, 4)
   l_id = write_line_geo(geof, l_id, 4, 1)
   l_id = write_line_geo(geof, l_id, 5, 6)
   l_id = write_line_geo(geof, l_id, 6, 7)
   l_id = write_line_geo(geof, l_id, 7, 8)
   l_id = write_line_geo(geof, l_id, 8, 5)
   # line loop to define surface
   geof.write("Line Loop(9) = {1, 2, 3, 4};\n")
   geof.write("Line Loop(10) = {5, 6, 7, 8};\n")
   # define surface
   geof.write("Plane Surface(11) = {9, 10};\n")
   # close file
   geof.close()
References copy_contact_zone(), create_input_file(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), generate_tri_particle_gmsh_input(), get_center(), get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), get_E(), get_eff_k(), get_G(), get_ref_rect_points(), get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), particle_locations(), util::io.print(), print_dbl_list(), serialize_matrix_list(), write_cir_line_geo(), write_contact_zone_part(), write_line_geo(), write_material_zone_part(), and write_point_geo().
Referenced by particle_locations_old().
generate_rect_floor_gmsh_input()
def problem_setup.generate_rect_floor_gmsh_input (inp_dir, filename, center, L, W, mesh_size, pp_tag)
Definition at line 671 of file problem_setup.py.
 def generate_rect_floor_gmsh_input(inp_dir, filename, center, L, W, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   points = get_ref_rect_points(center, L, W, False)
   h = mesh_size
   hout = h # 5*h
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   # points
   write_point_geo(geof, 1, points[0], hout)
   write_point_geo(geof, 2, points[1], hout)
   write_point_geo(geof, 3, points[2], h)
   write_point_geo(geof, 4, points[3], h)
   # line
   geof.write("Line(1) = {1, 2};\n")
   geof.write("Line(2) = {2, 3};\n")
   geof.write("Line(3) = {3, 4};\n")
   geof.write("Line(4) = {4, 1};\n")
   # surfaces
   geof.write("Line Loop(1) = {1, 2, 3, 4};\n")
   # plane surface
   geof.write("Plane Surface(1) = {1};\n")
   # close file
   geof.close()
References get_ref_rect_points(), and write_point_geo().
Referenced by generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3().
generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2()
def problem_setup.generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2 (inp_dir, filename, center, Lin, Win, L, W, mesh_size, pp_tag)
Definition at line 708 of file problem_setup.py.
 def generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2(inp_dir, filename, center, Lin, Win, L, W, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # center and radius
   Cx = center[0]
   Cy = center[1]
   Cz = center[2]
   # Domain
   h = mesh_size
   hout = 3*h
   # hole in bottom edge
   hole_radius = 0.5 * (0.5*(W - Win))# half of thickness in vertical direction
   # left side points
   p5 = [Cx + 0.2*L, Cy - 0.5*W, Cz]
   p12 = [Cx + 0.2*L, Cy - 0.5*Win, Cz]
   p13 = [Cx + 0.2*L, Cy - 0.5*W + hole_radius, Cz]
   p14 = [Cx + 0.2*L + hole_radius, Cy - 0.5*W + hole_radius, Cz]
   p6 = [Cx + 0.28*L, Cy - 0.5*W, Cz]
   p16 = [Cx + 0.28*L, Cy - 0.5*Win, Cz]
   p17 = [Cx + 0.28*L, Cy - 0.5*W + hole_radius, Cz]
   p15 = [Cx + 0.28*L - hole_radius, Cy - 0.5*W + hole_radius, Cz]
   # triangle protrusion on upper-right corner
   #p20 = [Cx + 0.5*Lin - 0.15*Lin, Cy + 0.5*Win - 0.3*Win, Cz]
   #p19 = [Cx + 0.5*Lin, Cy + 0.5*Win - 0.1*Win, Cz]
   #p21 = [Cx + 0.5*Lin - 0.1*Lin, Cy + 0.5*Win, Cz]
   p20, p19, p21 = get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win)
   # circular protrusion at bottom
   #circ_protrsn_r = 0.2*Win
   #p8 = [Cx - 0.5*Lin + 0.25*Lin, Cy - 0.5*Win, Cz]
   #p11 = [Cx - 0.5*Lin + 0.25*Lin + 2*circ_protrsn_r, Cy - 0.5*Win, Cz]
   #p9 = [Cx - 0.5*Lin + 0.25*Lin + circ_protrsn_r, Cy - 0.5*Win, Cz]
   #p10 = [Cx - 0.5*Lin + 0.25*Lin + circ_protrsn_r, Cy - 0.5*Win + circ_protrsn_r, Cz]
   circ_protrsn_r, p8, p11, p9, p10 = get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win)
   # create gmsh input file
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   # ---------------------- #
   # points                 #
   # ---------------------- #
   # points (as shown in drawing above)
   p_id = 1
   # points on outer side
   p_id = write_point_geo(geof, p_id, [Cx -0.5*L, Cy - 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, [Cx + 0.5*L, Cy - 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, [Cx + 0.5*L, Cy + 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, [Cx - 0.5*L, Cy + 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, p5, hout)
   p_id = write_point_geo(geof, p_id, p6, hout)
   # points on inner side
   p_id = write_point_geo(geof, p_id, [Cx - 0.5*Lin, Cy - 0.5*Win, Cz], h)
   p_id = write_point_geo(geof, p_id, p8, h)
   p_id = write_point_geo(geof, p_id, p9, hout) # treat this internal point as control for coarse mesh
   p_id = write_point_geo(geof, p_id, p10, h)
   p_id = write_point_geo(geof, p_id, p11, h)
   # circular opening points
   p_id = write_point_geo(geof, p_id, p12, h)
   p_id = write_point_geo(geof, p_id, p13, hout)
   p_id = write_point_geo(geof, p_id, p14, h)
   p_id = write_point_geo(geof, p_id, p15, h)
   p_id = write_point_geo(geof, p_id, p16, h)
   p_id = write_point_geo(geof, p_id, p17, hout)
   p_id = write_point_geo(geof, p_id, [Cx + 0.5*Lin, Cy - 0.5*Win, Cz], h)
   # triangular protrusion
   p_id = write_point_geo(geof, p_id, p19, h)
   p_id = write_point_geo(geof, p_id, p20, h)
   p_id = write_point_geo(geof, p_id, p21, h)
   p_id = write_point_geo(geof, p_id, [Cx - 0.5*Lin, Cy + 0.5*Win, Cz], h)
   # ---------------------- #
   # lines                  #
   # ---------------------- #
   # lines to form outer boundary (careful with the bottom edge as this will be divided into two lines)
   l_id = 1
   l_id = write_line_geo(geof, l_id, 1, 5)
   l_id = write_line_geo(geof, l_id, 6, 2)
   l_id = write_line_geo(geof, l_id, 2, 3)
   l_id = write_line_geo(geof, l_id, 3, 4)
   l_id = write_line_geo(geof, l_id, 4, 1)
   l_id = write_line_geo(geof, l_id, 7, 8)
   # circular arc for protrusion
   l_id = write_cir_line_geo(geof, l_id, 8, 9, 10)
   l_id = write_cir_line_geo(geof, l_id, 10, 9, 11)
   l_id = write_line_geo(geof, l_id, 11, 12)
   # circular arc for opening
   l_id = write_cir_line_geo(geof, l_id, 12, 13, 14)
   l_id = write_cir_line_geo(geof, l_id, 14, 13, 5)
   l_id = write_cir_line_geo(geof, l_id, 16, 17, 15)
   l_id = write_cir_line_geo(geof, l_id, 15, 17, 6)
   l_id = write_line_geo(geof, l_id, 16, 18)
   l_id = write_line_geo(geof, l_id, 18, 19)
   l_id = write_line_geo(geof, l_id, 19, 20)
   l_id = write_line_geo(geof, l_id, 20, 21)
   l_id = write_line_geo(geof, l_id, 21, 22)
   l_id = write_line_geo(geof, l_id, 22, 7)
   # ---------------------- #
   # line loops, ...        #
   # ---------------------- #
   # line loop to define surface
   # this works too ---> geof.write("Curve Loop(13) = {10, 6, -11, -1, -5, -4, -3, -2, -12, 7, 8, 9};\n")
   geof.write("Curve Loop(20) = {14, 15, 16, 17, 18, 19, 6, 7, 8, 9, 10, 11, -1, -5, -4, -3, -2, -12, -13};\n")
   # define surface
   geof.write("Plane Surface(21) = {20};\n")
   # # define physical groups
   # geof.write("Physical Point(22) = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22};\n")
   # geof.write("Physical Line(23) = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};\n")
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {21};\n" % (tag))
   # close file
   geof.close()
References get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), write_cir_line_geo(), write_line_geo(), and write_point_geo().
Referenced by generate_rect_container_gmsh_input().
generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3()
def problem_setup.generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3 (inp_dir, filename, center, Lin, Win, L, W, mesh_size, pp_tag)
Definition at line 849 of file problem_setup.py.
 def generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(inp_dir, filename, center, Lin, Win, L, W, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # center and radius
   Cx = center[0]
   Cy = center[1]
   Cz = center[2]
   # Domain
   h = mesh_size
   hout = h #3*h
   # hole in bottom edge
   # left side points
   p5 = [Cx + 0.2*L, Cy - 0.5*W, Cz]
   p12 = [Cx + 0.2*L, Cy - 0.5*Win, Cz]
   p6 = [Cx + 0.3*L, Cy - 0.5*W, Cz]
   p13 = [Cx + 0.3*L, Cy - 0.5*Win, Cz]
   # triangle protrusion on upper-right corner
   #p20 = [Cx + 0.5*Lin - 0.15*Lin, Cy + 0.5*Win - 0.3*Win, Cz]
   #p19 = [Cx + 0.5*Lin, Cy + 0.5*Win - 0.1*Win, Cz]
   #p21 = [Cx + 0.5*Lin - 0.1*Lin, Cy + 0.5*Win, Cz]
   p16, p15, p17 = get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win)
   # circular protrusion at bottom
   #circ_protrsn_r = 0.2*Win
   #p8 = [Cx - 0.5*Lin + 0.25*Lin, Cy - 0.5*Win, Cz]
   #p11 = [Cx - 0.5*Lin + 0.25*Lin + 2*circ_protrsn_r, Cy - 0.5*Win, Cz]
   #p9 = [Cx - 0.5*Lin + 0.25*Lin + circ_protrsn_r, Cy - 0.5*Win, Cz]
   #p10 = [Cx - 0.5*Lin + 0.25*Lin + circ_protrsn_r, Cy - 0.5*Win + circ_protrsn_r, Cz]
   circ_protrsn_r, p8, p11, p9, p10 = get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win)
   # create gmsh input file
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   # ---------------------- #
   # points                 #
   # ---------------------- #
   # points (as shown in drawing above)
   p_id = 1
   # points on outer side
   p_id = write_point_geo(geof, p_id, [Cx -0.5*L, Cy - 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, [Cx + 0.5*L, Cy - 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, [Cx + 0.5*L, Cy + 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, [Cx - 0.5*L, Cy + 0.5*W, Cz], hout)
   p_id = write_point_geo(geof, p_id, p5, hout)
   p_id = write_point_geo(geof, p_id, p6, hout)
   # points on inner side
   p_id = write_point_geo(geof, p_id, [Cx - 0.5*Lin, Cy - 0.5*Win, Cz], h)
   p_id = write_point_geo(geof, p_id, p8, h)
   p_id = write_point_geo(geof, p_id, p9, hout) # treat this internal point as control for coarse mesh
   p_id = write_point_geo(geof, p_id, p10, h)
   p_id = write_point_geo(geof, p_id, p11, h)
   # opening points
   p_id = write_point_geo(geof, p_id, p12, h)
   p_id = write_point_geo(geof, p_id, p13, h)
   p_id = write_point_geo(geof, p_id, [Cx + 0.5*Lin, Cy - 0.5*Win, Cz], h)
   # triangular protrusion
   p_id = write_point_geo(geof, p_id, p15, h)
   p_id = write_point_geo(geof, p_id, p16, h)
   p_id = write_point_geo(geof, p_id, p17, h)
   p_id = write_point_geo(geof, p_id, [Cx - 0.5*Lin, Cy + 0.5*Win, Cz], h)
   # ---------------------- #
   # lines                  #
   # ---------------------- #
   # lines to form outer boundary (careful with the bottom edge as this will be divided into two lines)
   l_id = 1
   l_id = write_line_geo(geof, l_id, 1, 5)
   l_id = write_line_geo(geof, l_id, 6, 2)
   l_id = write_line_geo(geof, l_id, 2, 3)
   l_id = write_line_geo(geof, l_id, 3, 4)
   l_id = write_line_geo(geof, l_id, 4, 1)
   l_id = write_line_geo(geof, l_id, 7, 8)
   # circular arc for protrusion
   l_id = write_cir_line_geo(geof, l_id, 8, 9, 10)
   l_id = write_cir_line_geo(geof, l_id, 10, 9, 11)
   l_id = write_line_geo(geof, l_id, 11, 12)
   # opening
   l_id = write_line_geo(geof, l_id, 5, 12)
   l_id = write_line_geo(geof, l_id, 13, 6)
   l_id = write_line_geo(geof, l_id, 13, 14)
   l_id = write_line_geo(geof, l_id, 14, 15)
   l_id = write_line_geo(geof, l_id, 15, 16)
   l_id = write_line_geo(geof, l_id, 16, 17)
   l_id = write_line_geo(geof, l_id, 17, 18)
   l_id = write_line_geo(geof, l_id, 18, 7)
   # ---------------------- #
   # line loops, ...        #
   # ---------------------- #
   # line loop to define surface
   geof.write("Curve Loop(20) = {12, 13, 14, 15, 16, 17, 6, 7, 8, 9, -10, -1, -5, -4, -3, -2, -11};\n")
   # define surface
   geof.write("Plane Surface(21) = {20};\n")
   # # define physical groups
   # geof.write("Physical Point(22) = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};\n")
   # geof.write("Physical Line(23) = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};\n")
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {21};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{9} In Surface {21};")
   # close file
   geof.close()
References copy_contact_zone(), create_input_file(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_rect_floor_gmsh_input(), generate_tri_particle_gmsh_input(), get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), get_E(), get_eff_k(), get_G(), get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), particle_locations(), util::io.print(), print_dbl_list(), write_cir_line_geo(), write_contact_zone_part(), write_line_geo(), write_material_zone_part(), and write_point_geo().
Referenced by generate_rect_container_gmsh_input().
generate_rigid_rect_container_moving_wall_setup_gmsh_input()
def problem_setup.generate_rigid_rect_container_moving_wall_setup_gmsh_input (inp_dir, filename, outer_rect, inner_rect, mesh_size, pp_tag)
Definition at line 1002 of file problem_setup.py.
 def generate_rigid_rect_container_moving_wall_setup_gmsh_input(inp_dir, filename, outer_rect, inner_rect, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # outer rectangle
   sim_Lx_out1 = outer_rect[0]
   sim_Ly_out1 = outer_rect[1]
   sim_Lz_out1 = outer_rect[2]
   sim_Lx_out2 = outer_rect[3]
   sim_Ly_out2 = outer_rect[4]
   sim_Lz_out2 = outer_rect[5]
   # inner rectangle
   sim_Lx_in1 = inner_rect[0]
   sim_Ly_in1 = inner_rect[1]
   sim_Lz_in1 = inner_rect[2]
   sim_Lx_in2 = inner_rect[3]
   sim_Ly_in2 = inner_rect[4]
   sim_Lz_in2 = inner_rect[5]
   # mesh size
   sim_h = mesh_size
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   #                L7                          L3
   #          4  + --- + 8                 7 + --- +  3
   #             |     |                     |     |
   #             |     |                     |     |
   #             |     | L6              L4  |     |
   #       L8    |     |                     |     |
   #             |     |                     |     | L2
   #             |     |         L5          |     |
   #             |     + ------------------- +     |
   #             |     5                     6     |
   #             |                                 |
   #          1  + ------------------------------- + 2
   #                             L1
   #
   #
   # for point 8 and 7 --> choose y coordinate from outer rectangle and x
   # coordinate from inner rectangle
   #
   # points
   #
   geof.write("Point(1) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out1, sim_Lz_out1, sim_h))
   geof.write("Point(2) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out1, sim_Lz_out1, sim_h))
   geof.write("Point(3) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out2, sim_Lz_out1, sim_h))
   geof.write("Point(4) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out2, sim_Lz_out1, sim_h))
   geof.write("Point(5) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in1, sim_Ly_in1, sim_Lz_in1, sim_h))
   geof.write("Point(6) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in2, sim_Ly_in1, sim_Lz_in1, sim_h))
   geof.write("Point(7) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in2, sim_Ly_out2, sim_Lz_in1, sim_h))
   geof.write("Point(8) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in1, sim_Ly_out2, sim_Lz_in1, sim_h))
   #
   # lines
   #
   geof.write("Line(1) = {1, 2};\n")
   geof.write("Line(2) = {2, 3};\n")
   geof.write("Line(3) = {3, 7};\n")
   geof.write("Line(4) = {7, 6};\n")
   geof.write("Line(5) = {6, 5};\n")
   geof.write("Line(6) = {5, 8};\n")
   geof.write("Line(7) = {8, 4};\n")
   geof.write("Line(8) = {4, 1};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4, 5, 6, 7, 8};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   tag = '"' + "a" + '"'
   geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # close file
   geof.close()
Referenced by generate_moving_rect_wall_gmsh_input().
generate_rigid_wall_gmsh_input()
def problem_setup.generate_rigid_wall_gmsh_input (inp_dir, filename, outer_rect, inner_rect, mesh_size, pp_tag)
Definition at line 392 of file problem_setup.py.
 def generate_rigid_wall_gmsh_input(inp_dir, filename, outer_rect, inner_rect, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # outer rectangle
   sim_Lx_out1 = outer_rect[0]
   sim_Ly_out1 = outer_rect[1]
   sim_Lz_out1 = outer_rect[2]
   sim_Lx_out2 = outer_rect[3]
   sim_Ly_out2 = outer_rect[4]
   sim_Lz_out2 = outer_rect[5]
   # inner rectangle
   sim_Lx_in1 = inner_rect[0]
   sim_Ly_in1 = inner_rect[1]
   sim_Lz_in1 = inner_rect[2]
   sim_Lx_in2 = inner_rect[3]
   sim_Ly_in2 = inner_rect[4]
   sim_Lz_in2 = inner_rect[5]
   # mesh size
   sim_h = mesh_size
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   #                L7                          L3
   #          4  + --- + 8                 7 + --- +  3
   #             |     |                     |     |
   #             |     |                     |     |
   #             |     | L6              L4  |     |
   #       L8    |     |                     |     |
   #             |     |                     |     | L2
   #             |     |         L5          |     |
   #             |     + ------------------- +     |
   #             |     5                     6     |
   #             |                                 |
   #          1  + ------------------------------- + 2
   #                             L1
   #
   #
   # for point 8 and 7 --> choose y coordinate from outer rectangle and x
   # coordinate from inner rectangle
   #
   # points
   #
   geof.write("Point(1) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out1, sim_Lz_out1, sim_h))
   geof.write("Point(2) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out1, sim_Lz_out1, sim_h))
   geof.write("Point(3) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out2, sim_Lz_out1, sim_h))
   geof.write("Point(4) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out2, sim_Lz_out1, sim_h))
   geof.write("Point(5) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in1, sim_Ly_in1, sim_Lz_in1, sim_h))
   geof.write("Point(6) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in2, sim_Ly_in1, sim_Lz_in1, sim_h))
   geof.write("Point(7) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in2, sim_Ly_out2, sim_Lz_in1, sim_h))
   geof.write("Point(8) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_in1, sim_Ly_out2, sim_Lz_in1, sim_h))
   #
   # lines
   #
   geof.write("Line(1) = {1, 2};\n")
   geof.write("Line(2) = {2, 3};\n")
   geof.write("Line(3) = {3, 7};\n")
   geof.write("Line(4) = {7, 6};\n")
   geof.write("Line(5) = {6, 5};\n")
   geof.write("Line(6) = {5, 8};\n")
   geof.write("Line(7) = {8, 4};\n")
   geof.write("Line(8) = {4, 1};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4, 5, 6, 7, 8};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   tag = '"' + "a" + '"'
   geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # close file
   geof.close()
Referenced by generate_moving_wall_gmsh_input().
generate_tri_particle_gmsh_input()
def problem_setup.generate_tri_particle_gmsh_input (inp_dir, filename, center, radius, mesh_size, pp_tag)
Definition at line 592 of file problem_setup.py.
 def generate_tri_particle_gmsh_input(inp_dir, filename, center, radius, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # points
   points = get_ref_triangle_points(center, radius, True)
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   for i in range(4):
     p = points[i]
     sts = "Point({}) = ".format(i+1)
     sts += "{"
     sts += "{}, {}, {}, {}".format(p[0], p[1], p[2], mesh_size)
     sts += "};\n"
     geof.write(sts);
   #
   # circlular arc
   #
   geof.write("Line(1) = {2, 3};\n")
   geof.write("Line(2) = {3, 4};\n")
   geof.write("Line(3) = {4, 2};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   # tag = '"' + "a" + '"'
   # geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # # add center point to plane surface
   geof.write("Point{1} In Surface {1};")
   # close file
   geof.close()
References get_ref_triangle_points().
Referenced by create_input_file(), does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_cylindrical_wall_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), get_center(), particle_locations(), and particle_locations_old().
generate_wall_gmsh_input() [1/2]
def problem_setup.generate_wall_gmsh_input (inp_dir, filename, center, outer_radius, inner_radius, bar_width, bar_length, mesh_size, pp_tag)
Definition at line 705 of file problem_setup.py.
 def generate_wall_gmsh_input(inp_dir, filename, center, outer_radius, inner_radius, bar_width, bar_length, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # center and radius
   Cx = center[0]
   Cy = center[1]
   Cz = center[2]
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   points = []
   points.append([Cx, Cy, Cz])
   points.append([outer_radius, 0., 0.])
   points.append([0., outer_radius, 0.])
   points.append([-outer_radius, 0., 0.])
   points.append([0., -outer_radius, 0.])
   points.append([inner_radius, 0.5*bar_width, 0.])
   points.append([inner_radius, -0.5*bar_width, 0.])
   points.append([0., inner_radius, 0.])
   points.append([-inner_radius, 0., 0.])
   points.append([0., -inner_radius, 0.])
   points.append([inner_radius - bar_length, 0.5*bar_width, 0.])
   points.append([inner_radius - bar_length, -0.5*bar_width, 0.])
   count = 0
   for p in points:
     count += 1
     geof.write("Point(%d) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (count, p[0], p[1], p[2], mesh_size))
   #
   # circular arc
   #
   circles = []
   circles.append([2, 1, 3])
   circles.append([3, 1, 4])
   circles.append([4, 1, 5])
   circles.append([5, 1, 2])
   circles.append([6, 1, 8])
   circles.append([8, 1, 9])
   circles.append([9, 1, 10])
   circles.append([10, 1, 7])
   count = 0
   for c in circles:
     count += 1
     geof.write("Circle(%d) = {%d, %d, %d};\n" % (count, c[0], c[1], c[2]))
   #
   # line
   #
   lines = []
   lines.append([6, 11])
   lines.append([11, 12])
   lines.append([12, 7])
   #count = 0
   for l in lines:
     count += 1
     geof.write("Line(%d) = {%d, %d};\n" % (count, l[0], l[1]))
   #
   # curve loop
   #
   geof.write("Line Loop(1) = {2, 3, 4, 1};\n")
   geof.write("Line Loop(2) = {6, 7, 8, -11, -10, -9, 5};\n")
   #
   # plane surface and physical tag
   #
   geof.write("Plane Surface(1) = {1, 2};\n")
   #geof.write("Physical Surface(1) = {1};\n")
   #geof.write("Physical Point(2) = {9, 4, 10, 5, 2, 7, 6, 11, 12, 3, 8};\n")
   tag = '"' + "a" + '"'
   geof.write("Physical Surface(%s) = {1};\n" % (tag))
   geof.close()
Referenced by create_input_file(), generate_wall_gmsh_input(), particle_locations(), and particle_locations_orient().
generate_wall_gmsh_input() [2/2]
def problem_setup.generate_wall_gmsh_input (inp_dir, filename, rectangle, mesh_size, pp_tag)
Definition at line 223 of file problem_setup.py.
 def generate_wall_gmsh_input(inp_dir, filename, rectangle, mesh_size, pp_tag):
   sim_inp_dir = str(inp_dir)
   # outer rectangle
   sim_Lx_out1 = rectangle[0]
   sim_Ly_out1 = rectangle[1]
   sim_Lz_out1 = rectangle[2]
   sim_Lx_out2 = rectangle[3]
   sim_Ly_out2 = rectangle[4]
   sim_Lz_out2 = rectangle[5]
   # mesh size
   sim_h = mesh_size
   #
   # create .geo file for gmsh
   #
   geof = open(sim_inp_dir + filename + '_' + str(pp_tag) + '.geo','w')
   geof.write("cl__1 = 1;\n")
   geof.write("Mesh.MshFileVersion = 2.2;\n")
   #
   # points
   #
   geof.write("Point(1) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out1, sim_Lz_out1, sim_h));
   geof.write("Point(2) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out1, sim_Lz_out1, sim_h))
   geof.write("Point(3) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out2, sim_Ly_out2, sim_Lz_out1, sim_h))
   geof.write("Point(4) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (sim_Lx_out1, sim_Ly_out2, sim_Lz_out1, sim_h))
   #
   # lines
   #
   geof.write("Line(1) = {1, 2};\n")
   geof.write("Line(2) = {2, 3};\n")
   geof.write("Line(3) = {3, 4};\n")
   geof.write("Line(4) = {4, 1};\n")
   #
   # surfaces
   #
   geof.write("Line Loop(1) = {1, 2, 3, 4};\n")
   #
   # plane surface
   #
   geof.write("Plane Surface(1) = {1};\n")
   #
   # physical surface
   #
   tag = '"' + "a" + '"'
   geof.write("Physical Surface(%s) = {1};\n" % (tag))
   # close file
   geof.close()
References create_input_file(), generate_particle_gmsh_input(), generate_wall_gmsh_input(), get_E(), get_eff_k(), get_G(), particle_locations_orient(), and print_dbl_list().
get_center()
def problem_setup.get_center (p1, p2)
Definition at line 146 of file problem_setup.py.
 def get_center(p1, p2):
   return [0.5*(p1[i] + p2[i]) for i in range(3)]
References does_intersect_with_rectangle_wall_with_protrusion_and_opening(), does_rect_intersect_rect(), does_rect_intersect_rect_use_pair_coord(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_tri_particle_gmsh_input(), get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), get_ref_drum_points(), get_ref_hex_points(), get_ref_rect_points(), get_ref_triangle_points(), get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), particle_locations(), util::io.print(), and rotate().
Referenced by generate_rect_container_gmsh_input(), and particle_locations_old().
get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening()
def problem_setup.get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening (center, Lin, Win)
Definition at line 63 of file problem_setup.py.
 def get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win):
     Cx = center[0]
     Cy = center[1]
     Cz = center[2]
     # circular protrusion at bottom
     circ_protrsn_r = 0.1*Win
     p8 = [Cx - 0.5*Lin + 0.2*Lin, Cy - 0.5*Win, Cz]
     p11 = [Cx - 0.5*Lin + 0.2*Lin + 2*circ_protrsn_r, Cy - 0.5*Win, Cz]
     p9 = [Cx - 0.5*Lin + 0.2*Lin + circ_protrsn_r, Cy - 0.5*Win, Cz]
     p10 = [Cx - 0.5*Lin + 0.2*Lin + circ_protrsn_r, Cy - 0.5*Win + circ_protrsn_r, Cz]
     return circ_protrsn_r, p8, p11, p9, p10
Referenced by does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), get_center(), and serialize_matrix_list().
get_E()
def problem_setup.get_E (K, nu)
Definition at line 136 of file problem_setup.py.
 def get_E(K, nu):
   return 3. * K * (1. - 2. * nu)
Referenced by copy_contact_zone(), create_input_file(), does_intersect(), generate_cylindrical_wall_gmsh_input(), generate_drum_particle_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_particle_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), generate_wall_gmsh_input(), particle_locations(), particle_locations_orient(), serialize_matrix_list(), and write_cir_line_geo().
get_eff_k()
def problem_setup.get_eff_k (k1, k2)
Definition at line 143 of file problem_setup.py.
 def get_eff_k(k1, k2):
   return 2. * k1 * k2 / (k1 + k2)
Referenced by copy_contact_zone(), create_input_file(), does_intersect(), generate_cylindrical_wall_gmsh_input(), generate_drum_particle_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_particle_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), generate_wall_gmsh_input(), particle_locations(), particle_locations_orient(), serialize_matrix_list(), and write_cir_line_geo().
get_G()
def problem_setup.get_G (E, nu)
Definition at line 139 of file problem_setup.py.
 def get_G(E, nu):
   return E / (2. * (1. + nu))
Referenced by copy_contact_zone(), create_input_file(), does_intersect(), generate_cylindrical_wall_gmsh_input(), generate_drum_particle_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_particle_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), generate_wall_gmsh_input(), particle_locations(), particle_locations_orient(), serialize_matrix_list(), and write_cir_line_geo().
get_max()
def problem_setup.get_max (l)
Definition at line 147 of file problem_setup.py.
 def get_max(l):
   l = np.array(l)
   return l.max()
Referenced by copy_contact_zone(), does_intersect(), does_particle_intersect(), particle_locations(), particle_locations_old(), serialize_matrix_list(), and write_cir_line_geo().
get_ref_drum_points()
def problem_setup.get_ref_drum_points (center, radius, width, add_center = False)
Definition at line 236 of file problem_setup.py.
 def get_ref_drum_points(center, radius, width, add_center = False):
   # drum2d
   #
   #             v3                                v2
   #               +                               +
   #
   #
   #                      +         o           +
   #                     v4         x            v1
   #
   #               +                                +
   #               v5                               v6
   #
   # Axis is a vector from x to v1
   #
   axis = [1., 0., 0.]
   # center and radius
   sim_Cx = center[0]
   sim_Cy = center[1]
   sim_Cz = center[2]
   sim_radius = radius
   rotate_axis = [0., 0., 1.]
   x1 = rotate(axis, np.pi/3., rotate_axis)
   x2 = rotate(axis, -np.pi/3., rotate_axis)
   points = []
   if add_center:
     points.append(center)
   # v1
   points.append([center[i] + width*0.5*axis[i] for i in range(3)])
   # v2
   points.append([center[i] + radius*x1[i] for i in range(3)])
   # v3
   points.append([center[i] + radius*x1[i] - radius*axis[i] for i in range(3)])
   # v4
   points.append([center[i] - width*0.5*axis[i] for i in range(3)])
   # v5
   v6 = [center[i] + radius*x2[i] for i in range(3)]
   points.append([v6[i] - radius*axis[i] for i in range(3)])
   # v6
   points.append(v6)
   return points
References rotate().
Referenced by does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_drum2d_particle_gmsh_input(), generate_drum_particle_gmsh_input(), generate_particle_gmsh_input(), get_center(), get_ref_rect_points(), particle_locations(), particle_locations_old(), and particle_locations_orient().
get_ref_hex_points()
def problem_setup.get_ref_hex_points (center, radius, add_center = False)
Definition at line 199 of file problem_setup.py.
 def get_ref_hex_points(center, radius, add_center = False):
   # drum2d
   #
   #                        v3           v2
   #                         +           +
   #
   #
   #                      +         o           +
   #                     v4         x            v1
   #
   #                         +           +
   #                        v5           v6
   #
   # Axis is a vector from x to v1
   #
   axis = [1., 0., 0.]
   # center and radius
   sim_Cx = center[0]
   sim_Cy = center[1]
   sim_Cz = center[2]
   sim_radius = radius
   rotate_axis = [0., 0., 1.]
   points = []
   if add_center:
     points.append(center)
   for i in range(6):
     xi = rotate(axis, i*np.pi/3., rotate_axis)
     points.append([center[i] + radius * xi[i] for i in range(3)])
   return points
References rotate().
Referenced by does_intersect(), does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_hex_particle_gmsh_input(), get_center(), get_ref_rect_points(), particle_locations(), and particle_locations_old().
get_ref_rect_points() [1/2]
def problem_setup.get_ref_rect_points (center, L, W, add_center = False)
Definition at line 155 of file problem_setup.py.
 def get_ref_rect_points(center, L, W, add_center = False):
   points = []
   if add_center:
     points.append(center)
   points.append([center[0] - 0.5*L, center[1] - 0.5*W, center[2]])
   points.append([center[0] + 0.5*L, center[1] - 0.5*W, center[2]])
   points.append([center[0] + 0.5*L, center[1] + 0.5*W, center[2]])
   points.append([center[0] - 0.5*L, center[1] + 0.5*W, center[2]])
   return points
References does_rect_intersect_rect(), get_ref_drum_points(), get_ref_hex_points(), get_ref_rect_points(), get_ref_triangle_points(), and rotate().
get_ref_rect_points() [2/2]
def problem_setup.get_ref_rect_points (center, radius, add_center = False)
Definition at line 114 of file problem_setup.py.
 def get_ref_rect_points(center, radius, add_center = False):
   p1 = [center[0] - radius, center[1] - radius, center[2]]
   p2 = [center[0] + radius, center[1] - radius, center[2]]
   p3 = [center[0] + radius, center[1] + radius, center[2]]
   p4 = [center[0] - radius, center[1] + radius, center[2]]
   return [p1, p2, p3, p4]
References get_ref_drum_points(), get_ref_hex_points(), get_ref_triangle_points(), and rotate().
Referenced by generate_rect_container_gmsh_input(), generate_rect_floor_gmsh_input(), get_center(), get_ref_rect_points(), and particle_locations_old().
get_ref_triangle_points()
def problem_setup.get_ref_triangle_points (center, radius, add_center = False)
Definition at line 168 of file problem_setup.py.
 def get_ref_triangle_points(center, radius, add_center = False):
   # triangle
   #                       2
   #                        +
   #
   #
   #                        o
   #                        1
   #
   #              +-------------------+
   #             3                    4
   # center and radius
   sim_Cx = center[0]
   sim_Cy = center[1]
   sim_Cz = center[2]
   sim_radius = radius
   cp = np.cos(np.pi/6.)
   sp = np.sin(np.pi/6.)
   points = []
   if add_center:
     points.append([sim_Cx, sim_Cy, sim_Cz])
   points.append([sim_Cx, sim_Cy + sim_radius, sim_Cz])
   points.append([sim_Cx - sim_radius*cp, sim_Cy - sim_radius*sp, sim_Cz])
   points.append([sim_Cx + sim_radius*cp, sim_Cy - sim_radius*sp, sim_Cz])
   return points
Referenced by does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_tri_particle_gmsh_input(), get_center(), get_ref_rect_points(), particle_locations(), and particle_locations_old().
get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening()
def problem_setup.get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening (center, Lin, Win)
Definition at line 49 of file problem_setup.py.
 def get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(center, Lin, Win):
     Cx = center[0]
     Cy = center[1]
     Cz = center[2]
     # triangle protrusion on upper-right corner
     p20 = [Cx + 0.5*Lin - 0.15*Lin, Cy + 0.5*Win - 0.3*Win, Cz]
     p19 = [Cx + 0.5*Lin, Cy + 0.5*Win - 0.1*Win, Cz]
     p21 = [Cx + 0.5*Lin - 0.1*Lin, Cy + 0.5*Win, Cz]
     return p20, p19, p21
Referenced by does_intersect_with_rectangle_wall_with_protrusion_and_opening(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), get_center(), and serialize_matrix_list().
particle_locations() [1/6]
def problem_setup.particle_locations (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, N1, N2, R_in, bar_rect, z_coord, add_orient = True)
Definition at line 270 of file problem_setup.py.
 def particle_locations(inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, N1, N2, R_in, bar_rect, z_coord, add_orient = True):
   np.random.seed(30)
   sim_inp_dir = str(inp_dir)
   """Generate particle location data"""
   particles = []
   points = []
   method_to_use = 0
   if method_to_use == 0:
     pcount = 0
     count = 0
     while pcount < N2 and count < 100*N2:
       if count%N2 == 0:
         print('large particle iter = ', count)
       # random radius and center location
       r = R2 + np.random.uniform(-0.1 * R2, 0.1 * R2)
       x = center[0] + np.random.uniform(-R_in + R2 + padding, R_in - R2- padding)
       y = np.random.uniform(-R_in + R2+padding, max_y - R2-padding)
       p_zone = np.random.choice(id_choices2, size=1)[0]
       p = [p_zone, x, y, center[2], r]
       # check if it collides of existing particles
       pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
       if pintersect == False:
         particles.append(p)
         pcount += 1
       count +=1
     pcount = 0
     count = 0
     while pcount < N1 and count < 100*N1:
       if count%N1 == 0:
         print('small particle iter = ', count)
       # random radius and center location
       r = R1 + np.random.uniform(-0.1 * R1, 0.1 * R1)
       x = center[0] + np.random.uniform(-R_in + R1 + padding, R_in - R1- padding)
       y = np.random.uniform(-R_in + R1 + padding, max_y - R1 - padding)
       p_zone = np.random.choice(id_choices1, size=1)[0]
       p = [p_zone, x,y,center[2], r]
       # check if it collides of existing particles
       pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
       if pintersect == False:
         particles.append(p)
         pcount += 1
       count +=1
   elif method_to_use == 1:
     Nmax = N1 + N2
     # find how approximate number of rows and cols we can have
     check_r = R1
     if R1 > R2:
       check_r = R2
     rows = int(R_in / check_r)
     cols = int(R_in / check_r)
     rads = [R1, R2]
     counter = 0
     x_old = -R_in
     x_old_right = R_in
     y_old = -R_in
     pad = padding
     cx = 0.
     cy = 0.
     cz = z_coord
     r = 0.
     row_rads = []
     row_rads.append(R1)
     row_rads.append(R2)
     for i in range(rows):
       if i > 0:
         y_old = cy + get_max(row_rads)
       # reset
       row_rads = []
       row_rads.append(R1)
       row_rads.append(R2)
       num_p_cols = 0
       j = 0
       while num_p_cols < cols - 1 and j < Nmax:
         if j == 0:
           # for odd row, take x_old as first and for even take as last
           x_old = -R_in
           x_old_right = R_in
         # ptype = counter % 2
         p_type = 0 # 1 or 2
         p_index = 0 # zone this particle it belongs
         if np.random.uniform(0., 1.) < 0.7:
           p_type = 0
           p_index = np.random.choice(id_choices1, size=1)[0]
         else:
           p_type = 1
           p_index = np.random.choice(id_choices2, size=1)[0]
         r0 = rads[p_type]
         # perturb radius
         r = r0 + np.random.uniform(-0.1 * r0, 0.1 * r0)
         # r = r0
         row_rads.append(r)
         # random horizontal perturbation by 10% of radius
         rph = np.random.uniform(-0.1 * r0, 0.1 * r0)
         cx0 = x_old + pad + r
         cx = cx0 + rph
         # for even row, we start from right edge of rectange
         if i%2 == 0:
           cx0 = x_old_right - pad - r
           cx = cx0 - rph
         cy = y_old + pad + r
         # check if it collides of existing particles
         p = [float(p_index), cx, cy, cz, r]
         pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
         if pintersect == False:
           particles.append([float(p_index), cx, cy, cz, r])
           # set x_old
           if i % 2 == 0:
             x_old_right = cx - r
           else:
             x_old = cx + r
           counter += 1
           num_p_cols += 1
         j += 1
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   if add_orient:
     inpf.write("i, x, y, z, r, o\n")
     counter = 0
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], np.random.uniform(0., 2.*np.pi)))
       counter += 1
   else:
     inpf.write("i, x, y, z, r\n")
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4]))
   inpf.close()
   # to visualize in paraview
   write_vtu = False
   if write_vtu:
     points = []
     rads = []
     zones = []
     for p in particles:
       points.append([p[1], p[2], p[3]])
       rads.append(p[-1])
       zones.append(int(p[0]))
     points = np.array(points)
     rads = np.array(rads)
     zones = np.array(zones)
     mesh = pv.PolyData(points)
     mesh["radius"] = rads
     mesh["zone"] = zones
     pv.save_meshio(sim_inp_dir + 'particle_locations_' + str(pp_tag) + '.vtu', mesh)
   print('number of particles created = {}'.format(len(particles)))
   return len(particles), particles
References does_intersect_with_cylindrical_wall(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_tri_particle_gmsh_input(), get_max(), get_ref_drum_points(), get_ref_hex_points(), get_ref_triangle_points(), particle_locations(), and util::io.print().
particle_locations() [2/6]
def problem_setup.particle_locations (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, Nmax, R_in, bar_rect, z_coord, add_orient = True)
Definition at line 287 of file problem_setup.py.
 def particle_locations(inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, Nmax, R_in, bar_rect, z_coord, add_orient = True):
   np.random.seed(30)
   sim_inp_dir = str(inp_dir)
   """Generate particle location data"""
   particles = []
   points = []
   method_to_use = 0
   if method_to_use == 0:
     N1 = 30
     N2 = 10
     pcount = 0
     count = 0
     while pcount < N2 and count < 100*N2:
       if count%N2 == 0:
         print('large particle iter = ', count)
       # random radius and center location
       r = R2 + np.random.uniform(-0.1 * R2, 0.1 * R2)
       x = center[0] + np.random.uniform(-R_in + R2 + padding, R_in - R2- padding)
       y = np.random.uniform(-R_in + R2+padding, max_y - R2-padding)
       p_zone = np.random.choice(id_choices2, size=1)[0]
       p = [p_zone, x, y, center[2], r]
       # check if it collides of existing particles
       pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
       if pintersect == False:
         particles.append(p)
         pcount += 1
       count +=1
     pcount = 0
     count = 0
     while pcount < N1 and count < 100*N1:
       if count%N1 == 0:
         print('small particle iter = ', count)
       # random radius and center location
       r = R1 + np.random.uniform(-0.1 * R1, 0.1 * R1)
       x = center[0] + np.random.uniform(-R_in + R1 + padding, R_in - R1- padding)
       y = np.random.uniform(-R_in + R1 + padding, max_y - R1 - padding)
       p_zone = np.random.choice(id_choices1, size=1)[0]
       p = [p_zone, x,y,center[2], r]
       # check if it collides of existing particles
       pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
       if pintersect == False:
         particles.append(p)
         pcount += 1
       count +=1
   elif method_to_use == 1:
     # find how approximate number of rows and cols we can have
     check_r = R1
     if R1 > R2:
       check_r = R2
     rows = int(R_in / check_r)
     cols = int(R_in / check_r)
     rads = [R1, R2]
     counter = 0
     x_old = -R_in
     x_old_right = R_in
     y_old = -R_in
     pad = padding
     cx = 0.
     cy = 0.
     cz = z_coord
     r = 0.
     row_rads = []
     row_rads.append(R1)
     row_rads.append(R2)
     for i in range(rows):
       if i > 0:
         y_old = cy + get_max(row_rads)
       # reset
       row_rads = []
       row_rads.append(R1)
       row_rads.append(R2)
       num_p_cols = 0
       j = 0
       while num_p_cols < cols - 1 and j < Nmax:
         if j == 0:
           # for odd row, take x_old as first and for even take as last
           x_old = -R_in
           x_old_right = R_in
         # ptype = counter % 2
         p_type = 0 # 1 or 2
         p_index = 0 # zone this particle it belongs
         if np.random.uniform(0., 1.) < 0.7:
           p_type = 0
           p_index = np.random.choice(id_choices1, size=1)[0]
         else:
           p_type = 1
           p_index = np.random.choice(id_choices2, size=1)[0]
         r0 = rads[p_type]
         # perturb radius
         r = r0 + np.random.uniform(-0.1 * r0, 0.1 * r0)
         # r = r0
         row_rads.append(r)
         # random horizontal perturbation by 10% of radius
         rph = np.random.uniform(-0.1 * r0, 0.1 * r0)
         cx0 = x_old + pad + r
         cx = cx0 + rph
         # for even row, we start from right edge of rectange
         if i%2 == 0:
           cx0 = x_old_right - pad - r
           cx = cx0 - rph
         cy = y_old + pad + r
         # check if it collides of existing particles
         p = [float(p_index), cx, cy, cz, r]
         pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
         if pintersect == False:
           particles.append([float(p_index), cx, cy, cz, r])
           # set x_old
           if i % 2 == 0:
             x_old_right = cx - r
           else:
             x_old = cx + r
           counter += 1
           num_p_cols += 1
         j += 1
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   if add_orient:
     inpf.write("i, x, y, z, r, o\n")
     counter = 0
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], np.random.uniform(0., 2.*np.pi)))
       counter += 1
   else:
     inpf.write("i, x, y, z, r\n")
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4]))
   inpf.close()
   # to visualize in paraview
   points = []
   rads = []
   zones = []
   for p in particles:
     points.append([p[1], p[2], p[3]])
     rads.append(p[-1])
     zones.append(int(p[0]))
   points = np.array(points)
   rads = np.array(rads)
   zones = np.array(zones)
   mesh = pv.PolyData(points)
   mesh["radius"] = rads
   mesh["zone"] = zones
   pv.save_meshio(sim_inp_dir + 'particle_locations_' + str(pp_tag) + '.vtu', mesh)
   print('number of particles created = {}'.format(len(particles)))
   return len(particles), particles
References does_intersect_with_cylindrical_wall(), get_max(), and util::io.print().
Referenced by create_input_file(), does_intersect_with_rectangle_wall_with_protrusion_and_opening(), does_particle_intersect(), generate_cylindrical_wall_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_particle_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), get_center(), and particle_locations().
particle_locations() [3/6]
def problem_setup.particle_locations (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, R_in, bar_rect, z_coord, add_orient = True)
Definition at line 270 of file problem_setup.py.
 def particle_locations(inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, R_in, bar_rect, z_coord, add_orient = True):
   np.random.seed(30)
   sim_inp_dir = str(inp_dir)
   """Generate particle location data"""
   particles = []
   points = []
   method_to_use = 0
   if method_to_use == 0:
     N1 = 40
     N2 = 10
     pcount = 0
     count = 0
     while pcount < N2 and count < 100*N2:
       if count%N2 == 0:
         print('large particle iter = ', count)
       # random radius and center location
       r = R2 + np.random.uniform(-0.1 * R2, 0.1 * R2)
       x = center[0] + np.random.uniform(-R_in + R2 + padding, R_in - R2- padding)
       y = np.random.uniform(-R_in + R2+padding, max_y - R2-padding)
       p_zone = np.random.choice(id_choices2, size=1)[0]
       p = [p_zone, x, y, center[2], r]
       # check if it collides of existing particles
       pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
       if pintersect == False:
         particles.append(p)
         pcount += 1
       count +=1
     pcount = 0
     count = 0
     while pcount < N1 and count < 100*N1:
       if count%N1 == 0:
         print('small particle iter = ', count)
       # random radius and center location
       r = R1 + np.random.uniform(-0.1 * R1, 0.1 * R1)
       x = center[0] + np.random.uniform(-R_in + R1 + padding, R_in - R1- padding)
       y = np.random.uniform(-R_in + R1 + padding, max_y - R1 - padding)
       p_zone = np.random.choice(id_choices1, size=1)[0]
       p = [p_zone, x,y,center[2], r]
       # check if it collides of existing particles
       pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
       if pintersect == False:
         particles.append(p)
         pcount += 1
       count +=1
   elif method_to_use == 1:
     Nmax = 50
     # find how approximate number of rows and cols we can have
     check_r = R1
     if R1 > R2:
       check_r = R2
     rows = int(R_in / check_r)
     cols = int(R_in / check_r)
     rads = [R1, R2]
     counter = 0
     x_old = -R_in
     x_old_right = R_in
     y_old = -R_in
     pad = padding
     cx = 0.
     cy = 0.
     cz = z_coord
     r = 0.
     row_rads = []
     row_rads.append(R1)
     row_rads.append(R2)
     for i in range(rows):
       if i > 0:
         y_old = cy + get_max(row_rads)
       # reset
       row_rads = []
       row_rads.append(R1)
       row_rads.append(R2)
       num_p_cols = 0
       j = 0
       while num_p_cols < cols - 1 and j < Nmax:
         if j == 0:
           # for odd row, take x_old as first and for even take as last
           x_old = -R_in
           x_old_right = R_in
         # ptype = counter % 2
         p_type = 0 # 1 or 2
         p_index = 0 # zone this particle it belongs
         if np.random.uniform(0., 1.) < 0.7:
           p_type = 0
           p_index = np.random.choice(id_choices1, size=1)[0]
         else:
           p_type = 1
           p_index = np.random.choice(id_choices2, size=1)[0]
         r0 = rads[p_type]
         # perturb radius
         r = r0 + np.random.uniform(-0.1 * r0, 0.1 * r0)
         # r = r0
         row_rads.append(r)
         # random horizontal perturbation by 10% of radius
         rph = np.random.uniform(-0.1 * r0, 0.1 * r0)
         cx0 = x_old + pad + r
         cx = cx0 + rph
         # for even row, we start from right edge of rectange
         if i%2 == 0:
           cx0 = x_old_right - pad - r
           cx = cx0 - rph
         cy = y_old + pad + r
         # check if it collides of existing particles
         p = [float(p_index), cx, cy, cz, r]
         pintersect = does_intersect_with_cylindrical_wall(p, particles, R_in, center, bar_rect, padding)
         if pintersect == False:
           particles.append([float(p_index), cx, cy, cz, r])
           # set x_old
           if i % 2 == 0:
             x_old_right = cx - r
           else:
             x_old = cx + r
           counter += 1
           num_p_cols += 1
         j += 1
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   if add_orient:
     inpf.write("i, x, y, z, r, o\n")
     counter = 0
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], np.random.uniform(0., 2.*np.pi)))
       counter += 1
   else:
     inpf.write("i, x, y, z, r\n")
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4]))
   inpf.close()
   # to visualize in paraview
   write_vtu = False
   if write_vtu:
     points = []
     rads = []
     zones = []
     for p in particles:
       points.append([p[1], p[2], p[3]])
       rads.append(p[-1])
       zones.append(int(p[0]))
     points = np.array(points)
     rads = np.array(rads)
     zones = np.array(zones)
     mesh = pv.PolyData(points)
     mesh["radius"] = rads
     mesh["zone"] = zones
     pv.save_meshio(sim_inp_dir + 'particle_locations_' + str(pp_tag) + '.vtu', mesh)
   print('number of particles created = {}'.format(len(particles)))
   return len(particles), particles
References copy_contact_zone(), create_input_file(), does_intersect_with_cylindrical_wall(), generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_tri_particle_gmsh_input(), generate_wall_gmsh_input(), get_E(), get_eff_k(), get_G(), get_max(), get_ref_drum_points(), get_ref_hex_points(), get_ref_triangle_points(), particle_locations(), util::io.print(), print_dbl_list(), write_contact_zone_part(), and write_material_zone_part().
particle_locations() [4/6]
def problem_setup.particle_locations (inp_dir, pp_tag, R1, R2, offset)
Generate particle location data
Definition at line 69 of file problem_setup.py.
 def particle_locations(inp_dir, pp_tag, R1, R2, offset):
   """Generate particle location data"""
   sim_particles = []
   sim_particles.append([0., R1, R1, 0., R1, 0.])
   sim_particles.append([1., R1, 2. * R1 + R2 + offset, 0., R2, np.pi*0.5])
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   inpf.write("i, x, y, z, r, o\n")
   for p in sim_particles:
     inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], p[5]))
   inpf.close()
References particle_locations().
particle_locations() [5/6]
def problem_setup.particle_locations (inp_dir, pp_tag, R1, R2, offset, w1_rect_five_format, w2_rect_five_format)
Generate particle location data
Definition at line 71 of file problem_setup.py.
 def particle_locations(inp_dir, pp_tag, R1, R2, offset, w1_rect_five_format, w2_rect_five_format):
   """Generate particle location data"""
   sim_particles = []
   sim_particles.append([0., R1, R1, 0., R1])
   sim_particles.append([1., R1, 2. * R1 + R2 + offset, 0., R2])
   sim_particles.append([2., w1_rect_five_format[2], w1_rect_five_format[3], w1_rect_five_format[4], w1_rect_five_format[0]])
   sim_particles.append([3., w2_rect_five_format[2], w2_rect_five_format[3], w2_rect_five_format[4], w2_rect_five_format[0]])
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   inpf.write("i, x, y, z, r\n")
   for p in sim_particles:
     inpf.write("%d, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4]))
   inpf.close()
References particle_locations().
particle_locations() [6/6]
def problem_setup.particle_locations (inp_dir, pp_tag, R1, R2, rect, mesh_size, padding, add_orient = True)
Generate particle location data
Definition at line 151 of file problem_setup.py.
 def particle_locations(inp_dir, pp_tag, R1, R2, rect, mesh_size, padding, add_orient = True):
   """Generate particle location data"""
   #
   #
   #   Given rectangle, we want to fill it with particles of R1 and R2 radius
   #   in alternate fashion with padding between each particle
   #
   #
   particles = []
   points = []
   # find how approximate number of rows and cols we can have
   check_r = R1
   if R1 > R2:
     check_r = R2
   rows = int((rect[3] - rect[0])/ check_r)
   cols = int((rect[4] - rect[1])/ check_r)
   rads = [R1, R2]
   counter = 0
   x_old = rect[0]
   x_old_right = rect[3]
   y_old = rect[1]
   pad = padding
   cx = 0.
   cy = 0.
   cz = 0.
   r = 0.
   row_rads = []
   row_rads.append(R1)
   row_rads.append(R2)
   for i in range(rows):
     if i > 0:
       y_old = cy + get_max(row_rads)
     # reset
     row_rads = []
     row_rads.append(R1)
     row_rads.append(R2)
     num_p_cols = 0
     j = 0
     while num_p_cols < cols - 1 and j < 500:
       if j == 0:
         # for odd row, take x_old as first and for even take as last
         x_old = rect[0]
         x_old_right = rect[3]
       # ptype = counter % 2
       ptype = 1
       if np.random.uniform(0., 1.) < 0.7:
         ptype = 0
       r0 = rads[ptype]
       # perturb radius
       r = r0 + np.random.uniform(-0.1 * r0, 0.1 * r0)
       # r = r0
       row_rads.append(r)
       # random horizontal perturbation by 10% of radius
       rph = np.random.uniform(-0.1 * r0, 0.1 * r0)
       cx0 = x_old + pad + r
       cx = cx0 + rph
       # for even row, we start from right edge of rectange
       if i%2 == 0:
         cx0 = x_old_right - pad - r
         cx = cx0 - rph
       cy = y_old + pad + r
       cz = rect[2]
       inters = does_intersect_rect([cx, cy, cz], r, particles, pad, rect)
       inters_parts = does_intersect
       if inters == False:
         particles.append([float(ptype), cx, cy, cz, r])
         # set x_old
         if i % 2 == 0:
             x_old_right = cx - r
         else:
             x_old = cx + r
         counter += 1
         num_p_cols += 1
       j += 1
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   if add_orient:
     inpf.write("i, x, y, z, r, o\n")
     counter = 0
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], np.random.uniform(0., 2.*np.pi)))
       counter += 1
   else:
     inpf.write("i, x, y, z, r\n")
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4]))
   inpf.close()
   # for p in particles:
   #   points.append([p[1], p[2], p[3]])
   # points = np.array(points)
   # mesh = pv.PolyData(points)
   # pv.save_meshio('particle_locations_' + str(pp_tag) + '.vtu', mesh)
   print('number of particles created = {}'.format(len(particles)))
References does_intersect_rect(), generate_cir_particle_gmsh_input(), generate_hex_particle_gmsh_input(), get_max(), get_ref_hex_points(), particle_locations(), and util::io.print().
particle_locations_old()
def problem_setup.particle_locations_old (inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, N1, N2, rect, z_coord, add_orient = True)
Generate particle location data
Definition at line 547 of file problem_setup.py.
 def particle_locations_old(inp_dir, pp_tag, center, padding, max_y, mesh_size, R1, R2, id_choices1, id_choices2, N1, N2, rect, z_coord, add_orient = True):
   """Generate particle location data"""
   def does_intersect_old(p, r, R, particles, padding):
     for q in particles:
       pq = np.array([p[i] - q[i] for i in range(3)])
       if np.linalg.norm(pq) <= r + R + padding:
         return True
     return False
   def does_intersect_rect_old(p, r, particles, padding, rect):
     # check intersection with rectangle
     pr = [p[0] - r, p[1] - r, p[2], p[0] + r, p[1] + r, p[2]]
     if pr[0] < rect[0] + padding or pr[1] < rect[1] + padding or pr[3] > rect[3] - padding or pr[4] > rect[4] - padding:
       # print('circle (xc = {}, r = {:5.3e}) intersects rect = {} with pad = {:5.3e}'.format(p, r, rect, padding))
       return True
     # loop over particles
     # for pi in particles:
     #   dx = [p[0] - pi[1], p[1] - pi[2], p[2] - pi[3]]
     #   rR = r + pi[4] + padding
     #   if np.linalg.norm(dx) < rR:
     #     return True
     # print('circle (xc = {}, r = {:5.3e}) does not intersects rect = {} with pad = {:5.3e}'.format(p, r, rect, padding))
     return False
   #
   #
   #   Given rectangle, we want to fill it with particles of R1 and R2 radius
   #   in alternate fashion with padding between each particle
   #
   #
   particles = []
   points = []
   # find how approximate number of rows and cols we can have
   check_r = R1
   if R1 > R2:
     check_r = R2
   rows = int((rect[3] - rect[0])/ check_r)
   cols = int((rect[4] - rect[1])/ check_r)
   rads = [R1, R2]
   counter = 0
   x_old = rect[0]
   x_old_right = rect[3]
   y_old = rect[1]
   pad = padding
   cx = 0.
   cy = 0.
   cz = 0.
   r = 0.
   row_rads = []
   row_rads.append(R1)
   row_rads.append(R2)
   for i in range(rows):
     if i > 0:
       y_old = cy + get_max(row_rads)
     # reset
     row_rads = []
     row_rads.append(R1)
     row_rads.append(R2)
     num_p_cols = 0
     j = 0
     while num_p_cols < cols - 1 and j < 500:
       if j == 0:
         # for odd row, take x_old as first and for even take as last
         x_old = rect[0]
         x_old_right = rect[3]
       # type of particle (type 1 or 2, e.g., small or large)
       p_type = counter % 2
       r0 = rads[p_type]
       # zone this particle belongs to
       p_zone = 0
       if p_type == 0:
         p_zone = np.random.choice(id_choices1, size=1)[0]
       else:
         p_zone = np.random.choice(id_choices2, size=1)[0]
       # perturb radius
       r = r0 + np.random.uniform(-0.1 * r0, 0.1 * r0)
       # r = r0
       row_rads.append(r)
       # random horizontal perturbation by 10% of radius
       rph = np.random.uniform(-0.1 * r0, 0.1 * r0)
       cx0 = x_old + pad + r
       cx = cx0 + rph
       # for even row, we start from right edge of rectange
       if i%2 == 0:
         cx0 = x_old_right - pad - r
         cx = cx0 - rph
       cy = y_old + pad + r
       cz = rect[2]
       inters = does_intersect_rect_old([cx, cy, cz], r, particles, pad, rect)
       inters_parts = does_intersect_old
       if inters == False:
         particles.append([float(p_zone), cx, cy, cz, r])
         # set x_old
         if i % 2 == 0:
           x_old_right = cx - r
         else:
           x_old = cx + r
         counter += 1
         num_p_cols += 1
       j += 1
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   if add_orient:
     inpf.write("i, x, y, z, r, o\n")
     counter = 0
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], np.random.uniform(0., 2.*np.pi)))
       counter += 1
   else:
     inpf.write("i, x, y, z, r\n")
     for p in particles:
       inpf.write("%d, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4]))
   inpf.close()
   # to visualize in paraview
   write_vtu = False
   if write_vtu:
     points = []
     rads = []
     zones = []
     for p in particles:
       points.append([p[1], p[2], p[3]])
       rads.append(p[-1])
       zones.append(int(p[0]))
     points = np.array(points)
     rads = np.array(rads)
     zones = np.array(zones)
     mesh = pv.PolyData(points)
     mesh["radius"] = rads
     mesh["zone"] = zones
     pv.save_meshio(sim_inp_dir + 'particle_locations_' + str(pp_tag) + '.vtu', mesh)
   print('number of particles created = {}'.format(len(particles)))
   return len(particles), particles
References generate_cir_particle_gmsh_input(), generate_drum2d_particle_gmsh_input(), generate_hex_particle_gmsh_input(), generate_rect_container_gmsh_input(), generate_tri_particle_gmsh_input(), get_center(), get_max(), get_ref_drum_points(), get_ref_hex_points(), get_ref_rect_points(), get_ref_triangle_points(), util::io.print(), write_line_geo(), and write_point_geo().
particle_locations_orient() [1/2]
def problem_setup.particle_locations_orient (inp_dir, pp_tag, R1, R2, offset)
Generate particle location data
Definition at line 83 of file problem_setup.py.
 def particle_locations_orient(inp_dir, pp_tag, R1, R2, offset):
   """Generate particle location data"""
   sim_particles = []
   sim_particles.append([0., R1, R1, 0., R1, 0.5*np.pi])
   sim_particles.append([1., R1+1.*R1*np.sin(np.pi/3.), 2. * R1 + R2 + offset, 0., R2, 0.5*np.pi])
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   inpf.write("i, x, y, z, r, o\n")
   for p in sim_particles:
     inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], p[5]))
   inpf.close()
References get_ref_drum_points(), and rotate().
Referenced by generate_drum_particle_gmsh_input(), generate_wall_gmsh_input(), and particle_locations_orient().
particle_locations_orient() [2/2]
def problem_setup.particle_locations_orient (inp_dir, pp_tag, R1, R2, offset, w1_rect_five_format, w2_rect_five_format)
Generate particle location data
Definition at line 88 of file problem_setup.py.
 def particle_locations_orient(inp_dir, pp_tag, R1, R2, offset, w1_rect_five_format, w2_rect_five_format):
   """Generate particle location data"""
   sim_particles = []
   sim_particles.append([0., R1, R1, 0., R1, 0.5*np.pi])
   sim_particles.append([1., R1+1.*R1*np.sin(np.pi/3.), 2. * R1 + R2 + offset, 0., R2, 0.3*np.pi])
   sim_particles.append([2., w1_rect_five_format[2], w1_rect_five_format[3], w1_rect_five_format[4], w1_rect_five_format[0], 0.])
   sim_particles.append([3., w2_rect_five_format[2], w2_rect_five_format[3], w2_rect_five_format[4], w2_rect_five_format[0], 0.])
   inpf = open(inp_dir + 'particle_locations_' + str(pp_tag) + '.csv','w')
   inpf.write("i, x, y, z, r, o\n")
   for p in sim_particles:
     inpf.write("%d, %Lf, %Lf, %Lf, %Lf, %Lf\n" % (int(p[0]), p[1], p[2], p[3], p[4], p[5]))
   inpf.close()
References create_input_file(), generate_particle_gmsh_input(), generate_wall_gmsh_input(), get_E(), get_eff_k(), get_G(), get_ref_drum_points(), particle_locations_orient(), util::io.print(), print_dbl_list(), rect_to_five_param(), and rotate().
print_bool()
def problem_setup.print_bool (arg, prefix = "")
Definition at line 7 of file problem_setup.py.
 def print_bool(arg, prefix = ""):
   str = prefix
   if arg == True:
     str += "True\n"
   else:
     str += "False\n"
   return str
print_dbl()
def problem_setup.print_dbl (arg, prefix = "")
Definition at line 16 of file problem_setup.py.
 def print_dbl(arg, prefix = ""):
   str = prefix + "%4.6e\n" % (arg)
   return str
print_dbl_list()
def problem_setup.print_dbl_list (arg, prefix = "")
Definition at line 25 of file problem_setup.py.
 def print_dbl_list(arg, prefix = ""):
   str = prefix + "["
   N = len(arg)
   for i in range(N):
     str += "%4.6e" % (arg[i])
     if i < N - 1:
       str += ", "
     else:
       str += "]\n"
   return str
Referenced by create_input_file(), generate_cylindrical_wall_gmsh_input(), generate_drum_particle_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_moving_wall_gmsh_input(), generate_particle_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), generate_wall_gmsh_input(), particle_locations(), and particle_locations_orient().
print_int()
def problem_setup.print_int (arg, prefix = "")
Definition at line 21 of file problem_setup.py.
 def print_int(arg, prefix = ""):
   str = prefix + "%d\n" % (arg)
   return str
print_int_list()
def problem_setup.print_int_list (arg, prefix = "")
Definition at line 37 of file problem_setup.py.
 def print_int_list(arg, prefix = ""):
   str = prefix + "["
   N = len(arg)
   for i in range(N):
     str += "%d" % (arg[i])
     if i < N - 1:
       str += ", "
     else:
       str += "]\n"
   return str
Referenced by copy_contact_zone(), serialize_matrix_list(), and write_cir_line_geo().
rect_to_five_param()
def problem_setup.rect_to_five_param (r)
Definition at line 68 of file problem_setup.py.
 def rect_to_five_param(r):
   return [r[3] - r[0], r[4] - r[1], 0.5*(r[0] + r[3]), 0.5*(r[1] + r[4]), 0.5*(r[2] + r[5])]
Referenced by particle_locations_orient().
rotate()
def problem_setup.rotate (p, theta, axis)
Definition at line 152 of file problem_setup.py.
 def rotate(p, theta, axis):
   p_np = np.array(p)
   axis_np = np.array(axis)
   ct = np.cos(theta);
   st = np.sin(theta);
   # dot
   p_dot_n = np.dot(p_np,axis_np)
   # cross
   n_cross_p = np.cross(axis_np, p_np)
   return (1. - ct) * p_dot_n * axis_np + ct * p_np + st * n_cross_p
Referenced by copy_contact_zone(), does_intersect(), get_center(), get_ref_drum_points(), get_ref_hex_points(), get_ref_rect_points(), particle_locations_orient(), and write_cir_line_geo().
serialize_matrix_list()
def problem_setup.serialize_matrix_list (p)
Definition at line 49 of file problem_setup.py.
 def serialize_matrix_list(p):
   s = []
   for q in p:
     for w in q:
       s.append(w)
   return s
References copy_contact_zone(), get_circ_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), get_E(), get_eff_k(), get_G(), get_max(), get_tri_protrusion_points_for_rectangle_wall_with_protrusion_and_opening(), print_int_list(), write_cir_line_geo(), write_contact_zone_part(), write_line_geo(), write_material_zone_part(), and write_point_geo().
Referenced by generate_rect_container_gmsh_input().
write_cir_line_geo()
def problem_setup.write_cir_line_geo (geof, l_id, p1_id, p2_id, p3_id)
Definition at line 87 of file problem_setup.py.
 def write_cir_line_geo(geof, l_id, p1_id, p2_id, p3_id):
     geof.write("Circle(%d) = {%d, %d, %d};\n" % (l_id, p1_id, p2_id, p3_id))
     return l_id + 1
References copy_contact_zone(), get_E(), get_eff_k(), get_G(), get_max(), print_int_list(), rotate(), write_contact_zone_part(), and write_material_zone_part().
Referenced by generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), and serialize_matrix_list().
write_contact_zone_part()
def problem_setup.write_contact_zone_part (inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, zone_string, Kn)
Definition at line 108 of file problem_setup.py.
 def write_contact_zone_part(inpf, R_contact_factor, damping_active, friction_active, beta_n_eps, friction_coeff, Kn_factor, beta_n_factor, zone_string, Kn):
   inpf.write("  Zone_%s:\n" % (zone_string))
   inpf.write("    Contact_Radius_Factor: %4.6e\n" % (R_contact_factor))
   if damping_active == False:
     inpf.write("    Damping_On: false\n")
   if friction_active == False:
     inpf.write("    Friction_On: false\n")
   inpf.write("    Kn: %4.6e\n" % (Kn))
   inpf.write("    Epsilon: %4.6e\n" % (beta_n_eps))
   inpf.write("    Friction_Coeff: %4.6e\n" % (friction_coeff))
   inpf.write("    Kn_Factor: %4.6e\n" % (Kn_factor))
   inpf.write("    Beta_n_Factor: %4.6e\n" % (beta_n_factor))
Referenced by create_input_file(), generate_cylindrical_wall_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), particle_locations(), serialize_matrix_list(), and write_cir_line_geo().
write_line_geo()
def problem_setup.write_line_geo (geof, l_id, p1_id, p2_id)
Definition at line 83 of file problem_setup.py.
 def write_line_geo(geof, l_id, p1_id, p2_id):
     geof.write("Line(%d) = {%d, %d};\n" % (l_id, p1_id, p2_id))
     return l_id + 1
Referenced by generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), particle_locations_old(), and serialize_matrix_list().
write_material_zone_part()
def problem_setup.write_material_zone_part (inpf, zone_string, horizon, rho, K, G, Gc)
Definition at line 123 of file problem_setup.py.
 def write_material_zone_part(inpf, zone_string, horizon, rho, K, G, Gc):
   inpf.write("  Zone_%s:\n" % (zone_string))
   inpf.write("    Type: PDState\n")
   inpf.write("    Horizon: %4.6e\n" % (horizon))
   inpf.write("    Density: %4.6e\n" % (rho))
   inpf.write("    Compute_From_Classical: true\n")
   inpf.write("    K: %4.6e\n" % (K))
   inpf.write("    G: %4.6e\n" % (G))
   inpf.write("    Gc: %4.6e\n" % (Gc))
   inpf.write("    Influence_Function:\n")
   inpf.write("      Type: 1\n")
Referenced by create_input_file(), generate_cylindrical_wall_gmsh_input(), generate_moving_rect_wall_gmsh_input(), generate_rect_container_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), particle_locations(), serialize_matrix_list(), and write_cir_line_geo().
write_point_geo()
def problem_setup.write_point_geo (geof, p_id, x, h)
Definition at line 79 of file problem_setup.py.
 def write_point_geo(geof, p_id, x, h):
     geof.write("Point(%d) = {%4.6e, %4.6e, %4.6e, %4.6e};\n" % (p_id, x[0], x[1], x[2], h))
     return p_id + 1
Referenced by generate_rect_container_gmsh_input(), generate_rect_floor_gmsh_input(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type2(), generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), particle_locations_old(), and serialize_matrix_list().
Variable Documentation
inp_dir
string problem_setup.inp_dir = './'
----------------------------------------------------—## ----------------------------------------------------—##
Definition at line 1219 of file problem_setup.py.
pp_tag
int problem_setup.pp_tag = 0
Definition at line 1220 of file problem_setup.py.