PeriDEM: util::methods Namespace Reference
util::methods Namespace Reference
Provides fast methods to add/subtract list of data, to find maximum/minimum from list of data.
Functions
template<typename T >
size_t maxIndex (const std::vector< T > &data)
Returns the index corresponding to maximum from list of data.
template<typename T >
size_t minIndex (const std::vector< T > &data)
Returns the index corresponding to minimum from list of data.
template<typename T >
T max (const std::vector< T > &data)
Returns the maximum from list of data.
template<typename T >
T min (const std::vector< T > &data)
Returns the minimim from list of data.
template<typename T >
std::pair< size_t, T > maxAndMaxIndex (const std::vector< T > &data)
Returns the maximum and index of maximum from list of data.
template<typename T >
std::pair< size_t, T > minAndMinIndex (const std::vector< T > &data)
Returns the minimum and index of minimum from list of data.
template<typename T >
size_t maxIndex (const std::vector< T > &data, size_t data_start, size_t data_end)
Returns the index corresponding to maximum from list of data.
size_t maxLengthIndex (const std::vector< util::Point > &data)
Returns the index that has maximum length of point from list of points.
size_t minLengthIndex (const std::vector< util::Point > &data)
Returns the index that has minimum length of point from list of points.
double maxLength (const std::vector< util::Point > &data)
Returns the maximum length of point from list of points.
double minLength (const std::vector< util::Point > &data)
Returns the minimum length of point from list of points.
std::pair< double, size_t > maxLengthAndMaxLengthIndex (const std::vector< util::Point > &data)
Returns the maximum length of point and index from list of points.
std::pair< double, size_t > minLengthAndMinLengthIndex (const std::vector< util::Point > &data)
Returns the minimum length of point and index from list of points.
template<typename T >
T add (const std::vector< T > &data)
Returns the sum of data.
bool isFree (const int &i, const unsigned int &dof)
Returns true if degree of freedom is free.
bool isFree (const uint8_t &i, const unsigned int &dof)
Returns true if degree of freedom is free.
template<typename T >
bool isInList (const T &i, const std::vector< T > &list)
Find if data is in the list.
bool isTagInList (const std::string &tag, const std::vector< std::string > &tags)
Returns true if tag is found in the list of tags.
template<typename T >
void addToList (const T &i, std::vector< T > &list)
Add element to the list.
float timeDiff (std::chrono::steady_clock::time_point begin, std::chrono::steady_clock::time_point end, std::string unit="microseconds")
Returns difference between two times.
template<typename T_out >
T_out getKeyData (std::string key, std::map< std::string, T_out > &data_map, bool issue_err=false)
Get data for a key.
template<typename T_out >
void appendKeyData (std::string key, T_out data, std::map< std::string, T_out > &data_map, bool issue_err=false)
Append value to data associated with key.
template<typename T_out >
void setKeyData (std::string key, T_out data, std::map< std::string, T_out > &data_map, bool issue_err=false)
Set value to data associated with key.
Detailed Description
Provides fast methods to add/subtract list of data, to find maximum/minimum from list of data.
Function Documentation
add()
template<typename T > T util::methods::add (const std::vector< T > & data) inline
Returns the sum of data.
Parameters
data List of real numbers
Returns
value Sum of the numbers
Definition at line 238 of file methods.h.
{
  return std::reduce(data.begin(), data.end());
};
addToList()
template<typename T > void util::methods::addToList (const T & i, std::vector< T > & list) inline
Add element to the list.
Parameters
i Item to add
list Vector of elements
Definition at line 289 of file methods.h.
{
  for (const auto &j : list)
    if (j == i)
      return;
  list.emplace_back(i);
};
appendKeyData()
template<typename T_out > void util::methods::appendKeyData (std::string key, T_out data, std::map< std::string, T_out > & data_map, bool issue_err = false) inline
Append value to data associated with key.
Parameters
key Key to append the data to
Definition at line 344 of file methods.h.
{
  if (data_map.find(key) == data_map.end()) {
    if (issue_err) {
      std::cerr << "Error: key = " << key << " does not exist in data map.\n";
      exit(EXIT_FAILURE);
    }
    else {
      data_map[key] = data;
    }
  }
  else {
    data_map[key] = data_map[key] + data;
  }
};
getKeyData()
template<typename T_out > T_out util::methods::getKeyData (std::string key, std::map< std::string, T_out > & data_map, bool issue_err = false) inline
Get data for a key.
Parameters
key Key to access the data
Returns
data Value of data
Definition at line 325 of file methods.h.
{
  if (issue_err) {
    if (data_map.find(key) == data_map.end()) {
      std::cerr << "Error: key = " << key << " does not exist in data map.\n";
      exit(EXIT_FAILURE);
    }
  }
  return data_map[key];
};
isFree() [1/2]
bool util::methods::isFree (const int & i, const unsigned int & dof) inline
Returns true if degree of freedom is free.
Parameters
i Fixity value
dof Degree of freedom to probe (dof = 0 for x, dof = 1 for y, and dof = 2 for z)
Returns
True True if dof is free
Definition at line 249 of file methods.h.
{
      return !(i >> dof & 1UL);
};
Referenced by model::DEMModel::init().
isFree() [2/2]
bool util::methods::isFree (const uint8_t & i, const unsigned int & dof) inline
Returns true if degree of freedom is free.
Parameters
i Fixity value
dof Degree of freedom to probe (dof = 0 for x, dof = 1 for y, and dof = 2 for z)
Returns
True True if dof is free
Definition at line 254 of file methods.h.
{
      return !(i >> dof & 1UL);
};
isInList()
template<typename T > bool util::methods::isInList (const T & i, const std::vector< T > & list) inline
Find if data is in the list.
Parameters
tag Tag to search
tags List of tags
Returns
True True if tag exists
Definition at line 265 of file methods.h.
{
      for (const auto &j : list)
        if (j == i)
          return true;
      return false;
};
Referenced by util::geometry::isNumberOfParamForGeometryValid(), and isTagInList().
isTagInList()
bool util::methods::isTagInList (const std::string & tag, const std::vector< std::string > & tags) inline
Returns true if tag is found in the list of tags.
Parameters
tag Tag to search
tags List of tags
Returns
True True if tag exists
Definition at line 279 of file methods.h.
{
  return isInList(tag, tags);
};
References isInList().
Referenced by rw::writer::VtkParticleWriter::appendNodes(), model::DEMModel::createGeometryAtSite(), util::geometry::createGeomObjectOld(), model::DEMModel::output(), inp::Input::setParticleDeck(), model::DEMModel::setupQuadratureData(), and model::DEMModel::updateGeometryObjectsPostInit().
max()
template<typename T > T util::methods::max (const std::vector< T > & data) inline
Returns the maximum from list of data.
Parameters
data List of real numbers
Returns
value Maximum value
Definition at line 74 of file methods.h.
{
      return data[util::methods::maxIndex(data)];
};
References maxIndex().
Referenced by model::DEMModel::init(), and model::DEMModel::updateContactNeighborSearchParameters().
maxAndMaxIndex()
template<typename T > std::pair< size_t, T > util::methods::maxAndMaxIndex (const std::vector< T > & data) inline
Returns the maximum and index of maximum from list of data.
Parameters
data List of real numbers
Returns
pair Maximum value and index
Definition at line 94 of file methods.h.
{
      auto i = util::methods::maxIndex(data);
      return {data[i], i};
};
References maxIndex().
maxIndex() [1/2]
template<typename T > size_t util::methods::maxIndex (const std::vector< T > & data) inline
Returns the index corresponding to maximum from list of data.
Parameters
data List of real numbers
Returns
i Index with a maximum value
Definition at line 38 of file methods.h.
{
      // initialize original index locations
      std::vector<size_t> idx(data.size());
      std::iota(idx.begin(), idx.end(), 0);
      std::stable_sort(idx.begin(), idx.end(),
                       [&data](size_t i1, size_t i2) {return data[i1] > data[i2];});
      return idx[0];
};
Referenced by util::geometry::ComplexGeomObject::center(), max(), maxAndMaxIndex(), maxLength(), maxLengthAndMaxLengthIndex(), maxLengthIndex(), and model::DEMModel::updateContactNeighborSearchParameters().
maxIndex() [2/2]
template<typename T > size_t util::methods::maxIndex (const std::vector< T > & data, size_t data_start, size_t data_end) inline
Returns the index corresponding to maximum from list of data.
Parameters
data List of real numbers
Returns
i Index with a maximum value
Definition at line 117 of file methods.h.
{
  if (data.size() == 0) {
    std::cerr << "Error: maxIndex() is called with data of size " << data.size()
              << ".\n";
    exit(EXIT_FAILURE);
  }
  if (data_end == 0 or data_end > data.size()) {
    std::cerr << "Error: maxIndex() data_end = " << data_end
              << " is not valid for the data of size " << data.size()
              << ".\n";
    exit(EXIT_FAILURE);
  }
  if (data_start > data.size() - 1) {
    std::cerr << "Error: maxIndex() data_start = " << data_start
              << " is not valid for the data of size " << data.size()
              << ".\n";
    exit(EXIT_FAILURE);
  }
  // initialize original index locations
  std::vector<size_t> idx(data_end - data_start);
  std::iota(idx.begin(), idx.end() , 0);
  std::stable_sort(idx.begin(), idx.end(),
                   [&data, &data_start](size_t i1, size_t i2)
                   {return data[i1 + data_start] > data[i2 + data_start];});
  return idx[0] + data_start;
};
maxLength()
double util::methods::maxLength (const std::vector< util::Point > & data) inline
Returns the maximum length of point from list of points.
Parameters
data List of points
Returns
value Maximum length of point
Definition at line 182 of file methods.h.
{
      std::vector<double> length_data(data.size());
      for (size_t i = 0; i < data.size(); i++)
        length_data[i] = data[i].length();
      return length_data[util::methods::maxIndex(length_data)];
};
References maxIndex().
maxLengthAndMaxLengthIndex()
std::pair< double, size_t > util::methods::maxLengthAndMaxLengthIndex (const std::vector< util::Point > & data) inline
Returns the maximum length of point and index from list of points.
Parameters
data List of points
Returns
pair Maximum length of point and index
Definition at line 208 of file methods.h.
{
      std::vector<double> length_data(data.size());
      for (size_t i = 0; i < data.size(); i++)
        length_data[i] = data[i].length();
      auto i = util::methods::maxIndex(length_data);
      return {length_data[i], i};
};
References maxIndex().
Referenced by model::DEMModel::checkStop().
maxLengthIndex()
size_t util::methods::maxLengthIndex (const std::vector< util::Point > & data) inline
Returns the index that has maximum length of point from list of points.
Parameters
data List of points
Returns
i Index with maximum length of point
Definition at line 156 of file methods.h.
{
      std::vector<double> length_data(data.size());
      for (size_t i = 0; i < data.size(); i++)
        length_data[i] = data[i].length();
      return util::methods::maxIndex(length_data);
};
References maxIndex().
min()
template<typename T > T util::methods::min (const std::vector< T > & data) inline
Returns the minimim from list of data.
Parameters
data List of real numbers
Returns
value Minimum value
Definition at line 84 of file methods.h.
{
      return data[util::methods::minIndex(data)];
};
References minIndex().
minAndMinIndex()
template<typename T > std::pair< size_t, T > util::methods::minAndMinIndex (const std::vector< T > & data) inline
Returns the minimum and index of minimum from list of data.
Parameters
data List of real numbers
Returns
pair Minimum value and index
Definition at line 105 of file methods.h.
{
      auto i = util::methods::minIndex(data);
      return {data[i], i};
};
References minIndex().
minIndex()
template<typename T > size_t util::methods::minIndex (const std::vector< T > & data) inline
Returns the index corresponding to minimum from list of data.
Parameters
data List of real numbers
Returns
i Index with a minimum value
Definition at line 56 of file methods.h.
{
      // initialize original index locations
      std::vector<size_t> idx(data.size());
      std::iota(idx.begin(), idx.end(), 0);
      std::stable_sort(idx.begin(), idx.end(),
                       [&data](size_t i1, size_t i2) {return data[i1] < data[i2];});
      return idx[0];
};
Referenced by min(), minAndMinIndex(), minLength(), minLengthAndMinLengthIndex(), and minLengthIndex().
minLength()
double util::methods::minLength (const std::vector< util::Point > & data) inline
Returns the minimum length of point from list of points.
Parameters
data List of points
Returns
value Minimum length of point
Definition at line 195 of file methods.h.
{
      std::vector<double> length_data(data.size());
      for (size_t i = 0; i < data.size(); i++)
        length_data[i] = data[i].length();
      return length_data[util::methods::minIndex(length_data)];
};
References minIndex().
minLengthAndMinLengthIndex()
std::pair< double, size_t > util::methods::minLengthAndMinLengthIndex (const std::vector< util::Point > & data) inline
Returns the minimum length of point and index from list of points.
Parameters
data List of points
Returns
pair Minimum length of point and index
Definition at line 222 of file methods.h.
{
      std::vector<double> length_data(data.size());
      for (size_t i = 0; i < data.size(); i++)
        length_data[i] = data[i].length();
      auto i = util::methods::minIndex(length_data);
      return {length_data[i], i};
};
References minIndex().
minLengthIndex()
size_t util::methods::minLengthIndex (const std::vector< util::Point > & data) inline
Returns the index that has minimum length of point from list of points.
Parameters
data List of points
Returns
i Index with minimum length of point
Definition at line 169 of file methods.h.
{
  std::vector<double> length_data(data.size());
  for (size_t i = 0; i < data.size(); i++)
    length_data[i] = data[i].length();
  return util::methods::minIndex(length_data);
};
References minIndex().
setKeyData()
template<typename T_out > void util::methods::setKeyData (std::string key, T_out data, std::map< std::string, T_out > & data_map, bool issue_err = false) inline
Set value to data associated with key.
Parameters
key Key to append the data to
Definition at line 366 of file methods.h.
{
  if (data_map.find(key) == data_map.end()) {
    if (issue_err) {
      std::cerr << "Error: key = " << key << " does not exist in data map.\n";
      exit(EXIT_FAILURE);
    }
  }
  data_map[key] = data;
};
timeDiff()
float util::methods::timeDiff (std::chrono::steady_clock::time_point begin, std::chrono::steady_clock::time_point end, std::string unit = "microseconds") inline
Returns difference between two times.
Parameters
begin Beginning time
end Ending time
unit Unit in which time difference is to be returned
Returns
time Time difference
Definition at line 304 of file methods.h.
{
      if (unit == "microseconds")
        return std::chrono::duration_cast<std::chrono::microseconds>(end - begin).count();
      else if (unit == "milliseconds")
        return std::chrono::duration_cast<std::chrono::milliseconds>(end - begin).count();
      else if (unit == "seconds")
        return std::chrono::duration_cast<std::chrono::seconds>(end - begin).count();
      else {
        std::cerr << "Unit = " << unit << " not valid.\n";
        exit(EXIT_FAILURE);
      }
};
Referenced by model::DEMModel::computeForces(), peridynamics::Model::computeForces(), model::DEMModel::init(), model::DEMModel::integrate(), twoparticle_demo::Model::integrate(), main(), fe::metisGraphPartition(), nsearch::NFlannSearchKd< dim >::setInputCloud(), test::testGraphPartitioning(), test::testPeriDEM(), test::testTaskflow(), and test::testTriElemTime().