PeriDEM: util::io Namespace Reference
util::io Namespace Reference
Provides geometrical methods such as point inside rectangle.
Data Structures
class InputParser
Input command line argument parser.
class Logger
Prints log to std::cout and also write to the file.
struct LoggerDeck
Deck to store log parameters.
Functions
std::string getTabS (int nt)
Returns tab spaces of given size.
template<class T >
std::string printStr (const T &msg, int nt=print_default_tab)
Returns formatted string for output.
template<class T >
std::string printStr (const std::vector< T > &list, int nt=print_default_tab)
Returns formatted string for output.
template<>
std::string printStr (const std::vector< util::Point > &list, int nt)
Returns formatted string for output.
template<class T >
void print (const T &msg, int nt=print_default_tab, int printMpiRank=print_default_mpi_rank)
Prints formatted information.
template<class T >
void print (const std::vector< T > &list, int nt=print_default_tab, int printMpiRank=print_default_mpi_rank)
Prints formatted information.
template<class T >
std::string printStr (const std::vector< std::vector< T >> &list, int nt=print_default_tab)
Returns formatted string for output.
template<class T >
void print (const std::vector< std::vector< T >> &list, int nt=print_default_tab, int printMpiRank=print_default_mpi_rank)
std::string printBoxStr (const std::pair< util::Point, util::Point > &box, int nt=print_default_tab)
Returns formatted string for output.
void printBox (const std::pair< util::Point, util::Point > &box, int nt=print_default_tab, int printMpiRank=print_default_mpi_rank)
Prints formatted string for output.
std::string printBoxStr (const std::pair< std::vector< double >, std::vector< double >> &box, int nt=print_default_tab)
void printBox (const std::pair< std::vector< double >, std::vector< double >> &box, int nt=print_default_tab, int printMpiRank=print_default_mpi_rank)
void initLogger (int debug_level=logger_default_debug_lvl, std::string filename="")
Initializes the logger.
void log (std::ostringstream &oss, bool screen_out=false, int printMpiRank=print_default_mpi_rank)
Global method to log the message.
void log (const std::string &str, bool screen_out=false, int printMpiRank=print_default_mpi_rank)
Global method to log the message.
std::string getFilenameFromPath (std::string const &path, std::string const &delims="/\\")
Get filename removing path from the string Source - https://stackoverflow.com/a/24386991.
std::string removeExtensionFromFile (std::string const &filename)
Remove extension from the filename Source - https://stackoverflow.com/a/24386991.
std::string getExtensionFromFile (std::string const &filename)
Get extension from the filename.
std::string checkAndCreateNewFilename (std::string const &filename, std::string filename_ext)
Check for extension and if possible create new filename from a given filename and a given extension.
bool isFileEmpty (std::string filename)
Check if file is empty or null.
bool isFileEmpty (std::ifstream &pFile)
Check if file is empty or null.
Variables
const int print_default_tab = 0
Default value of tab used in outputting formatted information.
const int print_default_mpi_rank = 0
Default mpi rank in printing information.
const int logger_default_debug_lvl = 5
Default debug level for logger.
Detailed Description
Provides geometrical methods such as point inside rectangle.
Function Documentation
checkAndCreateNewFilename()
std::string util::io::checkAndCreateNewFilename (std::string const & filename, std::string filename_ext) inline
Check for extension and if possible create new filename from a given filename and a given extension.
Parameters
filename Filename with/without extension
filename_ext Extension to check for and append if needed
Returns
string New filename if successful
Definition at line 443 of file io.h.
 {
   auto f_ext = util::io::getExtensionFromFile(filename);
   std::string f = filename;
   if (f_ext.empty()) {
     f = f + "." + filename_ext;
   }
   else {
     if (f_ext != filename_ext) {
       std::cerr << "checkAndCreateNewFilename(): Argument filename = "
                 << filename << " has extension = "
                 << f_ext << " which does not match expected extension = "
                 << filename_ext << std::endl;
       exit(EXIT_FAILURE);
     }
   }
   return f;
 }
References getExtensionFromFile().
Referenced by rw::writer::MshWriter::MshWriter(), rw::reader::VtkParticleReader::VtkParticleReader(), and rw::reader::VtkReader::VtkReader().
getExtensionFromFile()
std::string util::io::getExtensionFromFile (std::string const & filename) inline
Get extension from the filename.
Parameters
filename Filename with extension
Returns
string Extension
Definition at line 428 of file io.h.
 {
   typename std::string::size_type const p(filename.find_last_of('.'));
   //return filename.substr(p + 1);
   return p > 0 && p != std::string::npos ? filename.substr(p+1) : "";
 }
Referenced by checkAndCreateNewFilename(), fe::Mesh::createData(), and fe::Mesh::readElementData().
getFilenameFromPath()
std::string util::io::getFilenameFromPath (std::string const & path, std::string const & delims = "/\\") inline
Get filename removing path from the string Source - https://stackoverflow.com/a/24386991.
Parameters
path Filename with path
delims Delimiter to separate the filename from the path
Returns
string Filename
Definition at line 404 of file io.h.
 {
   return path.substr(path.find_last_of(delims) + 1);
 }
Referenced by test::testGraphPartitioning(), and test::testMPI().
getTabS()
std::string util::io::getTabS (int nt) inline
Returns tab spaces of given size.
Parameters
nt Number of tabs
Returns
string Tab spaces
Definition at line 40 of file io.h.
{
   std::string tabS = "";
   for (int i = 0; i < nt; i++)
     tabS += "\t";
   return tabS;
 };
Referenced by model::DEMModel::output(), printBoxStr(), inp::PNeighborDeck::printStr(), inp::PICDeck::printStr(), material::BaseInfluenceFn::printStr(), printStr(), inp::Zone::printStr(), inp::MeshDeck::printStr(), fe::QuadData::printStr(), inp::ContactPairDeck::printStr(), geometry::Fracture::printStr(), inp::MatData::printStr(), inp::ParticleDeck::printStr(), inp::PBCData::printStr(), inp::ModelDeck::printStr(), particle::ParticleTransform::printStr(), inp::OutputDeck::printStr(), material::ConstInfluenceFn::printStr(), particle::RefParticle::printStr(), material::LinearInfluenceFn::printStr(), inp::ContactDeck::printStr(), material::Material::printStr(), util::geometry::GeomObject::printStr(), material::GaussianInfluenceFn::printStr(), inp::ParticleZone::printStr(), fe::Mesh::printStr(), util::geometry::NullGeomObject::printStr(), inp::MaterialDeck::printStr(), util::geometry::Line::printStr(), material::RnpMaterial::printStr(), util::geometry::Triangle::printStr(), util::geometry::Square::printStr(), particle::BaseParticle::printStr(), material::PmbMaterial::printStr(), util::geometry::Rectangle::printStr(), material::PdElastic::printStr(), util::geometry::Hexagon::printStr(), util::geometry::Drum2D::printStr(), material::PdState::printStr(), util::geometry::Cube::printStr(), util::geometry::Cuboid::printStr(), util::geometry::Circle::printStr(), util::geometry::Sphere::printStr(), util::geometry::Cylinder::printStr(), util::geometry::AnnulusGeomObject::printStr(), and util::geometry::ComplexGeomObject::printStr().
initLogger()
void util::io::initLogger (int debug_level = logger_default_debug_lvl, std::string filename = "")
Initializes the logger.
Parameters
debug_level Specify debug level/verbosity
filename Specify filename for logs
Definition at line 15 of file io.cpp.
{
   if (logger_p != nullptr)
     return;
   auto deck = new LoggerDeck(debug_level, filename);
   logger_p = new Logger(deck);
 }
References anonymous_namespace{io.cpp}::logger_p.
Referenced by model::DEMModel::DEMModel(), and main().
isFileEmpty() [1/2]
bool util::io::isFileEmpty (std::ifstream & pFile) inline
Check if file is empty or null.
Parameters
pFile File stream
Returns
bool True if file is empty
Definition at line 480 of file io.h.
{
   return pFile.peek() == std::ifstream::traits_type::eof();
 }
isFileEmpty() [2/2]
bool util::io::isFileEmpty (std::string filename) inline
Check if file is empty or null.
Parameters
filename Filename with/without extension
Returns
bool True if file is empty
Definition at line 469 of file io.h.
{
   std::ifstream pFile(filename);
   return pFile.peek() == std::ifstream::traits_type::eof();
 }
Referenced by rw::reader::MshReader::readCells(), rw::reader::MshReader::readMesh(), and rw::reader::MshReader::readNodes().
log() [1/2]
void util::io::log (const std::string & str, bool screen_out = false, int printMpiRank = print_default_mpi_rank)
Global method to log the message.
Parameters
str Message
screen_out Specify if it goes to std::cout as well
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 24 of file io.cpp.
{
   // for now, we do not call assert and rather create a logger if it does not exist
   /*
   //assert((logger_p != nullptr) && "logger_p "
   //                                   "(pointer of type util::io::Logger) is not initialized. "
   //                                   "Call util::io::initLogger(debug_level, log_filename) once at the beginning.");
   */
   if (logger_p == nullptr)
     logger_p = new Logger();
   logger_p->log(str, screen_out, printMpiRank);
 }
References util::io::Logger::log(), and anonymous_namespace{io.cpp}::logger_p.
log() [2/2]
void util::io::log (std::ostringstream & oss, bool screen_out = false, int printMpiRank = print_default_mpi_rank)
Global method to log the message.
Parameters
oss Message
screen_out Specify if it goes to std::cout as well
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 38 of file io.cpp.
{
   // for now, we do not call assert and rather create a logger if it does not exist
   /*
   //assert((logger_p != nullptr) && "logger_p "
   //                                   "(pointer of type util::io::Logger) is not initialized. "
   //                                   "Call util::io::initLogger(debug_level, log_filename) once at the beginning.");
   */
   if (logger_p == nullptr)
     logger_p = new Logger();
   logger_p->log(oss, screen_out, printMpiRank);
 }
References util::io::Logger::log(), anonymous_namespace{io.cpp}::logger_p, and anonymous_namespace{main.cpp}::oss.
Referenced by model::DEMModel::applyInitialCondition(), model::DEMModel::checkStop(), model::DEMModel::computeContactForces(), model::DEMModel::computeExternalDisplacementBC(), model::DEMModel::computeExternalForces(), model::DEMModel::computeForces(), model::DEMModel::computePeridynamicForces(), fe::Mesh::createData(), model::DEMModel::createParticles(), model::DEMModel::createParticlesFromFile(), model::DEMModel::createParticleUsingParticleZoneGeomObject(), model::DEMModel::init(), model::DEMModel::integrate(), model::DEMModel::log(), model::DEMModel::output(), fe::Mesh::readElementData(), model::DEMModel::restart(), and model::DEMModel::setupContact().
print() [1/3]
template<class T > void util::io::print (const std::vector< std::vector< T >> & list, int nt = print_default_tab, int printMpiRank = print_default_mpi_rank) inline
Parameters
list List of objects
nt Number of tabs
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 154 of file io.h.
{
   if (printMpiRank < 0 or util::parallel::mpiRank() == printMpiRank)
     std::cout << printStr(list, nt);
 };
References util::parallel::mpiRank(), and printStr().
print() [2/3]
template<class T > void util::io::print (const std::vector< T > & list, int nt = print_default_tab, int printMpiRank = print_default_mpi_rank) inline
Prints formatted information.
Parameters
list List of objects
nt Number of tabs
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 120 of file io.h.
{
   if (printMpiRank < 0 or util::parallel::mpiRank() == printMpiRank)
       std::cout << printStr(list, nt);
 };
References util::parallel::mpiRank(), and printStr().
print() [3/3]
template<class T > void util::io::print (const T & msg, int nt = print_default_tab, int printMpiRank = print_default_mpi_rank) inline
Prints formatted information.
Parameters
msg Message
nt Number of tabs
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 108 of file io.h.
{
   if (printMpiRank < 0 or util::parallel::mpiRank() == printMpiRank)
     std::cout << printStr(msg, nt);
 };
References util::parallel::mpiRank(), and printStr().
Referenced by fe::Mesh::computeVol(), problem_setup::create_input_file(), discretize_circle::discretize_circle(), problem_setup::does_intersect_with_rectangle_wall_with_protrusion_and_opening(), anonymous_namespace{testParallelCompLib.cpp}::exchangeDispData(), problem_setup::generate_cylindrical_wall_gmsh_input(), problem_setup::generate_rect_container_gmsh_input(), problem_setup::generate_rectangle_with_protrusion_and_opening_wall_gmsh_input_type3(), problem_setup::get_center(), main(), problem_setup::particle_locations(), discretize_circle_dense::print_point(), discretize_circle::print_point(), discretize_circle_equidist::print_point(), test::testMPI(), and test::testTaskflow().
printBox() [1/2]
void util::io::printBox (const std::pair< std::vector< double >, std::vector< double >> & box, int nt = print_default_tab, int printMpiRank = print_default_mpi_rank) inline
Parameters
box Pair of corner points of box
nt Number of tabs to prefix
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 208 of file io.h.
{
   if (printMpiRank < 0 or util::parallel::mpiRank() == printMpiRank)
     std::cout << printBoxStr(box, nt);
 };
References util::parallel::mpiRank(), and printBoxStr().
printBox() [2/2]
void util::io::printBox (const std::pair< util::Point, util::Point > & box, int nt = print_default_tab, int printMpiRank = print_default_mpi_rank) inline
Prints formatted string for output.
Parameters
box Pair of corner points of box
nt Number of tabs to prefix
printMpiRank MPI rank to do log/print. Negative value means all ranks log.
Definition at line 184 of file io.h.
{
     if (printMpiRank < 0 or util::parallel::mpiRank() == printMpiRank)
       std::cout << printBoxStr(box, nt);
 };
References util::parallel::mpiRank(), and printBoxStr().
printBoxStr() [1/2]
std::string util::io::printBoxStr (const std::pair< std::vector< double >, std::vector< double >> & box, int nt = print_default_tab) inline
Parameters
box Pair of corner points of box
nt Number of tabs to prefix
Returns
string Formatted string
Definition at line 193 of file io.h.
{
   auto tabS = getTabS(nt);
   std::ostringstream oss;
   oss << tabS << "Corner point 1 = (" << printStr<double>(box.first, 0)
               << ")" << std::endl;
   oss << tabS << "Corner point 2 = (" << printStr<double>(box.second, 0)
               << ")" << std::endl;
   return oss.str();
 };
References getTabS(), and anonymous_namespace{main.cpp}::oss.
printBoxStr() [2/2]
std::string util::io::printBoxStr (const std::pair< util::Point, util::Point > & box, int nt = print_default_tab) inline
Returns formatted string for output.
Parameters
box Pair of corner points of box
nt Number of tabs to prefix
Returns
string Formatted string
Definition at line 168 of file io.h.
{
   auto tabS = getTabS(nt);
   std::ostringstream oss;
   oss << tabS << "Corner point 1 = " << box.first.printStr(nt, 0) << std::endl;
   oss << tabS << "Corner point 2 = " << box.second.printStr(nt, 0) << std::endl;
   return oss.str();
 };
References getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by printBox(), fe::Mesh::printStr(), util::geometry::Line::printStr(), util::geometry::Square::printStr(), util::geometry::Rectangle::printStr(), util::geometry::Cube::printStr(), util::geometry::Cuboid::printStr(), util::geometry::Circle::printStr(), util::geometry::Sphere::printStr(), util::geometry::Cylinder::printStr(), util::geometry::AnnulusGeomObject::printStr(), and util::geometry::ComplexGeomObject::printStr().
printStr() [1/4]
template<class T > std::string util::io::printStr (const std::vector< std::vector< T >> & list, int nt = print_default_tab) inline
Returns formatted string for output.
Parameters
list List of objects
nt Number of tabs to prefix
Returns
string Formatted string
Definition at line 128 of file io.h.
{
   auto tabS = getTabS(nt);
   std::ostringstream oss;
   oss << tabS;
   size_t i = 0;
   for (auto l : list) {
     oss << "(";
     for (size_t k = 0; k < l.size(); k++) {
       oss << l[k];
       if (k < l.size() - 1)
         oss << ", ";
     }
     oss << ")";
     i++;
     if (i != list.size())
       oss << ", ";
   }
   return oss.str();
 }
References getTabS(), and anonymous_namespace{main.cpp}::oss.
printStr() [2/4]
template<class T > std::string util::io::printStr (const std::vector< T > & list, int nt = print_default_tab) inline
Returns formatted string for output.
Parameters
list List of objects
nt Number of tabs to prefix
Returns
string Formatted string
Definition at line 67 of file io.h.
{
   auto tabS = getTabS(nt);
   std::ostringstream oss;
   oss << tabS;
   size_t i = 0;
   for (auto l : list) {
     oss << l;
     i++;
     if (i != list.size())
       oss << ", ";
   }
   return oss.str();
 };
References getTabS(), and anonymous_namespace{main.cpp}::oss.
printStr() [3/4]
template<> std::string util::io::printStr (const std::vector< util::Point > & list, int nt) inline
Returns formatted string for output.
Parameters
list List of objects
nt Number of tabs to prefix
Returns
string Formatted string
Definition at line 85 of file io.h.
{
   auto tabS = getTabS(nt);
   std::ostringstream oss;
   oss << tabS;
   size_t i = 0;
   for (auto l : list) {
     oss << "(" << l[0] << ", " << l[1] << ", " << l[2] << ")";
     i++;
     if (i != list.size())
       oss << ", ";
   }
   return oss.str();
 };
References getTabS(), and anonymous_namespace{main.cpp}::oss.
printStr() [4/4]
template<class T > std::string util::io::printStr (const T & msg, int nt = print_default_tab) inline
Returns formatted string for output.
Parameters
msg Message
nt Number of tabs to prefix
Returns
string Formatted string
Definition at line 54 of file io.h.
{
   std::ostringstream oss;
   oss << getTabS(nt) << msg;
   return oss.str();
 };
References getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by util::checkMatrix(), fe::Mesh::computeVol(), fe::Mesh::createData(), model::DEMModel::createGeometryAtSite(), util::geometry::createGeomObjectOld(), model::DEMModel::createParticlesFromFile(), main(), model::DEMModel::output(), print(), anonymous_namespace{geomObjects.cpp}::printErrMsg(), inp::Zone::printStr(), fe::QuadData::printStr(), inp::ParticleDeck::printStr(), inp::ParticleZone::printStr(), util::geometry::Triangle::printStr(), util::geometry::Square::printStr(), util::geometry::Rectangle::printStr(), util::geometry::Hexagon::printStr(), util::geometry::Drum2D::printStr(), util::geometry::Cube::printStr(), util::geometry::Cuboid::printStr(), and test::testTetElem().
removeExtensionFromFile()
std::string util::io::removeExtensionFromFile (std::string const & filename) inline
Remove extension from the filename Source - https://stackoverflow.com/a/24386991.
Parameters
filename Filename with extension
Returns
string Filename without extension
Definition at line 416 of file io.h.
 {
   typename std::string::size_type const p(filename.find_last_of('.'));
   return p > 0 && p != std::string::npos ? filename.substr(0, p) : filename;
 }
Referenced by test::testGraphPartitioning(), and test::testMPI().
Variable Documentation
logger_default_debug_lvl
const int util::io::logger_default_debug_lvl = 5
Default debug level for logger.
Definition at line 33 of file io.h.
print_default_mpi_rank
const int util::io::print_default_mpi_rank = 0
Default mpi rank in printing information.
Definition at line 30 of file io.h.
print_default_tab
const int util::io::print_default_tab = 0
Default value of tab used in outputting formatted information.
Definition at line 27 of file io.h.
Referenced by anonymous_namespace{testParallelCompLib.cpp}::exchangeDispData(), and test::testMPI().