PeriDEM: anonymous_namespace{testParallelCompLib.cpp} Namespace Reference
anonymous_namespace{testParallelCompLib.cpp} Namespace Reference
Functions
void printMsg (std::string msg, int mpiRank, int printMpiRank)
double f1 (const double &x)
double f2 (const double &x)
void setupOwnerAndGhost (size_t mpiSize, size_t mpiRank, const std::vector< size_t > &nodePartition, const std::vector< std::vector< size_t >> &nodeNeighs, std::vector< size_t > &ownedNodes, std::vector< size_t > &ownedInternalNodes, std::vector< size_t > &ownedBdryNodes, std::vector< std::pair< std::vector< size_t >, std::vector< size_t >>> &ghostData)
void exchangeDispData (size_t mpiSize, size_t mpiRank, const std::vector< std::pair< std::vector< size_t >, std::vector< size_t >>> &ghostData, std::vector< std::pair< std::vector< util::Point >, std::vector< util::Point >>> &dispGhostData, std::vector< util::Point > &dispNodes)
Function Documentation
exchangeDispData()
void anonymous_namespace{testParallelCompLib.cpp}::exchangeDispData (size_t mpiSize, size_t mpiRank, const std::vector< std::pair< std::vector< size_t >, std::vector< size_t >>> & ghostData, std::vector< std::pair< std::vector< util::Point >, std::vector< util::Point >>> & dispGhostData, std::vector< util::Point > & dispNodes)
Definition at line 164 of file testParallelCompLib.cpp.
{
     // resize dispGhostData if not done
     dispGhostData.resize(mpiSize);
     for (size_t j_proc = 0; j_proc < mpiSize; j_proc++) {
       auto j_data_size = ghostData[j_proc].first.size(); // same size for second
       dispGhostData[j_proc].first.resize(j_data_size);
       dispGhostData[j_proc].second.resize(j_data_size);
     }
     // exchange data
     util::io::print("\n\nBegin exchange data\n\n");
     util::io::print(fmt::format("\n\nThis processor's rank = {}\n\n", mpiRank), util::io::print_default_tab, -1);
     MPI_Request mpiRequests[2*(mpiSize-1)];
     size_t requestCounter = 0;
     for (size_t j_proc=0; j_proc<mpiSize; j_proc++) {
       auto & sendIds = ghostData[j_proc].second;
       auto & recvIds = ghostData[j_proc].first;
       if (j_proc != mpiRank and recvIds.size() != 0) {
         util::io::print(fmt::format("\n\n    Processing j_proc = {}\n\n", j_proc), util::io::print_default_tab, -1);
         // fill in ghost displacement data that we are sending from nodal displacement data
         for (size_t k = 0; k<sendIds.size(); k++)
           dispGhostData[j_proc].second[k] = dispNodes[sendIds[k]];
         // send data from this process to j_proc
         MPI_Isend(dispGhostData[j_proc].second.data(), 3*sendIds.size(),
                   MPI_DOUBLE, j_proc, 0, MPI_COMM_WORLD,
                   &mpiRequests[requestCounter++]);
         // receive data from j_proc
         MPI_Irecv(dispGhostData[j_proc].first.data(), 3*recvIds.size(),
                   MPI_DOUBLE, j_proc, 0, MPI_COMM_WORLD,
                   &mpiRequests[requestCounter++]);
       }
     } // loop over j_proc
     util::io::print("\n\nCalling MPI_Waitall\n\n");
     MPI_Waitall(requestCounter, mpiRequests, MPI_STATUSES_IGNORE);
     util::io::print("\n\nUpdate dispNodes data\n\n");
     for (size_t j_proc=0; j_proc<mpiSize; j_proc++) {
       auto & recvIds = ghostData[j_proc].first;
       if (j_proc != mpiRank and recvIds.size() != 0) {
         for (size_t k = 0; k<recvIds.size(); k++)
           dispNodes[recvIds[k]] = dispGhostData[j_proc].first[k];
       }
     } // loop over j_proc
   } // exchangeDispData()
References util::parallel::mpiRank(), util::parallel::mpiSize(), util::io::print(), and util::io::print_default_tab.
Referenced by test::testMPI().
f1()
double anonymous_namespace{testParallelCompLib.cpp}::f1 (const double & x)
Definition at line 45 of file testParallelCompLib.cpp.
{
     return x*x*x + std::exp(x) - std::sin(x);
   }
Referenced by test::testGraphPartitioning(), and test::testTaskflow().
f2()
double anonymous_namespace{testParallelCompLib.cpp}::f2 (const double & x)
Definition at line 49 of file testParallelCompLib.cpp.
{
     return 2*(x-0.5)*(x-0.5)*(x-0.5) + std::exp(x-0.5) - std::cos(x-0.5);
   }
Referenced by test::testTaskflow().
printMsg()
void anonymous_namespace{testParallelCompLib.cpp}::printMsg (std::string msg, int mpiRank, int printMpiRank)
Definition at line 36 of file testParallelCompLib.cpp.
{
     if (printMpiRank < 0) {
       std::cout << msg;
     } else {
       if (mpiRank == printMpiRank)
         std::cout << msg;
     }
   }
References util::parallel::mpiRank().
Referenced by test::testMPI().
setupOwnerAndGhost()
void anonymous_namespace{testParallelCompLib.cpp}::setupOwnerAndGhost (size_t mpiSize, size_t mpiRank, const std::vector< size_t > & nodePartition, const std::vector< std::vector< size_t >> & nodeNeighs, std::vector< size_t > & ownedNodes, std::vector< size_t > & ownedInternalNodes, std::vector< size_t > & ownedBdryNodes, std::vector< std::pair< std::vector< size_t >, std::vector< size_t >>> & ghostData)
Definition at line 53 of file testParallelCompLib.cpp.
{
     auto numNodes = nodePartition.size();
     // clear data
     ownedNodes.clear();
     ownedInternalNodes.clear();
     ownedBdryNodes.clear();
     ghostData.resize(mpiSize);
     for (size_t i_proc=0; i_proc<mpiSize; i_proc++) {
       ghostData[i_proc].first.clear();
       ghostData[i_proc].second.clear();
     }
     // setup
     for (size_t i=0; i<numNodes; i++) {
       if (nodePartition[i] == mpiRank) {
         // this processor owns this node
         ownedNodes.push_back(i);
         // ascertain if this node has neighboring nodes owned by other processors
         bool ghostExist = false;
         for (auto j : nodeNeighs[i]) {
           auto j_proc = nodePartition[j];
           if (j_proc != mpiRank) {
             ghostExist = true;
             // add j to ghost node list (to receive from j_proc)
             ghostData[j_proc].first.push_back(j);
             // add i to ghost node list (to send to j_proc)
             ghostData[j_proc].second.push_back(i);
           }
         }
         if (ghostExist)
           ownedBdryNodes.push_back(i);
         else
           ownedInternalNodes.push_back(i);
       } // loop over neighboring nodes
     } // loop over nodes
     bool debugGhostData = false;
     if (debugGhostData and mpiRank == 0) {
       std::vector<std::vector<std::pair<std::vector<size_t>, std::vector<size_t>>>> ghostDataAllProc(
               mpiSize);
       std::vector<std::vector<size_t>> numGhostDataAllProc(mpiSize);
       for (size_t i_proc = 0; i_proc < mpiSize; i_proc++) {
         numGhostDataAllProc[i_proc].resize(mpiSize);
         ghostDataAllProc[i_proc].resize(mpiSize);
       }
       for (size_t i_proc = 0; i_proc < mpiSize; i_proc++) {
         // assume we are i_proc and then create ghostData for i_proc
         for (size_t i = 0; i < numNodes; i++) {
           if (nodePartition[i] == i_proc) {
             // i_proc processor owns this node
             for (auto j: nodeNeighs[i]) {
               auto j_proc = nodePartition[j];
               if (j_proc != i_proc) {
                 // add to ghost node list
                 ghostDataAllProc[i_proc][j_proc].first.push_back(j);
               }
             }
           } // loop over neighboring nodes
         } // loop over nodes
         // total number of ghost nodes from neighboring processors
         for (size_t j_proc = 0; j_proc < mpiSize; j_proc++)
           numGhostDataAllProc[i_proc][j_proc] = ghostDataAllProc[i_proc][j_proc].first.size();
       } // loop over i_proc
       // print the information
       std::cout << "\n\nGhost data debug output\n\n";
       bool found_asym = false;
       for (size_t i_proc = 0; i_proc < mpiSize; i_proc++) {
         for (size_t j_proc = 0; j_proc < mpiSize; j_proc++) {
           std::cout << fmt::format("(i,j) = ({}, {}), num data = {}\n",
                                    i_proc, j_proc,
                                    numGhostDataAllProc[i_proc][j_proc]);
           if (j_proc > i_proc) {
             if (numGhostDataAllProc[i_proc][j_proc] == numGhostDataAllProc[j_proc][i_proc])
               std::cout << fmt::format("    symmetric: data ({}, {}) = data ({}, {})\n",
                                        i_proc, j_proc, j_proc, i_proc);
             else {
               found_asym = true;
               std::cout << fmt::format(
                       "    asymmetric: data ({}, {}) != data ({}, {})\n",
                       i_proc, j_proc, j_proc, i_proc);
             }
           }
         }
       }
       if (found_asym)
         std::cout << "Found asymetric ghost data\n";
       else
         std::cout << "No asymetric ghost data\n";
     }
   } // setupOwnerAndGhost()
References util::parallel::mpiRank(), and util::parallel::mpiSize().
Referenced by test::testMPI().