PeriDEM: /Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/main.cpp File Reference
main.cpp File Reference
#include <PeriDEMConfig.h>
#include <iostream>
#include <algorithm>
#include <ctime>
#include "inp/input.h"
#include "model/dem/demModel.h"
#include "util/io.h"
#include "util/parallelUtil.h"
#include "util/methods.h"
#include <fmt/format.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 26 of file main.cpp.
{
  // init parallel
  util::parallel::initMpi(argc, argv);
  int mpiSize = util::parallel::mpiSize(), mpiRank = util::parallel::mpiRank();
  util::io::print(fmt::format("Initialized MPI. MPI size = {}, MPI rank = {}\n", mpiSize, mpiRank));
  util::io::print(util::parallel::getMpiStatus()->printStr());
  util::io::InputParser input(argc, argv);
  if (input.cmdOptionExists("-h") or !input.cmdOptionExists("-i")) {
    // print help
    std::cout << "Syntax to run PeriDEM: PeriDEM -i <input file> -nThreads <number of threads>" << std::endl;
    std::cout << "Example: PeriDEM -i input.yaml -nThreads 4" << std::endl;
    exit(EXIT_FAILURE);
  }
  unsigned int nThreads;
  if (input.cmdOptionExists("-nThreads")) nThreads = std::stoi(input.getCmdOption("-nThreads"));
  else {
    nThreads = std::thread::hardware_concurrency();
    util::io::print(fmt::format("Running test with default number of threads = {}\n", nThreads));
  }
  // set number of threads
  util::parallel::initNThreads(nThreads);
  util::io::print(fmt::format("Number of threads = {}\n", util::parallel::getNThreads()));
  // print program version
  std::cout << "PeriDEM"
            << " (Version " << MAJOR_VERSION << "." << MINOR_VERSION << "."
            << UPDATE_VERSION << ")" << std::endl;
  // current time
  auto begin = steady_clock::now();
  // read input data
  std::string filename = input.getCmdOption("-i");
  auto *deck = new inp::Input(filename);
  // check which model to run
  if (deck->isPeriDEM()) {
    model::DEMModel dem(deck);
    dem.run(deck);
  } else {
    std::cout << "PeriDEM model not found in input file.\n";
  }
  // get time elapsed
  auto end = steady_clock::now();
  std::cout << "Total simulation time (s) = "
            << util::methods::timeDiff(begin, end, "seconds")
            << std::endl;
}
References util::io::InputParser::cmdOptionExists(), util::io::InputParser::getCmdOption(), util::parallel::getMpiStatus(), util::parallel::getNThreads(), util::parallel::initMpi(), util::parallel::initNThreads(), MAJOR_VERSION, MINOR_VERSION, util::parallel::mpiRank(), util::parallel::mpiSize(), util::io::print(), model::DEMModel::run(), util::methods::timeDiff(), and UPDATE_VERSION.