PeriDEM: inp::MeshDeck Struct Reference
inp::MeshDeck Struct Reference
Input
Structure to read and store mesh related input data.
#include <meshDeck.h>
Public Member Functions
MeshDeck ()
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
size_t d_dim
Dimension.
std::string d_spatialDiscretization
Tag for spatial discretization.
std::string d_filename
Filename to read mesh data.
bool d_computeMeshSize
Flag which indicates if mesh size is to be computed.
double d_h
Mesh size.
Detailed Description
Structure to read and store mesh related input data.
Definition at line 25 of file meshDeck.h.
Constructor & Destructor Documentation
MeshDeck()
inp::MeshDeck::MeshDeck () inline
Constructor.
Definition at line 53 of file meshDeck.h.
: d_dim(0), d_computeMeshSize(false), d_h(0.){};
Member Function Documentation
print()
void inp::MeshDeck::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 84 of file meshDeck.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::MeshDeck::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 62 of file meshDeck.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- MeshDeck --------" << std::endl << std::endl;
    oss << tabS << "Dimension = " << d_dim << std::endl;
    oss << tabS << "Spatial discretization type = " << d_spatialDiscretization
        << std::endl;
    oss << tabS << "Filename = " << d_filename << std::endl;
    oss << tabS << "Compute mesh size = " << d_computeMeshSize << std::endl;
    oss << tabS << "Mesh size = " << d_h << std::endl;
    oss << tabS << std::endl;
    return oss.str();
  }
References d_computeMeshSize, d_dim, d_filename, d_h, d_spatialDiscretization, and util::io::getTabS().
Referenced by fe::Mesh::Mesh(), print(), inp::ParticleZone::printStr(), and inp::WallZone::printStr().
Field Documentation
d_computeMeshSize
bool inp::MeshDeck::d_computeMeshSize
Flag which indicates if mesh size is to be computed.
Definition at line 45 of file meshDeck.h.
Referenced by printStr(), and inp::Input::setZoneMeshDeck().
d_dim
size_t inp::MeshDeck::d_dim
Dimension.
Definition at line 28 of file meshDeck.h.
Referenced by printStr(), and inp::Input::setZoneMeshDeck().
d_filename
std::string inp::MeshDeck::d_filename
Filename to read mesh data.
Definition at line 42 of file meshDeck.h.
Referenced by printStr(), and inp::Input::setZoneMeshDeck().
d_h
double inp::MeshDeck::d_h
Mesh size.
Definition at line 48 of file meshDeck.h.
Referenced by printStr(), and inp::Input::setZoneMeshDeck().
d_spatialDiscretization
std::string inp::MeshDeck::d_spatialDiscretization
Tag for spatial discretization.
List of allowed values are:
finite_difference
weak_finite_element
nodal_finite_element
truss_finite_element
Definition at line 39 of file meshDeck.h.
Referenced by printStr(), and inp::Input::setZoneMeshDeck().
The documentation for this struct was generated from the following file:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/inp/decks/meshDeck.h