PeriDEM: util::geometry::GeomData Struct Reference
util::geometry::GeomData Struct Reference
Input data for geometrical objects.
#include <geomObjectsUtil.h>
Public Member Functions
GeomData ()
Constructor.
GeomData (const GeomData &z)
Constructor.
void createNullGeomObject (std::string description="")
Creates NullGeomObject.
void copyGeometry (GeomData &z, size_t dim)
Copies the geometry details.
void copyGeometry (std::string &name, std::vector< double > &params, std::pair< std::vector< std::string >, std::vector< std::string > > &complexInfo, std::shared_ptr< util::geometry::GeomObject > &geom, size_t dim)
Copies the geometry details.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
std::string d_geomName
Zone type.
std::vector< double > d_geomParams
Zone parameters.
std::shared_ptr< util::geometry::GeomObject > d_geom_p
Zone geometry.
std::pair< std::vector< std::string >, std::vector< std::string > > d_geomComplexInfo
Zone geometry info if it is a complex type.
Detailed Description
Input data for geometrical objects.
Definition at line 21 of file geomObjectsUtil.h.
Constructor & Destructor Documentation
GeomData() [1/2]
util::geometry::GeomData::GeomData () inline
Constructor.
Definition at line 38 of file geomObjectsUtil.h.
: d_geom_p(nullptr) {};
GeomData() [2/2]
util::geometry::GeomData::GeomData (const GeomData & z) inline
Constructor.
Parameters
z Another GeomData object
Definition at line 45 of file geomObjectsUtil.h.
        : d_geomName(z.d_geomName),
          d_geomParams(z.d_geomParams),
          d_geom_p(z.d_geom_p),
          d_geomComplexInfo(z.d_geomComplexInfo) {};
Member Function Documentation
copyGeometry() [1/2]
void util::geometry::GeomData::copyGeometry (GeomData & z, size_t dim)
Copies the geometry details.
Parameters
z Another GeomData object that will be modified
dim Dimension of the object
Definition at line 959 of file geomObjectsUitl.cpp.
{
      z.d_geomName = d_geomName;
      z.d_geomParams = d_geomParams;
      z.d_geomComplexInfo = d_geomComplexInfo;
      if (d_geom_p->d_name == "null") {
        z.d_geom_p =
                std::make_shared<util::geometry::NullGeomObject>(
                        d_geom_p->d_description);
      } else if (d_geom_p->d_name.empty()) {
        z.d_geom_p =
                std::make_shared<util::geometry::GeomObject>(
                        d_geom_p->d_name, d_geom_p->d_description);
      } else {
        util::geometry::createGeomObject(z, dim);
      }
    }
References util::geometry::createGeomObject(), d_geom_p, d_geomComplexInfo, d_geomName, and d_geomParams.
Referenced by inp::Input::setParticleData().
copyGeometry() [2/2]
void util::geometry::GeomData::copyGeometry (std::string & name, std::vector< double > & params, std::pair< std::vector< std::string >, std::vector< std::string > > & complexInfo, std::shared_ptr< util::geometry::GeomObject > & geom, size_t dim)
Copies the geometry details.
Parameters
name Name of geometry
params Parameters
complexInfo Pair of vector of geometry names and flags for complex geometry
geom Pointer to geometry object
dim Dimension of the object
Definition at line 977 of file geomObjectsUitl.cpp.
{
      name = d_geomName;
      params = d_geomParams;
      complexInfo = d_geomComplexInfo;
      if (d_geom_p->d_name == "null") {
        geom =
                std::make_shared<util::geometry::NullGeomObject>(
                        d_geom_p->d_description);
      } else if (d_geom_p->d_name.empty()) {
        geom =
                std::make_shared<util::geometry::GeomObject>(
                        d_geom_p->d_name, d_geom_p->d_description);
      } else {
        util::geometry::createGeomObject(name,
                                         params,
                                         complexInfo.first,
                                         complexInfo.second,
                                         geom, dim);
      }
    }
References util::geometry::createGeomObject().
createNullGeomObject()
void util::geometry::GeomData::createNullGeomObject (std::string description = "") inline
Creates NullGeomObject.
Parameters
description Description (if any)
Definition at line 55 of file geomObjectsUtil.h.
{
  d_geomName = "null";
  d_geomParams.resize(0);
  d_geom_p = std::make_shared<util::geometry::NullGeomObject>(
          description);
};
References d_geom_p, d_geomName, and d_geomParams.
print()
void util::geometry::GeomData::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 123 of file geomObjectsUtil.h.
{
  std::cout << printStr(nt, lvl);
}
References printStr().
printStr()
std::string util::geometry::GeomData::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 92 of file geomObjectsUtil.h.
{
  auto tabS = util::io::getTabS(nt);
  std::ostringstream oss;
  oss << tabS << "------- GeomData --------" << std::endl
      << std::endl;
  oss << tabS << "Type = " << d_geomName << std::endl;
  oss << tabS << "Parameters = ["
      << util::io::printStr<double>(d_geomParams, 0)
      << "]" << std::endl;
  if (!d_geomComplexInfo.first.empty()) {
    oss << tabS << "Vec type for complex geometry = ["
        << util::io::printStr(d_geomComplexInfo.first, 0)
        << "]" << std::endl;
    oss << tabS << "Vec flag for complex geometry = ["
        << util::io::printStr(d_geomComplexInfo.second, 0)
        << "]" << std::endl;
  }
  if (d_geom_p != nullptr)
    oss << d_geom_p->printStr(nt + 1, lvl);
  return oss.str();
}
References d_geom_p, d_geomComplexInfo, d_geomName, d_geomParams, util::io::getTabS(), and util::io::printStr().
Referenced by print(), inp::MeshDeck::printStr(), inp::ParticleDeck::printStr(), inp::PBCData::printStr(), inp::Zone::printStr(), and inp::ParticleZone::printStr().
Field Documentation
d_geom_p
std::shared_ptr<util::geometry::GeomObject> util::geometry::GeomData::d_geom_p
Zone geometry.
Definition at line 30 of file geomObjectsUtil.h.
Referenced by copyGeometry(), util::geometry::createGeomObject(), createNullGeomObject(), loading::ParticleFLoading::needToComputeDof(), loading::ParticleULoading::needToComputeDof(), inp::PBCData::printStr(), printStr(), inp::Input::setParticleData(), and inp::Input::setZoneData().
d_geomComplexInfo
std::pair<std::vector<std::string>, std::vector<std::string> > util::geometry::GeomData::d_geomComplexInfo
Zone geometry info if it is a complex type.
Definition at line 33 of file geomObjectsUtil.h.
Referenced by copyGeometry(), util::geometry::createGeomObject(), printStr(), and anonymous_namespace{input.cpp}::readGeometry().
d_geomName
std::string util::geometry::GeomData::d_geomName
Zone type.
Definition at line 24 of file geomObjectsUtil.h.
Referenced by copyGeometry(), util::geometry::createGeomObject(), createNullGeomObject(), printStr(), and anonymous_namespace{input.cpp}::readGeometry().
d_geomParams
std::vector<double> util::geometry::GeomData::d_geomParams
Zone parameters.
Definition at line 27 of file geomObjectsUtil.h.
Referenced by copyGeometry(), util::geometry::createGeomObject(), createNullGeomObject(), printStr(), and anonymous_namespace{input.cpp}::readGeometry().
The documentation for this struct was generated from the following files:
/home/user/project/src/util/geomObjectsUtil.h
/home/user/project/src/util/geomObjectsUitl.cpp