PeriDEM: inp::MatData Struct Reference
inp::MatData Struct Reference
Structure for elastic properties and fracture properties.
#include <materialDeck.h>
Public Member Functions
MatData ()
Constructor.
MatData (const MatData &md)
Copy constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Conversion methods
double toNu (double lambda, double mu)
Compute Poisson's ratio from Lame parameters.
double toNuEG (double E, double G)
Compute Poisson's ratio from Young's and Shear modulus.
double toE (double K, double nu)
Compute Young's modulus E from Bulk modulus K and Poisson's ratio nu.
double toK (double E, double nu)
Compute Bulk modulus K from Young's modulus K and Poisson's ratio nu.
double toLambdaE (double E, double nu)
Compute Lame first parameter lambda from Young's modulus E and Poisson's ratio nu.
double toLambdaK (double K, double nu)
Compute Lame first parameter lambda from Bulk modulus K and Poisson's ratio nu.
double toGE (double E, double nu)
Compute shear modulus from Young's modulus E and Poisson's ratio nu.
double toGK (double K, double nu)
Compute shear modulus from Bulk modulus K and Poisson's ratio nu.
double toELambda (double lambda, double nu)
Compute Young's modulus E from Lame first parameter lambda and Poisson's ratio nu.
double toGc (double KIc, double nu, double E)
Compute critical energy release rate Gc from critical stress-intensity factor KIc, Poisson's ratio nu, and Young's modulus E.
double toKIc (double Gc, double nu, double E)
Compute critical stress-intensity factor KIc from critical energy release rate Gc, Poisson's ratio \(nu\), and Young's modulus E.
Data Fields
Elastic material properties
double d_E
Young's elastic modulus.
double d_G
Shear modulus or Lame second parameter.
double d_K
Bulk modulus.
double d_nu
Poisson's ratio.
double d_lambda
Lame first parameter.
double d_mu
Lame second parameter.
Fracture properties
double d_KIc
Critical stress intensity factor.
double d_Gc
Critical energy release rate.
Detailed Description
Structure for elastic properties and fracture properties.
Definition at line 22 of file materialDeck.h.
Constructor & Destructor Documentation
MatData() [1/2]
inp::MatData::MatData () inline
Constructor.
Definition at line 65 of file materialDeck.h.
      : d_E(-1.), d_G(-1.), d_K(-1.), d_nu(-1.), d_lambda(-1.), d_mu(-1.),
        d_KIc(-1.), d_Gc(-1.){};
MatData() [2/2]
inp::MatData::MatData (const MatData & md) inline
Copy constructor.
Parameters
md Another MatData object
Definition at line 74 of file materialDeck.h.
      : d_E(md.d_E), d_G(md.d_G), d_K(md.d_K), d_nu(md.d_nu),
        d_lambda(md.d_lambda), d_mu(md.d_mu), d_KIc(md.d_KIc), d_Gc(md.d_Gc){};
Member Function Documentation
print()
void inp::MatData::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 109 of file materialDeck.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::MatData::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 85 of file materialDeck.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- MatData --------" << std::endl << std::endl;
    oss << tabS << "Young's modulus = " << d_E << std::endl;
    oss << tabS << "Shear modulus = " << d_G << std::endl;
    oss << tabS << "Bulk modulus = " << d_K << std::endl;
    oss << tabS << "Poisson ratio = " << d_nu << std::endl;
    oss << tabS << "Lame parameter Lambda = " << d_lambda << std::endl;
    oss << tabS << "Lame parameter Mu = " << d_mu << std::endl;
    oss << tabS << "Critical stress intensity factor = " << d_KIc << std::endl;
    oss << tabS << "Critical energy release rate = " << d_Gc << std::endl;
    oss << tabS << std::endl;
    return oss.str();
  }
References d_E, d_G, d_Gc, d_K, d_KIc, d_lambda, d_mu, d_nu, and util::io::getTabS().
Referenced by print(), and inp::MaterialDeck::printStr().
toE()
double inp::MatData::toE (double K, double nu) inline
Compute Young's modulus E from Bulk modulus K and Poisson's ratio nu.
Parameters
K Bulk modulus
nu Poisson's ratio
Returns
E Young's modulus
Definition at line 138 of file materialDeck.h.
{ return K * (3. * (1. - 2. * nu)); }
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), and material::RnpMaterial::computeParameters().
toELambda()
double inp::MatData::toELambda (double lambda, double nu) inline
Compute Young's modulus E from Lame first parameter lambda and Poisson's ratio nu.
Parameters
lambda Lame first parameter
nu Poisson's ratio
Returns
E Young's modulus
Definition at line 193 of file materialDeck.h.
{
    return lambda * (1. + nu) * (1. - 2. * nu) / nu;
  }
toGc()
double inp::MatData::toGc (double KIc, double nu, double E) inline
Compute critical energy release rate Gc from critical stress-intensity factor KIc, Poisson's ratio nu, and Young's modulus E.
Below conversion from KIc to Gc assumes plane-stress condition. For plane-stress condition, we need to modify the Young's modulus \(E\) to \(\frac{E}{1 - \nu^2} \) where \(\nu\) is the Poisson's ratio.
Parameters
KIc Critical stress-intensity factor
nu Poisson's ratio
E Young's modulus
Returns
Gc Critical energy release rate
Definition at line 210 of file materialDeck.h.
{ return KIc * KIc / E; }
Referenced by material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), and material::RnpMaterial::computeParameters().
toGE()
double inp::MatData::toGE (double E, double nu) inline
Compute shear modulus from Young's modulus E and Poisson's ratio nu.
Parameters
E Young's modulus
nu Poisson's ratio
Returns
G Shear modulus
Definition at line 174 of file materialDeck.h.
{ return E / (2. * (1. + nu)); }
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), and material::RnpMaterial::computeParameters().
toGK()
double inp::MatData::toGK (double K, double nu) inline
Compute shear modulus from Bulk modulus K and Poisson's ratio nu.
Parameters
K Bulk modulus
nu Poisson's ratio
Returns
G Shear modulus
Definition at line 182 of file materialDeck.h.
{
    return 3. * K * (1. - 2. * nu) / (2. * (1. + nu));
  }
toK()
double inp::MatData::toK (double E, double nu) inline
Compute Bulk modulus K from Young's modulus K and Poisson's ratio nu.
Parameters
E Young's modulus
nu Poisson's ratio
Returns
K Bulk modulus
Definition at line 146 of file materialDeck.h.
{ return E / (3. * (1. - 2. * nu)); }
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), and material::RnpMaterial::computeParameters().
toKIc()
double inp::MatData::toKIc (double Gc, double nu, double E) inline
Compute critical stress-intensity factor KIc from critical energy release rate Gc, Poisson's ratio \(nu\), and Young's modulus E.
Below conversion from Gc to KIc assumes plane-stress condition. For plane-stress condition, we need to modify the Young's modulus \(E\) to \(\frac{E}{1 - \nu^2} \) where \(\nu\) is the Poisson's ratio.
Parameters
Gc Critical energy release rate
nu Poisson's ratio
E Young's modulus
Returns
KIc Critical stress-intensity factor
Definition at line 225 of file materialDeck.h.
{ return std::sqrt(Gc * E); }
Referenced by material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), and material::RnpMaterial::computeParameters().
toLambdaE()
double inp::MatData::toLambdaE (double E, double nu) inline
Compute Lame first parameter lambda from Young's modulus E and Poisson's ratio nu.
Parameters
E Young's modulus
nu Poisson's ratio
Returns
lambda Lame first parameter
Definition at line 155 of file materialDeck.h.
{
    return E * nu / ((1. + nu) * (1. - 2. * nu));
  }
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), and material::RnpMaterial::computeParameters().
toLambdaK()
double inp::MatData::toLambdaK (double K, double nu) inline
Compute Lame first parameter lambda from Bulk modulus K and Poisson's ratio nu.
Parameters
K Bulk modulus
nu Poisson's ratio
Returns
lambda Lame first parameter
Definition at line 166 of file materialDeck.h.
{ return 3. * K * nu / (1. + nu); }
toNu()
double inp::MatData::toNu (double lambda, double mu) inline
Compute Poisson's ratio from Lame parameters.
Parameters
lambda Lame first parameter
mu Lame second parameter
Returns
nu Poisson's ratio
Definition at line 122 of file materialDeck.h.
{ return lambda * 0.5 / (lambda + mu); }
toNuEG()
double inp::MatData::toNuEG (double E, double G) inline
Compute Poisson's ratio from Young's and Shear modulus.
Parameters
E Youngs modulus
G Shear modulus
Returns
nu Poisson's ratio
Definition at line 130 of file materialDeck.h.
{ return E * 0.5 / G - 1.; }
Field Documentation
d_E
double inp::MatData::d_E
Young's elastic modulus.
Definition at line 30 of file materialDeck.h.
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
d_G
double inp::MatData::d_G
Shear modulus or Lame second parameter.
Definition at line 33 of file materialDeck.h.
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
d_Gc
double inp::MatData::d_Gc
Critical energy release rate.
Definition at line 58 of file materialDeck.h.
Referenced by material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
d_K
double inp::MatData::d_K
Bulk modulus.
Definition at line 36 of file materialDeck.h.
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
d_KIc
double inp::MatData::d_KIc
Critical stress intensity factor.
Definition at line 55 of file materialDeck.h.
Referenced by material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
d_lambda
double inp::MatData::d_lambda
Lame first parameter.
Definition at line 42 of file materialDeck.h.
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
d_mu
double inp::MatData::d_mu
Lame second parameter.
Definition at line 45 of file materialDeck.h.
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
d_nu
double inp::MatData::d_nu
Poisson's ratio.
Definition at line 39 of file materialDeck.h.
Referenced by material::PdElastic::computeParameters(), material::PdState::computeParameters(), material::PmbMaterial::computeParameters(), material::RnpMaterial::computeParameters(), printStr(), and inp::Input::setZoneMaterialDeck().
The documentation for this struct was generated from the following file:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/inp/decks/materialDeck.h