PeriDEM: util::Matrix3 Struct Reference
util::Matrix3 Struct Reference
A structure to represent 3d matrices.
#include <matrix.h>
Public Member Functions
Matrix3 ()
Constructor.
Matrix3 (const util::Point &diagonal)
Constructor.
Matrix3 (const util::Point &a1, const util::Point &a2, const util::Point &a3)
Constructor.
Matrix3 (const std::vector< std::vector< double >> &m)
Constructor.
Matrix3 (const Matrix3 &m)
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Prints the information.
void print (int nt=0, int lvl=0) const
Prints the information.
Point operator() (size_t i)
Returns row of matrix.
Point operator() (size_t i) const
Returns row of matrix.
float & operator() (size_t i, size_t j)
Returns element of matrix.
const float & operator() (size_t i, size_t j) const
Returns element of matrix.
util::Point dot (const util::Point &v)
Computes the dot product between matrix and vector.
std::vector< double > dot (const std::vector< double > &v) const
Computes the dot product between matrix and vector.
Matrix3 transpose () const
Computes the tranpose of matrix.
double det () const
Computes the determinant of matrix.
Matrix3 inv () const
Computes the determinant of matrix.
Data Fields
Data members
float d_data [3][3] {}
data
Detailed Description
A structure to represent 3d matrices.
Definition at line 19 of file matrix.h.
Constructor & Destructor Documentation
Matrix3() [1/5]
util::Matrix3::Matrix3 () inline
Constructor.
Definition at line 34 of file matrix.h.
             {
     d_data[0][0] = 0.;
     d_data[0][1] = 0.;
     d_data[0][2] = 0.;
     d_data[1][0] = 0.;
     d_data[1][1] = 0.;
     d_data[1][2] = 0.;
     d_data[2][0] = 0.;
     d_data[2][1] = 0.;
     d_data[2][2] = 0.;
   };
References d_data.
Referenced by inv(), and transpose().
Matrix3() [2/5]
util::Matrix3::Matrix3 (const util::Point & diagonal) inline
Constructor.
Parameters
diagonal Diagonal vector
Definition at line 54 of file matrix.h.
{
     d_data[0][0] = diagonal.d_x;
     d_data[0][1] = 0.;
     d_data[0][2] = 0.;
     d_data[1][0] = 0.;
     d_data[1][1] = diagonal.d_y;
     d_data[1][2] = 0.;
     d_data[2][0] = 0.;
     d_data[2][1] = 0.;
     d_data[2][2] = diagonal.d_z;
   };
References d_data, util::Point::d_x, util::Point::d_y, and util::Point::d_z.
Matrix3() [3/5]
util::Matrix3::Matrix3 (const util::Point & a1, const util::Point & a2, const util::Point & a3) inline
Constructor.
Parameters
a1 first row
a2 second row
a3 third row
Definition at line 76 of file matrix.h.
{
     d_data[0][0] = a1.d_x;
     d_data[0][1] = a1.d_y;
     d_data[0][2] = a1.d_z,
     d_data[1][0] = a2.d_x;
     d_data[1][1] = a2.d_y;
     d_data[1][2] = a2.d_z;
     d_data[2][0] = a3.d_x;
     d_data[2][1] = a3.d_y;
     d_data[2][2] = a3.d_z;
   };
References d_data, util::Point::d_x, util::Point::d_y, and util::Point::d_z.
Matrix3() [4/5]
util::Matrix3::Matrix3 (const std::vector< std::vector< double >> & m) inline
Constructor.
Parameters
m Matrix in vector template
Definition at line 94 of file matrix.h.
{
     for (size_t i=0; i<3; i++)
       for (size_t j=0; j<3; j++)
         d_data[i][j] = m[i][j];
   }
References d_data.
Matrix3() [5/5]
util::Matrix3::Matrix3 (const Matrix3 & m) inline
Constructor.
Parameters
m Matrix in vector template
Definition at line 105 of file matrix.h.
{
     for (size_t i=0; i<3; i++)
       for (size_t j=0; j<3; j++)
         d_data[i][j] = m(i,j);
   }
References d_data.
Member Function Documentation
det()
double util::Matrix3::det () const inline
Computes the determinant of matrix.
Returns
det Determinant
Definition at line 215 of file matrix.h.
                      {
     return (*this)(0,0) * ((*this)(1,1) * (*this)(2,2) - (*this)(2,1) * (*this)(1,2)) -
            (*this)(0,1) * ((*this)(1,0) * (*this)(2,2) - (*this)(2,0) * (*this)(1,2)) +
            (*this)(0,2) * ((*this)(1,0) * (*this)(2,1) - (*this)(2,0) * (*this)(1,1));
   }
Referenced by inv().
dot() [1/2]
std::vector<double> util::Matrix3::dot (const std::vector< double > & v) const inline
Computes the dot product between matrix and vector.
Parameters
v vector
Returns
vector Dot product
Definition at line 180 of file matrix.h.
{
     auto r = std::vector<double>(3,0.);
     for (size_t i=0; i<3; i++)
       for (size_t j=0; j<3; j++)
         r[i] += (*this)(i,j) * v[j];
     return r;
   }
dot() [2/2]
util::Point util::Matrix3::dot (const util::Point & v) inline
Computes the dot product between matrix and vector.
Parameters
v vector
Returns
vector Dot product
Definition at line 174 of file matrix.h.
{
     return {(*this)(0) * v, (*this)(1) * v, (*this)(2) * v};
   }
inv()
Matrix3 util::Matrix3::inv () const inline
Computes the determinant of matrix.
Returns
inv Inverse of m
Definition at line 226 of file matrix.h.
                       {
     Matrix3 m = Matrix3();
     auto det_inv = 1. / this->det();
     m(0,0) = det_inv *
               ((*this)(1,1) * (*this)(2,2) - (*this)(2,1) * (*this)(1,2));
     m(0,1) = -det_inv *
               ((*this)(0,1) * (*this)(2,2) - (*this)(2,1) * (*this)(0,2));
     m(0,2) = det_inv *
               ((*this)(0,1) * (*this)(1,2) - (*this)(1,1) * (*this)(0,2));
     m(1,0) = -det_inv *
               ((*this)(1,0) * (*this)(2,2) - (*this)(2,0) * (*this)(1,2));
     m(1,1) = det_inv *
               ((*this)(0,0) * (*this)(2,2) - (*this)(2,0) * (*this)(0,2));
     m(1,2) = -det_inv *
               ((*this)(0,0) * (*this)(1,2) - (*this)(1,0) * (*this)(0,2));
     m(2,0) = det_inv *
               ((*this)(1,0) * (*this)(2,1) - (*this)(2,0) * (*this)(1,1));
     m(2,1) = -det_inv *
               ((*this)(0,0) * (*this)(2,1) - (*this)(2,0) * (*this)(0,1));
     m(2,2) = det_inv *
               ((*this)(0,0) * (*this)(1,1) - (*this)(1,0) * (*this)(0,1));
     return m;
   }
References det(), and Matrix3().
operator()() [1/4]
Point util::Matrix3::operator() (size_t i) inline
Returns row of matrix.
Parameters
i Row id
Returns
Row Row
Definition at line 147 of file matrix.h.
{
     return Point(d_data[i]);
   }
References d_data.
operator()() [2/4]
Point util::Matrix3::operator() (size_t i) const inline
Returns row of matrix.
Parameters
i Row id
Returns
Row Row
Definition at line 152 of file matrix.h.
{
     return Point(d_data[i]);
   }
References d_data.
operator()() [3/4]
float& util::Matrix3::operator() (size_t i, size_t j) inline
Returns element of matrix.
Parameters
i Row id
j Column id
Returns
Element Element of matrix
Definition at line 163 of file matrix.h.
 { return d_data[i][j]; }
References d_data.
operator()() [4/4]
const float& util::Matrix3::operator() (size_t i, size_t j) const inline
Returns element of matrix.
Parameters
i Row id
j Column id
Returns
Element Element of matrix
Definition at line 166 of file matrix.h.
 { return d_data[i][j]; }
References d_data.
print()
void util::Matrix3::print (int nt = 0, int lvl = 0) const inline
Prints the information.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 139 of file matrix.h.
 { std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string util::Matrix3::printStr (int nt = 0, int lvl = 0) const inline
Prints the information.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string Formatted string
Definition at line 118 of file matrix.h.
{
     std::string tabS = "";
     for (int i = 0; i < nt; i++)
       tabS += "\t";
     std::ostringstream oss;
     for (size_t i=0; i<3; i++)
       oss << tabS << "[" << (*this)(i, 0) << ", " << (*this)(i, 1) << ", "
           << (*this)(i, 2) << "]" << std::endl;
     oss << std::endl;
     return oss.str();
   }
References anonymous_namespace{main.cpp}::oss.
Referenced by print().
transpose()
Matrix3 util::Matrix3::transpose () const inline
Computes the tranpose of matrix.
Returns
Matrix Transpose of m
Definition at line 194 of file matrix.h.
{
     Matrix3 m = Matrix3(*this);
     m(0,1) = (*this)(1,0);
     m(0,2) = (*this)(2,0);
     m(1,0) = (*this)(0,1);
     m(1,2) = (*this)(2,1);
     m(2,0) = (*this)(0,2);
     m(2,1) = (*this)(1,2);
     return m;
   }
References Matrix3().
Field Documentation
d_data
float util::Matrix3::d_data[3][3] {}
data
Definition at line 27 of file matrix.h.
Referenced by Matrix3(), and operator()().
The documentation for this struct was generated from the following file:
/home/user/project/src/util/matrix.h