PeriDEM: inp::Zone Struct Reference
inp::Zone Struct Reference
Input
User-input data for zones.
#include <zoneDeck.h>
Public Member Functions
Zone ()
Constructor.
Zone (const Zone &z)
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
std::string d_type
Zone type.
std::vector< double > d_params
Zone parameters.
std::shared_ptr< util::geometry::GeomObject > d_geom_p
Zone geometry.
size_t d_zoneId
Specify zone to which this particle belongs to.
Detailed Description
User-input data for zones.
Definition at line 28 of file zoneDeck.h.
Constructor & Destructor Documentation
Zone() [1/2]
inp::Zone::Zone () inline
Constructor.
Definition at line 45 of file zoneDeck.h.
 : d_geom_p(nullptr){};
Zone() [2/2]
inp::Zone::Zone (const Zone & z) inline
Constructor.
Parameters
z Another zone object
Definition at line 52 of file zoneDeck.h.
       : d_type(z.d_type), d_params(z.d_params), d_geom_p(z.d_geom_p),
         d_zoneId(z.d_zoneId){};
Member Function Documentation
print()
void inp::Zone::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 83 of file zoneDeck.h.
 { std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::Zone::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 63 of file zoneDeck.h.
{
     auto tabS = util::io::getTabS(nt);
     std::ostringstream oss;
     oss << tabS << "------- Zone --------" << std::endl << std::endl;
     oss << tabS << "Type = " << d_type << ", Zone id = " << d_zoneId
         << std::endl;
     oss << tabS << "Parameters = [" << util::io::printStr<double>(d_params, 0)
         << "]" << std::endl;
     oss << d_geom_p->printStr(nt+1, lvl);
     return oss.str();
   }
References d_geom_p, d_params, d_type, d_zoneId, util::io::getTabS(), and anonymous_namespace{main.cpp}::oss.
Referenced by print(), inp::ParticleZone::printStr(), and inp::WallZone::printStr().
Field Documentation
d_geom_p
std::shared_ptr<util::geometry::GeomObject> inp::Zone::d_geom_p
Zone geometry.
Definition at line 37 of file zoneDeck.h.
Referenced by printStr(), and inp::Input::setZoneData().
d_params
std::vector<double> inp::Zone::d_params
Zone parameters.
Definition at line 34 of file zoneDeck.h.
Referenced by printStr(), and inp::Input::setZoneData().
d_type
std::string inp::Zone::d_type
Zone type.
Definition at line 31 of file zoneDeck.h.
Referenced by printStr(), and inp::Input::setZoneData().
d_zoneId
size_t inp::Zone::d_zoneId
Specify zone to which this particle belongs to.
Definition at line 40 of file zoneDeck.h.
Referenced by printStr().
The documentation for this struct was generated from the following file:
/home/user/project/src/inp/pdecks/zoneDeck.h