PeriDEM: inp::PICDeck Struct Reference
inp::PICDeck Struct Reference
Input
User-input data for particle neighbor search.
#include <pICDeck.h>
Public Member Functions
PICDeck ()
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
bool d_icActive
Specify if particle initial condition is active.
util::Point d_icVec
Initial velocity vector.
std::vector< size_t > d_pList
List of particles (if any)
std::vector< size_t > d_wList
List of walls (if any)
Detailed Description
User-input data for particle neighbor search.
Definition at line 24 of file pICDeck.h.
Constructor & Destructor Documentation
PICDeck()
inp::PICDeck::PICDeck () inline
Constructor.
Definition at line 41 of file pICDeck.h.
: d_icActive(false), d_icVec(){};
Member Function Documentation
print()
void inp::PICDeck::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 74 of file pICDeck.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::PICDeck::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 50 of file pICDeck.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- PICDeck --------" << std::endl << std::endl;
    oss << tabS << "IC active  = " << d_icActive << std::endl;
    oss << tabS << "IC vector = " << d_icVec.printStr(0, 0) << std::endl;
    if (!d_pList.empty())
      oss << tabS << "Particle list = ["
          << util::io::printStr<size_t>(d_pList, 0) << "]" << std::endl;
    if (!d_wList.empty())
      oss << tabS << "Wall list = ["
          << util::io::printStr<size_t>(d_wList, 0) << "]" << std::endl;
    oss << tabS << std::endl;
    return oss.str();
  }
References d_icActive, d_icVec, d_pList, d_wList, util::io::getTabS(), util::io::printStr(), and util::Point::printStr().
Referenced by print(), and inp::ParticleDeck::printStr().
Field Documentation
d_icActive
bool inp::PICDeck::d_icActive
Specify if particle initial condition is active.
Definition at line 27 of file pICDeck.h.
Referenced by printStr().
d_icVec
util::Point inp::PICDeck::d_icVec
Initial velocity vector.
Definition at line 30 of file pICDeck.h.
Referenced by printStr().
d_pList
std::vector<size_t> inp::PICDeck::d_pList
List of particles (if any)
Definition at line 33 of file pICDeck.h.
Referenced by printStr().
d_wList
std::vector<size_t> inp::PICDeck::d_wList
List of walls (if any)
Definition at line 36 of file pICDeck.h.
Referenced by printStr().
The documentation for this struct was generated from the following file:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/inp/pdecks/pICDeck.h