PeriDEM: inp::ContactDeck Struct Reference
inp::ContactDeck Struct Reference
Structure to read and store particle-particle contact related input data.
#include <contactDeck.h>
Public Member Functions
const ContactPairDeck & getContact (const size_t &i, const size_t &j) const
Returns the contact data.
ContactPairDeck & getContact (const size_t &i, const size_t &j)
Returns the contact data.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
std::vector< std::vector< ContactPairDeck > > d_data
Store contact parameters for each pair of zone.
Detailed Description
Structure to read and store particle-particle contact related input data.
Definition at line 181 of file contactDeck.h.
Member Function Documentation
getContact() [1/2]
ContactPairDeck & inp::ContactDeck::getContact (const size_t & i, const size_t & j) inline
Returns the contact data.
Parameters
i Zone i
j Zone j
Returns
data Contact data between zone i and j
Definition at line 201 of file contactDeck.h.
{
    //return d_data[i < j ? i : j][i < j ? j : i];
    return d_data[i][j];
  }
References d_data.
getContact() [2/2]
const ContactPairDeck & inp::ContactDeck::getContact (const size_t & i, const size_t & j) const inline
Returns the contact data.
Parameters
i Zone i
j Zone j
Returns
data Contact data between zone i and j
Definition at line 195 of file contactDeck.h.
{
    //return d_data[i < j ? i : j][i < j ? j : i];
    return d_data[i][j];
  }
References d_data.
Referenced by printStr().
print()
void inp::ContactDeck::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 237 of file contactDeck.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::ContactDeck::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 213 of file contactDeck.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- ContactDeck --------" << std::endl << std::endl;
    for (size_t i =0; i<d_data.size(); i++) {
      for (size_t j = 0; j < d_data.size(); j++) {
        oss << tabS << "ContactPairDeck id = (" << i << "," << j << ") info:"
                  << std::endl;
        oss << getContact(i,j).printStr(nt+2, lvl);
      }
    }
    oss << tabS << std::endl;
    return oss.str();
  }
References d_data, getContact(), util::io::getTabS(), and inp::ContactPairDeck::printStr().
Referenced by print().
Field Documentation
d_data
std::vector<std::vector<ContactPairDeck> > inp::ContactDeck::d_data
Store contact parameters for each pair of zone.
Definition at line 186 of file contactDeck.h.
Referenced by getContact(), getContact(), and printStr().
The documentation for this struct was generated from the following file:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/inp/pdecks/contactDeck.h