PeriDEM: inp::ParticleDeck Struct Reference
inp::ParticleDeck Struct Reference
Input
Structure to read and store particle related input data.
#include <particleDeck.h>
Public Member Functions
ParticleDeck ()
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
std::vector< inp::Zone > d_zoneVec
All zones.
std::vector< std::pair< std::string, size_t > > d_zoneToPorWDeck
Maps particle/wall to corresponding zone.
std::vector< inp::ParticleZone > d_pZones
Particle in zones.
std::vector< inp::WallZone > d_wZones
Walls.
std::shared_ptr< util::geometry::GeomObject > d_contGeom_p
Geometry of container in which all particles reside. Currently, we only support rectangle (2-d) and cuboid (3-d)
inp::PNeighborDeck d_pNeighDeck
Neighbor search data.
bool d_gravityActive
Gravity loading value.
util::Point d_gravity
Gravity loading value.
std::vector< inp::PBCData > d_forceDeck
Force loading deck.
std::vector< inp::PBCData > d_dispDeck
Displacement loading deck.
inp::PICDeck d_icDeck
Initial condition deck.
std::string d_testName
Specify test name (if any)
size_t d_wallIdCompressiveTest
if it is a compressive test, specify wall id and direction
size_t d_wallForceDirectionCompressiveTest
if it is a compressive test, specify force direction on wall
Detailed Description
Structure to read and store particle related input data.
Definition at line 30 of file particleDeck.h.
Constructor & Destructor Documentation
ParticleDeck()
inp::ParticleDeck::ParticleDeck () inline
Constructor.
Definition at line 80 of file particleDeck.h.
       : d_contGeom_p(nullptr), d_pNeighDeck(inp::PNeighborDeck()),
         d_gravityActive(false), d_gravity(), d_icDeck(),
         d_testName(""), d_wallIdCompressiveTest(0),
         d_wallForceDirectionCompressiveTest(0) {};
Member Function Documentation
print()
void inp::ParticleDeck::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 145 of file particleDeck.h.
 { std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::ParticleDeck::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 93 of file particleDeck.h.
{
     auto tabS = util::io::getTabS(nt);
     std::ostringstream oss;
     oss << tabS << "------- ParticleDeck --------" << std::endl << std::endl;
     oss << tabS << "Number of particle zones  = " << d_pZones.size() << std::endl;
     oss << tabS << "Number of wall zones  = " << d_wZones.size() << std::endl;
     oss << tabS << "Particle data:" << std::endl;
     for (size_t i = 0; i < d_pZones.size(); i++) {
       oss << tabS << "Particle data for zone = " << i << std::endl;
       oss << d_pZones[i].printStr(nt+1, lvl);
     }
     oss << tabS << "Wall data:" << std::endl;
     for (size_t i = 0; i < d_wZones.size(); i++) {
       oss << tabS << "Wall data for zone = " << i << std::endl;
       oss << d_wZones[i].printStr(nt+1, lvl);
     }
     oss << tabS << "Container geometry info:" << std::endl;
     oss << d_contGeom_p->printStr(nt+1, lvl);
     oss << tabS << "Neighbor data:" << std::endl;
     oss << d_pNeighDeck.printStr(nt+1, lvl);
     oss << tabS << "Gravity: Status = " << d_gravityActive
         << ", force = " << d_gravity.printStr(0, 0) << std::endl;
     oss << tabS << "Num of Force BC = " << d_forceDeck.size() << std::endl;
     oss << tabS << "Force BC info:" << std::endl;
     size_t bc_count = 0;
     for (const auto &f: d_forceDeck) {
       oss << tabS << "  Force BC id = " << bc_count++ << std::endl;
       oss << f.printStr(nt+2, lvl);
     }
     oss << tabS << "Num of Displacement BC = " << d_dispDeck.size() <<
     std::endl;
     oss << tabS << "Displacement BC info:" << std::endl;
     bc_count = 0;
     for (const auto &f: d_dispDeck) {
       oss << tabS << "  Displacement BC id = " << bc_count++ << std::endl;
       oss << f.printStr(nt+2, lvl);
     }
     oss << tabS << "IC data:" << std::endl;
     oss << d_icDeck.printStr(nt+1, lvl);
     oss << tabS << "Test name = " << d_testName << std::endl;
     oss << tabS << std::endl;
     return oss.str();
   }
References d_contGeom_p, d_dispDeck, d_forceDeck, d_gravity, d_gravityActive, d_icDeck, d_pNeighDeck, d_pZones, d_testName, d_wZones, util::io::getTabS(), anonymous_namespace{main.cpp}::oss, inp::PNeighborDeck::printStr(), inp::PICDeck::printStr(), and util::Point::printStr().
Referenced by print().
Field Documentation
d_contGeom_p
std::shared_ptr<util::geometry::GeomObject> inp::ParticleDeck::d_contGeom_p
Geometry of container in which all particles reside. Currently, we only support rectangle (2-d) and cuboid (3-d)
Definition at line 48 of file particleDeck.h.
Referenced by printStr().
d_dispDeck
std::vector<inp::PBCData> inp::ParticleDeck::d_dispDeck
Displacement loading deck.
Definition at line 63 of file particleDeck.h.
Referenced by printStr().
d_forceDeck
std::vector<inp::PBCData> inp::ParticleDeck::d_forceDeck
Force loading deck.
Definition at line 60 of file particleDeck.h.
Referenced by printStr().
d_gravity
util::Point inp::ParticleDeck::d_gravity
Gravity loading value.
Definition at line 57 of file particleDeck.h.
Referenced by printStr().
d_gravityActive
bool inp::ParticleDeck::d_gravityActive
Gravity loading value.
Definition at line 54 of file particleDeck.h.
Referenced by printStr().
d_icDeck
inp::PICDeck inp::ParticleDeck::d_icDeck
Initial condition deck.
Definition at line 66 of file particleDeck.h.
Referenced by printStr().
d_pNeighDeck
inp::PNeighborDeck inp::ParticleDeck::d_pNeighDeck
Neighbor search data.
Definition at line 51 of file particleDeck.h.
Referenced by printStr().
d_pZones
std::vector<inp::ParticleZone> inp::ParticleDeck::d_pZones
Particle in zones.
Definition at line 39 of file particleDeck.h.
Referenced by printStr().
d_testName
std::string inp::ParticleDeck::d_testName
Specify test name (if any)
Definition at line 69 of file particleDeck.h.
Referenced by printStr().
d_wallForceDirectionCompressiveTest
size_t inp::ParticleDeck::d_wallForceDirectionCompressiveTest
if it is a compressive test, specify force direction on wall
Definition at line 75 of file particleDeck.h.
d_wallIdCompressiveTest
size_t inp::ParticleDeck::d_wallIdCompressiveTest
if it is a compressive test, specify wall id and direction
Definition at line 72 of file particleDeck.h.
d_wZones
std::vector<inp::WallZone> inp::ParticleDeck::d_wZones
Walls.
Definition at line 42 of file particleDeck.h.
Referenced by printStr().
d_zoneToPorWDeck
std::vector<std::pair<std::string, size_t> > inp::ParticleDeck::d_zoneToPorWDeck
Maps particle/wall to corresponding zone.
Definition at line 36 of file particleDeck.h.
d_zoneVec
std::vector<inp::Zone> inp::ParticleDeck::d_zoneVec
All zones.
Definition at line 33 of file particleDeck.h.
The documentation for this struct was generated from the following file:
/home/user/project/src/inp/pdecks/particleDeck.h