PeriDEM: util::SymMatrix3 Struct Reference
util::SymMatrix3 Struct Reference
A structure to represent 3d matrices.
#include <matrix.h>
Public Member Functions
SymMatrix3 ()
Constructor.
SymMatrix3 (const util::Point &diagonal)
Constructor.
SymMatrix3 (const std::vector< double > &m)
Constructor.
SymMatrix3 (const std::vector< std::vector< double >> &m)
Constructor.
SymMatrix3 (const Matrix3 &m)
Constructor.
SymMatrix3 (const SymMatrix3 &m)
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Point operator() (size_t i)
Returns row of matrix.
Point operator() (size_t i) const
Returns row of matrix.
float & operator() (size_t i, size_t j)
Returns element of matrix.
const float & operator() (size_t i, size_t j) const
Returns element of matrix.
float & get (size_t i)
Returns row of matrix.
const float & get (size_t i) const
Returns row of matrix.
void copy (double m[6]) const
Copy.
util::Point dot (const util::Point &v)
Computes the dot product of this matrix with another vector.
std::vector< double > dot (const std::vector< double > &v) const
Computes the dot product of this matrix with another vector.
SymMatrix3 transpose () const
Computes the tranpose of matrix.
double det () const
Computes the determinant of matrix.
SymMatrix3 inv () const
Computes the determinant of matrix.
Data Fields
Data members
0 - xx component 1 - yy component 2 - zz component 3 - yz component 4 - xz component 5 - xy component
float d_data [6] {}
data
Detailed Description
A structure to represent 3d matrices.
Definition at line 258 of file matrix.h.
Constructor & Destructor Documentation
SymMatrix3() [1/6]
util::SymMatrix3::SymMatrix3 () inline
Constructor.
Definition at line 280 of file matrix.h.
                {
     d_data[0] = 0.;
     d_data[1] = 0.;
     d_data[2] = 0.;
     d_data[3] = 0.;
     d_data[4] = 0.;
     d_data[5] = 0.;
   };
References d_data.
Referenced by inv().
SymMatrix3() [2/6]
util::SymMatrix3::SymMatrix3 (const util::Point & diagonal) inline
Constructor.
Parameters
diagonal Diagonal vector
Definition at line 295 of file matrix.h.
{
     d_data[0] = diagonal.d_x;
     d_data[1] = diagonal.d_y;
     d_data[2] = diagonal.d_z;
     d_data[3] = 0.;
     d_data[4] = 0.;
     d_data[5] = 0.;
   };
References d_data, util::Point::d_x, util::Point::d_y, and util::Point::d_z.
SymMatrix3() [3/6]
util::SymMatrix3::SymMatrix3 (const std::vector< double > & m) inline
Constructor.
Parameters
m Matrix in vector template
Definition at line 311 of file matrix.h.
{
     d_data[0] = m[0];
     d_data[1] = m[1];
     d_data[2] = m[2];
     d_data[3] = m[3];
     d_data[4] = m[4];
     d_data[5] = m[5];
   }
References d_data.
SymMatrix3() [4/6]
util::SymMatrix3::SymMatrix3 (const std::vector< std::vector< double >> & m) inline
Constructor.
Parameters
m Matrix
Definition at line 326 of file matrix.h.
{
     d_data[0] = m[0][0];
     d_data[1] = m[1][1];
     d_data[2] = m[2][2];
     d_data[3] = 0.5 * (m[1][2] + m[2][1]);
     d_data[4] = 0.5 * (m[0][2] + m[2][0]);
     d_data[5] = 0.5 * (m[0][1] + m[1][0]);
   }
References d_data.
SymMatrix3() [5/6]
util::SymMatrix3::SymMatrix3 (const Matrix3 & m) inline
Constructor.
Parameters
m Matrix
Definition at line 341 of file matrix.h.
{
     d_data[0] = m(0,0);
     d_data[1] = m(1,1);
     d_data[2] = m(2,2);
     d_data[3] = 0.5 * (m(1,2) + m(2,1));
     d_data[4] = 0.5 * (m(0,2) + m(2,0));
     d_data[5] = 0.5 * (m(0,1) + m(1,0));
   }
References d_data.
SymMatrix3() [6/6]
util::SymMatrix3::SymMatrix3 (const SymMatrix3 & m) inline
Constructor.
Parameters
m Matrix
Definition at line 356 of file matrix.h.
{
     for (size_t i=0; i<6; i++)
       d_data[i] = m.d_data[i];
   }
References d_data.
Member Function Documentation
copy()
void util::SymMatrix3::copy (double m[6]) const inline
Copy.
Parameters
m Symmetric matrix in vector form
Definition at line 443 of file matrix.h.
{
     for (size_t i=0; i<6; i++)
       m[i] = d_data[i];
   }
References d_data.
det()
double util::SymMatrix3::det () const inline
Computes the determinant of matrix.
Returns
det Determinant
Definition at line 484 of file matrix.h.
                      {
     return (*this)(0,0) * ((*this)(1,1) * (*this)(2,2) - (*this)(2,1) * (*this)(1,2)) -
            (*this)(0,1) * ((*this)(1,0) * (*this)(2,2) - (*this)(2,0) * (*this)(1,2)) +
            (*this)(0,2) * ((*this)(1,0) * (*this)(2,1) - (*this)(2,0) * (*this)(1,1));
   }
Referenced by inv().
dot() [1/2]
std::vector<double> util::SymMatrix3::dot (const std::vector< double > & v) const inline
Computes the dot product of this matrix with another vector.
Parameters
v A vector
Returns
Vector Resulting vector
Definition at line 460 of file matrix.h.
{
     auto r = std::vector<double>(3,0.);
     for (size_t i=0; i<3; i++)
       for (size_t j=0; j<3; j++)
         r[i] += (*this)(i,j) * v[j];
     return r;
   }
dot() [2/2]
util::Point util::SymMatrix3::dot (const util::Point & v) inline
Computes the dot product of this matrix with another vector.
Parameters
v A vector
Returns
Vector Resulting vector
Definition at line 454 of file matrix.h.
{
     return {(*this)(0) * v, (*this)(1) * v, (*this)(2) * v};
   }
get() [1/2]
float& util::SymMatrix3::get (size_t i) inline
Returns row of matrix.
Parameters
i Row id
Returns
Row Row
Definition at line 429 of file matrix.h.
{
     return d_data[i];
   }
References d_data.
get() [2/2]
const float& util::SymMatrix3::get (size_t i) const inline
Returns row of matrix.
Parameters
i Row id
Returns
Row Row
Definition at line 434 of file matrix.h.
{
     return d_data[i];
   }
References d_data.
inv()
SymMatrix3 util::SymMatrix3::inv () const inline
Computes the determinant of matrix.
Returns
inv Inverse of m
Definition at line 495 of file matrix.h.
{
     SymMatrix3 m = SymMatrix3();
     auto det_inv = 1. / this->det();
     m(0,0) = det_inv *
              ((*this)(1,1) * (*this)(2,2) - (*this)(2,1) * (*this)(1,2));
     m(0,1) = -det_inv *
              ((*this)(0,1) * (*this)(2,2) - (*this)(2,1) * (*this)(0,2));
     m(0,2) = det_inv *
              ((*this)(0,1) * (*this)(1,2) - (*this)(1,1) * (*this)(0,2));
     m(1,0) = -det_inv *
              ((*this)(1,0) * (*this)(2,2) - (*this)(2,0) * (*this)(1,2));
     m(1,1) = det_inv *
              ((*this)(0,0) * (*this)(2,2) - (*this)(2,0) * (*this)(0,2));
     m(1,2) = -det_inv *
              ((*this)(0,0) * (*this)(1,2) - (*this)(1,0) * (*this)(0,2));
     m(2,0) = det_inv *
              ((*this)(1,0) * (*this)(2,1) - (*this)(2,0) * (*this)(1,1));
     m(2,1) = -det_inv *
              ((*this)(0,0) * (*this)(2,1) - (*this)(2,0) * (*this)(0,1));
     m(2,2) = det_inv *
              ((*this)(0,0) * (*this)(1,1) - (*this)(1,0) * (*this)(0,1));
     return m;
   }
References det(), and SymMatrix3().
operator()() [1/4]
Point util::SymMatrix3::operator() (size_t i) inline
Returns row of matrix.
Parameters
i Row id
Returns
Row Row
Definition at line 398 of file matrix.h.
{
       return {(*this)(i, 0), (*this)(i, 1), (*this)(i, 2)};
   }
operator()() [2/4]
Point util::SymMatrix3::operator() (size_t i) const inline
Returns row of matrix.
Parameters
i Row id
Returns
Row Row
Definition at line 403 of file matrix.h.
{
     return {(*this)(i, 0), (*this)(i, 1), (*this)(i, 2)};
   }
operator()() [3/4]
float& util::SymMatrix3::operator() (size_t i, size_t j) inline
Returns element of matrix.
Parameters
i Row id
j Column id
Returns
Element Element of matrix
Definition at line 414 of file matrix.h.
{
     return d_data[i == j ? i : 6 - i - j];
   }
References d_data.
operator()() [4/4]
const float& util::SymMatrix3::operator() (size_t i, size_t j) const inline
Returns element of matrix.
Parameters
i Row id
j Column id
Returns
Element Element of matrix
Definition at line 419 of file matrix.h.
{
     return d_data[i == j ? i : 6 - i - j];
   }
References d_data.
print()
void util::SymMatrix3::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 390 of file matrix.h.
 { std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string util::SymMatrix3::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 369 of file matrix.h.
{
     std::string tabS = "";
     for (int i = 0; i < nt; i++)
       tabS += "\t";
     std::ostringstream oss;
     for (size_t i=0; i<3; i++)
       oss << tabS << "[" << (*this)(i, 0) << ", " << (*this)(i, 1) << ", "
           << (*this)(i, 2) << "]" << std::endl;
     oss << std::endl;
     return oss.str();
   }
References anonymous_namespace{main.cpp}::oss.
Referenced by print().
transpose()
SymMatrix3 util::SymMatrix3::transpose () const inline
Computes the tranpose of matrix.
Returns
Matrix Transpose of m
Definition at line 474 of file matrix.h.
{
     return (*this);
   }
Field Documentation
d_data
float util::SymMatrix3::d_data[6] {}
data
Definition at line 273 of file matrix.h.
Referenced by copy(), get(), operator()(), and SymMatrix3().
The documentation for this struct was generated from the following file:
/home/user/project/src/util/matrix.h