PeriDEM: inp::WallZone Struct Reference
inp::WallZone Struct Reference
User-input data for wall zone.
#include <zoneDeck.h>
Public Member Functions
WallZone ()
Constructor.
WallZone (const WallZone &wz)
Copy constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
inp::Zone d_zone
Zone data.
std::string d_type
Wall type. If type is "rigid" then the wall in this zone is not meshed.
inp::MaterialDeck d_matDeck
Store material information.
bool d_meshFlag
Specify if we mesh wall.
inp::MeshDeck d_meshDeck
Store mesh information.
bool d_allDofsConstrained
Specify if all dofs are constrained.
Detailed Description
User-input data for wall zone.
Definition at line 211 of file zoneDeck.h.
Constructor & Destructor Documentation
WallZone() [1/2]
inp::WallZone::WallZone () inline
Constructor.
Definition at line 237 of file zoneDeck.h.
      : d_zone(inp::Zone()), d_meshFlag(true), d_matDeck(inp::MaterialDeck()),
        d_meshDeck(inp::MeshDeck()), d_allDofsConstrained(true) {};
WallZone() [2/2]
inp::WallZone::WallZone (const WallZone & wz) inline
Copy constructor.
Parameters
wz Another WallZone object
Definition at line 246 of file zoneDeck.h.
      : d_zone(wz.d_zone), d_type(wz.d_type), d_matDeck(wz.d_matDeck),
        d_meshFlag(wz.d_meshFlag), d_meshDeck(wz.d_meshDeck),
        d_allDofsConstrained(wz.d_allDofsConstrained){};
Member Function Documentation
print()
void inp::WallZone::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 281 of file zoneDeck.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::WallZone::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 258 of file zoneDeck.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS <<  "------- WallZone --------" << std::endl << std::endl;
    oss << d_zone.printStr(nt+1, lvl);
    oss << tabS << "Type = " << d_type << std::endl;
    oss << tabS << "Mesh flag = " << d_meshFlag << std::endl;
    oss << tabS << "BC Type = " << d_meshFlag << std::endl;
    oss << tabS << "All dofs constrained = " << d_allDofsConstrained << std::endl;
    oss << d_matDeck.printStr(nt+1, lvl);
    oss << d_meshDeck.printStr(nt+1, lvl);
    oss << tabS << std::endl;
    return oss.str();
  }
References d_allDofsConstrained, d_matDeck, d_meshDeck, d_meshFlag, d_type, d_zone, util::io::getTabS(), inp::MaterialDeck::printStr(), inp::MeshDeck::printStr(), and inp::Zone::printStr().
Referenced by print().
Field Documentation
d_allDofsConstrained
bool inp::WallZone::d_allDofsConstrained
Specify if all dofs are constrained.
Definition at line 232 of file zoneDeck.h.
Referenced by printStr(), inp::Input::setWallData(), and particle::Wall::Wall().
d_matDeck
inp::MaterialDeck inp::WallZone::d_matDeck
Store material information.
Definition at line 223 of file zoneDeck.h.
Referenced by printStr(), and particle::Wall::Wall().
d_meshDeck
inp::MeshDeck inp::WallZone::d_meshDeck
Store mesh information.
Definition at line 229 of file zoneDeck.h.
Referenced by printStr().
d_meshFlag
bool inp::WallZone::d_meshFlag
Specify if we mesh wall.
Definition at line 226 of file zoneDeck.h.
Referenced by printStr(), and inp::Input::setWallData().
d_type
std::string inp::WallZone::d_type
Wall type. If type is "rigid" then the wall in this zone is not meshed.
Definition at line 220 of file zoneDeck.h.
Referenced by printStr(), and inp::Input::setWallData().
d_zone
inp::Zone inp::WallZone::d_zone
Zone data.
Definition at line 214 of file zoneDeck.h.
Referenced by printStr().
The documentation for this struct was generated from the following file:
/Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/src/inp/pdecks/zoneDeck.h