PeriDEM: util::geometry::BoxPartition Struct Reference
util::geometry::BoxPartition Struct Reference
Defines simple rectangle domain.
#include <geomObjects.h>
Public Member Functions
BoxPartition ()
bool isNear (const BoxPartition &box, const double &tol) const
bool isNear (const util::Point &x, const double &tol) const
void addNode (const size_t &i)
Data Fields
util::Point d_xc
std::pair< util::Point, util::Point > d_box
double d_r
std::vector< size_t > d_nodes
Detailed Description
Defines simple rectangle domain.
Definition at line 31 of file geomObjects.h.
Constructor & Destructor Documentation
BoxPartition()
util::geometry::BoxPartition::BoxPartition () inline
Definition at line 38 of file geomObjects.h.
                  : d_xc(util::Point()),
                    d_box({util::Point(), util::Point()}),
                    d_r(0.) {}
Member Function Documentation
addNode()
void util::geometry::BoxPartition::addNode (const size_t & i) inline
Definition at line 60 of file geomObjects.h.
{
     for (const auto &j : d_nodes)
       if (j == i)
         return;
     d_nodes.push_back(i);
   }
References d_nodes.
isNear() [1/2]
bool util::geometry::BoxPartition::isNear (const BoxPartition & box, const double & tol) const inline
Definition at line 42 of file geomObjects.h.
{
     auto dx = d_xc - box.d_xc;
     return dx.length() < d_r + box.d_r + tol;
   }
References d_r, d_xc, util::Point::length(), and anonymous_namespace{testFeLib.cpp}::tol.
isNear() [2/2]
bool util::geometry::BoxPartition::isNear (const util::Point & x, const double & tol) const inline
Definition at line 47 of file geomObjects.h.
{
     if (util::isLess(x.d_x, d_box.first.d_x - tol) or
         util::isLess(x.d_y, d_box.first.d_y - tol) or
         util::isLess(x.d_z, d_box.first.d_z - tol) or
         util::isGreater(x.d_x, d_box.second.d_x + tol) or
         util::isGreater(x.d_y, d_box.second.d_y + tol) or
         util::isGreater(x.d_z, d_box.second.d_z + tol))
       return false;
     return true;
   }
References d_box, util::Point::d_x, util::Point::d_y, util::Point::d_z, util::isGreater(), util::isLess(), and anonymous_namespace{testFeLib.cpp}::tol.
Field Documentation
d_box
std::pair<util::Point, util::Point> util::geometry::BoxPartition::d_box
Definition at line 34 of file geomObjects.h.
Referenced by isNear().
d_nodes
std::vector<size_t> util::geometry::BoxPartition::d_nodes
Definition at line 36 of file geomObjects.h.
Referenced by addNode().
d_r
double util::geometry::BoxPartition::d_r
Definition at line 35 of file geomObjects.h.
Referenced by isNear().
d_xc
util::Point util::geometry::BoxPartition::d_xc
Definition at line 33 of file geomObjects.h.
Referenced by isNear().
The documentation for this struct was generated from the following file:
/home/user/project/src/util/geomObjects.h