PeriDEM: inp::PNeighborDeck Struct Reference
inp::PNeighborDeck Struct Reference
User-input data for particle neighbor search.
#include <pNeighborDeck.h>
Public Member Functions
PNeighborDeck ()
Constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
std::string d_updateCriteria
Neighbor search update criteria (if any)
double d_sFactor
Neighbor search factor (search length is factor times biggest radius of particle)
double d_sTol
Neighbor search tolerance.
size_t d_neighUpdateInterval
Neighbor update time interval (for contact)
Detailed Description
User-input data for particle neighbor search.
Definition at line 21 of file pNeighborDeck.h.
Constructor & Destructor Documentation
PNeighborDeck()
inp::PNeighborDeck::PNeighborDeck () inline
Constructor.
Definition at line 41 of file pNeighborDeck.h.
      : d_updateCriteria("simple_all"),
        d_sFactor(1.),
        d_sTol(0.),
        d_neighUpdateInterval(1) {};
Member Function Documentation
print()
void inp::PNeighborDeck::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Definition at line 74 of file pNeighborDeck.h.
{ std::cout << printStr(nt, lvl); }
References printStr().
printStr()
std::string inp::PNeighborDeck::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Definition at line 54 of file pNeighborDeck.h.
{
    auto tabS = util::io::getTabS(nt);
    std::ostringstream oss;
    oss << tabS << "------- PNeighborDeck --------" << std::endl << std::endl;
    oss << tabS << "Update criteria  = " << d_updateCriteria << std::endl;
    oss << tabS << "Search factor = " << d_sFactor << std::endl;
    oss << tabS << "Search tolerance = " << d_sTol << std::endl;
    oss << tabS << "Search update interval = " << d_neighUpdateInterval << std::endl;
    oss << tabS << std::endl;
    return oss.str();
  }
References d_neighUpdateInterval, d_sFactor, d_sTol, d_updateCriteria, and util::io::getTabS().
Referenced by print(), and inp::ParticleDeck::printStr().
Field Documentation
d_neighUpdateInterval
size_t inp::PNeighborDeck::d_neighUpdateInterval
Neighbor update time interval (for contact)
Definition at line 36 of file pNeighborDeck.h.
Referenced by printStr().
d_sFactor
double inp::PNeighborDeck::d_sFactor
Neighbor search factor (search length is factor times biggest radius of particle)
Definition at line 28 of file pNeighborDeck.h.
Referenced by printStr().
d_sTol
double inp::PNeighborDeck::d_sTol
Neighbor search tolerance.
Definition at line 33 of file pNeighborDeck.h.
Referenced by printStr().
d_updateCriteria
std::string inp::PNeighborDeck::d_updateCriteria
Neighbor search update criteria (if any)
Definition at line 24 of file pNeighborDeck.h.
Referenced by printStr().
The documentation for this struct was generated from the following file:
/home/user/project/src/inp/pdecks/pNeighborDeck.h