PeriDEM: /Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/test/test_exec/peridem/testPeriDEM.cpp File Reference
testPeriDEM.cpp File Reference
#include <PeriDEMConfig.h>
#include "testPeriDEMLib.h"
#include "util/io.h"
#include "util/parallelUtil.h"
#include <fmt/format.h>
#include <iostream>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 18 of file testPeriDEM.cpp.
{
  // init parallel
  util::parallel::initMpi(argc, argv);
  int mpiSize = util::parallel::mpiSize(), mpiRank = util::parallel::mpiRank();
  util::io::print(fmt::format("Initialized MPI. MPI size = {}, MPI rank = {}\n", mpiSize, mpiRank));
  util::io::print(util::parallel::getMpiStatus()->printStr());
  util::io::InputParser input(argc, argv);
  if (input.cmdOptionExists("-h") or !input.cmdOptionExists("-i")) {
    // print help
    std::cout << argv[0] << " (Version " << MAJOR_VERSION << "."
              << MINOR_VERSION << "." << UPDATE_VERSION
              << ") -i <data-filepath> -nThreads <number of threads to be used in taskflow>" << std::endl;
    exit(EXIT_FAILURE);
  }
  // read input file
  std::string filepath = input.getCmdOption("-i");
  unsigned int nThreads;
  if (input.cmdOptionExists("-nThreads")) nThreads = std::stoi(input.getCmdOption("-nThreads"));
  else {
    nThreads = std::thread::hardware_concurrency();
    util::io::print(fmt::format("Running test with default number of threads = {}\n", nThreads));
  }
  // set number of threads
  util::parallel::initNThreads(nThreads);
  util::io::print(fmt::format("Number of threads = {}\n", util::parallel::getNThreads()));
  // run test
  auto msg = test::testPeriDEM(filepath);
  if (msg == "pass")
    std::cout << "testPeriDEM: Pass\n";
  else {
    std::cerr << "Error: " << msg << "\n";
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
References util::io::InputParser::cmdOptionExists(), util::io::InputParser::getCmdOption(), util::parallel::getMpiStatus(), util::parallel::getNThreads(), util::parallel::initMpi(), util::parallel::initNThreads(), MAJOR_VERSION, MINOR_VERSION, util::parallel::mpiRank(), util::parallel::mpiSize(), util::io::print(), test::testPeriDEM(), and UPDATE_VERSION.