PeriDEM: /Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/test/test_exec/util/testUtil.cpp File Reference
testUtil.cpp File Reference
#include "testUtilLib.h"
#include "util/io.h"
#include "util/parallelUtil.h"
#include <fmt/format.h>
#include <iostream>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 17 of file testUtil.cpp.
{
  // init parallel
  util::parallel::initMpi(argc, argv);
  int mpiSize = util::parallel::mpiSize(), mpiRank = util::parallel::mpiRank();
  util::io::print(fmt::format("Initialized MPI. MPI size = {}, MPI rank = {}\n", mpiSize, mpiRank));
  util::io::print(util::parallel::getMpiStatus()->printStr());
  test::testUtilMethods();
  return EXIT_SUCCESS;
}
References util::parallel::getMpiStatus(), util::parallel::initMpi(), util::parallel::mpiRank(), util::parallel::mpiSize(), util::io::print(), and test::testUtilMethods().