PeriDEM: /Users/prashant/Dropbox/Systems/MacLap/work/new_peridem_works/temp/push_docs_to_gh-pages/PeriDEM/test/test_exec/particle/testParticle.cpp File Reference
testParticle.cpp File Reference
#include "testParticleLib.h"
#include "util/io.h"
#include "util/parallelUtil.h"
#include <fmt/format.h>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 16 of file testParticle.cpp.
           {
  // init parallel
  util::parallel::initMpi();
  int mpiSize = util::parallel::mpiSize(), mpiRank = util::parallel::mpiRank();
  util::io::print(fmt::format("Initialized MPI. MPI size = {}, MPI rank = {}\n", mpiSize, mpiRank));
  util::io::print(util::parallel::getMpiStatus()->printStr());
  test::testTransform();
  return EXIT_SUCCESS;
}
References util::parallel::getMpiStatus(), util::parallel::initMpi(), util::parallel::mpiRank(), util::parallel::mpiSize(), util::io::print(), and test::testTransform().