# -------------------------------------------
# Copyright (c) 2021 - 2026 Prashant K. Jha
# -------------------------------------------
# PeriDEM https://github.com/prashjha/PeriDEM
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE)

add_subdirectory(util)
add_subdirectory(fe)
add_subdirectory(nsearch)
add_subdirectory(contact)
add_subdirectory(parallelcomp)
add_subdirectory(meshpartitioning)
add_subdirectory(mesh_gen)
add_subdirectory(inp)
