# -------------------------------------------
# Copyright (c) 2021 - 2024 Prashant K. Jha
# -------------------------------------------
# PeriDEM https://github.com/prashjha/PeriDEM
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE)

# base ubuntu image with essentials and vtk
FROM prashjha/peridem-base-bionic:latest

# Set metadata
LABEL maintainer="Prashant K. Jha <pjha.sci@gmail.com>"
LABEL description="PeriDEM docker image"

## build command
## docker build -t prashjha/peridem-bionic:latest -f ./Dockerfile-bionic . 2>&1 | tee log-peridem-bionic.txt

# -----------------------
# setup user (for mpi tests)
# username - user
# password - password
# add only if the user does not exist
# -----------------------
RUN if id user >/dev/null 2>&1; then echo "User 'user' already exists"; else echo "User 'user' does not exist so creating user 'user'" && useradd -m user && yes password | passwd user && usermod -s /bin/bash user; fi

# change user
USER user
WORKDIR /home/user

# -----------------------
# setup git pull method
# -----------------------
RUN git config --global url."https://github.com/".insteadOf git@github.com: && \
    git config --global url."https://".insteadOf git://

# -----------------------
# build peridem
# -----------------------
RUN git clone https://github.com/prashjha/PeriDEM.git &&\
    cd PeriDEM &&\
    git submodule update --init --recursive && \
    mkdir -p build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DEnable_Tests=ON \
          -DDisable_Docker_MPI_Tests=OFF \
          -DVTK_DIR=/usr/local/lib/cmake/vtk-9.3 \
          -DMETIS_DIR=/usr/lib \
          .. && \
    make -j 2 && \
    make install

