# -------------------------------------------
# Copyright (c) 2021 - 2026 Prashant K. Jha
# -------------------------------------------
# PeriDEM https://github.com/prashjha/PeriDEM
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE)

# C++ drivers (Enable_Examples). JSON/deck demos under compressive/ use bin/PeriDEM.
add_subdirectory(twop_circ_contact)
add_subdirectory(ellipse_triangle)
