#!/usr/bin/env python3
# -------------------------------------------
# Copyright (c) 2021 - 2026 Prashant K. Jha
# -------------------------------------------
# PeriDEM https://github.com/prashjha/PeriDEM
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE)

"""Compare the Python and C++ decks and runs for the example problems.

Each example under ``examples/`` has a ``problem.py`` that builds its deck with
:class:`peridem.Deck`. Two independent things are checked here:

**deck**
    The Python deck against the deck the corresponding C++ driver writes, key
    by key, including every floating-point value. This measures whether the
    Python setup reproduces the C++ setup. It applies only to examples that
    have a C++ driver.

**run**
    The Python deck run twice, once through ``bin/PeriDEM`` in a separate
    process and once through the in-process interface, into separate
    directories, then compared node by node. This measures whether the
    interface and the executable give the same result.

No case reads a deck generated by the C++ side. A deck compared with itself
yields no information.

Run it directly for a table::

    PYTHONPATH=build/linux/python python3 python/tests/test_example_parity.py
    PYTHONPATH=build/linux/python python3 python/tests/test_example_parity.py -k attrition

The two full-size Silling plate cases are skipped unless
``PERIDEM_PARITY_FULL=1`` is set. Their C++ driver takes about 20 minutes to
build the neighbour lists.
"""

from __future__ import annotations

import contextlib
import importlib.util
import inspect
import os
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
if str(REPO / "python") not in sys.path:
    for _b in (REPO / "build/linux/python", REPO / "build/python"):
        if (_b / "peridem").is_dir():
            sys.path.insert(0, str(_b))
            break

import peridem  # noqa: E402
from peridem.parity import (  # noqa: E402
    compare_decks,
    find_peridem_binary,
    run_pair,
)

EXAMPLES = REPO / "examples"
BUILD = REPO / "build/linux"
FULL = os.environ.get("PERIDEM_PARITY_FULL", "0") == "1"


def load_problem(rel: str):
    """Import the ``problem.py`` of an example by path."""
    path = EXAMPLES / rel / "problem.py"
    name = "peridem_example_" + rel.replace("/", "_")
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


@dataclass
class Case:
    """One example, its short-run settings, and its C++ reference driver."""

    name: str
    example: str
    #: kwargs for problem.build_deck for the shortened comparison run
    short: dict[str, Any] = field(default_factory=dict)
    #: C++ driver relative to the build dir, and the args that make it write
    #: the same deck. ``{out}`` / ``{inp}`` are filled in.
    driver: str | None = None
    driver_args: list[str] = field(default_factory=list)
    #: kwargs for build_deck when comparing against that driver's deck
    deck_args: dict[str, Any] = field(default_factory=dict)
    n_threads: int = 1
    heavy: bool = False
    #: "out_inp": driver takes -outputDir/-inputDir separately;
    #: "base": driver takes one -outputDir and makes out/ and inp/ under it.
    driver_layout: str = "out_inp"
    #: False when the example reads committed .msh files rather than meshing
    #: in-process; the run then must not be pointed at an empty mesh dir.
    generates_mesh: bool = True
    #: also check that seeding the pre-notch from Python cuts the same number
    #: of bonds the C++ driver reports
    prenotch: bool = False

    def build(self, mod, output: str, **extra: Any):
        kwargs = dict(self.short)
        kwargs.update(extra)
        # Not every example takes a mesh_dir (some mesh entirely in memory).
        accepted = inspect.signature(mod.build_deck).parameters
        kwargs = {k: v for k, v in kwargs.items() if k in accepted}
        return mod.build_deck(output, **kwargs)


@contextlib.contextmanager
def quiet(log: Path | None):
    """Send the solver's own stdout/stderr to a log file, not the terminal.

    The C++ side writes on file descriptors 1 and 2, so redirecting
    ``sys.stdout`` is not enough.
    """
    if log is None:
        yield
        return
    log.parent.mkdir(parents=True, exist_ok=True)
    sys.stdout.flush()
    sys.stderr.flush()
    saved = os.dup(1), os.dup(2)
    fd = os.open(log, os.O_WRONLY | os.O_CREAT | os.O_TRUNC)
    try:
        os.dup2(fd, 1)
        os.dup2(fd, 2)
        yield
    finally:
        sys.stdout.flush()
        sys.stderr.flush()
        os.dup2(saved[0], 1)
        os.dup2(saved[1], 2)
        for f in (fd, *saved):
            os.close(f)


CASES: list[Case] = [
    Case(
        name="twop_circ_contact",
        example="PeriDEM/twop_circ_contact",
        short=dict(final_time=1.33e-5, num_steps=40),
        driver="examples/PeriDEM/twop_circ_contact/example_twop_circ_contact",
        driver_args=["-numSteps", "40", "-finalTime", "0.0000133"],
        deck_args=dict(final_time=1.33e-5, num_steps=40),
    ),
    Case(
        name="ellipse_triangle",
        example="PeriDEM/ellipse_triangle",
        short=dict(final_time=4.0e-6, num_steps=40),
        driver="examples/PeriDEM/ellipse_triangle/example_ellipse_triangle",
        driver_args=["-numSteps", "40", "-finalTime", "0.000004"],
        deck_args=dict(final_time=4.0e-6, num_steps=40),
    ),
    Case(
        name="compressive_n12",
        example="PeriDEM/compressive/n12",
        short=dict(final_time=4.0e-6, num_steps=20),
        driver="test/test_data/peridem/jha2021_comp_n50/Test_PeriDEM_jha2021_comp_n50",
        driver_args=["-numSteps", "20", "-finalTime", "0.000004",
                     "-noRequireContact"],
        deck_args=dict(final_time=4.0e-6, num_steps=20),
        n_threads=4,
    ),
    Case(
        name="peridynamics_circle",
        example="Peridynamics/circle",
        short=dict(final_time=2.0e-4, num_steps=400, output_interval=100),
    ),
    Case(
        name="peridynamics_rectangle",
        example="Peridynamics/rectangle",
        short=dict(final_time=2.0e-4, num_steps=400, output_interval=100),
    ),
    Case(
        name="attrition_sim1",
        generates_mesh=False,
        example="PeriDEM/attrition/sim1_rotating_cylinder",
        short=dict(final_time=2.0e-4, num_steps=2000, output_interval=1000),
        n_threads=4,
    ),
    Case(
        name="attrition_sim2",
        generates_mesh=False,
        example="PeriDEM/attrition/sim2_thin_container",
        short=dict(final_time=2.0e-4, num_steps=2000, output_interval=1000),
        n_threads=4,
    ),
    Case(
        name="silling_kw_quick",
        example="PeriDEM/silling_kw",
        short=dict(quick=True, final_time=2.0e-6, num_steps=200),
        driver="test/test_data/peridem/notched_impact_inbuilt/"
               "Test_PeriDEM_notched_impact_inbuilt",
        driver_layout="base",
        driver_args=["-quick"],
        deck_args=dict(quick=True, final_time=None, num_steps=None),
        prenotch=True,
        n_threads=4,
    ),
    Case(
        name="silling_kw_2d",
        example="PeriDEM/silling_kw",
        short=dict(final_time=1.0e-7, num_steps=40),
        driver="test/test_data/peridem/notched_impact_inbuilt/"
               "Test_PeriDEM_notched_impact_inbuilt",
        driver_layout="base",
        driver_args=["-finalTime", "1e-7"],
        deck_args=dict(final_time=1.0e-7),
        prenotch=True,
        n_threads=8,
        heavy=True,
    ),
    Case(
        name="silling_kw_3d",
        example="PeriDEM/silling_kw",
        short=dict(dim3=True, final_time=5.0e-9, num_steps=2),
        driver="test/test_data/peridem/notched_impact_inbuilt/"
               "Test_PeriDEM_notched_impact_inbuilt",
        driver_layout="base",
        driver_args=["-dim3", "-finalTime", "5e-9"],
        deck_args=dict(dim3=True, final_time=5.0e-9),
        prenotch=True,
        n_threads=8,
        heavy=True,
    ),
]

BY_NAME = {c.name: c for c in CASES}


def _driver_path(case: Case) -> Path | None:
    if case.driver is None:
        return None
    p = BUILD / case.driver
    return p if p.is_file() and os.access(p, os.X_OK) else None


def check_deck(case: Case, work: Path) -> tuple[str, str]:
    """Run the C++ driver, then diff its deck against the Python one.

    Returns the verdict and the driver's own output.
    """
    import subprocess

    exe = _driver_path(case)
    if exe is None:
        return "no C++ driver", ""
    out, inp = work / "cpp_ref/out", work / "cpp_ref/inp"
    out.mkdir(parents=True, exist_ok=True)
    inp.mkdir(parents=True, exist_ok=True)
    if case.driver_layout == "base":
        cmd = [str(exe), "-nThreads", str(case.n_threads),
               "-outputDir", str(work / "cpp_ref"), *case.driver_args]
    else:
        cmd = [str(exe), "-nThreads", str(case.n_threads),
               "-outputDir", str(out), "-inputDir", str(inp),
               *case.driver_args]
    # -deckOnly stops the driver right after it writes the deck. The
    # pre-notch check needs the bond count the driver reports at init, so
    # those cases let it run (their -finalTime keeps that short).
    if not case.prenotch:
        cmd.append("-deckOnly")
    proc = subprocess.run(cmd, cwd=work, capture_output=True, text=True)
    log = proc.stdout + proc.stderr
    ref = inp / "input.json"
    if not ref.is_file():
        tail = "\n".join(log.splitlines()[-15:])
        raise RuntimeError(f"{case.name}: driver wrote no deck\n{tail}")

    mod = load_problem(case.example)
    py = case.build(mod, str(out) + "/", mesh_dir=inp, **case.deck_args)
    diff = compare_decks(ref, py.to_dict(), rtol=1e-14)
    if not diff.equal:
        raise AssertionError(f"{case.name}: {diff}")
    return "identical", log


def check_prenotch(case: Case, work: Path, driver_log: str) -> str:
    """Seed the pre-notch from Python; compare to the count the driver cut."""
    import re

    m = re.search(r"prenotch=(\d+)", driver_log)
    if not m:
        return "driver reported none"
    expected = int(m.group(1))

    mod = load_problem(case.example)
    inp = work / "prenotch/inp"
    inp.mkdir(parents=True, exist_ok=True)
    deck = case.build(mod, str(work / "prenotch/out") + "/", mesh_dir=inp,
                      **case.deck_args)
    (work / "prenotch/out").mkdir(parents=True, exist_ok=True)
    peridem.init(n_threads=case.n_threads)
    sim = deck.simulation(workdir=work / "prenotch")
    sim.setup()
    got = mod.seed_prenotch(sim, deck.extra_info)
    if got != expected:
        raise AssertionError(
            f"{case.name}: pre-notch cut {got} bonds, C++ cut {expected}")
    return f"{got} bonds"


def check_run(case: Case, work: Path):
    """Run the Python deck through bin/PeriDEM and through the interface."""
    mod = load_problem(case.example)
    extra: dict[str, Any] = {}
    if case.generates_mesh:
        # Generated meshes are written under the temporary directory.
        (work / "meshes").mkdir(parents=True, exist_ok=True)
        extra["mesh_dir"] = work / "meshes"
    deck = case.build(mod, "out/", **extra)
    return run_pair(deck, work / "pair", n_threads=case.n_threads)


def run_case(case: Case, keep: Path | None = None,
             log: bool = False) -> dict[str, Any]:
    root = Path(keep) / case.name if keep else None
    ctx = tempfile.TemporaryDirectory() if root is None else None
    work = root if root is not None else Path(ctx.name)  # type: ignore[union-attr]
    work.mkdir(parents=True, exist_ok=True)
    try:
        with quiet(work / "solver.log" if log else None):
            deck_status, driver_log = check_deck(case, work)
            notch = (check_prenotch(case, work, driver_log)
                     if case.prenotch else "")
            res = check_run(case, work)
        return {"case": case.name, "deck": deck_status, "result": res,
                "prenotch": notch,
                "log": work / "solver.log" if log else None}
    finally:
        if ctx is not None:
            ctx.cleanup()


# ---------------------------------------------------------------------------
# pytest entry points
# ---------------------------------------------------------------------------

try:  # pragma: no cover - only when pytest is installed
    import pytest

    _selected = [c for c in CASES if FULL or not c.heavy]

    @pytest.mark.parametrize("case", _selected, ids=lambda c: c.name)
    def test_example_parity(case: Case) -> None:
        try:
            find_peridem_binary()
        except FileNotFoundError as exc:
            pytest.skip(str(exc))
        info = run_case(case)
        res = info["result"]
        assert res.report, f"{case.name}: no fields compared"
        assert res.max_linf == 0.0, (
            f"{case.name}: fields differ\n{res.table(case.name)}")

except ImportError:  # pragma: no cover
    pass


# ---------------------------------------------------------------------------
# Direct run
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    import argparse

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("-k", "--select", action="append", default=[],
                   help="only cases whose name contains this (repeatable)")
    p.add_argument("--full", action="store_true",
                   help="include the heavy full-size cases")
    p.add_argument("--keep", metavar="DIR", default=None,
                   help="keep the run directories under DIR")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="let the solver write to the terminal")
    args = p.parse_args(argv)

    cases = [c for c in CASES if args.full or FULL or not c.heavy]
    if args.select:
        cases = [c for c in cases
                 if any(s in c.name for s in args.select)]
    if not cases:
        print("no cases selected", file=sys.stderr)
        return 2

    try:
        exe = find_peridem_binary()
    except FileNotFoundError as exc:
        print(exc, file=sys.stderr)
        return 2
    print(f"peridem {peridem.version()}   bin/PeriDEM {exe}\n")

    rows: list[tuple[str, str, str, str, str]] = []
    failures = 0
    for case in cases:
        print(f"[{case.name}] ...", flush=True)
        try:
            info = run_case(case, keep=Path(args.keep) if args.keep else None,
                            log=not args.verbose)
        except Exception as exc:  # noqa: BLE001 - report and continue
            failures += 1
            rows.append((case.name, "ERROR", "-", "-",
                         str(exc).splitlines()[0]))
            print(f"  FAILED: {exc}", file=sys.stderr)
            continue
        res = info["result"]
        ok = res.max_linf == 0.0
        failures += 0 if ok else 1
        nodes = int(next(iter(res.report.values()))["n"]) if res.report else 0
        rows.append((case.name, info["deck"], info.get("prenotch") or "-",
                     f"{nodes}", f"{res.max_linf:.3e}"))
        print(res.table(case.name))
        print()

    width = max(len(r[0]) for r in rows) + 2
    total = width + 60
    print("=" * total)
    print(f"{'case':<{width}}{'deck vs C++':<16}{'prenotch':<16}"
          f"{'nodes':>8}{'max Linf':>16}")
    print("-" * total)
    for name, deck, notch, nodes, linf in rows:
        print(f"{name:<{width}}{deck:<16}{notch:<16}{nodes:>8}{linf:>16}")
    print("=" * total)
    print("all identical" if failures == 0 else f"{failures} case(s) failed")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
