PeriDEM: fe::QuadElem Class Reference
fe::QuadElem Class Reference
A class for mapping and quadrature related operations for bi-linear quadrangle element.
#include <quadElem.h>
Public Member Functions
QuadElem (size_t order)
Constructor for quadrangle element.
double elemSize (const std::vector< util::Point > &nodes) override
Returns the area of element.
std::vector< fe::QuadData > getQuadDatas (const std::vector< util::Point > &nodes) override
Get vector of quadrature data.
std::vector< fe::QuadData > getQuadPoints (const std::vector< util::Point > &nodes) override
Get vector of quadrature data.
Public Member Functions inherited from fe::BaseElem
BaseElem (size_t order, size_t element_type)
Constructor.
size_t getElemType ()
Get element type.
size_t getQuadOrder ()
Get order of quadrature approximation.
size_t getNumQuadPoints ()
Get number of quadrature points in the data.
virtual std::vector< double > getShapes (const util::Point &p, const std::vector< util::Point > &nodes)
Returns the values of shape function at point p.
virtual std::vector< std::vector< double > > getDerShapes (const util::Point &p, const std::vector< util::Point > &nodes)
Returns the values of derivative of shape function at point p.
Private Member Functions
std::vector< double > getShapes (const util::Point &p) override
Returns the values of shape function at point p on reference element.
std::vector< std::vector< double > > getDerShapes (const util::Point &p) override
Returns the values of derivative of shape function at point p on reference element.
double getJacobian (const util::Point &p, const std::vector< util::Point > &nodes, std::vector< std::vector< double >> *J) override
Computes the Jacobian of map .
void init () override
Compute the quadrature points for quadrangle element.
Detailed Description
A class for mapping and quadrature related operations for bi-linear quadrangle element.
The reference quadrangle element is given by vertices .
The shape functions at point are
Derivative of shape functions at point are as follows
Map is given by
where are vertices of element .
Jacobian of the map is given by
and determinant of Jacobian is
Constructor & Destructor Documentation
QuadElem()
fe::QuadElem::QuadElem (size_t order) explicit
Constructor for quadrangle element.
Parameters
order Order of quadrature point approximation
Member Function Documentation
elemSize()
double fe::QuadElem::elemSize (const std::vector< util::Point > & nodes) override virtual
Returns the area of element.
If quadrangle is given by points then the area is
where are the x and y component of point .
Note that area and Jacobian of map are related as
where and is the Jacobian of map at point .
Parameters
nodes Vertices of element
Returns
vector Vector of shape functions at point p
Implements fe::BaseElem.
getDerShapes()
std::vector< std::vector< double > > fe::QuadElem::getDerShapes (const util::Point & p) override private virtual
Returns the values of derivative of shape function at point p on reference element.
Parameters
p Location of point
Returns
vector Vector of derivative of shape functions
Implements fe::BaseElem.
Referenced by getJacobian(), and init().
getJacobian()
double fe::QuadElem::getJacobian (const util::Point & p, const std::vector< util::Point > & nodes, std::vector< std::vector< double >> * J) override private virtual
Computes the Jacobian of map .
Parameters
p Location of point in reference element
nodes Vertices of element
J Matrix to store the Jacobian (if not nullptr)
Returns
det(J) Determinant of the Jacobain
Implements fe::BaseElem.
Referenced by getQuadDatas(), and getQuadPoints().
getQuadDatas()
std::vector< fe::QuadData > fe::QuadElem::getQuadDatas (const std::vector< util::Point > & nodes) override virtual
Get vector of quadrature data.
Given element vertices, this method returns the list of quadrature point and essential quantities at quadrature points. Here, order of quadrature approximation is set in the constructor. List of data
quad point
quad weight
shape function evaluated at quad point
derivative of shape function evaluated at quad point
Jacobian matrix
determinant of the Jacobian
Let is the given element with vertices and let is the reference element.
To compute quadrature point, we first compute the quadrature points on , and then map the point on to the point on using the map .
To compute the quadrature weight, we compute the quadrature weight associated to the quadrature point in reference triangle . Suppose is the quadrature weight associated to quadrature point , then the quadrature point associated to the mapped point is given by
where is the determinant of the Jacobian of map . is the value of at point .
We compute shape functions associated to at the quadrature point using formula
To compute the derivatives of shape functions such as associated to , we use the relation between derivatives of shape function in and described in fe::TriElem::getDerShapes.
Parameters
nodes Vector of vertices of an element
Returns
vector Vector of QuadData
Implements fe::BaseElem.
getQuadPoints()
std::vector< fe::QuadData > fe::QuadElem::getQuadPoints (const std::vector< util::Point > & nodes) override virtual
Get vector of quadrature data.
Given element vertices, this method returns the list of quadrature point and essential quantities at quadrature points. Here, order of quadrature approximation is set in the constructor. List of data
quad point
quad weight
shape function evaluated at quad point
This function is lite version of QuadElem::getQuadDatas.
Parameters
nodes Vector of vertices of an element
Returns
vector Vector of QuadData
Implements fe::BaseElem.
getShapes()
std::vector< double > fe::QuadElem::getShapes (const util::Point & p) override private virtual
Returns the values of shape function at point p on reference element.
Parameters
p Location of point
Returns
vector Vector of shape functions at point p
Implements fe::BaseElem.
Referenced by init().
The documentation for this class was generated from the following files:
/home/prashant/work/peridem_works/PeriDEM_docs/src/fe/quadElem.h
/home/prashant/work/peridem_works/PeriDEM_docs/src/fe/quadElem.cpp