PeriDEM: model::ModelData Class Reference
model::ModelData Class Reference
Explicit
A class to store model data.
#include <modelData.h>
Public Member Functions
ModelData (inp::Input *deck)
Constructor.
particle::BaseParticle *& getBaseParticle (size_t i)
Get pointer to base particle.
const particle::BaseParticle * getBaseParticle (size_t i) const
particle::Particle *& getParticle (size_t i)
Get pointer to particle (excluding wall)
const particle::Particle * getParticle (size_t i) const
particle::Wall *& getWall (size_t i)
Get pointer to wall.
const particle::Wall * getWall (size_t i) const
double getDensity (size_t i)
Get density of particle.
double getHorizon (size_t i)
Get horizon of particle.
size_t & getPtId (size_t i)
Get particle id given the location in particle list.
const size_t & getPtId (size_t i) const
void setPtId (size_t i, const size_t &id)
Set particle id given the location in particle list.
Get and set reference coordinate
util::Point & getXRef (size_t i)
Get reference coordinate of the node.
const util::Point & getXRef (size_t i) const
void setXRef (size_t i, const util::Point &x)
Set reference coordinate of the node.
void addXRef (size_t i, const util::Point &x)
Add reference coordinate of the node.
void setXRef (size_t i, int dof, double x)
Set specific reference coordinate of the node.
void addXRef (size_t i, int dof, double x)
Add specific reference coordinate of the node.
Get and set current coordinate
util::Point & getX (size_t i)
Get current coordinate of the node.
const util::Point & getX (size_t i) const
void setX (size_t i, const util::Point &x)
Set current coordinate of the node.
void addX (size_t i, const util::Point &x)
Add current coordinate of the node.
void setX (size_t i, int dof, double x)
Set specific current coordinate of the node.
void addX (size_t i, int dof, double x)
Add to specific current coordinate of the node.
Get and set displacement
util::Point & getU (size_t i)
Get displacement of the node.
const util::Point & getU (size_t i) const
void setU (size_t i, const util::Point &u)
Set displacement of the node.
void addU (size_t i, const util::Point &u)
Add to displacement of the node.
void setU (size_t i, int dof, double u)
Set displacement of the node.
void addU (size_t i, int dof, double u)
Add to displacement of the node.
Get and set velocity
util::Point & getV (size_t i)
Get velocity of the node.
const util::Point & getV (size_t i) const
void setV (size_t i, const util::Point &v)
Set velocity of the node.
void addV (size_t i, const util::Point &v)
Add to velocity of the node.
void setV (size_t i, int dof, double v)
Set velocity of the node.
void addV (size_t i, int dof, double v)
Add to velocity of the node.
Get and set force
util::Point & getF (size_t i)
Get force of the node.
const util::Point & getF (size_t i) const
void setF (size_t i, const util::Point &f)
Set force of the node.
void addF (size_t i, const util::Point &f)
Add to force of the node.
void setF (size_t i, int dof, double f)
Set force of the node.
void addF (size_t i, int dof, double f)
Add to force of the node.
Get and set volume
double & getVol (size_t i)
Get volume of the node.
const double & getVol (size_t i) const
void setVol (size_t i, const double &vol)
Set volume of the node.
void addVol (size_t i, const double &vol)
Add to volume of the node.
Get and set fixity
uint8_t & getFix (size_t i)
Get fixity of the node.
const uint8_t & getFix (size_t i) const
void setFix (size_t i, const unsigned int &dof, const bool &flag)
Set fixity of the node.
Get and set mx
double & getMx (size_t i)
Get weighted-volume (mx) of the node.
const double & getMx (size_t i) const
void setMx (size_t i, const double &mx)
Set weighted-volume (mx) of the node.
void addMx (size_t i, const double &mx)
Add to weighted-volume (mx) of the node.
Get and set thetax
double & getThetax (size_t i)
Get volumetric deformation (thetax) of the node.
const double & getThetax (size_t i) const
void setThetax (size_t i, const double &thetax)
Set volumetric deformation (thetax) of the node.
void addThetax (size_t i, const double &thetax)
Add to volumetric deformation (thetax) of the node.
Data Fields
size_t d_n
Current time step.
double d_time
Current time.
size_t d_infoN
Print log step interval.
inp::Input * d_input_p
Pointer to Input object.
std::shared_ptr< inp::ModelDeck > d_modelDeck_p
Model deck.
std::shared_ptr< inp::RestartDeck > d_restartDeck_p
Restart deck.
std::shared_ptr< inp::OutputDeck > d_outputDeck_p
Output deck.
std::shared_ptr< inp::ParticleDeck > d_pDeck_p
Particle deck.
std::shared_ptr< inp::ContactDeck > d_cDeck_p
Contact deck.
bool d_stop
flag to stop the simulation midway
double d_hMax
Minimum mesh over all particles and walls.
double d_hMin
Maximum mesh over all particles and walls.
double d_maxContactR
Maximum contact radius between over pairs of particles and walls.
std::vector< std::shared_ptr< particle::RefParticle > > d_rParticles
Pointer to reference particle.
std::vector< particle::BaseParticle * > d_allParticles
List of particles + walls.
std::vector< particle::Particle * > d_particles
List of particles.
std::vector< particle::Wall * > d_walls
List of particles.
std::vector< std::vector< size_t > > d_zInfo
Zone information of particles.
std::unique_ptr< loading::ParticleULoading > d_uLoading_p
Pointer to displacement Loading object.
std::unique_ptr< loading::ParticleFLoading > d_fLoading_p
Pointer to force Loading object.
std::unique_ptr< geometry::Fracture > d_fracture_p
Fracture state of bonds.
std::unique_ptr< NSearch > d_nsearch_p
Pointer to nsearch.
std::vector< util::Point > d_xRef
reference positions of the nodes
std::vector< util::Point > d_x
Current positions of the nodes.
std::vector< util::Point > d_u
Displacement of the nodes.
std::vector< util::Point > d_v
Velocity of the nodes.
std::vector< util::Point > d_f
Total force on the nodes.
std::vector< double > d_vol
Nodal volumes.
std::vector< size_t > d_ptId
Global node to particle id (walls are assigned id after last particle id)
std::vector< std::vector< size_t > > d_neighC
Neighbor data for contact forces.
std::vector< std::vector< size_t > > d_neighPd
Neighbor data for peridynamic forces.
std::vector< std::vector< float > > d_neighPdSqdDist
Square distance neighbor data for peridynamic forces.
std::vector< uint8_t > d_fix
Vector of fixity mask of each node.
std::vector< uint8_t > d_forceFixity
Vector of fixity mask of each node for force.
std::vector< double > d_thetaX
Dilation.
std::vector< double > d_mX
Weighted volume.
std::vector< size_t > d_fPdCompNodes
List of global nodes on which force (peridynamic/internal) is to be computed.
std::vector< size_t > d_fContCompNodes
List of global nodes on which force (contact) is to be computed.
std::vector< float > d_Z
Damage at nodes.
Detailed Description
A class to store model data.
Constructor & Destructor Documentation
ModelData()
model::ModelData::ModelData (inp::Input * deck) inline
Constructor.
Parameters
deck Input deck
Member Function Documentation
addF() [1/2]
void model::ModelData::addF (size_t i, const util::Point & f) inline
Add to force of the node.
Parameters
i Global id of node
f Force to add
addF() [2/2]
void model::ModelData::addF (size_t i, int dof, double f) inline
Add to force of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
f Force to add
addMx()
void model::ModelData::addMx (size_t i, const double & mx) inline
Add to weighted-volume (mx) of the node.
Parameters
i Global id of node
mx Weighted-volume to add
addThetax()
void model::ModelData::addThetax (size_t i, const double & thetax) inline
Add to volumetric deformation (thetax) of the node.
Parameters
i Global id of node
thetax Volumetric deformation to add
addU() [1/2]
void model::ModelData::addU (size_t i, const util::Point & u) inline
Add to displacement of the node.
Parameters
i Global id of node
u Displacement to add
addU() [2/2]
void model::ModelData::addU (size_t i, int dof, double u) inline
Add to displacement of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
u Displacement to add
addV() [1/2]
void model::ModelData::addV (size_t i, const util::Point & v) inline
Add to velocity of the node.
Parameters
i Global id of node
v Velocity to add
addV() [2/2]
void model::ModelData::addV (size_t i, int dof, double v) inline
Add to velocity of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
v Velocity to add
addVol()
void model::ModelData::addVol (size_t i, const double & vol) inline
Add to volume of the node.
Parameters
i Global id of node
vol Volume to add
addX() [1/2]
void model::ModelData::addX (size_t i, const util::Point & x) inline
Add current coordinate of the node.
Parameters
i Global id of node
x Current coordinate to add
addX() [2/2]
void model::ModelData::addX (size_t i, int dof, double x) inline
Add to specific current coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Current coordinate to add
addXRef() [1/2]
void model::ModelData::addXRef (size_t i, const util::Point & x) inline
Add reference coordinate of the node.
Parameters
i Global id of node
x Reference coordinate to add
addXRef() [2/2]
void model::ModelData::addXRef (size_t i, int dof, double x) inline
Add specific reference coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Reference coordinate to add
getBaseParticle()
particle::BaseParticle* & model::ModelData::getBaseParticle (size_t i) inline
Get pointer to base particle.
Parameters
i Location in the particle list
Returns
Pointer Pointer to base particle
Referenced by rw::writer::VtkParticleWriter::appendNodes(), model::DEMModel::computeContactForces(), model::DEMModel::computeForces(), and model::DEMModel::init().
getDensity()
double model::ModelData::getDensity (size_t i)
Get density of particle.
Parameters
i Location in the particle list
Returns
rho Density
Referenced by model::DEMModel::computeForces(), and model::DEMModel::integrateCD().
getF()
util::Point& model::ModelData::getF (size_t i) inline
Get force of the node.
Parameters
i Global id of node
Returns
f Force
getFix()
uint8_t& model::ModelData::getFix (size_t i) inline
Get fixity of the node.
Parameters
i Global id of node
Returns
flag Fixity
getHorizon()
double model::ModelData::getHorizon (size_t i)
Get horizon of particle.
Parameters
i Location in the particle list
Returns
eps Horizon
getMx()
double& model::ModelData::getMx (size_t i) inline
Get weighted-volume (mx) of the node.
Parameters
i Global id of node
Returns
mx Weighted-volume
getParticle()
particle::Particle* & model::ModelData::getParticle (size_t i) inline
Get pointer to particle (excluding wall)
Parameters
i Location in the particle list
Returns
Pointer Pointer to particle
getPtId()
size_t& model::ModelData::getPtId (size_t i) inline
Get particle id given the location in particle list.
Parameters
i Location in the particle list
Returns
Id Particle id
Referenced by rw::writer::VtkParticleWriter::appendNodes(), model::DEMModel::computeContactForces(), and model::DEMModel::computeForces().
getThetax()
double& model::ModelData::getThetax (size_t i) inline
Get volumetric deformation (thetax) of the node.
Parameters
i Global id of node
Returns
thetax Volumetric deformation
getU()
util::Point& model::ModelData::getU (size_t i) inline
Get displacement of the node.
Parameters
i Global id of node
Returns
u Displacement
getV()
util::Point& model::ModelData::getV (size_t i) inline
Get velocity of the node.
Parameters
i Global id of node
Returns
v Velocity
getVol()
double& model::ModelData::getVol (size_t i) inline
Get volume of the node.
Parameters
i Global id of node
Returns
vol Volume
getWall()
particle::Wall* & model::ModelData::getWall (size_t i) inline
Get pointer to wall.
Parameters
i Location in the wall list
Returns
Pointer Pointer to wall
Referenced by model::DEMModel::computeContactForces().
getX()
util::Point& model::ModelData::getX (size_t i) inline
Get current coordinate of the node.
Parameters
i Global id of node
Returns
x Current coordinate
Referenced by rw::reader::VtkParticleReader::readNodes().
getXRef()
util::Point& model::ModelData::getXRef (size_t i) inline
Get reference coordinate of the node.
Parameters
i Global id of node
Returns
x Reference coordinate
Referenced by rw::reader::VtkParticleReader::readNodes().
setF() [1/2]
void model::ModelData::setF (size_t i, const util::Point & f) inline
Set force of the node.
Parameters
i Global id of node
f Force to set
setF() [2/2]
void model::ModelData::setF (size_t i, int dof, double f) inline
Set force of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
f Force to set
setFix()
void model::ModelData::setFix (size_t i, const unsigned int & dof, const bool & flag) inline
Set fixity of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
flag Fixity to set
setMx()
void model::ModelData::setMx (size_t i, const double & mx) inline
Set weighted-volume (mx) of the node.
Parameters
i Global id of node
mx Weighted-volume to set
setPtId()
void model::ModelData::setPtId (size_t i, const size_t & id) inline
Set particle id given the location in particle list.
Parameters
i Location in the particle list
Returns
Id Particle id to set
setThetax()
void model::ModelData::setThetax (size_t i, const double & thetax) inline
Set volumetric deformation (thetax) of the node.
Parameters
i Global id of node
thetax Volumetric deformation to set
setU() [1/2]
void model::ModelData::setU (size_t i, const util::Point & u) inline
Set displacement of the node.
Parameters
i Global id of node
u Displacement to set
Referenced by rw::reader::VtkParticleReader::readNodes().
setU() [2/2]
void model::ModelData::setU (size_t i, int dof, double u) inline
Set displacement of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
u Displacement to set
setV() [1/2]
void model::ModelData::setV (size_t i, const util::Point & v) inline
Set velocity of the node.
Parameters
i Global id of node
v Velocity to set
Referenced by rw::reader::VtkParticleReader::readNodes().
setV() [2/2]
void model::ModelData::setV (size_t i, int dof, double v) inline
Set velocity of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
v Velocity to set
setVol()
void model::ModelData::setVol (size_t i, const double & vol) inline
Set volume of the node.
Parameters
i Global id of node
vol Volume to set
setX() [1/2]
void model::ModelData::setX (size_t i, const util::Point & x) inline
Set current coordinate of the node.
Parameters
i Global id of node
x Current coordinate to set
Referenced by rw::reader::VtkParticleReader::readNodes().
setX() [2/2]
void model::ModelData::setX (size_t i, int dof, double x) inline
Set specific current coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Current coordinate to set
setXRef() [1/2]
void model::ModelData::setXRef (size_t i, const util::Point & x) inline
Set reference coordinate of the node.
Parameters
i Global id of node
x Reference coordinate to set
setXRef() [2/2]
void model::ModelData::setXRef (size_t i, int dof, double x) inline
Set specific reference coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Reference coordinate to set
Field Documentation
d_fix
std::vector<uint8_t> model::ModelData::d_fix
Vector of fixity mask of each node.
First bit represents x-dof, second represents y-dof, and third represents z-dof. 0 represents free dof and 1 represents fixed dof.
We store data in uint8_t type which can hold 8 bit. At present we only use first 3 bits.
Referenced by rw::writer::VtkParticleWriter::appendNodes(), model::DEMModel::computeForces(), model::DEMModel::init(), and model::DEMModel::integrateCD().
d_mX
std::vector<double> model::ModelData::d_mX
Weighted volume.
In case of nonlinear peridynamic state based model, this data is not required
Referenced by model::DEMModel::computeForces().
d_thetaX
std::vector<double> model::ModelData::d_thetaX
Dilation.
In case of nonlinear peridynamic state based model, this will be the spherical (hydrostatic) strain
Referenced by rw::writer::VtkParticleWriter::appendNodes(), and model::DEMModel::computeForces().
The documentation for this class was generated from the following files:
/home/prashant/work/peridem_works/PeriDEM_docs/src/model/modelData.h
/home/prashant/work/peridem_works/PeriDEM_docs/src/model/modelData.cpp