PeriDEM: particle::BaseParticle Class Reference
particle::BaseParticle Class Reference
A class to store particle geometry, nodal discretization, and methods.
#include <baseParticle.h>
Public Member Functions
BaseParticle (std::string type="none")
Constructor.
BaseParticle (std::string type, size_t id, size_t type_id, size_t zone_id, size_t dim, size_t num_nodes, double h, std::shared_ptr< model::ModelData > model_data)
Constructor.
Accessors
std::string getType () const
Get type of this object.
int getTypeIndex () const
Get type (in integer format) of this object.
size_t getId () const
Get id.
size_t getTypeId () const
Get id among the group of object in the same type as this.
size_t getDimension () const
Get the dimension of the domain.
double getMeshSize () const
Get mesh size.
double getDensity () const
Get density.
double getHorizon () const
Get horizon.
material::Material * getMaterial ()
Get pointer to material object.
const material::Material * getMaterial () const
size_t getNumNodes () const
Get the number of nodes.
size_t getNodeId (size_t i_loc) const
Get global id of node given the local id of node in this object.
Get and set reference coordinate
util::Point & getXRef (size_t i)
Get reference coordinate of the node.
const util::Point & getXRef (size_t i) const
void setXRef (size_t i, const util::Point &x)
Set reference coordinate of the node.
void addXRef (size_t i, const util::Point &x)
Add reference coordinate of the node.
void setXRef (size_t i, int dof, double x)
Set specific reference coordinate of the node.
void addXRef (size_t i, int dof, double x)
Add specific reference coordinate of the node.
util::Point & getXRefLocal (size_t i)
Get reference coordinate of the node given node's local id.
const util::Point & getXRefLocal (size_t i) const
void setXRefLocal (size_t i, const util::Point &x)
Set reference coordinate of the node given node's local id.
void addXRefLocal (size_t i, const util::Point &x)
Add to reference coordinate of the node given node's local id.
void setXRefLocal (size_t i, int dof, double x)
Set specific reference coordinate of the node given node's local id.
void addXRefLocal (size_t i, int dof, double x)
Add to specific reference coordinate of the node given node's local id.
Get and set current coordinate
util::Point & getX (size_t i)
Get current coordinate of the node.
const util::Point & getX (size_t i) const
void setX (size_t i, const util::Point &x)
Set current coordinate of the node.
void addX (size_t i, const util::Point &x)
Add current coordinate of the node.
void setX (size_t i, int dof, double x)
Set specific current coordinate of the node.
void addX (size_t i, int dof, double x)
Add to specific current coordinate of the node.
util::Point & getXLocal (size_t i)
Get current coordinate of the node given node's local id.
const util::Point & getXLocal (size_t i) const
void setXLocal (size_t i, const util::Point &x)
Set current coordinate of the node given node's local id.
void addXLocal (size_t i, const util::Point &x)
Add to current coordinate of the node given node's local id.
void setXLocal (size_t i, int dof, double x)
Set specific current coordinate of the node given node's local id.
void addXLocal (size_t i, int dof, double x)
Add to specific current coordinate of the node given node's local id.
Get and set displacement
util::Point & getU (size_t i)
Get displacement of the node.
const util::Point & getU (size_t i) const
void setU (size_t i, const util::Point &u)
Set displacement of the node.
void addU (size_t i, const util::Point &u)
Add to displacement of the node.
void setU (size_t i, int dof, double x)
Set displacement of the node.
void addU (size_t i, int dof, double x)
Add to displacement of the node.
util::Point & getULocal (size_t i)
Get displacement of the node given node's local id.
const util::Point & getULocal (size_t i) const
void setULocal (size_t i, const util::Point &u)
Set displacement of the node given node's local id.
void addULocal (size_t i, const util::Point &u)
Add to displacement of the node given node's local id.
void setULocal (size_t i, int dof, double u)
Set displacement of the node given node's local id.
void addULocal (size_t i, int dof, double u)
Add to displacement of the node given node's local id.
Get and set velocity
util::Point & getV (size_t i)
Get velocity of the node.
const util::Point & getV (size_t i) const
void setV (size_t i, const util::Point &v)
Set velocity of the node.
void addV (size_t i, const util::Point &v)
Add to velocity of the node.
void setV (size_t i, int dof, double v)
Set velocity of the node.
void addV (size_t i, int dof, double v)
Add to velocity of the node.
util::Point & getVLocal (size_t i)
Get velocity of the node given node's local id.
const util::Point & getVLocal (size_t i) const
void setVLocal (size_t i, const util::Point &v)
Set velocity of the node given node's local id.
void addVLocal (size_t i, const util::Point &v)
Add to velocity of the node given node's local id.
void setVLocal (size_t i, int dof, double v)
Set velocity of the node given node's local id.
void addVLocal (size_t i, int dof, double v)
Add to velocity of the node given node's local id.
Get and set force
util::Point & getF (size_t i)
Get force of the node.
const util::Point & getF (size_t i) const
void setF (size_t i, const util::Point &f)
Set force of the node.
void addF (size_t i, const util::Point &f)
Add to force of the node.
void setF (size_t i, int dof, double f)
Set force of the node.
void addF (size_t i, int dof, double f)
Add to force of the node.
util::Point & getFLocal (size_t i)
Get force of the node given node's local id.
const util::Point & getFLocal (size_t i) const
void setFLocal (size_t i, const util::Point &f)
Set force of the node given node's local id.
void addFLocal (size_t i, const util::Point &f)
Add to force of the node given node's local id.
void setFLocal (size_t i, int dof, double f)
Set force of the node given node's local id.
void addFLocal (size_t i, int dof, double f)
Add to force of the node given node's local id.
Get and set volume
double & getVol (size_t i)
Get volume of the node.
const double & getVol (size_t i) const
void setVol (size_t i, const double &vol)
Set volume of the node.
void addVol (size_t i, const double &vol)
Add to volume of the node.
double & getVolLocal (size_t i)
Get volume of the node given node's local id.
const double & getVolLocal (size_t i) const
void setVolLocal (size_t i, const double &vol)
Set volume of the node given node's local id.
void addVolLocal (size_t i, const double &vol)
Add to volume of the node given node's local id.
Get and set fixity
uint8_t & getFix (size_t i)
Get fixity of the node.
const uint8_t & getFix (size_t i) const
void setFix (size_t i, const unsigned int &dof, const bool &flag)
Set fixity of the node.
uint8_t & getFixLocal (size_t i)
Get fixity of the node given node's local id.
const uint8_t & getFixLocal (size_t i) const
void setFixLocal (size_t i, const unsigned int &dof, const bool &flag)
Set fixity of the node given node's local id.
Get and set mx
double & getMx (size_t i)
Get weighted-volume (mx) of the node.
const double & getMx (size_t i) const
void setMx (size_t i, const double &mx)
Set weighted-volume (mx) of the node.
void addMx (size_t i, const double &mx)
Add to weighted-volume (mx) of the node.
double & getMxLocal (size_t i)
Get weighted-volume (mx) of the node given node's local id.
const double & getMxLocal (size_t i) const
void setMxLocal (size_t i, const double &mx)
Set weighted-volume (mx) of the node given node's local id.
void addMxLocal (size_t i, const double &mx)
Add to weighted-volume (mx) of the node given node's local id.
Get and set thetax
double & getThetax (size_t i)
Get volumetric deformation (thetax) of the node.
const double & getThetax (size_t i) const
void setThetax (size_t i, const double &thetax)
Set volumetric deformation (thetax) of the node.
void addThetax (size_t i, const double &thetax)
Add to volumetric deformation (thetax) of the node.
double & getThetaxLocal (size_t i)
Get volumetric deformation (thetax) of the node given node's local id.
const double & getThetaxLocal (size_t i) const
void setThetaxLocal (size_t i, const double &thetax)
Set volumetric deformation (thetax) of the node given node's local id.
void addThetaxLocal (size_t i, const double &thetax)
Add to volumetric deformation (thetax) of the node given node's local id.
Data Fields
std::string d_type
particle type
int d_typeIndex
size_t d_id
Id of this particle.
size_t d_typeId
Id of this particle in the category (for example if this is a wall, what is its id in vector of walls)
size_t d_zoneId
Specify zone to which this particle belongs to.
size_t d_dim
Dimension of this particle.
size_t d_numNodes
Number of nodes in this particle.
double d_h
mesh size
bool d_computeForce
Specify if we compute force.
double d_horizon
horizon
double d_density
density
std::unique_ptr< material::Material > d_material_p
Pointer to peridynamic material object.
double d_Rc
Contact radius for contact between internal nodes of particle.
double d_Kn
Normal contact coefficient for internal contact.
size_t d_globStart
Id of first node of this object in global node list.
size_t d_globEnd
Id of last node of this object in global node list.
std::shared_ptr< model::ModelData > d_modelData_p
Reference to model class.
Detailed Description
A class to store particle geometry, nodal discretization, and methods.
This class generates a base particle for peri-dem simulations. It holds the nodal positions, geometry of particle, list of nodes
Constructor & Destructor Documentation
BaseParticle() [1/2]
particle::BaseParticle::BaseParticle (std::string type = "none") inline
Constructor.
Parameters
type Type of the particle (e.g. particle or wall)
BaseParticle() [2/2]
particle::BaseParticle::BaseParticle (std::string type, size_t id, size_t type_id, size_t zone_id, size_t dim, size_t num_nodes, double h, std::shared_ptr< model::ModelData > model_data) inline
Constructor.
Parameters
type Type of the object (e.g. particle or wall)
id Id of this object in list of all base particle objects
type_id Id of this object in list of specific type of particles (e.g. id in the list of walls or particles)
zone_id Zone id this object belongs to
dim Spatial dimension
num_nodes Number of nodes
h Mesh size
model_data Global model data
Member Function Documentation
addF() [1/2]
void particle::BaseParticle::addF (size_t i, const util::Point & f) inline
Add to force of the node.
Parameters
i Global id of node
f Force to add
addF() [2/2]
void particle::BaseParticle::addF (size_t i, int dof, double f) inline
Add to force of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
f Force to add
addFLocal() [1/2]
void particle::BaseParticle::addFLocal (size_t i, const util::Point & f) inline
Add to force of the node given node's local id.
Parameters
i Local id of node
f Force to add
addFLocal() [2/2]
void particle::BaseParticle::addFLocal (size_t i, int dof, double f) inline
Add to force of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
f Force to add
addMx()
void particle::BaseParticle::addMx (size_t i, const double & mx) inline
Add to weighted-volume (mx) of the node.
Parameters
i Global id of node
mx Weighted-volume to add
addMxLocal()
void particle::BaseParticle::addMxLocal (size_t i, const double & mx) inline
Add to weighted-volume (mx) of the node given node's local id.
Parameters
i Local id of node
mx Weighted-volume to add
addThetax()
void particle::BaseParticle::addThetax (size_t i, const double & thetax) inline
Add to volumetric deformation (thetax) of the node.
Parameters
i Global id of node
thetax Volumetric deformation to add
addThetaxLocal()
void particle::BaseParticle::addThetaxLocal (size_t i, const double & thetax) inline
Add to volumetric deformation (thetax) of the node given node's local id.
Parameters
i Local id of node
thetax Volumetric deformation to add
addU() [1/2]
void particle::BaseParticle::addU (size_t i, const util::Point & u) inline
Add to displacement of the node.
Parameters
i Global id of node
u Displacement to add
addU() [2/2]
void particle::BaseParticle::addU (size_t i, int dof, double x) inline
Add to displacement of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
u Displacement to add
addULocal() [1/2]
void particle::BaseParticle::addULocal (size_t i, const util::Point & u) inline
Add to displacement of the node given node's local id.
Parameters
i Local id of node
u Displacement to add
addULocal() [2/2]
void particle::BaseParticle::addULocal (size_t i, int dof, double u) inline
Add to displacement of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
u Displacement to add
addV() [1/2]
void particle::BaseParticle::addV (size_t i, const util::Point & v) inline
Add to velocity of the node.
Parameters
i Global id of node
v Velocity to add
addV() [2/2]
void particle::BaseParticle::addV (size_t i, int dof, double v) inline
Add to velocity of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
v Velocity to add
addVLocal() [1/2]
void particle::BaseParticle::addVLocal (size_t i, const util::Point & v) inline
Add to velocity of the node given node's local id.
Parameters
i Local id of node
v Velocity to add
addVLocal() [2/2]
void particle::BaseParticle::addVLocal (size_t i, int dof, double v) inline
Add to velocity of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
v Velocity to add
addVol()
void particle::BaseParticle::addVol (size_t i, const double & vol) inline
Add to volume of the node.
Parameters
i Global id of node
vol Volume to add
addVolLocal()
void particle::BaseParticle::addVolLocal (size_t i, const double & vol) inline
Add to volume of the node given node's local id.
Parameters
i Local id of node
vol Volume to add
addX() [1/2]
void particle::BaseParticle::addX (size_t i, const util::Point & x) inline
Add current coordinate of the node.
Parameters
i Global id of node
x Current coordinate to add
addX() [2/2]
void particle::BaseParticle::addX (size_t i, int dof, double x) inline
Add to specific current coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Current coordinate to add
addXLocal() [1/2]
void particle::BaseParticle::addXLocal (size_t i, const util::Point & x) inline
Add to current coordinate of the node given node's local id.
Parameters
i Local id of node
x Current coordinate to add
addXLocal() [2/2]
void particle::BaseParticle::addXLocal (size_t i, int dof, double x) inline
Add to specific current coordinate of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
x Current coordinate to add
addXRef() [1/2]
void particle::BaseParticle::addXRef (size_t i, const util::Point & x) inline
Add reference coordinate of the node.
Parameters
i Global id of node
x Reference coordinate to add
addXRef() [2/2]
void particle::BaseParticle::addXRef (size_t i, int dof, double x) inline
Add specific reference coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Reference coordinate to add
addXRefLocal() [1/2]
void particle::BaseParticle::addXRefLocal (size_t i, const util::Point & x) inline
Add to reference coordinate of the node given node's local id.
Parameters
i Local id of node
x Reference coordinate to add
addXRefLocal() [2/2]
void particle::BaseParticle::addXRefLocal (size_t i, int dof, double x) inline
Add to specific reference coordinate of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
x Reference coordinate to add
getDensity()
double particle::BaseParticle::getDensity () const inline
Get density.
Returns
rho Density
getDimension()
size_t particle::BaseParticle::getDimension () const inline
Get the dimension of the domain.
Returns
N Dimension
Referenced by particle::Particle::Particle(), and particle::Wall::Wall().
getF()
util::Point& particle::BaseParticle::getF (size_t i) inline
Get force of the node.
Parameters
i Global id of node
Returns
f Force
getFix()
uint8_t& particle::BaseParticle::getFix (size_t i) inline
Get fixity of the node.
Parameters
i Global id of node
Returns
flag Fixity
getFixLocal()
uint8_t& particle::BaseParticle::getFixLocal (size_t i) inline
Get fixity of the node given node's local id.
Parameters
i Local id of node
Returns
flag Fixity
getFLocal()
util::Point& particle::BaseParticle::getFLocal (size_t i) inline
Get force of the node given node's local id.
Parameters
i Local id of node
Returns
f Force
getHorizon()
double particle::BaseParticle::getHorizon () const inline
Get horizon.
Returns
eps Horizon
getId()
size_t particle::BaseParticle::getId () const inline
Get id.
Returns
id ID of this object
getMaterial()
material::Material* particle::BaseParticle::getMaterial () inline
Get pointer to material object.
Returns
material Pointer to material object
getMeshSize()
double particle::BaseParticle::getMeshSize () const inline
Get mesh size.
Returns
h Mesh size
getMx()
double& particle::BaseParticle::getMx (size_t i) inline
Get weighted-volume (mx) of the node.
Parameters
i Global id of node
Returns
mx Weighted-volume
getMxLocal()
double& particle::BaseParticle::getMxLocal (size_t i) inline
Get weighted-volume (mx) of the node given node's local id.
Parameters
i Local id of node
Returns
mx Weighted-volume
getNodeId()
size_t particle::BaseParticle::getNodeId (size_t i_loc) const inline
Get global id of node given the local id of node in this object.
Parameters
i_loc Local id of node
Returns
Id Gloabl id of node
getNumNodes()
size_t particle::BaseParticle::getNumNodes () const inline
Get the number of nodes.
Returns
N number of nodes
Referenced by loading::ParticleFLoading::apply(), loading::ParticleULoading::applyParticle(), and loading::ParticleULoading::setFixityParticle().
getThetax()
double& particle::BaseParticle::getThetax (size_t i) inline
Get volumetric deformation (thetax) of the node.
Parameters
i Global id of node
Returns
thetax Volumetric deformation
getThetaxLocal()
double& particle::BaseParticle::getThetaxLocal (size_t i) inline
Get volumetric deformation (thetax) of the node given node's local id.
Parameters
i Local id of node
Returns
thetax Volumetric deformation
getType()
std::string particle::BaseParticle::getType () const inline
Get type of this object.
Returns
Type Type
Referenced by loading::ParticleFLoading::apply(), loading::ParticleULoading::ParticleULoading(), and loading::ParticleULoading::setFixityParticle().
getTypeId()
size_t particle::BaseParticle::getTypeId () const inline
Get id among the group of object in the same type as this.
Returns
id ID of this object
Referenced by rw::writer::VtkParticleWriter::appendNodes(), loading::ParticleFLoading::apply(), loading::ParticleULoading::applyParticle(), particle::Wall::getWallId(), and loading::ParticleULoading::setFixityParticle().
getTypeIndex()
int particle::BaseParticle::getTypeIndex () const inline
Get type (in integer format) of this object.
Returns
Type Type
getU()
util::Point& particle::BaseParticle::getU (size_t i) inline
Get displacement of the node.
Parameters
i Global id of node
Returns
u Displacement
getULocal()
util::Point& particle::BaseParticle::getULocal (size_t i) inline
Get displacement of the node given node's local id.
Parameters
i Local id of node
Returns
u Displacement
getV()
util::Point& particle::BaseParticle::getV (size_t i) inline
Get velocity of the node.
Parameters
i Global id of node
Returns
v Velocity
getVLocal()
util::Point& particle::BaseParticle::getVLocal (size_t i) inline
Get velocity of the node given node's local id.
Parameters
i Local id of node
Returns
v Velocity
getVol()
double& particle::BaseParticle::getVol (size_t i) inline
Get volume of the node.
Parameters
i Global id of node
Returns
vol Volume
getVolLocal()
double& particle::BaseParticle::getVolLocal (size_t i) inline
Get volume of the node given node's local id.
Parameters
i Local id of node
Returns
vol Volume
getX()
util::Point& particle::BaseParticle::getX (size_t i) inline
Get current coordinate of the node.
Parameters
i Global id of node
Returns
x Current coordinate
getXLocal()
util::Point& particle::BaseParticle::getXLocal (size_t i) inline
Get current coordinate of the node given node's local id.
Parameters
i Local id of node
Returns
x Current coordinate
getXRef()
util::Point& particle::BaseParticle::getXRef (size_t i) inline
Get reference coordinate of the node.
Parameters
i Global id of node
Returns
x Reference coordinate
getXRefLocal()
util::Point& particle::BaseParticle::getXRefLocal (size_t i) inline
Get reference coordinate of the node given node's local id.
Parameters
i Local id of node
Returns
x Reference coordinate
Referenced by loading::ParticleULoading::setFixityParticle().
setF() [1/2]
void particle::BaseParticle::setF (size_t i, const util::Point & f) inline
Set force of the node.
Parameters
i Global id of node
f Force to set
setF() [2/2]
void particle::BaseParticle::setF (size_t i, int dof, double f) inline
Set force of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
f Force to set
setFix()
void particle::BaseParticle::setFix (size_t i, const unsigned int & dof, const bool & flag) inline
Set fixity of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
flag Fixity to set
setFixLocal()
void particle::BaseParticle::setFixLocal (size_t i, const unsigned int & dof, const bool & flag) inline
Set fixity of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
flag Fixity to set
Referenced by loading::ParticleULoading::setFixityParticle().
setFLocal() [1/2]
void particle::BaseParticle::setFLocal (size_t i, const util::Point & f) inline
Set force of the node given node's local id.
Parameters
i Local id of node
f Force to set
setFLocal() [2/2]
void particle::BaseParticle::setFLocal (size_t i, int dof, double f) inline
Set force of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
f Force to set
setMx()
void particle::BaseParticle::setMx (size_t i, const double & mx) inline
Set weighted-volume (mx) of the node.
Parameters
i Global id of node
mx Weighted-volume to set
setMxLocal()
void particle::BaseParticle::setMxLocal (size_t i, const double & mx) inline
Set weighted-volume (mx) of the node given node's local id.
Parameters
i Local id of node
mx Weighted-volume to set
setThetax()
void particle::BaseParticle::setThetax (size_t i, const double & thetax) inline
Set volumetric deformation (thetax) of the node.
Parameters
i Global id of node
thetax Volumetric deformation to set
setThetaxLocal()
void particle::BaseParticle::setThetaxLocal (size_t i, const double & thetax) inline
Set volumetric deformation (thetax) of the node given node's local id.
Parameters
i Local id of node
thetax Volumetric deformation to set
setU() [1/2]
void particle::BaseParticle::setU (size_t i, const util::Point & u) inline
Set displacement of the node.
Parameters
i Global id of node
u Displacement to set
setU() [2/2]
void particle::BaseParticle::setU (size_t i, int dof, double x) inline
Set displacement of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
u Displacement to set
setULocal() [1/2]
void particle::BaseParticle::setULocal (size_t i, const util::Point & u) inline
Set displacement of the node given node's local id.
Parameters
i Local id of node
u Displacement to set
setULocal() [2/2]
void particle::BaseParticle::setULocal (size_t i, int dof, double u) inline
Set displacement of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
u Displacement to set
setV() [1/2]
void particle::BaseParticle::setV (size_t i, const util::Point & v) inline
Set velocity of the node.
Parameters
i Global id of node
v Velocity to set
setV() [2/2]
void particle::BaseParticle::setV (size_t i, int dof, double v) inline
Set velocity of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
v Velocity to set
setVLocal() [1/2]
void particle::BaseParticle::setVLocal (size_t i, const util::Point & v) inline
Set velocity of the node given node's local id.
Parameters
i Local id of node
v Velocity to set
setVLocal() [2/2]
void particle::BaseParticle::setVLocal (size_t i, int dof, double v) inline
Set velocity of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
v Velocity to set
setVol()
void particle::BaseParticle::setVol (size_t i, const double & vol) inline
Set volume of the node.
Parameters
i Global id of node
vol Volume to set
setVolLocal()
void particle::BaseParticle::setVolLocal (size_t i, const double & vol) inline
Set volume of the node given node's local id.
Parameters
i Local id of node
vol Volume to set
setX() [1/2]
void particle::BaseParticle::setX (size_t i, const util::Point & x) inline
Set current coordinate of the node.
Parameters
i Global id of node
x Current coordinate to set
setX() [2/2]
void particle::BaseParticle::setX (size_t i, int dof, double x) inline
Set specific current coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Current coordinate to set
setXLocal() [1/2]
void particle::BaseParticle::setXLocal (size_t i, const util::Point & x) inline
Set current coordinate of the node given node's local id.
Parameters
i Local id of node
x Current coordinate to set
setXLocal() [2/2]
void particle::BaseParticle::setXLocal (size_t i, int dof, double x) inline
Set specific current coordinate of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
x Current coordinate to set
setXRef() [1/2]
void particle::BaseParticle::setXRef (size_t i, const util::Point & x) inline
Set reference coordinate of the node.
Parameters
i Global id of node
x Reference coordinate to set
setXRef() [2/2]
void particle::BaseParticle::setXRef (size_t i, int dof, double x) inline
Set specific reference coordinate of the node.
Parameters
i Global id of node
dof Direction or degree of freedom to be modified
x Reference coordinate to set
setXRefLocal() [1/2]
void particle::BaseParticle::setXRefLocal (size_t i, const util::Point & x) inline
Set reference coordinate of the node given node's local id.
Parameters
i Local id of node
x Reference coordinate to set
setXRefLocal() [2/2]
void particle::BaseParticle::setXRefLocal (size_t i, int dof, double x) inline
Set specific reference coordinate of the node given node's local id.
Parameters
i Local id of node
dof Direction or degree of freedom to be modified
x Reference coordinate to set
The documentation for this class was generated from the following file:
/home/prashant/work/peridem_works/PeriDEM_docs/src/particle/baseParticle.h