PeriDEM: inp::MaterialDeck Struct Reference
inp::MaterialDeck Struct Reference
Input
Structure to read and store material related data.
#include <materialDeck.h>
Public Member Functions
MaterialDeck ()
Constructor.
MaterialDeck (const MaterialDeck &md)
Copy constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
Data Fields
bool d_isPlaneStrain
Indicates if the 2-d simulation is of plane-strain type (thick material) or plane-stress type (thin material)
std::string d_materialType
Material type.
size_t d_bondPotentialType
Type of pairwise (bond-based) potential.
size_t d_statePotentialType
Type of hydrostatic (state-based) potential.
size_t d_influenceFnType
Type of influence function.
std::vector< double > d_bondPotentialParams
List of parameters for pairwise potential.
std::vector< double > d_statePotentialParams
List of parameters for hydrostatic potential.
std::vector< double > d_influenceFnParams
List of parameters for influence function.
bool d_irreversibleBondBreak
Flag for irreversible breaking of bonds.
bool d_stateContributionFromBrokenBond
Flag for contribution to hydrostatic force from the broken bond.
double d_checkScFactor
Factor to check if bond is broken.
bool d_computeParamsFromElastic
Compute Peridynamic material properties from elastic properties.
inp::MatData d_matData
List of elastic and fracture properties.
double d_density
Density of material.
double d_horizon
Horizon for peridynamic interaction.
double d_horizonMeshRatio
Horizon to mesh ratio.
Detailed Description
Structure to read and store material related data.
Constructor & Destructor Documentation
MaterialDeck()
inp::MaterialDeck::MaterialDeck (const MaterialDeck & md) inline
Copy constructor.
Parameters
md Another MaterialDeck object
Member Function Documentation
print()
void inp::MaterialDeck::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
printStr()
std::string inp::MaterialDeck::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Referenced by material::PdState::computeParameters(), print(), inp::ParticleZone::printStr(), and inp::WallZone::printStr().
Field Documentation
d_irreversibleBondBreak
bool inp::MaterialDeck::d_irreversibleBondBreak
Flag for irreversible breaking of bonds.
True means bond breaking is irreversible.
Referenced by printStr(), and inp::Input::setZoneMaterialDeck().
The documentation for this struct was generated from the following file:
/home/user/project/src/inp/decks/materialDeck.h