PeriDEM: util::Point Struct Reference
util::Point Struct Reference
A structure to represent 3d vectors.
#include <point.h>
Public Member Functions
Point ()
Constructor.
template<class T >
Point (T x, T y, T z)
Constructor.
template<class T >
Point (T x[3])
Constructor.
Point (const std::vector< double > &p)
Constructor.
Point (const Point &p)
Copy constructor.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing printable information about the object.
void print (int nt=0, int lvl=0) const
Prints the information about the object.
double length () const
Computes the Euclidean length of the vector.
double lengthSq () const
Computes the Euclidean length of the vector.
double dot (const Point &b) const
Computes the dot product of this vector with another point.
double dist (const Point &b) const
Computes the distance between a given point from this point.
Point cross (const Point &b) const
Computes the cross product between this vector and given vector.
Point project (const Point &b, bool is_unit=false) const
Computes projection of vector on this vector.
Point projectNormal (const Point &b, bool is_unit=false) const
Computes projection of vector on plane with normal as this vector.
Data Fields
double d_x
the x coordinate
double d_y
the y coordinate
double d_z
the z coordinate
Group operators
Point & operator+= (const double b)
Addition by scalar operator.
Point & operator-= (const double b)
Subtraction by scalar operator.
Point & operator*= (const double b)
Multiplication by scalar operator.
Point & operator+= (const Point &b)
Addition operator.
Point & operator-= (const Point &b)
Subtraction operator.
Point & operator*= (const Point &b)
Multiplication (pointwise/elementwise) operator.
Point & operator/= (const double b)
Division by scalar operator.
double & operator[] (size_t i)
Access operator.
const double & operator[] (size_t i) const
Access operator.
Point operator+ (Point lhs, const Point &rhs)
Addition operator.
Point operator- (Point lhs, const Point &rhs)
Subtraction operator.
double operator* (Point lhs, const Point rhs)
Multiplication (dot) operator.
Point operator* (Point lhs, const double rhs)
Scalar product operator.
Point operator+ (Point lhs, const double rhs)
Addition by scalar operator.
Point operator+ (const double lhs, Point rhs)
Addition by scalar operator.
Point operator- (Point lhs, const double rhs)
Subtraction by scalar operator.
Point operator- (const double lhs, Point rhs)
Subtraction by scalar operator.
Point operator* (const double lhs, Point rhs)
Multiplication by scalar operator.
Point operator/ (Point lhs, const double rhs)
Division by scalar operator.
Detailed Description
A structure to represent 3d vectors.
Constructor & Destructor Documentation
Point() [1/4]
template<class T > util::Point::Point (T x, T y, T z) inline
Constructor.
Parameters
x The x coordinate
y The y coordinate
z The z coordinate
Point() [2/4]
template<class T > util::Point::Point (T x[3]) inline explicit
Constructor.
Parameters
x The coordinate vector
Point() [3/4]
util::Point::Point (const std::vector< double > & p) inline explicit
Constructor.
Parameters
p Vector
Point() [4/4]
util::Point::Point (const Point & p) inline
Copy constructor.
Parameters
p Another Point object
Member Function Documentation
cross()
Point util::Point::cross (const Point & b) const inline
Computes the cross product between this vector and given vector.
Parameters
b Another vector
Returns
Vector Cross product
Referenced by util::angle(), and util::rotate().
dist()
double util::Point::dist (const Point & b) const inline
Computes the distance between a given point from this point.
Parameters
b Another point
Returns
Value Distance between the two points
Referenced by util::doubleGaussian2d(), and util::gaussian2d().
dot()
double util::Point::dot (const Point & b) const inline
Computes the dot product of this vector with another point.
Parameters
b Another vector
Returns
Value a dot product
Referenced by material::RnpMaterial::getS(), project(), and projectNormal().
length()
double util::Point::length () const inline
Computes the Euclidean length of the vector.
Returns
Length Euclidean length of the vector
Referenced by util::angle(), material::RnpMaterial::getBondForceDirection(), material::PmbMaterial::getS(), material::PdElastic::getS(), material::PdState::getS(), util::pointDistancePlane(), util::pointDistanceSegment(), project(), projectNormal(), and particle::RefParticle::RefParticle().
lengthSq()
double util::Point::lengthSq () const inline
Computes the Euclidean length of the vector.
Returns
Length Euclidean length of the vector
Referenced by util::isPointInsideCylinder(), and util::pointDistanceLine().
operator*=() [1/2]
Point& util::Point::operator*= (const double b) inline
Multiplication by scalar operator.
Parameters
b Scalar
Returns
point Vector after multiplying b to this point
operator*=() [2/2]
Point& util::Point::operator*= (const Point & b) inline
Multiplication (pointwise/elementwise) operator.
Parameters
b Vector
Returns
point Vector after elementwise multiplication of b with this point
operator+=() [1/2]
Point& util::Point::operator+= (const double b) inline
Addition by scalar operator.
Parameters
b Scalar
Returns
point Vector after adding b to this point
operator+=() [2/2]
Point& util::Point::operator+= (const Point & b) inline
Addition operator.
Parameters
b Vector to be added
Returns
point Vector after adding b to this point
operator-=() [1/2]
Point& util::Point::operator-= (const double b) inline
Subtraction by scalar operator.
Parameters
b Scalar
Returns
point Vector after subtracting b from this point
operator-=() [2/2]
Point& util::Point::operator-= (const Point & b) inline
Subtraction operator.
Parameters
b Vector to subtract
Returns
point Vector after subtracting b from this point
operator/=()
Point& util::Point::operator/= (const double b) inline
Division by scalar operator.
Parameters
b Scalar
Returns
point Vector after dividing b elementwise from this point
operator[]() [1/2]
double& util::Point::operator[] (size_t i) inline
Access operator.
Parameters
i Index of element in vector to access
Returns
value Value of ith element in vector
operator[]() [2/2]
const double& util::Point::operator[] (size_t i) const inline
Access operator.
Parameters
i Index of element in vector to access
Returns
value Value of ith element in vector
print()
void util::Point::print (int nt = 0, int lvl = 0) const inline
Prints the information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
printStr()
std::string util::Point::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing printable information about the object.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
string String containing printable information about the object
Referenced by print(), inp::PICDeck::printStr(), fe::QuadData::printStr(), inp::ParticleDeck::printStr(), and particle::ParticleTransform::printStr().
project()
Point util::Point::project (const Point & b, bool is_unit = false) const inline
Computes projection of vector on this vector.
Parameters
b Another vector
is_unit Specify if this is a unit vector
Returns
Vector Projection vector
projectNormal()
Point util::Point::projectNormal (const Point & b, bool is_unit = false) const inline
Computes projection of vector on plane with normal as this vector.
Parameters
b Another vector
is_unit Specify if this is a unit vector
Returns
Vector Projection vector
Friends And Related Function Documentation
operator* [1/3]
Point operator* (const double lhs, Point rhs) friend
Multiplication by scalar operator.
Parameters
lhs lhs scalar
rhs rhs vector
Returns
point Vector after multiplying lhs to rhs pointwise
operator* [2/3]
Point operator* (Point lhs, const double rhs) friend
Scalar product operator.
Parameters
lhs lhs (to be modified)
rhs rhs scalar (to be multiplied to lhs)
Returns
point lhs after multiplying rhs to it
operator* [3/3]
double operator* (Point lhs, const Point rhs) friend
Multiplication (dot) operator.
Parameters
lhs lhs
rhs rhs
Returns
product Dot product of two vectors
operator+ [1/3]
Point operator+ (const double lhs, Point rhs) friend
Addition by scalar operator.
Parameters
lhs lhs scalar
rhs rhs (to be added to lhs)
Returns
point After adding lhs to rhs
operator+ [2/3]
Point operator+ (Point lhs, const double rhs) friend
Addition by scalar operator.
Parameters
lhs lhs (to be modified)
rhs rhs (to be added to lhs)
Returns
point lhs after adding rhs to it
operator+ [3/3]
Point operator+ (Point lhs, const Point & rhs) friend
Addition operator.
Parameters
lhs lhs (to be modified)
rhs rhs (to be added to lhs)
Returns
point lhs after adding rhs to it
operator- [1/3]
Point operator- (const double lhs, Point rhs) friend
Subtraction by scalar operator.
Parameters
lhs lhs scalar
rhs rhs (to be subtracted from lhs)
Returns
point After subtracting rhs from lhs
operator- [2/3]
Point operator- (Point lhs, const double rhs) friend
Subtraction by scalar operator.
Parameters
lhs lhs (to be modified)
rhs rhs (to be subtracted from lhs)
Returns
point lhs after subtracting rhs from it
operator- [3/3]
Point operator- (Point lhs, const Point & rhs) friend
Subtraction operator.
Parameters
lhs lhs (to be modified)
rhs rhs (to be subtracted from lhs)
Returns
point lhs after subtracting rhs from it
operator/
Point operator/ (Point lhs, const double rhs) friend
Division by scalar operator.
Parameters
lhs lhs scalar
rhs rhs vector
Returns
point Vector after dividing lhs to rhs pointwise
The documentation for this struct was generated from the following file:
/home/user/project/src/util/point.h