# base ubuntu image with petsc, libmesh, hpx
FROM u1804-comp

## usage:
## 1. build command
## docker build --no-cache -t u1804-clion -f Dockerfile-u1804-clion .
## 2. run
## docker run -d --cap-add sys_ptrace -p127.0.0.1:2222:22 --name clion_remote_env u1804-clion
## 3. set ssh
## ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222"
## 4. stop
## docker stop clion_remote_env
## 5. ssh credentials (test user)
## user@password 

# Set metadata
LABEL maintainer="Prashant K. Jha <pjha.sci@gmail.com>"
LABEL description="Ubuntu 18.04 for clion remote developement"

RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_test_clion \
  && mkdir /run/sshd

RUN useradd -m user \
  && yes password | passwd user

RUN usermod -s /bin/bash user

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]
