name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey **#** thanks for reporting an issue! We will try to get in touch with you soon.'
        pr-message: 'Hey **#** thanks for your contribution! We will try to get in touch with you soon.'
